Repository CrowdDotDev/crowd.dev, pull requests merged in 2022-12, with the labels that each got.

#292 Twitter rate limit handling
  .github/PULL_REQUEST_TEMPLATE.md
  backend/src/serverless/integrations/services/integrations/hackerNewsIntegrationService.ts
  backend/src/serverless/integrations/usecases/hackerNews/getPostsByKeywords.ts
  backend/src/serverless/integrations/usecases/slack/errorHandler.ts
  backend/src/serverless/integrations/usecases/slack/getChannels.ts
  backend/src/serverless/integrations/usecases/slack/getMember.ts
  backend/src/serverless/integrations/usecases/slack/getMembers.ts
  backend/src/serverless/integrations/usecases/slack/getMessages.ts
  backend/src/serverless/integrations/usecases/slack/getMessagesInThreads.ts
  backend/src/serverless/integrations/usecases/slack/getTeam.ts
  backend/src/serverless/integrations/usecases/twitter/errorHandler.ts
  backend/src/serverless/integrations/usecases/twitter/getFollowers.ts
  backend/src/serverless/integrations/usecases/twitter/getPostsByHashtag.ts
  backend/src/serverless/integrations/usecases/twitter/getPostsByMention.ts
  backend/src/serverless/integrations/usecases/twitter/getProfiles.ts
  backend/src/services/conversationService.ts
  backend/src/services/eagleEyeContentService.ts
  backend/src/types/activityTypes.ts
  backend/src/types/baseError.ts
  backend/src/types/integration/rateLimitError.ts
Labels: Bug

#295 Save report on drop instead of move to avoid a Too Many Requests error
  frontend/src/modules/report/components/report-grid-layout.vue
Labels: Bug

#293 Bugfix/twitter rate limit handling c 188
  backend/src/serverless/integrations/usecases/slack/errorHandler.ts
  backend/src/serverless/integrations/usecases/slack/getChannels.ts
  backend/src/serverless/integrations/usecases/slack/getMember.ts
  backend/src/serverless/integrations/usecases/slack/getMembers.ts
  backend/src/serverless/integrations/usecases/slack/getMessages.ts
  backend/src/serverless/integrations/usecases/slack/getMessagesInThreads.ts
  backend/src/serverless/integrations/usecases/slack/getTeam.ts
  backend/src/serverless/integrations/usecases/twitter/errorHandler.ts
  backend/src/serverless/integrations/usecases/twitter/getFollowers.ts
  backend/src/serverless/integrations/usecases/twitter/getPostsByHashtag.ts
  backend/src/serverless/integrations/usecases/twitter/getPostsByMention.ts
  backend/src/serverless/integrations/usecases/twitter/getProfiles.ts
Labels: Bug

#301 Fix reports issues
  frontend/src/modules/report/components/report-grid-layout.vue
  frontend/src/modules/report/pages/report-view-page.vue
  frontend/src/modules/widget/components/cube/_query_builder/DimensionSelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/FilterComponent.vue
  frontend/src/modules/widget/components/cube/_query_builder/Order.vue
  frontend/src/modules/widget/components/cube/widget-cube-builder.vue
  frontend/src/modules/widget/components/widget-table.vue
  frontend/src/modules/widget/components/widget.vue
Labels: Bug

#303 Fix additional report issues
  frontend/src/i18n/en.js
  frontend/src/modules/report/report-charts.js
  frontend/src/modules/widget/components/cube/_query_builder/ChartType.vue
  frontend/src/modules/widget/components/cube/_query_builder/DimensionSelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/FilterComponent.vue
  frontend/src/modules/widget/components/cube/_query_builder/TimeDimensionSelect.vue
  frontend/src/modules/widget/components/cube/widget-cube-builder.vue
  frontend/src/modules/widget/components/widget.vue
Labels: Bug

#296 Github organization enrichment: name sanitization
  backend/src/database/migrations/U1669832400__organizationCacheIndexUpdates.sql
  backend/src/database/migrations/V1669832400__organizationCacheIndexUpdates.sql
  backend/src/serverless/integrations/usecases/github/graphql/organizations.ts
Labels: Bug

#308 Removed number of activities from the organizations new and active view
  frontend/src/modules/organization/store/constants.js
Labels: Bug

#312 Fixed pagination when getting members from Twitter
  backend/src/serverless/integrations/usecases/twitter/getPostsByMention.ts
Labels: Bug

#311 GitHub rate limit error detection
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/types/regularTypes.ts
  backend/src/serverless/integrations/usecases/github/graphql/baseQuery.ts
  backend/src/serverless/integrations/usecases/github/graphql/members.ts
  backend/src/serverless/integrations/usecases/github/graphql/organizations.ts
Labels: Bug

#310 Display markdown in activities
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/scss/html.scss
  frontend/src/assets/scss/index.scss
  frontend/src/integrations/devto/components/activity/devto-activity-content.vue
  frontend/src/integrations/discord/components/activity/discord-activity-content.vue
  frontend/src/integrations/hackernews/components/activity/hackerNews-activity-content.vue
  frontend/src/main.js
  frontend/src/modules/activity/components/activity-content.vue
  frontend/src/plugins/marked.js
  frontend/src/plugins/sanitize.js
Labels: Improvement

#315 Make sure that we call AWS Comprehend API with utf-8 string.
  backend/src/services/activityService.ts
  backend/src/services/aws.ts
Labels: Bug

#317 Exclude our internal tenants from telemetry and add events organization and integrations
  backend/src/segment/identify.ts
  backend/src/segment/identifyTenant.ts
  backend/src/segment/telemetryTrack.ts
  backend/src/services/integrationService.ts
  backend/src/services/memberService.ts
  backend/src/services/organizationService.ts
  frontend/.env.dist.local
Labels: Bug

#320 Move Qdrant to the cloud version
  premium/eagle-eye/crowd-eagle-eye/crowd/eagle_eye/apis/vector_api.py
  premium/eagle-eye/crowd-eagle-eye/crowd/eagle_eye/config.py
  premium/eagle-eye/crowd-eagle-eye/crowd/eagle_eye/sync.py
Labels: Bug

#321 Add search button to eagle eye
  frontend/src/premium/eagle-eye/components/eagle-eye-filter.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-search.vue
  frontend/src/premium/eagle-eye/store/actions.js
  frontend/src/shared/store/actions.js
Labels: Improvement

#326 Fix dashboard evolutions
  frontend/src/modules/dashboard/components/dashboard-count.vue
Labels: Bug

#322 Detect which channel the thread started from.
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
  backend/src/serverless/integrations/types/discordTypes.ts
Labels: Bug

#327 Stop processing if there are no posts with such hashtag
  backend/src/serverless/integrations/usecases/twitter/getPostsByHashtag.ts
Labels: Bug

#336 Upped thresholds for merge suggestions and included email and displayName to the computation
  backend/src/serverless/microservices/python/crowd-backend/crowd/backend/models/member.py
  backend/src/serverless/microservices/python/crowd-backend/crowd/backend/repository/repository.py
  backend/src/serverless/microservices/python/crowd-check-merge-members/crowd/check_merge_members/merge_suggestions.py
Labels: Improvement

#337 Fix tasks related members input
  frontend/src/modules/task/components/task-form.vue
  frontend/src/modules/task/task-model.js
  frontend/src/shared/form/autocomplete-many-input.vue
  frontend/src/shared/loading/loader.vue
  frontend/src/shared/shared-module.js
Labels: Bug

#342 Cubejs preaggregations updates
  backend/src/cubejs/schema/Activities.js
  backend/src/cubejs/schema/Members.js
  backend/src/cubejs/schema/Organizations.js
  backend/src/cubejs/schema/Sentiment.js
Labels: Improvement

#347 Member email trim function typo
  backend/src/services/memberService.ts
Labels: Bug

#346 Ensure index attributes call removed while creating a document
  backend/src/search-engine/repositories/indexable.ts
Labels: Bug

#318 Tenant plans and feature flagging
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/package-lock.json
  backend/package.json
  backend/src/api/automation/automationCreate.ts
  backend/src/api/automation/automationDestroy.ts
  backend/src/api/automation/index.ts
  backend/src/api/conversation/conversationSettingsUpdate.ts
  backend/src/api/index.ts
  backend/src/api/integration/__tests__/integrationProtectedFields.test.ts
  backend/src/api/microservice/__tests__/microserviceProtectedFields.test.ts
  backend/src/api/plan/stripe/checkout.ts
  backend/src/api/plan/stripe/portal.ts
  backend/src/api/tenant/tenantCreate.ts
  backend/src/api/tenant/tenantFind.ts
  backend/src/bin/jobs/downgradeExpiredTrialPlans.ts
  backend/src/bin/jobs/index.ts
  backend/src/bin/scripts/change-tenant-plan.ts
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/database/migrations/U1670239828__tenantPlanUpdates.sql
  backend/src/database/migrations/V1670239828__tenantPlanUpdates.sql
  backend/src/database/models/tenant.ts
  backend/src/database/repositories/__tests__/tenantRepository.test.ts
  backend/src/database/repositories/automationRepository.ts
  backend/src/database/repositories/tenantRepository.ts
  backend/src/database/utils/sequelizeTestUtils.ts
  backend/src/feature-flags/ensureFlagUpdated.ts
  backend/src/feature-flags/isFeatureEnabled.ts
  backend/src/feature-flags/setTenantProperties.ts
  backend/src/i18n/en.ts
  backend/src/middlewares/featureFlagMiddleware.ts
  backend/src/security/permissions.ts
  backend/src/security/plans.ts
  backend/src/segment/identify.ts
  backend/src/segment/identifyTenant.ts
  backend/src/segment/telemetryTrack.ts
  backend/src/segment/track.ts
  backend/src/services/__tests__/conversationService.test.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/__tests__/organizationService.test.ts
  backend/src/services/__tests__/tenantService.test.ts
  backend/src/services/organizationService.ts
  backend/src/services/premium/user/userDestroyer.ts
  backend/src/services/premium/user/userEditor.ts
  backend/src/services/tenantService.ts
  backend/src/services/user/__tests__/permissionChecker.test.ts
  backend/src/services/user/permissionChecker.ts
  backend/src/types/common.ts
  frontend/src/security/permissions.js
  frontend/src/security/plans.js
Labels: Feature

#335 Integrate posthog in frontend
  frontend/package-lock.json
  frontend/package.json
  frontend/scripts/docker-entrypoint.sh
  frontend/src/assets/scss/badge.scss
  frontend/src/config.js
  frontend/src/integrations/integrations-config.js
  frontend/src/main.js
  frontend/src/modules/auth/auth-current-tenant.js
  frontend/src/modules/automation/automation-store.js
  frontend/src/modules/automation/components/list/automation-list-table.vue
  frontend/src/modules/automation/pages/automation-list-page.vue
  frontend/src/modules/index.js
  frontend/src/modules/layout/components/error-page.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/layout/components/paywall-page.vue
  frontend/src/modules/layout/components/workspace-dropdown.vue
  frontend/src/modules/organization/organization-routes.js
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/modules/settings/pages/settings-page.vue
  frontend/src/modules/settings/settings-routes.js
  frontend/src/modules/tenant/components/tenant-list-drawer.vue
  frontend/src/premium/community-help-center/community-help-center-routes.js
  frontend/src/premium/community-help-center/components/settings/_general.vue
  frontend/src/premium/community-help-center/pages/community-help-center-page.vue
  frontend/src/premium/eagle-eye/eagle-eye-routes.js
  frontend/src/premium/eagle-eye/pages/eagle-eye-page.vue
  frontend/src/premium/user/permission-checker.js
  frontend/src/shared/error/errors.js
  frontend/src/utils/date.js
  frontend/src/utils/posthog.js
  frontend/tailwind.config.js
Labels: Feature

#343 Fix copy for HackerNews on Integrations page
  frontend/src/integrations/hackernews/config.js
Labels: Improvement

#348 Infrastructure for in-app TypeForm surveys
  frontend/scripts/docker-entrypoint.sh
  frontend/src/config.js
  frontend/src/modules/layout/components/layout.vue
Labels: Improvement

#350 Plan page
  frontend/src/assets/scss/badge.scss
  frontend/src/modules/member/components/member-badge.vue
  frontend/src/modules/organization/components/organization-name.vue
  frontend/src/modules/settings/components/plan-modal.vue
  frontend/src/modules/settings/pages/plans-page.vue
  frontend/src/modules/settings/pages/settings-page.vue
  frontend/src/modules/settings/settings-pricing-plans.js
  frontend/src/security/plans.js
  frontend/src/shared/dialog/dialog.vue
Labels: Feature

#353 Fix copy in pricing page
  frontend/src/modules/settings/pages/plans-page.vue
  frontend/src/modules/settings/settings-pricing-plans.js
Labels: Bug

#341 Send email once integration setup is done
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/database/migrations/U1670422647__addEmailSentAtToIntegrations.sql
  backend/src/database/migrations/V1670422647__addEmailSentAtToIntegrations.sql
  backend/src/database/models/integration.ts
  backend/src/database/repositories/integrationRepository.ts
  backend/src/i18n/en.ts
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/services/emailSender.ts
  frontend/src/modules/layout/components/layout.vue
Labels: Feature

#355 Tweak grid/container on pages
  frontend/src/modules/activity/pages/activity-list-page.vue
  frontend/src/modules/auth/pages/profile-form-page.vue
  frontend/src/modules/integration/components/integration-list-page.vue
  frontend/src/modules/layout/components/page-wrapper.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-engagement-level.vue
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/pages/organization-form-page.vue
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/modules/organization/pages/organization-view-page.vue
  frontend/src/modules/report/pages/report-form-page.vue
  frontend/src/modules/report/pages/report-list-page.vue
  frontend/src/modules/settings/pages/settings-page.vue
  frontend/src/modules/task/pages/task-page.vue
  frontend/src/premium/community-help-center/pages/community-help-center-page.vue
  frontend/src/premium/eagle-eye/pages/eagle-eye-page.vue
  frontend/src/shared/layout/page-wrapper.vue
  frontend/src/shared/shared-module.js
Labels: Improvement

#358 Posthog request proxy from frontend
  backend/src/services/eagleEyeContentService.ts
  frontend/scripts/docker-entrypoint.sh
  frontend/src/config.js
  frontend/src/main.js
Labels: Bug

#357 Organizations paywall
  frontend/public/images/organizations-paywall.png
  frontend/src/assets/scss/dialogs.scss
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/dashboard/components/organization/dashboard-organization-item.vue
  frontend/src/modules/layout/components/paywall-modal.vue
  frontend/src/modules/layout/layout-routes.js
  frontend/src/modules/layout/pages/error-page.vue
  frontend/src/modules/layout/pages/paywall-page.vue
  frontend/src/modules/layout/pages/temporary-paywall-page.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/organization/organization-routes.js
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/modules/settings/settings-routes.js
  frontend/src/premium/community-help-center/community-help-center-routes.js
  frontend/src/premium/eagle-eye/eagle-eye-routes.js
Labels: Feature

#359 Fix EagleEye's API throwing a 500 when sending posts to exclude
  premium/eagle-eye/crowd-eagle-eye/crowd/eagle_eye/apis/vector_api.py
Labels: Bug

#363 Tenants created after the 18th of December only had trial for 14 days. It should be until the 15th of January.
  backend/src/database/repositories/tenantRepository.ts
  backend/src/services/__tests__/tenantService.test.ts
Labels: Bug

#366 Add missing interaction to trial tag
  frontend/src/assets/scss/badge.scss
  frontend/src/modules/layout/components/workspace-dropdown.vue
Labels: Bug

#369 Fix sorting in dashboard active members
  frontend/src/modules/dashboard/store/actions.js
Labels: Bug

#367 Update logos and images
  frontend/public/android-chrome-192x192.png
  frontend/public/android-chrome-512x512.png
  frontend/public/fonts/element-icons.ttf
  frontend/public/fonts/element-icons.woff
  frontend/public/icons/apple-touch-icon.png
  frontend/public/icons/logo/crowd.svg
  frontend/public/images/automations-empty-state.svg
  frontend/public/images/empty-state/eagle-eye.svg
  frontend/public/images/error/403.svg
  frontend/public/images/error/404.svg
  frontend/public/images/error/500.svg
  frontend/public/images/icon-all-black.png
  frontend/public/images/icon-black.png
  frontend/public/images/icon.png
  frontend/public/images/integrations/crunchbase.png
  frontend/public/images/integrations/custom.svg
  frontend/public/images/integrations/hackernews.svg
  frontend/public/images/integrations/linkedin.png
  frontend/public/images/integrations/make.svg
  frontend/public/images/integrations/reddit.svg
  frontend/public/images/invitation.jpg
  frontend/public/images/linkedin.svg
  frontend/public/images/logo-all-black.png
  frontend/public/images/logo-black.png
  frontend/public/images/logo.png
  frontend/public/images/logo/crowd.svg
  frontend/public/images/paywall/organizations.png
  frontend/public/images/real-data.svg
  frontend/public/images/sample-data.svg
  frontend/public/images/tenant-create.svg
  frontend/public/images/user-placeholder.png
  frontend/public/index.html
  frontend/src/integrations/crunchbase/config.js
  frontend/src/integrations/hackernews/config.js
  frontend/src/integrations/linkedin/config.js
  frontend/src/integrations/make/config.js
  frontend/src/integrations/reddit/config.js
  frontend/src/modules/auth/components/layout/auth-layout-side.vue
  frontend/src/modules/auth/layouts/auth-layout.vue
  frontend/src/modules/integration/components/integration-list.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/layout/components/paywall-modal.vue
  frontend/src/modules/layout/components/workspace-dropdown.vue
  frontend/src/modules/layout/pages/error-page.vue
  frontend/src/modules/layout/pages/paywall-page.vue
  frontend/src/modules/layout/pages/temporary-paywall-page.vue
  frontend/src/modules/onboard/pages/onboard-page.vue
  frontend/src/modules/report/pages/report-view-page-public.vue
  frontend/src/premium/eagle-eye/pages/eagle-eye-page.vue
Labels: Improvement

#370 Notes and tasks were being unlinked when updating tags
  backend/src/database/repositories/memberRepository.ts
Labels: Bug

#372 Change "Read more" URL for custom integrations
  frontend/src/modules/integration/components/integration-connect.vue
Labels: Bug

#365 Handle nodejs-worker SIGTERM gracefully
  backend/src/bin/nodejs-worker.ts
  backend/src/bin/worker/integrations.ts
  backend/src/serverless/integrations/services/integrationProcessor.ts
Labels: Improvement

#371 Update trial plan layout
  frontend/public/favicon.ico
  frontend/src/modules/settings/pages/plans-page.vue
Labels: Improvement

#373 Fix pre selection of member in tasks creation
  frontend/src/modules/task/components/task-form.vue
Labels: Bug

#374 Add members joinedAt filter and column to all views
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/member-model.js
  frontend/src/modules/member/store/state.js
  frontend/src/modules/organization/organization-model.js
  frontend/src/shared/fields/date-time-field.js
  frontend/src/shared/filter/components/filter-dropdown.vue
Labels: Improvement

#375 Fix most engaged view sorter
  frontend/src/modules/member/store/state.js
Labels: Improvement

#356 Asynchronous csv exports
  backend/config/custom-environment-variables.json
  backend/package-lock.json
  backend/package.json
  backend/src/api/auth/authMe.ts
  backend/src/api/member/index.ts
  backend/src/api/member/memberExport.ts
  backend/src/bin/jobs/downgradeExpiredTrialPlans.ts
  backend/src/bin/scripts/change-tenant-plan.ts
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/database/repositories/filters/queryParser.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/feature-flags/setTenantProperties.ts
  backend/src/i18n/en.ts
  backend/src/segment/identifyTenant.ts
  backend/src/serverless/microservices/nodejs/csv-export/csvExportWorker.ts
  backend/src/serverless/microservices/nodejs/csv-export/test.json
  backend/src/serverless/microservices/nodejs/messageTypes.ts
  backend/src/serverless/microservices/nodejs/package-lock.json
  backend/src/serverless/microservices/nodejs/package.json
  backend/src/serverless/microservices/nodejs/workerFactory.ts
  backend/src/serverless/utils/nodeWorkerSQS.ts
  backend/src/services/emailSender.ts
  backend/src/services/memberService.ts
  backend/src/types/common.ts
  frontend/src/assets/scss/confirm-dialog.scss
  frontend/src/modules/activity/components/activity-dropdown.vue
  frontend/src/modules/automation/components/automation-dropdown.vue
  frontend/src/modules/automation/pages/automation-list-page.vue
  frontend/src/modules/conversation/components/conversation-dropdown.vue
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/member/components/form/member-form-global-attributes.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/member/store/actions.js
  frontend/src/modules/notes/components/note-dropdown.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/organization/pages/organization-form-page.vue
  frontend/src/modules/report/components/report-dropdown.vue
  frontend/src/modules/report/components/report-grid-layout.vue
  frontend/src/modules/report/components/report-list-toolbar.vue
  frontend/src/modules/task/components/task-archived.vue
  frontend/src/modules/task/components/task-closed-dropdown.vue
  frontend/src/modules/task/components/task-dropdown.vue
  frontend/src/premium/community-help-center/components/community-help-center-settings.vue
  frontend/src/premium/community-help-center/components/community-help-center-toolbar.vue
  frontend/src/premium/user/components/list/user-list-toolbar.vue
  frontend/src/premium/user/components/user-dropdown.vue
  frontend/src/shared/confirm-dialog/confirm-dialog.js
  frontend/src/shared/dialog/confirm-dialog.js
  frontend/src/shared/dialog/information-dialog.js
  frontend/src/shared/error/errors.js
  frontend/src/shared/pagination/pagination-sorter.vue
  package-lock.json
Labels: Feature

#378 Fix joined date filter organization
  frontend/src/modules/organization/store/constants.js
Labels: Bug

#377 Fix member manual creation with email only
  frontend/src/modules/member/components/form/member-form-identities.vue
Labels: Bug

#379 Fix missing assignee label within task form
  backend/src/database/repositories/userRepository.ts
  frontend/src/modules/task/components/task-form.vue
  frontend/src/modules/task/task-model.js
Labels: Bug

#380 Add missing paywalls
  frontend/public/images/paywall/community-help-center.png
  frontend/public/images/paywall/eagle-eye.png
  frontend/src/modules/layout/components/paywall-modal.vue
  frontend/src/modules/layout/pages/paywall-page.vue
  frontend/src/premium/community-help-center/components/settings/_general.vue
  frontend/src/premium/eagle-eye/eagle-eye-routes.js
  frontend/tailwind.config.js
Labels: Improvement

#381 Remove integration task suggestion when there are active integrations
  frontend/src/modules/dashboard/components/dashboard-task.vue
  frontend/src/modules/task/components/task-suggested.vue
  frontend/src/modules/task/store/constants.js
Labels: Improvement

#382 Add application error handler to report unhandled and network issues
  frontend/src/main.js
  frontend/src/modules/layout/components/layout.vue
  frontend/src/shared/error/errors.js
  frontend/src/shared/monitoring/identify.js
  frontend/src/shared/segment/identify.js
Labels: Improvement

#376 Incoming webhook error log fix
  backend/src/database/repositories/incomingWebhookRepository.ts
  backend/src/serverless/integrations/workers/githubWebhookWorker.ts
  backend/src/types/webhooks.ts
Labels: Bug
