Repository CrowdDotDev/crowd.dev, pull requests merged in 2022-10, with the labels that each got.

#68 Bugfix for newly hosted webhook handler.
  backend/src/api/apiResponseHandler.ts
  backend/src/serverless/integrations/webhooks/github.ts
  backend/src/serverless/integrations/workers/githubWebhookWorker.ts
Labels: type:bug 🐞

#71 Frontend runtime configuration mode for self/cloud hosted image
  frontend/.env.dist.composed
  frontend/.env.dist.local
  frontend/Dockerfile.kube
  frontend/Dockerfile.kube.dockerignore
  frontend/public/index.html
  frontend/scripts/docker-entrypoint.sh
  frontend/src/config.js
  scripts/builders/frontend.sh
  scripts/cli
  scripts/services/frontend.yaml
Labels: type:enhancement ✨

#73 Remove SSL for local environment
  README.md
  backend/.env.dist
  backend/.env.dist.compose
  backend/.env.dist.composed
  backend/.env.dist.local
  backend/.env.dist.prod
  backend/.env.dist.staging
  backend/package.json
  backend/src/api/index.ts
  backend/src/api/integration/__tests__/integrationProtectedFields.test.ts
  backend/src/api/microservice/__tests__/microserviceProtectedFields.test.ts
  frontend/.env.dist
  frontend/.env.dist.local
  frontend/Dockerfile-frontend-dev
  frontend/Dockerfile.dev
  frontend/package.json
  frontend/src/modules/integration/components/integration-list.vue
  frontend/vue.config.js
  nginx/.gitignore
  nginx/Dockerfile-nginx
  nginx/ssl/init-certs.sh
  nginx/ssl/selfsigned_cert.pem
  nginx/ssl/selfsigned_key.pem
  nginx/templates/default.conf.template
  nginx/templates/default.conf.template.deploy
  premium/conversations/.dockerignore
  premium/conversations/Dockerfile-conversations
  premium/conversations/Dockerfile.dev
  scripts/cli
  scripts/scaffold.yaml
  scripts/services/api.yaml
  scripts/services/conversations.yaml
  scripts/services/frontend.yaml
  scripts/services/job-generator.yaml
  scripts/services/nodejs-worker.yaml
  scripts/services/premium-api.yaml
  scripts/services/premium-job-generator.yaml
  scripts/services/premium-python-worker.yaml
  scripts/services/python-worker.yaml
Labels: type:enhancement ✨, codeball:needs-careful-review

#79 Tables redesign (conversations, reports, and users)
  frontend/src/assets/scss/badge.scss
  frontend/src/assets/scss/buttons.scss
  frontend/src/assets/scss/index.scss
  frontend/src/assets/scss/table.scss
  frontend/src/assets/scss/tabs.scss
  frontend/src/modules/activity/components/activity-dropdown.vue
  frontend/src/modules/conversation/components/conversation-dropdown.vue
  frontend/src/modules/conversation/components/conversation-list-page.vue
  frontend/src/modules/conversation/components/conversation-list-table.vue
  frontend/src/modules/conversation/components/conversation-settings.vue
  frontend/src/modules/conversation/conversation-store.js
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/report/components/report-dropdown.vue
  frontend/src/modules/report/components/report-list-page.vue
  frontend/src/modules/report/components/report-list-table.vue
  frontend/src/modules/report/report-store.js
  frontend/src/modules/settings/components/settings-page.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-header.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-page.vue
  frontend/src/premium/user/components/user-dropdown.vue
  frontend/src/premium/user/components/user-list-table.vue
  frontend/src/premium/user/user-list-store.js
  frontend/src/shared/pagination/pagination.vue
Labels: type:enhancement ✨, codeball:needs-careful-review

#81 Activity and conversation cards & listing
  frontend/src/assets/scss/layout.scss
  frontend/src/modules/activity/components/activity-content.vue
  frontend/src/modules/activity/components/activity-dropdown.vue
  frontend/src/modules/activity/components/activity-item.vue
  frontend/src/modules/activity/components/activity-list.vue
  frontend/src/modules/activity/components/integrations/devto/activity-devto-channel.vue
  frontend/src/modules/activity/components/integrations/devto/activity-devto-content.vue
  frontend/src/modules/activity/components/integrations/devto/activity-devto-message.vue
  frontend/src/modules/activity/components/integrations/discord/activity-discord-channel.vue
  frontend/src/modules/activity/components/integrations/discord/activity-discord-content.vue
  frontend/src/modules/activity/components/integrations/discord/activity-discord-message.vue
  frontend/src/modules/activity/components/integrations/github/activity-github-channel.vue
  frontend/src/modules/activity/components/integrations/github/activity-github-message.vue
  frontend/src/modules/activity/components/integrations/slack/activity-slack-channel.vue
  frontend/src/modules/activity/components/integrations/slack/activity-slack-message.vue
  frontend/src/modules/activity/pages/activity-list-page.vue
  frontend/src/modules/conversation/components/conversation-dropdown.vue
  frontend/src/modules/conversation/components/conversation-form-page.vue
  frontend/src/modules/conversation/components/conversation-item.vue
  frontend/src/modules/conversation/components/conversation-list.vue
  frontend/src/modules/conversation/components/conversation-reply.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-item.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-item.vue
  frontend/src/modules/dashboard/components/dashboard-activities.vue
Labels: type:feature 🚀

#86 New integrations page
  frontend/public/images/custom-integration.svg
  frontend/public/images/linkedin.svg
  frontend/public/images/make.svg
  frontend/public/images/reddit.svg
  frontend/src/assets/scss/buttons.scss
  frontend/src/assets/scss/drawer.scss
  frontend/src/jsons/integrations.json
  frontend/src/middleware/auth/auth-guard.js
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/modules/integration/components/integration-list-page.vue
  frontend/src/modules/integration/components/integration-list.vue
  frontend/src/modules/integration/components/platforms/integration-custom.vue
  frontend/src/modules/integration/components/platforms/integration-devto-drawer.vue
  frontend/src/modules/integration/components/platforms/integration-devto.vue
  frontend/src/modules/integration/components/platforms/integration-discord.vue
  frontend/src/modules/integration/components/platforms/integration-github.vue
  frontend/src/modules/integration/components/platforms/integration-slack.vue
  frontend/src/modules/integration/components/platforms/integration-soon.vue
  frontend/src/modules/integration/components/platforms/integration-twitter-drawer.vue
  frontend/src/modules/integration/components/platforms/integration-twitter.vue
  frontend/src/modules/integration/integration-store.js
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
Labels: type:enhancement ✨, codeball:needs-careful-review

#83 Hotfix/cron timezone fix
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/package-lock.json
  backend/package.json
  backend/src/bin/job-generator.ts
  backend/src/bin/jobs/checkSqsQueues.ts
  backend/src/bin/jobs/index.ts
  backend/src/bin/jobs/weeklyAnalyticsEmailsCoordinator.ts
  backend/src/bin/nodejs-worker.ts
  backend/src/config/configTypes.ts
  backend/src/database/models/index.ts
  backend/src/utils/slack.ts
  premium/job-generator/src/job-generator.ts
  scripts/cli
Labels: type:enhancement ✨, codeball:needs-careful-review

#93 Add shared store
  frontend/src/modules/activity/activity-service.js
  frontend/src/modules/activity/store/actions.js
  frontend/src/modules/activity/store/getters.js
  frontend/src/modules/activity/store/mutations.js
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/store/actions.js
  frontend/src/modules/member/store/getters.js
  frontend/src/modules/member/store/mutations.js
  frontend/src/shared/filter/components/filter-dropdown.vue
  frontend/src/shared/filter/components/filter-list-item.vue
  frontend/src/shared/filter/components/filter-list-operator.vue
  frontend/src/shared/filter/components/filter-list.vue
  frontend/src/shared/filter/components/type/filter-type-boolean.vue
  frontend/src/shared/filter/components/type/filter-type-date.vue
  frontend/src/shared/filter/components/type/filter-type-keywords.vue
  frontend/src/shared/filter/components/type/filter-type-number.vue
  frontend/src/shared/filter/components/type/filter-type-search.vue
  frontend/src/shared/filter/components/type/filter-type-select-async.vue
  frontend/src/shared/filter/components/type/filter-type-select-group.vue
  frontend/src/shared/filter/components/type/filter-type-select-multi.vue
  frontend/src/shared/filter/components/type/filter-type-select.vue
  frontend/src/shared/filter/components/type/filter-type-string.vue
  frontend/src/shared/filter/helpers/build-api-payload.js
  frontend/src/shared/filter/helpers/different-util.js
  frontend/src/shared/filter/helpers/operators.js
  frontend/src/shared/filter/helpers/query-filter.js
  frontend/src/shared/filters/format-date-filter.js
  frontend/src/shared/filters/format-datetime-filter.js
  frontend/src/shared/shared-module.js
  frontend/src/shared/store/actions.js
  frontend/src/shared/store/constants.js
  frontend/src/shared/store/getters.js
  frontend/src/shared/store/index.js
  frontend/src/shared/store/mutations.js
Labels: codeball:needs-careful-review

#96 Feature/api v1 tweaks for dashboard
  backend/config/custom-environment-variables.json
  backend/src/api/components/conversation/examples.yaml
  backend/src/api/components/conversation/models.yaml
  backend/src/api/components/member/examples.yaml
  backend/src/api/components/member/models.yaml
  backend/src/api/components/member/query.yaml
  backend/src/api/components/organization/examples.yaml
  backend/src/api/components/organization/models.yaml
  backend/src/cubejs/schema/Identities.js
  backend/src/cubejs/schema/MemberIdentities.js
  backend/src/cubejs/schema/MemberOrganizations.js
  backend/src/cubejs/schema/Members.js
  backend/src/database/repositories/__tests__/conversationRepository.test.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/filters/__tests__/queryParser.test.ts
  backend/src/database/repositories/filters/queryParser.ts
  backend/src/database/repositories/filters/queryTypes.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/database/utils/sequelizeFilterUtils.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/__tests__/organizationService.test.ts
  frontend/src/modules/activity/activity-service.js
  frontend/src/modules/dashboard/store/actions.js
  frontend/src/modules/member/member-service.js
Labels: codeball:needs-careful-review

#97 Eagle eye redesign
  frontend/src/premium/eagle-eye/components/eagle-eye-counter.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-filter.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-header.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-list-item.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-list.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-page.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-search.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-sorter.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-tabs.vue
  frontend/src/premium/eagle-eye/eagle-eye-date-field.js
  frontend/src/premium/eagle-eye/eagle-eye-model.js
  frontend/src/premium/eagle-eye/eagle-eye-module.js
  frontend/src/premium/eagle-eye/eagle-eye-platform-field.js
  frontend/src/premium/eagle-eye/eagle-eye-routes.js
  frontend/src/premium/eagle-eye/eagle-eye-service.js
  frontend/src/premium/eagle-eye/eagle-eye-store.js
  frontend/src/premium/eagle-eye/store/actions.js
  frontend/src/premium/eagle-eye/store/constants.js
  frontend/src/premium/eagle-eye/store/getters.js
  frontend/src/premium/eagle-eye/store/index.js
  frontend/src/premium/eagle-eye/store/mutations.js
  frontend/src/premium/eagle-eye/store/state.js
  frontend/src/shared/filter/components/filter-dropdown.vue
  frontend/src/shared/filter/components/filter-list.vue
  frontend/src/shared/filter/components/type/filter-type-select-multi.vue
  frontend/src/shared/filter/components/type/filter-type-select.vue
  frontend/src/shared/filter/helpers/build-api-payload.js
Labels: type:enhancement ✨, codeball:needs-careful-review

#98 Manage workspaces
  frontend/src/assets/scss/badge.scss
  frontend/src/assets/scss/dialogs.scss
  frontend/src/modules/activity/components/activity-dropdown.vue
  frontend/src/modules/conversation/components/conversation-dropdown.vue
  frontend/src/modules/layout/components/support-dropdown.vue
  frontend/src/modules/layout/components/workspace-dropdown.vue
  frontend/src/modules/tenant/components/tenant-form-page.vue
  frontend/src/modules/tenant/components/tenant-form.vue
  frontend/src/modules/tenant/components/tenant-list-drawer.vue
  frontend/src/modules/tenant/components/tenant-list-page.vue
  frontend/src/modules/tenant/components/tenant-list-table.vue
  frontend/src/modules/tenant/components/tenant-list-toolbar.vue
  frontend/src/modules/tenant/store/actions.js
  frontend/src/modules/tenant/store/getters.js
  frontend/src/modules/tenant/store/index.js
  frontend/src/modules/tenant/store/mutations.js
  frontend/src/modules/tenant/store/state.js
  frontend/src/modules/tenant/tenant-destroy-store.js
  frontend/src/modules/tenant/tenant-form-store.js
  frontend/src/modules/tenant/tenant-invitation-store.js
  frontend/src/modules/tenant/tenant-list-store.js
  frontend/src/modules/tenant/tenant-module.js
  frontend/src/modules/tenant/tenant-routes.js
  frontend/src/modules/tenant/tenant-store.js
  frontend/tailwind.config.js
Labels: type:enhancement ✨, codeball:needs-careful-review

#99 Feature/onboarding backend
  backend/src/api/auth/authSignUp.ts
  backend/src/api/auth/authSocial.ts
  backend/src/database/models/tenant.ts
  backend/src/database/repositories/tenantRepository.ts
  backend/src/database/repositories/userRepository.ts
  backend/src/services/__tests__/tenantService.test.ts
  backend/src/services/auth/authService.ts
Labels: type:feature 🚀

#100 added a check to use either docker-compose or docker compose
  scripts/cli
Labels: type:enhancement ✨

#108 feature: Redesign settings executions list
  frontend/src/assets/scss/dialogs.scss
  frontend/src/modules/automation/components/list/automation-list-table.vue
  frontend/src/modules/automation/components/webhooks/webhook-execution-list.vue
  frontend/src/modules/automation/components/webhooks/webhook-execution.vue
  frontend/src/modules/automation/components/webhooks/webhook-form.vue
  frontend/src/modules/automation/pages/automation-list-page.vue
  frontend/src/modules/conversation/components/conversation-form.vue
  frontend/src/modules/conversation/components/conversation-list-filter.vue
  frontend/src/modules/conversation/components/conversation-settings.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/report/components/report-grid-layout.vue
  frontend/src/modules/settings/pages/settings-page.vue
  frontend/src/modules/settings/settings-routes.js
  frontend/src/modules/tag/components/tag-popover.vue
  frontend/src/modules/widget/components/dashboard/widget-benchmark.vue
  frontend/src/modules/widget/components/widget-number.vue
  frontend/src/premium/user/components/form/user-form.vue
  frontend/src/premium/user/components/list/user-list-table.vue
  frontend/src/premium/user/components/list/user-list-toolbar.vue
  frontend/src/premium/user/components/user-dropdown.vue
  frontend/src/premium/user/components/user-list-filter.vue
  frontend/src/premium/user/components/user-list-page.vue
  frontend/src/premium/user/components/user-view-page.vue
  frontend/src/premium/user/components/user-view-toolbar.vue
  frontend/src/premium/user/pages/user-edit-page.vue
  frontend/src/premium/user/pages/user-list-page.vue
  frontend/src/premium/user/pages/user-new-page.vue
  frontend/src/shared/dialog/dialog.vue
  frontend/src/shared/form/image-upload.vue
  frontend/src/shared/shared-module.js
Labels: type:feature 🚀, codeball:needs-careful-review

#104 Community help center redesign
  backend/package.json
  backend/source-local.sh
  backend/src/database/migrations/2022-10-24-add-enabled-to-conversation-settings.ts
  backend/src/database/models/conversationSettings.ts
  backend/src/database/sequelize-cli-config.ts
  backend/src/services/conversationService.ts
  frontend/src/assets/scss/form.scss
  frontend/src/assets/scss/table.scss
  frontend/src/modules/activity/components/activity-dropdown.vue
  frontend/src/modules/auth/auth-current-tenant.js
  frontend/src/modules/auth/auth-store.js
  frontend/src/modules/auth/store/getters.js
  frontend/src/modules/community-help-center/community-help-center-module.js
  frontend/src/modules/community-help-center/community-help-center-permissions.js
  frontend/src/modules/community-help-center/community-help-center-routes.js
  frontend/src/modules/community-help-center/components/community-help-center-conversation-drawer.vue
  frontend/src/modules/community-help-center/components/community-help-center-filter.vue
  frontend/src/modules/community-help-center/components/community-help-center-settings.vue
  frontend/src/modules/community-help-center/components/community-help-center-table.vue
  frontend/src/modules/community-help-center/components/community-help-center-tabs.vue
  frontend/src/modules/community-help-center/components/community-help-center-toolbar.vue
  frontend/src/modules/community-help-center/components/settings/_auto-publish.vue
  frontend/src/modules/community-help-center/components/settings/_general.vue
  frontend/src/modules/community-help-center/components/settings/_links.vue
  frontend/src/modules/community-help-center/components/settings/_theming.vue
  frontend/src/modules/community-help-center/components/settings/_toggle.vue
  frontend/src/modules/community-help-center/pages/community-help-center-page.vue
  frontend/src/modules/community-help-center/store/actions.js
  frontend/src/modules/community-help-center/store/constants.js
  frontend/src/modules/community-help-center/store/getters.js
  frontend/src/modules/community-help-center/store/index.js
  frontend/src/modules/community-help-center/store/mutations.js
  frontend/src/modules/community-help-center/store/state.js
  frontend/src/modules/conversation/components/conversation-details.vue
  frontend/src/modules/conversation/components/conversation-drawer.vue
  frontend/src/modules/conversation/components/conversation-dropdown.vue
  frontend/src/modules/conversation/components/conversation-form-page.vue
  frontend/src/modules/conversation/components/conversation-form.vue
  frontend/src/modules/conversation/components/conversation-list-page.vue
  frontend/src/modules/conversation/components/conversation-platform-tabs.vue
  frontend/src/modules/conversation/components/conversation-published-tabs.vue
  frontend/src/modules/conversation/components/conversation-settings.vue
  frontend/src/modules/conversation/conversation-module.js
  frontend/src/modules/conversation/conversation-routes.js
  frontend/src/modules/conversation/conversation-service.js
  frontend/src/modules/conversation/conversation-store.js
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-list.vue
  frontend/src/modules/index.js
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/report/components/report-dropdown.vue
  frontend/src/premium/user/components/user-dropdown.vue
  frontend/src/shared/store/actions.js
Labels: codeball:needs-careful-review

#111 Activity count fix
  frontend/src/modules/dashboard/components/dashboard-count.vue
Labels: type:bug 🐞, codeball:approved

#110 Sentiment - bug
  frontend/src/modules/activity/components/activity-item.vue
  frontend/src/modules/activity/components/activity-sentiment.vue
  frontend/src/modules/conversation/components/conversation-reply.vue
Labels: type:bug 🐞, codeball:needs-careful-review

#109 bug: Issues launch QA
  frontend/src/modules/activity/components/activity-dropdown.vue
  frontend/src/modules/automation/components/automation-dropdown.vue
  frontend/src/modules/community-help-center/components/community-help-center-settings.vue
  frontend/src/modules/community-help-center/components/community-help-center-toolbar.vue
  frontend/src/modules/conversation/components/conversation-dropdown.vue
  frontend/src/modules/conversation/components/conversation-settings.vue
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-channels.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/components/member-platform-input.vue
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/member/pages/member-merge-page.vue
  frontend/src/modules/report/components/report-dropdown.vue
  frontend/src/modules/report/components/report-grid-layout.vue
  frontend/src/modules/report/components/report-list-toolbar.vue
  frontend/src/modules/widget/components/dashboard/_settings/_benchmark-settings.vue
  frontend/src/plugins/confirm.js
  frontend/src/plugins/index.js
  frontend/src/premium/user/components/list/user-list-table.vue
  frontend/src/premium/user/components/list/user-list-toolbar.vue
  frontend/src/premium/user/components/user-dropdown.vue
  frontend/src/shared/form/custom-attribute-input.vue
Labels: type:bug 🐞

#115 Cube rendering fix
  frontend/src/modules/activity/components/integrations/discord/activity-discord-message.vue
  frontend/src/modules/activity/components/integrations/slack/activity-slack-message.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-sentiment.vue
  frontend/src/modules/dashboard/components/dashboard-count.vue
Labels: type:bug 🐞, codeball:needs-careful-review

#113 Reports (add/edit/view) redesign
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/scss/buttons.scss
  frontend/src/assets/scss/form.scss
  frontend/src/assets/scss/layout.scss
  frontend/src/modules/auth/pages/forgot-password-page.vue
  frontend/src/modules/auth/pages/invitation-page.vue
  frontend/src/modules/auth/pages/password-reset-page.vue
  frontend/src/modules/auth/pages/signin-page.vue
  frontend/src/modules/auth/pages/signup-page.vue
  frontend/src/modules/plan/components/plan-card-free.vue
  frontend/src/modules/plan/components/plan-card-paid.vue
  frontend/src/modules/report/components/report-create-dialog.vue
  frontend/src/modules/report/components/report-dropdown.vue
  frontend/src/modules/report/components/report-form-page.vue
  frontend/src/modules/report/components/report-form.vue
  frontend/src/modules/report/components/report-grid-layout.vue
  frontend/src/modules/report/components/report-list-table.vue
  frontend/src/modules/report/components/report-list-toolbar.vue
  frontend/src/modules/report/components/report-view-page-public.vue
  frontend/src/modules/report/components/report-view-page.vue
  frontend/src/modules/report/pages/report-form-page.vue
  frontend/src/modules/report/pages/report-list-page.vue
  frontend/src/modules/report/pages/report-view-page.vue
  frontend/src/modules/report/report-module.js
  frontend/src/modules/report/report-routes.js
  frontend/src/modules/report/report-service.js
  frontend/src/modules/report/report-store.js
  frontend/src/modules/report/store/actions.js
  frontend/src/modules/report/store/constants.js
  frontend/src/modules/report/store/getters.js
  frontend/src/modules/report/store/index.js
  frontend/src/modules/report/store/mutations.js
  frontend/src/modules/report/store/state.js
  frontend/src/modules/widget/components/cube/_query_builder/ChartType.vue
  frontend/src/modules/widget/components/cube/_query_builder/DateRangeSelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/DimensionSelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/FilterComponent.vue
  frontend/src/modules/widget/components/cube/_query_builder/GranularitySelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/Limit.vue
  frontend/src/modules/widget/components/cube/_query_builder/MeasureSelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/Order.vue
  frontend/src/modules/widget/components/cube/_query_builder/SyncModel.vue
  frontend/src/modules/widget/components/cube/_query_builder/TimeDimensionSelect.vue
  frontend/src/modules/widget/components/cube/widget-cube-builder.vue
  frontend/src/modules/widget/components/widget.vue
  frontend/src/modules/widget/widget-service.js
Labels: type:enhancement ✨, codeball:needs-careful-review

#118 Workspace issues & onboarding tenant creation
  frontend/src/modules/auth/auth-store.js
  frontend/src/modules/auth/store/actions.js
  frontend/src/modules/auth/store/mutations.js
  frontend/src/modules/dashboard/components/dashboard-filters.vue
  frontend/src/modules/layout/components/workspace-dropdown.vue
  frontend/src/modules/onboard/components/onboard-community.vue
  frontend/src/modules/onboard/layouts/onboard-layout.vue
  frontend/src/modules/onboard/onboard-routes.js
  frontend/src/modules/onboard/pages/onboard-page.vue
  frontend/src/modules/tenant/components/tenant-form.vue
  frontend/src/modules/tenant/components/tenant-list-drawer.vue
Labels: type:bug 🐞, codeball:needs-careful-review

#116 Sentiment: query fix
  frontend/src/modules/dashboard/components/activity/dashboard-activity-sentiment.vue
Labels: type:bug 🐞, codeball:approved

#114 bug: Activities and integrations critical issues
  frontend/src/jsons/integrations.json
  frontend/src/modules/activity/components/activity-list.vue
  frontend/src/modules/activity/components/list/activity-list-filter.vue
  frontend/src/modules/activity/pages/activity-list-page.vue
  frontend/src/modules/activity/store/actions.js
  frontend/src/modules/activity/store/state.js
  frontend/src/modules/audit-log/audit-log-store.js
  frontend/src/modules/automation/automation-store.js
  frontend/src/modules/automation/components/list/automation-list-table.vue
  frontend/src/modules/community-help-center/components/community-help-center-table.vue
  frontend/src/modules/conversation/components/conversation-list.vue
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/store/state.js
  frontend/src/modules/organization/store/getters.js
  frontend/src/modules/tenant/store/state.js
  frontend/src/premium/eagle-eye/components/eagle-eye-sorter.vue
  frontend/src/premium/eagle-eye/store/state.js
  frontend/src/premium/user/user-list-store.js
  frontend/src/shared/store/getters.js
  frontend/src/shared/store/mutations.js
Labels: type:bug 🐞, codeball:needs-careful-review

#121 Report charts
  frontend/src/modules/dashboard/store/state.js
  frontend/src/modules/report/components/report-grid-layout.vue
  frontend/src/modules/report/report-charts.js
  frontend/src/modules/widget/components/cube/widget-cube-builder.vue
  frontend/src/modules/widget/components/cube/widget-cube-renderer.vue
  frontend/src/modules/widget/components/cube/widget-cube.vue
  frontend/src/modules/widget/components/widget-number.vue
  frontend/tests/specs/e2e/auth/forgot-password.spec.js
  frontend/tests/specs/e2e/auth/password-reset.spec.js
Labels: type:feature 🚀, codeball:needs-careful-review

#122 Fix dashboard period
  frontend/src/modules/dashboard/store/state.js
Labels: type:bug 🐞, codeball:needs-careful-review

#127 Minor bug fixes & changes
  frontend/src/modules/auth/pages/forgot-password-page.vue
  frontend/src/modules/conversation/components/conversation-details.vue
  frontend/src/modules/dashboard/components/dashboard-activities.vue
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
Labels: type:bug 🐞

#128 Members items clickable
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/member/dashboard-member-item.vue
Labels: type:bug 🐞, codeball:approved

#131 Add some report and routes fixes
  frontend/public/images/auth/partners-nogrid.png
  frontend/public/images/auth/partners.png
  frontend/src/modules/activity/store/actions.js
  frontend/src/modules/activity/store/mutations.js
  frontend/src/modules/auth/components/layout/auth-layout-side.vue
  frontend/src/modules/community-help-center/store/actions.js
  frontend/src/modules/member/member-routes.js
  frontend/src/modules/member/store/actions.js
  frontend/src/modules/report/components/report-dropdown.vue
  frontend/src/modules/report/pages/report-view-page-public.vue
  frontend/src/modules/report/pages/report-view-page.vue
  frontend/src/modules/report/report-routes.js
  frontend/src/modules/report/store/actions.js
  frontend/src/modules/tenant/store/actions.js
  frontend/src/premium/eagle-eye/store/actions.js
  frontend/src/shared/store/actions.js
  frontend/src/shared/store/index.js
Labels: type:enhancement ✨

#130 bug: Critical menu issues
  frontend/public/icons/crowd-icons.svg
  frontend/src/modules/layout/components/account-dropdown.vue
  frontend/src/modules/layout/components/support-dropdown.vue
  frontend/src/modules/layout/components/workspace-dropdown.vue
  frontend/src/modules/member/components/member-last-activity.vue
  frontend/src/modules/member/components/view/member-view-activities.vue
Labels: codeball:approved

#129 New Sample Data
  .github/workflows/CI-node.yaml
  backend/package-lock.json
  backend/package.json
  backend/src/database/initializers/sample-data.json
  backend/src/database/repositories/conversationRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/database/repositories/tagRepository.ts
  backend/src/serverless/microservices/python/crowd-check-merge-members/crowd/check_merge_members/merge_suggestions.py
  backend/src/services/__tests__/sampleDataService.test.ts
  backend/src/services/activityService.ts
  backend/src/services/conversationService.ts
  backend/src/services/memberAttributeSettingsService.ts
  backend/src/services/memberService.ts
  backend/src/services/organizationService.ts
  backend/src/services/sampleDataService.ts
  backend/src/services/tagService.ts
  frontend/src/modules/conversation/components/conversation-list.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/tag/components/tag-list.vue
  frontend/src/shared/avatar/avatar.vue
  premium/conversations/package.json
Labels: codeball:needs-careful-review

#132 Organizations enrichment through GitHub API
  backend/jest.config.js
  backend/src/database/attributes/member/github.ts
  backend/src/database/initializers/entities/2022-10-26-api-v1-organization-cache-enrichment.ts
  backend/src/database/initializers/sample-data.json
  backend/src/database/repositories/organizationCacheRepository.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/usecases/github/graphql/baseQuery.ts
  backend/src/serverless/integrations/usecases/github/graphql/organizations.ts
  backend/src/serverless/integrations/webhooks/__tests__/github.test.ts
  backend/src/serverless/integrations/webhooks/github.ts
  backend/src/serverless/microservices/nodejs/automation/workers/__tests__/newActivityWorker.test.ts
  backend/src/services/__tests__/activityService.test.ts
  backend/src/services/__tests__/memberAttributeSettingsService.test.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/organizationService.ts
  frontend/src/modules/member/components/list/member-list-table.vue
Labels: codeball:needs-careful-review

#139 Hotfix/slack integration fix
  backend/config/production.json
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/slackIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/twitterIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/twitterReachIntegrationService.ts
  backend/src/types/integration/stepResult.ts
Labels: type:bug 🐞, codeball:needs-careful-review

#140 Fix store not being resetted on onboard page
  frontend/src/modules/activity/store/state.js
  frontend/src/modules/auth/store/actions.js
  frontend/src/modules/auth/store/state.js
  frontend/src/modules/community-help-center/store/state.js
  frontend/src/modules/dashboard/store/state.js
  frontend/src/modules/member/store/state.js
  frontend/src/modules/onboard/onboard-routes.js
  frontend/src/modules/organization/store/state.js
  frontend/src/modules/report/store/state.js
  frontend/src/modules/tenant/store/state.js
  frontend/src/premium/eagle-eye/store/state.js
  frontend/src/premium/user/user-destroy-store.js
  frontend/src/premium/user/user-form-store.js
  frontend/src/premium/user/user-list-store.js
  frontend/src/premium/user/user-view-store.js
  frontend/src/store/index.js
Labels: type:bug 🐞

#141 Fix Recent Actitivies tab in home
  frontend/src/modules/dashboard/components/activity/dashboard-activity-list.vue
Labels: type:bug 🐞

#142 Bugfix/merge suggestions
  backend/src/serverless/microservices/python/crowd-backend/crowd/backend/repository/repository.py
  backend/src/serverless/microservices/python/crowd-check-merge-members/crowd/check_merge_members/merge_suggestions.py
Labels: type:bug 🐞

#147 Add alert to create a fix flow for integrations with errors
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/modules/integration/components/integration-list-page.vue
  frontend/src/modules/integration/integration-store.js
  frontend/src/modules/layout/components/layout.vue
  frontend/src/shared/banner/banner.vue
Labels: type:enhancement ✨

#148 Fix community help center default sorter
  frontend/src/modules/community-help-center/store/state.js
Labels: type:bug 🐞

#149 Empty states for all pages
  frontend/src/middleware/auth/reset-store.js
  frontend/src/modules/activity/components/activity-list.vue
  frontend/src/modules/automation/pages/automation-list-page.vue
  frontend/src/modules/community-help-center/components/community-help-center-table.vue
  frontend/src/modules/conversation/components/conversation-list.vue
  frontend/src/modules/member/components/list/member-list-filter.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/onboard/onboard-routes.js
  frontend/src/modules/report/components/report-list-table.vue
  frontend/src/modules/report/pages/report-list-page.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-list.vue
  frontend/src/shared/empty-state/empty-state-cta.vue
  frontend/src/shared/shared-module.js
  frontend/src/store/index.js
Labels: codeball:needs-careful-review

#150 Fixes to filter-dropdown and activities conversation view
  frontend/src/modules/conversation/components/conversation-list.vue
  frontend/src/shared/filter/components/filter-dropdown.vue
Labels: type:bug 🐞
