Repository CrowdDotDev/crowd.dev, pull requests merged in 2022-08, with the labels that each got.

#5 Simplified start of development environment
  .github/workflows/CI-node.yaml
  .github/workflows/api-docs.yaml
  backend/Dockerfile-backend
  backend/Dockerfile-backend-dev
  backend/package.json
  backend/src/serverless/integrations/usecases/chat/getThreads.ts
  backend/util/install-all.sh
  backend/util/postinstall.sh
  start.sh
Labels: type:enhancement ✨

#6 Hotfix/eagle eye events
  backend/src/api/eagleEyeContent/eagleEyeContentList.ts
  backend/src/api/eagleEyeContent/eagleEyeContentSearch.ts
  backend/src/database/repositories/__tests__/eagleEyeContentRepository.test.ts
  backend/src/database/repositories/eagleEyeContentRepository.ts
  backend/src/services/eagleEyeContentService.ts
Labels: type:bug 🐞

#9 Fix EagleEye keyword filter
  backend/src/database/repositories/__tests__/eagleEyeContentRepository.test.ts
  backend/src/database/repositories/eagleEyeContentRepository.ts
Labels: type:bug 🐞, codeball:approved

#10 Weekly analytics emails for all workspace users
  backend/src/database/repositories/__tests__/userRepository.test.ts
  backend/src/database/repositories/userRepository.ts
  backend/src/serverless/microservices/nodejs/analytics/workers/weeklyAnalyticsEmailsWorker.ts
  backend/src/serverless/microservices/nodejs/nodeMicroserviceSQS.ts
  backend/src/serverless/microservices/nodejs/serverless.yml
  start.sh
Labels: type:bug 🐞

#13 Tweak eagle eye search bar UX
  frontend/src/i18n/en.js
  frontend/src/premium/eagle-eye/components/eagle-eye-counter.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-filter.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-list.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-page.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-search.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-sorter.vue
  frontend/src/premium/eagle-eye/eagle-eye-store.js
  frontend/src/shared/form/autocomplete-many-input.vue
  frontend/src/shared/form/autocomplete-one-input.vue
  frontend/src/shared/form/keywords-input.vue
  frontend/src/shared/shared-module.js
Labels: type:enhancement ✨

#7 Fixed edge case in engagement score normalisation
  backend/src/serverless/microservices/python/crowd-members-score/crowd/members_score/members_score.py
Labels: type:bug 🐞

#11 DEV.to integration
  backend/package-lock.json
  backend/package.json
  backend/src/api/integration/helpers/devtoCreateOrUpdate.ts
  backend/src/api/integration/helpers/devtoValidators.ts
  backend/src/api/integration/index.ts
  backend/src/database/repositories/__tests__/eagleEyeContentRepository.test.ts
  backend/src/database/repositories/activityRepository.ts
  backend/src/database/repositories/eagleEyeContentRepository.ts
  backend/src/serverless/integrations/iterators/__tests__/devtoIterator.test.ts
  backend/src/serverless/integrations/iterators/devtoIterator.ts
  backend/src/serverless/integrations/iterators/discordIterator.ts
  backend/src/serverless/integrations/iterators/githubIterator.ts
  backend/src/serverless/integrations/iterators/slackIterator.ts
  backend/src/serverless/integrations/iterators/twitterIterator.ts
  backend/src/serverless/integrations/package-lock.json
  backend/src/serverless/integrations/package.json
  backend/src/serverless/integrations/types/devtoTypes.ts
  backend/src/serverless/integrations/usecases/__tests__/devto.api.test.ts
  backend/src/serverless/integrations/usecases/devto/getOrganization.ts
  backend/src/serverless/integrations/usecases/devto/getUser.ts
  backend/src/serverless/integrations/usecases/devto/types.ts
  backend/src/serverless/integrations/workers/devtoWorker.ts
  backend/src/serverless/microservices/python/serverless/package.json
  backend/src/services/__tests__/conversationService.test.ts
  backend/src/services/activityService.ts
  backend/src/services/conversationService.ts
  backend/src/services/integrationService.ts
  backend/src/services/user/permissionChecker.ts
  backend/util/install-all.sh
  frontend/src/assets/scss/buttons.scss
  frontend/src/i18n/en.js
  frontend/src/jsons/integrations.json
  frontend/src/modules/activity/components/activity-header.vue
  frontend/src/modules/activity/components/activity-list-feed-item.vue
  frontend/src/modules/activity/components/activity-platform-tabs.vue
  frontend/src/modules/community-member/components/community-member-channels.vue
  frontend/src/modules/community-member/components/community-member-platform-tabs.vue
  frontend/src/modules/conversation/components/conversation-list-table.vue
  frontend/src/modules/conversation/components/conversation-platform-tabs.vue
  frontend/src/modules/integration/components/devto-integration-widget.vue
  frontend/src/modules/integration/components/integration-list.vue
  frontend/src/modules/integration/integration-service.js
  frontend/src/modules/integration/integration-store.js
  frontend/src/modules/widget/components/dashboard/widget-newest-members.vue
Labels: type:feature 🚀
