Repository CrowdDotDev/crowd.dev, pull requests merged in 2022-09, with the labels that each got.

#38 Twitter follows duplicate activities bug
  backend/src/database/initializers/twitterSourceIdsFixedTimestamps.ts
  backend/src/serverless/integrations/iterators/__tests__/twitterIterator.test.ts
  backend/src/serverless/integrations/iterators/twitterIterator.ts
Labels: type:bug 🐞

#44 Fixed
  backend/src/services/activityService.ts
Labels: type:bug 🐞, codeball:approved

#41 Fix some issues on open.crowd.dev
  premium/conversations/components/claim.vue
  premium/conversations/components/conversation.vue
  premium/conversations/components/conversationDetail.vue
  premium/conversations/package-lock.json
  premium/conversations/package.json
Labels: type:bug 🐞

#39 Feature/api v1 settings member attributes
  backend/src/api/components/core.yaml
  backend/src/api/components/examples.yaml
  backend/src/api/components/inputs.yaml
  backend/src/api/components/parameters.yaml
  backend/src/api/components/responses.yaml
  backend/src/api/settings/index.ts
  backend/src/api/settings/memberAttributeCreate.ts
  backend/src/api/settings/memberAttributeDestroy.ts
  backend/src/api/settings/memberAttributeFind.ts
  backend/src/api/settings/memberAttributeList.ts
  backend/src/api/settings/memberAttributeUpdate.ts
  backend/src/database/attributes/attribute.ts
  backend/src/database/attributes/member/devto.ts
  backend/src/database/attributes/member/discord.ts
  backend/src/database/attributes/member/enums.ts
  backend/src/database/attributes/member/github.ts
  backend/src/database/attributes/member/slack.ts
  backend/src/database/attributes/member/twitter.ts
  backend/src/database/attributes/types.ts
  backend/src/database/models/index.ts
  backend/src/database/models/memberAttributeSettings.ts
  backend/src/database/repositories/__tests__/memberAttributeSettingsRepository.test.ts
  backend/src/database/repositories/memberAttributeSettingsRepository.ts
  backend/src/database/repositories/types/memberAttributeSettingsTypes.ts
  backend/src/i18n/en.ts
  backend/src/security/permissions.ts
  backend/src/serverless/integrations/workers/devtoWorker.ts
  backend/src/serverless/integrations/workers/discordWorker.ts
  backend/src/serverless/integrations/workers/githubWorker.ts
  backend/src/serverless/integrations/workers/slackWorker.ts
  backend/src/serverless/integrations/workers/twitterWorker.ts
  backend/src/services/__tests__/memberAttributeSettingsService.test.ts
  backend/src/services/integrationService.ts
  backend/src/services/memberAttributeSettingsService.ts
  backend/src/utils/__tests__/camelCaseNames.test.ts
  backend/src/utils/camelCaseNames.ts
Labels: type:feature 🚀, codeball:needs-careful-review

#52 Eagle eye related hotfixes
  frontend/src/modules/integration/components/integration-list.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-list-item.vue
  frontend/src/shared/form/keywords-input.vue
Labels: type:bug 🐞

#47 GitHub integration: check repo can be queried before starting parsing
  backend/src/serverless/integrations/coordinators/devtoCoordinator.ts
  backend/src/serverless/integrations/coordinators/discordCoordinator.ts
  backend/src/serverless/integrations/coordinators/slackCoordinator.ts
  backend/src/serverless/integrations/coordinators/twitterCoordinator.ts
  backend/src/serverless/integrations/coordinators/twitterReachCoordinator.ts
  backend/src/serverless/integrations/iterators/__tests__/baseIteration.test.ts
  backend/src/serverless/integrations/iterators/__tests__/baseIteratorStatic.test.ts
  backend/src/serverless/integrations/iterators/__tests__/devtoIterator.test.ts
  backend/src/serverless/integrations/iterators/__tests__/discordIterator.test.ts
  backend/src/serverless/integrations/iterators/__tests__/githubIterator.test.ts
  backend/src/serverless/integrations/iterators/__tests__/slackIterator.test.ts
  backend/src/serverless/integrations/iterators/__tests__/testIterator.ts
  backend/src/serverless/integrations/iterators/__tests__/twitterIterator.test.ts
  backend/src/serverless/integrations/iterators/baseIterator.ts
  backend/src/serverless/integrations/iterators/devtoIterator.ts
  backend/src/serverless/integrations/iterators/discordIterator.ts
  backend/src/serverless/integrations/iterators/githubIterator.ts
  backend/src/serverless/integrations/iterators/slackIterator.ts
  backend/src/serverless/integrations/iterators/twitterIterator.ts
  backend/src/serverless/integrations/iterators/twitterReachIterator.ts
  backend/src/serverless/integrations/types/regularTypes.ts
  backend/src/serverless/integrations/workers/githubWorker.ts
  backend/src/services/integrationService.ts
Labels: codeball:needs-careful-review

#54 Add some fixes after merging vue3 and automations
  frontend/src/assets/scss/layout.scss
  frontend/src/modules/tenant/components/tenant-list-table.vue
  frontend/src/premium/user/components/user-list-table.vue
Labels: type:bug 🐞

#46 Engagement score KMeans bug hotfix
  backend/src/serverless/microservices/python/crowd-members-score/crowd/members_score/members_score.py
Labels: type:bug 🐞

#55 Hotfix: githubWebhook sourced automation triggers not firing
  backend/src/serverless/integrations/serverless.yml
Labels: type:bug 🐞, codeball:approved

#57 Feature/api v1 members refactor
  backend/src/api/components/core.yaml
  backend/src/api/components/examples.yaml
  backend/src/database/attributes/attribute.ts
  backend/src/database/attributes/member/crowd.ts
  backend/src/database/attributes/member/devto.ts
  backend/src/database/attributes/member/enums.ts
  backend/src/database/attributes/member/github.ts
  backend/src/database/attributes/member/twitter.ts
  backend/src/database/initializers/sample-data.json
  backend/src/database/models/member.ts
  backend/src/database/models/settings.ts
  backend/src/database/repositories/__tests__/activityRepository.test.ts
  backend/src/database/repositories/__tests__/conversationRepository.test.ts
  backend/src/database/repositories/__tests__/eagleEyeContentRepository.test.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/__tests__/taskRepository.test.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/types/memberTypes.ts
  backend/src/database/utils/sequelizeTestUtils.ts
  backend/src/i18n/en.ts
  backend/src/serverless/dbOperations/__tests__/operationsWorker.test.ts
  backend/src/serverless/integrations/iterators/__tests__/devtoIterator.test.ts
  backend/src/serverless/integrations/iterators/__tests__/discordIterator.test.ts
  backend/src/serverless/integrations/iterators/__tests__/githubIterator.test.ts
  backend/src/serverless/integrations/iterators/__tests__/slackIterator.test.ts
  backend/src/serverless/integrations/iterators/__tests__/twitterIterator.test.ts
  backend/src/serverless/integrations/iterators/__tests__/twitterReachIterator.test.ts
  backend/src/serverless/integrations/iterators/devtoIterator.ts
  backend/src/serverless/integrations/iterators/discordIterator.ts
  backend/src/serverless/integrations/iterators/githubIterator.ts
  backend/src/serverless/integrations/iterators/slackIterator.ts
  backend/src/serverless/integrations/iterators/twitterIterator.ts
  backend/src/serverless/integrations/iterators/twitterReachIterator.ts
  backend/src/serverless/integrations/types/messageTypes.ts
  backend/src/serverless/integrations/webhooks/__tests__/github.test.ts
  backend/src/serverless/integrations/webhooks/github.ts
  backend/src/serverless/integrations/workers/devtoWorker.ts
  backend/src/serverless/integrations/workers/discordWorker.ts
  backend/src/services/__tests__/activityService.test.ts
  backend/src/services/__tests__/conversationService.test.ts
  backend/src/services/__tests__/eagleEyeContentService.test.ts
  backend/src/services/__tests__/memberAttributeSettingsService.test.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/__tests__/sampleDataService.test.ts
  backend/src/services/__tests__/tenantService.test.ts
  backend/src/services/__tests__/test-sample-data.json
  backend/src/services/activityService.ts
  backend/src/services/auth/passportStrategies/slackStrategy.ts
  backend/src/services/helpers/__tests__/helperMerge.test.ts
  backend/src/services/helpers/merge.ts
  backend/src/services/memberAttributeSettingsService.ts
  backend/src/services/memberService.ts
  backend/src/services/sampleDataService.ts
  backend/src/utils/platforms.ts
Labels: type:feature 🚀, codeball:needs-careful-review

#56 Feature/advanced filtering
  backend/src/database/repositories/__tests__/activityRepository.test.ts
  backend/src/database/repositories/__tests__/conversationRepository.test.ts
  backend/src/database/repositories/__tests__/taskRepository.test.ts
  backend/src/database/repositories/activityRepository.ts
  backend/src/database/repositories/conversationRepository.ts
  backend/src/database/repositories/eagleEyeContentRepository.ts
  backend/src/database/repositories/filters/queryParser.ts
  backend/src/database/repositories/filters/queryTypes.ts
  backend/src/database/repositories/integrationRepository.ts
  backend/src/database/repositories/microserviceRepository.ts
  backend/src/database/repositories/noteRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/database/repositories/reportRepository.ts
  backend/src/database/repositories/tagRepository.ts
  backend/src/database/repositories/taskRepository.ts
  backend/src/database/repositories/widgetRepository.ts
  backend/src/i18n/en.ts
  backend/src/services/__tests__/activityService.test.ts
  backend/src/services/activityService.ts
  backend/src/services/aws.ts
Labels: codeball:needs-careful-review

#58 Fix report create/edit
  frontend/src/modules/report/components/report-form.vue
  frontend/src/modules/widget/components/cube/_query_builder/TimeDimensionSelect.vue
  frontend/src/modules/widget/components/cube/widget-cube-builder.vue
Labels: type:bug 🐞

#63 Copy tweak in Dashboard
  frontend/src/modules/dashboard/components/dashboard-datetime-based-widgets.vue
Labels: type:bug 🐞, codeball:approved

#64 Weekly emails new conversations filter should use first activity time
  backend/src/cubejs/metrics/newConversations.ts
  backend/src/cubejs/schema/Conversations.js
  backend/src/serverless/microservices/nodejs/analytics/workers/weeklyAnalyticsEmailsWorker.ts
  backend/src/serverless/microservices/nodejs/package-lock.json
  backend/src/serverless/microservices/nodejs/package.json
  backend/src/services/cubejs/cubeDimensions.ts
Labels: type:bug 🐞, codeball:needs-careful-review

#65 Tweak devto integration error handling
  frontend/src/assets/scss/layout.scss
  frontend/src/modules/integration/components/devto-integration-widget.vue
Labels: type:enhancement ✨

#61 Added organizations from GitHub
  backend/src/serverless/integrations/iterators/githubIterator.ts
  backend/src/serverless/integrations/types/messageTypes.ts
  backend/src/serverless/integrations/usecases/github/graphql/baseQuery.ts
  backend/src/serverless/integrations/usecases/github/graphql/organizations.ts
  backend/src/serverless/integrations/webhooks/__tests__/github.test.ts
  backend/src/serverless/integrations/webhooks/github.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/memberService.ts
Labels: codeball:needs-careful-review
