Repository CrowdDotDev/crowd.dev, pull requests merged in 2022-11, with the labels that each got.

#152 Cube preaggregations refresh triggers more often
  backend/src/cubejs/schema/Activities.js
  backend/src/cubejs/schema/Members.js
  backend/src/cubejs/schema/Sentiment.js
  backend/src/database/initializers/sample-data.json
Labels: codeball:needs-careful-review

#158 Add dash to empty information in member profile
  frontend/src/modules/member/components/view/member-view-header.vue
Labels: type:enhancement ✨

#156 Update sentiment color on dashboard page
  frontend/src/modules/dashboard/components/activity/dashboard-activity-sentiment.vue
Labels: type:enhancement ✨

#160 Rename premium/conversations to premium/community-help-center
  docker/docker-compose.default.yaml
  premium/community-help-center/.dockerignore
  premium/community-help-center/.gitignore
  premium/community-help-center/Dockerfile.dev
  premium/community-help-center/README.md
  premium/community-help-center/app.vue
  premium/community-help-center/assets/css/tailwind.css
  premium/community-help-center/components/avatar.vue
  premium/community-help-center/components/barAutocomplete.vue
  premium/community-help-center/components/claim.vue
  premium/community-help-center/components/conversation.vue
  premium/community-help-center/components/conversationDetail.vue
  premium/community-help-center/components/conversationWrapper.vue
  premium/community-help-center/components/loading.vue
  premium/community-help-center/components/mainCta.vue
  premium/community-help-center/components/mainSection.vue
  premium/community-help-center/components/navbar.vue
  premium/community-help-center/components/platformIcon.vue
  premium/community-help-center/components/tenantPage.vue
  premium/community-help-center/components/topHeader.vue
  premium/community-help-center/composables/states.ts
  premium/community-help-center/helpers/avatarColors.ts
  premium/community-help-center/helpers/config.ts
  premium/community-help-center/helpers/fromNow.ts
  premium/community-help-center/helpers/makeStyles.ts
  premium/community-help-center/helpers/searchClient.ts
  premium/community-help-center/helpers/transformData.ts
  premium/community-help-center/nuxt.config.ts
  premium/community-help-center/package-lock.json
  premium/community-help-center/package.json
  premium/community-help-center/pages/[slug]/[conversation].vue
  premium/community-help-center/pages/[slug]/index.vue
  premium/community-help-center/pages/index.vue
  premium/community-help-center/public/favicon.ico
  premium/community-help-center/sample-data/sampleData.ts
  premium/community-help-center/sample-data/specs.json
  premium/community-help-center/sample-data/update.ts
  premium/community-help-center/server/api/getConversations.ts
  premium/community-help-center/server/api/getTenantSlug.ts
  premium/community-help-center/server/api/getTenants.ts
  premium/community-help-center/server/api/helpers/fromNow.ts
  premium/community-help-center/server/api/helpers/getTenant.ts
  premium/community-help-center/server/api/helpers/initSearch.ts
  premium/community-help-center/server/api/helpers/transform.ts
  premium/community-help-center/server/middleware/tenantSlugMiddleware.ts
  premium/community-help-center/tailwind.config.js
  premium/community-help-center/tsconfig.json
Labels: type:enhancement ✨

#162 Update README.md
  README.md
Labels: codeball:approved

#161 Hide premium modules from UI
  frontend/src/config.js
  frontend/src/modules/community-help-center/community-help-center-module.js
  frontend/src/modules/index.js
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/settings/pages/settings-page.vue
  frontend/src/premium/community-help-center/community-help-center-module.js
  frontend/src/premium/community-help-center/community-help-center-permissions.js
  frontend/src/premium/community-help-center/community-help-center-routes.js
  frontend/src/premium/community-help-center/components/community-help-center-conversation-drawer.vue
  frontend/src/premium/community-help-center/components/community-help-center-filter.vue
  frontend/src/premium/community-help-center/components/community-help-center-settings.vue
  frontend/src/premium/community-help-center/components/community-help-center-table.vue
  frontend/src/premium/community-help-center/components/community-help-center-tabs.vue
  frontend/src/premium/community-help-center/components/community-help-center-toolbar.vue
  frontend/src/premium/community-help-center/components/settings/_auto-publish.vue
  frontend/src/premium/community-help-center/components/settings/_general.vue
  frontend/src/premium/community-help-center/components/settings/_links.vue
  frontend/src/premium/community-help-center/components/settings/_theming.vue
  frontend/src/premium/community-help-center/components/settings/_toggle.vue
  frontend/src/premium/community-help-center/pages/community-help-center-page.vue
  frontend/src/premium/community-help-center/store/actions.js
  frontend/src/premium/community-help-center/store/constants.js
  frontend/src/premium/community-help-center/store/getters.js
  frontend/src/premium/community-help-center/store/index.js
  frontend/src/premium/community-help-center/store/mutations.js
  frontend/src/premium/community-help-center/store/state.js
Labels: type:enhancement ✨, codeball:needs-careful-review

#163 Skip starting premium services using normal cli commands
  scripts/cli
Labels: type:bug 🐞

#159 Update copy of empty states
  frontend/src/modules/activity/components/activity-list.vue
  frontend/src/modules/automation/components/webhooks/webhook-execution-list.vue
  frontend/src/modules/conversation/components/conversation-list.vue
  frontend/src/modules/report/components/report-list-table.vue
  frontend/src/premium/community-help-center/community-help-center-routes.js
  frontend/src/premium/community-help-center/components/community-help-center-table.vue
  frontend/src/shared/empty-state/empty-state.vue
  frontend/src/shared/shared-module.js
Labels: type:enhancement ✨, type:bug 🐞

#164 Fix filters display and no results found state on members
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/pages/member-list-page.vue
Labels: type:bug 🐞

#167 Fix missing counter and paginator in Community Help Center page
  frontend/src/modules/automation/pages/automation-list-page.vue
  frontend/src/modules/report/components/report-list-table.vue
  frontend/src/premium/community-help-center/components/community-help-center-table.vue
  frontend/src/premium/user/components/list/user-list-table.vue
  frontend/src/shared/pagination/pagination-sorter.vue
Labels: type:bug 🐞

#168 Update sentiment filter to number format
  frontend/src/modules/activity/activity-sentiment-field.js
  frontend/src/shared/filter/helpers/build-api-payload.js
Labels: type:enhancement ✨

#166 Display numbers in compact format
  frontend/src/modules/activity/activity-date-field.js
  frontend/src/modules/activity/components/activity-header.vue
  frontend/src/modules/activity/components/activity-item.vue
  frontend/src/modules/automation/components/list/automation-list-table.vue
  frontend/src/modules/conversation/components/conversation-details.vue
  frontend/src/modules/conversation/components/conversation-item.vue
  frontend/src/modules/conversation/components/conversation-reply.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-item.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-item.vue
  frontend/src/modules/dashboard/components/dashboard-activities.vue
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/member/components/member-last-activity.vue
  frontend/src/modules/member/components/member-reach.vue
  frontend/src/modules/member/components/view/member-view-activities.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/modules/member/store/constants.js
  frontend/src/modules/widget/components/dashboard/widget-benchmark.vue
  frontend/src/modules/widget/components/dashboard/widget-newest-members.vue
  frontend/src/premium/community-help-center/components/community-help-center-table.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-list-item.vue
  frontend/src/premium/eagle-eye/eagle-eye-date-field.js
  frontend/src/shared/fields/date-field.js
  frontend/src/shared/fields/date-range-field.js
  frontend/src/shared/filter/components/filter-list-item.vue
  frontend/src/utils/date.js
  frontend/src/utils/github-get-star-history.js
  frontend/src/utils/number.js
  frontend/src/utils/time-ago.js
Labels: type:enhancement ✨

#169 Fix reach column on members list
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/utils/number.js
Labels: type:bug 🐞

#165 Automations Optimization, Devto automation activity type frontend fix & cli script for starting premium services
  backend/package.json
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/__tests__/taskRepository.test.ts
  backend/src/database/utils/sequelizeTestUtils.ts
  backend/src/serverless/dbOperations/__tests__/operationsWorker.test.ts
  backend/src/serverless/microservices/nodejs/automation/workers/newActivityWorker.ts
  backend/src/serverless/microservices/nodejs/automation/workers/newMemberWorker.ts
  backend/src/serverless/microservices/nodejs/automation/workers/util.ts
  backend/src/serverless/microservices/nodejs/automation/workers/webhookWorker.ts
  backend/src/serverless/microservices/nodejs/messageTypes.ts
  backend/src/serverless/microservices/nodejs/nodeMicroserviceSQS.ts
  backend/src/serverless/microservices/nodejs/workerFactory.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/activityService.ts
  backend/src/services/memberService.ts
  docker/docker-compose.test.yaml
  frontend/src/i18n/en.js
  frontend/src/jsons/activity-types.json
  premium/community-help-center/Dockerfile.dev
  scripts/cli
  scripts/services/community-help-center.yaml
  scripts/services/conversations.yaml
  scripts/utils
Labels: type:enhancement ✨, type:bug 🐞, codeball:needs-careful-review

#154 Removing redundant last activity plain in weekly emails conversations
  backend/.env.dist.composed
  backend/.env.dist.local
  backend/src/serverless/microservices/nodejs/analytics/workers/weeklyAnalyticsEmailsWorker.ts
Labels: type:bug 🐞, codeball:needs-careful-review

#171 Merge suggestions endpoint with pagination
  backend/src/api/tenant/tenantMembersToMerge.ts
  backend/src/database/repositories/filters/__tests__/queryParser.test.ts
  backend/src/database/repositories/filters/queryParser.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/__tests__/tenantService.test.ts
  backend/src/services/memberService.ts
  backend/src/services/tenantService.ts
Labels: codeball:needs-careful-review

#172 Update delete confirmation dialogs
  frontend/src/modules/activity/components/activity-dropdown.vue
  frontend/src/modules/automation/components/automation-dropdown.vue
  frontend/src/modules/conversation/components/conversation-dropdown.vue
  frontend/src/modules/conversation/components/conversation-form.vue
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-platform-input.vue
  frontend/src/modules/report/components/report-dropdown.vue
  frontend/src/modules/report/components/report-grid-layout.vue
  frontend/src/modules/report/components/report-list-toolbar.vue
  frontend/src/modules/widget/components/widget.vue
  frontend/src/premium/community-help-center/components/community-help-center-toolbar.vue
  frontend/src/premium/user/components/list/user-list-table.vue
  frontend/src/premium/user/components/list/user-list-toolbar.vue
  frontend/src/premium/user/components/user-dropdown.vue
  frontend/src/shared/confirm-dialog/confirm-dialog.js
  frontend/src/shared/form/custom-attribute-input.vue
Labels: type:enhancement ✨

#174 Member list returns full reach object & Standardization of member endpoints' outputs
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/__tests__/tenantService.test.ts
  backend/src/services/tenantService.ts
Labels: type:enhancement ✨, codeball:needs-careful-review

#170 When fetching Discord threads we are returning error instead of throwing it
  backend/src/serverless/integrations/usecases/chat/getThreads.ts
  scripts/cli
Labels: type:bug 🐞, codeball:needs-careful-review

#177 Get notes enhancements
  backend/src/database/repositories/__tests__/noteRepository.test.ts
  backend/src/database/repositories/noteRepository.ts
  backend/src/services/__tests__/memberService.test.ts
Labels: type:enhancement ✨, codeball:needs-careful-review

#179 Fix copy public url in CHC
  frontend/src/modules/conversation/components/conversation-dropdown.vue
Labels: type:bug 🐞

#175 Store views refactor, member tweaks/fixes, and more
  frontend/src/modules/activity/components/activity-list.vue
  frontend/src/modules/activity/store/actions.js
  frontend/src/modules/activity/store/state.js
  frontend/src/modules/conversation/components/conversation-list.vue
  frontend/src/modules/member/components/form/member-form-details.vue
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/list/member-list-tabs.vue
  frontend/src/modules/member/components/member-reach.vue
  frontend/src/modules/member/components/member-sentiment.vue
  frontend/src/modules/member/components/view/member-view-activities.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/modules/member/member-model.js
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/member/store/constants.js
  frontend/src/modules/member/store/state.js
  frontend/src/modules/report/components/report-list-table.vue
  frontend/src/modules/report/store/actions.js
  frontend/src/modules/report/store/mutations.js
  frontend/src/modules/report/store/state.js
  frontend/src/premium/community-help-center/components/community-help-center-table.vue
  frontend/src/premium/community-help-center/store/state.js
  frontend/src/shared/fields/generic-field.js
  frontend/src/shared/fields/json-field.js
  frontend/src/shared/filter/components/filter-dropdown.vue
  frontend/src/shared/filter/components/filter-list.vue
  frontend/src/shared/store/actions.js
  frontend/src/shared/store/getters.js
  frontend/src/shared/store/mutations.js
Labels: type:enhancement ✨, codeball:needs-careful-review

#178 Fix minor style issues and platform component
  frontend/src/assets/scss/table.scss
  frontend/src/modules/auth/pages/profile-form-page.vue
  frontend/src/modules/automation/components/list/automation-list-table.vue
  frontend/src/modules/member/components/member-channels.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/widget/components/dashboard/widget-newest-members.vue
  frontend/src/premium/community-help-center/components/community-help-center-table.vue
  frontend/src/premium/user/components/list/user-list-table.vue
  frontend/src/shared/platform/platform.vue
  frontend/src/shared/shared-module.js
Labels: type:bug 🐞, codeball:needs-careful-review

#182 `python-worker` module not found error bugfix
  backend/src/serverless/microservices/python/Dockerfile.kube
  backend/src/serverless/microservices/python/crowd-members-score/setup.py
  backend/src/serverless/microservices/python/start-python-worker.sh
Labels: type:enhancement ✨, type:bug 🐞

#186 Remove suffix from tenant slug
  frontend/src/modules/conversation/components/conversation-dropdown.vue
Labels: type:bug 🐞

#183 Fix reset view in Community Help Center and other modules
  frontend/src/premium/community-help-center/components/community-help-center-tabs.vue
  frontend/src/shared/filter/components/type/filter-type-search.vue
  frontend/src/shared/platform/platform.vue
Labels: type:bug 🐞

#188 Fix delete conversations
  frontend/src/i18n/en.js
  frontend/src/modules/conversation/conversation-service.js
Labels: type:bug 🐞

#193 Add email to support dropdown
  frontend/public/icons/crowd-icons.svg
  frontend/src/modules/layout/components/account-dropdown.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/layout/components/support-dropdown.vue
  frontend/src/shared/svg/svg.vue
Labels: type:enhancement ✨, type:bug 🐞

#192 Fix empty drawer after publish conversation
  frontend/src/premium/community-help-center/components/community-help-center-table.vue
  frontend/src/premium/community-help-center/pages/community-help-center-page.vue
Labels: type:bug 🐞

#180 Member notes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/scss/content.scss
  frontend/src/assets/scss/index.scss
  frontend/src/i18n/en.js
  frontend/src/main.js
  frontend/src/modules/activity/components/activity-content.vue
  frontend/src/modules/activity/components/integrations/devto/activity-devto-content.vue
  frontend/src/modules/activity/components/integrations/discord/activity-discord-content.vue
  frontend/src/modules/member/components/view/member-view-activities.vue
  frontend/src/modules/member/components/view/member-view-notes.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/modules/notes/components/note-dropdown.vue
  frontend/src/modules/notes/components/note-editor.vue
  frontend/src/modules/notes/components/note-item.vue
  frontend/src/modules/notes/note-model.js
  frontend/src/modules/notes/note-service.js
  frontend/src/plugins/sanitize.js
  frontend/src/premium/eagle-eye/components/eagle-eye-list-item.vue
  frontend/src/shared/form/editor.vue
Labels: type:feature 🚀, codeball:needs-careful-review

#190 Bad tenant url on tenant creation
  backend/src/database/repositories/__tests__/tenantRepository.test.ts
  backend/src/database/repositories/tenantRepository.ts
  backend/src/i18n/en.ts
  backend/src/services/__tests__/conversationService.test.ts
  backend/src/services/conversationService.ts
  backend/src/utils/__tests__/getCleanString.test.ts
  backend/src/utils/getCleanString.ts
Labels: type:enhancement ✨, codeball:needs-careful-review

#194 Added enter & esc key triggers to note editor
  frontend/src/modules/notes/components/note-editor.vue
Labels: type:feature 🚀

#196 Fix issue with load more in eagle eye
  frontend/src/premium/eagle-eye/components/eagle-eye-list.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-page.vue
  frontend/src/premium/eagle-eye/store/actions.js
  frontend/src/premium/eagle-eye/store/mutations.js
  frontend/src/shared/store/mutations.js
Labels: type:bug 🐞

#198 Fix menu UI/UX issues
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/layout/components/workspace-dropdown.vue
Labels: type:enhancement ✨

#200 Improve twitter hashtag configuration flow
  frontend/src/assets/scss/buttons.scss
  frontend/src/modules/integration/components/integration-connect.vue
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/modules/integration/components/platforms/integration-twitter-drawer.vue
  frontend/src/modules/integration/components/platforms/integration-twitter.vue
  frontend/src/modules/layout/components/menu.vue
Labels: type:enhancement ✨, codeball:needs-careful-review

#199 Add member NEW and TEAM badges
  frontend/src/assets/scss/badge.scss
  frontend/src/modules/activity/components/activity-item.vue
  frontend/src/modules/conversation/components/conversation-details.vue
  frontend/src/modules/conversation/components/conversation-item.vue
  frontend/src/modules/conversation/components/conversation-reply.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-item.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-item.vue
  frontend/src/modules/dashboard/components/member/dashboard-member-item.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-badge.vue
  frontend/src/modules/member/components/member-display-name.vue
  frontend/src/modules/member/components/member-engagement-level.vue
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
Labels: type:enhancement ✨

#197 Tasks module updates
  backend/src/api/components/task/examples.yaml
  backend/src/api/components/task/inputs.yaml
  backend/src/api/components/task/responses.yaml
  backend/src/api/note/noteCreate.ts
  backend/src/api/note/noteDestroy.ts
  backend/src/api/note/noteFind.ts
  backend/src/api/note/noteQuery.ts
  backend/src/api/note/noteUpdate.ts
  backend/src/api/task/index.ts
  backend/src/api/task/taskAssignTo.ts
  backend/src/api/task/taskAssignToByEmail.ts
  backend/src/api/task/taskBatchOperations.ts
  backend/src/api/task/taskCreate.ts
  backend/src/api/task/taskDestroy.ts
  backend/src/api/task/taskFind.ts
  backend/src/api/task/taskQuery.ts
  backend/src/api/task/taskUpdate.ts
  backend/src/api/task/taskUpdateStatus.ts
  backend/src/database/initializers/suggested-tasks.json
  backend/src/database/migrations/U1667915166__multipleTaskAssignees.sql
  backend/src/database/migrations/V1667915166__multipleTaskAssignees.sql
  backend/src/database/models/task.ts
  backend/src/database/repositories/__tests__/taskRepository.test.ts
  backend/src/database/repositories/taskRepository.ts
  backend/src/database/repositories/userRepository.ts
  backend/src/i18n/en.ts
  backend/src/security/permissions.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/__tests__/taskService.test.ts
  backend/src/services/__tests__/tenantService.test.ts
  backend/src/services/taskService.ts
  backend/src/services/tenantService.ts
  backend/tsconfig.json
Labels: type:enhancement ✨, codeball:needs-careful-review

#203 Fix integrations page on tenant switch
  frontend/src/modules/auth/store/actions.js
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/modules/integration/components/integration-list.vue
Labels: type:bug 🐞

#205 Add links to dashboard sentiment widget
  frontend/src/modules/activity/components/list/activity-list-filter.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-sentiment.vue
Labels: type:enhancement ✨

#206 Tweak toasts, alerts, and banners UI
  frontend/src/assets/scss/toast.scss
  frontend/src/modules/integration/components/integration-list-page.vue
  frontend/src/modules/integration/integration-store.js
  frontend/src/shared/alert/alert.vue
  frontend/src/shared/banner/banner.vue
  frontend/src/shared/message/message.js
  frontend/tailwind.config.js
Labels: type:enhancement ✨

#201 Discord integration to API
  backend/.gitignore
  backend/src/database/attributes/member/discord.ts
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
  backend/src/serverless/integrations/types/discordTypes.ts
  backend/src/serverless/integrations/usecases/chat/getMessages.ts
  backend/src/serverless/integrations/usecases/discord/getChannels.ts
  backend/src/serverless/integrations/usecases/discord/getMembers.ts
  backend/src/serverless/integrations/usecases/discord/getMessages.ts
  backend/src/serverless/integrations/usecases/discord/getThreads.ts
  backend/src/services/__tests__/memberAttributeSettingsService.test.ts
  backend/src/services/aws.ts
Labels: type:enhancement ✨

#211 Delete unused modules, components and styles
  frontend/src/assets/scss/filter.scss
  frontend/src/assets/scss/index.scss
  frontend/src/assets/scss/layout.scss
  frontend/src/assets/scss/plan.scss
  frontend/src/modules/audit-log/audit-log-exporter-fields.js
  frontend/src/modules/audit-log/audit-log-model.js
  frontend/src/modules/audit-log/audit-log-module.js
  frontend/src/modules/audit-log/audit-log-permissions.js
  frontend/src/modules/audit-log/audit-log-routes.js
  frontend/src/modules/audit-log/audit-log-service.js
  frontend/src/modules/audit-log/audit-log-store.js
  frontend/src/modules/audit-log/components/audit-log-filter.vue
  frontend/src/modules/audit-log/components/audit-log-page.vue
  frontend/src/modules/audit-log/components/audit-log-table.vue
  frontend/src/modules/audit-log/components/audit-log-toolbar.vue
  frontend/src/modules/index.js
  frontend/src/modules/plan/components/plan-card-free.vue
  frontend/src/modules/plan/components/plan-card-paid.vue
  frontend/src/modules/plan/components/plan-page.vue
  frontend/src/modules/plan/plan-module.js
  frontend/src/modules/plan/plan-permissions.js
  frontend/src/modules/plan/plan-routes.js
  frontend/src/modules/plan/plan-service.js
  frontend/src/modules/plan/plan-store.js
  frontend/src/shared/filter/filter-preview.vue
  frontend/src/shared/filter/filter-toggle.vue
  frontend/src/shared/shared-module.js
Labels: type:bug 🐞

#212 Better discord logging
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
  backend/src/serverless/integrations/types/discordTypes.ts
  backend/src/serverless/integrations/usecases/discord/getChannels.ts
  backend/src/serverless/integrations/usecases/discord/getMembers.ts
  backend/src/serverless/integrations/usecases/discord/getMessages.ts
  backend/src/serverless/integrations/usecases/discord/getThreads.ts
Labels: type:enhancement ✨

#202 Tasks
  frontend/src/app.vue
  frontend/src/assets/scss/dropdown.scss
  frontend/src/modules/activity/components/activity-content.vue
  frontend/src/modules/dashboard/components/dashboard-header.vue
  frontend/src/modules/dashboard/components/dashboard-task.vue
  frontend/src/modules/dashboard/pages/dashboard-page.vue
  frontend/src/modules/index.js
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/member/components/view/member-view-activities.vue
  frontend/src/modules/member/components/view/member-view-tasks.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/modules/task/components/task-archived.vue
  frontend/src/modules/task/components/task-closed-dropdown.vue
  frontend/src/modules/task/components/task-closed.vue
  frontend/src/modules/task/components/task-dropdown.vue
  frontend/src/modules/task/components/task-form.vue
  frontend/src/modules/task/components/task-item.vue
  frontend/src/modules/task/components/task-open.vue
  frontend/src/modules/task/components/task-sorting.vue
  frontend/src/modules/task/components/task-suggested.vue
  frontend/src/modules/task/pages/task-page.vue
  frontend/src/modules/task/store/actions.js
  frontend/src/modules/task/store/getters.js
  frontend/src/modules/task/store/index.js
  frontend/src/modules/task/store/mutations.js
  frontend/src/modules/task/store/state.js
  frontend/src/modules/task/task-model.js
  frontend/src/modules/task/task-module.js
  frontend/src/modules/task/task-permissions.js
  frontend/src/modules/task/task-routes.js
  frontend/src/modules/task/task-service.js
  frontend/src/security/permissions.js
  frontend/src/shared/avatar/avatar.vue
  frontend/src/shared/drawer/drawer.vue
  frontend/src/shared/form/autocomplete-many-input.vue
  frontend/tailwind.config.js
Labels: type:feature 🚀, codeball:needs-careful-review

#213 Filter for trending conversations
  frontend/src/modules/activity/store/constants.js
  frontend/src/modules/activity/store/state.js
Labels: type:bug 🐞

#214 Check conversation publishable before loading into the search engine
  backend/src/database/initializers/suggested-tasks.json
  backend/src/services/conversationService.ts
Labels: type:bug 🐞, codeball:needs-careful-review

#217 Tweak conversation drawer UI, add member links
  frontend/src/modules/activity/components/activity-item.vue
  frontend/src/modules/conversation/components/conversation-details.vue
  frontend/src/modules/conversation/components/conversation-item.vue
  frontend/src/modules/conversation/components/conversation-reply.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-item.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-item.vue
  frontend/src/modules/dashboard/components/member/dashboard-member-item.vue
  frontend/src/modules/member/components/member-badge.vue
  frontend/src/modules/member/components/member-display-name.vue
Labels: type:enhancement ✨

#215 Fix custom attributes with show true visibility
  frontend/src/modules/member/components/view/member-view-aside.vue
Labels: type:bug 🐞

#220 Bugfix/average sentiment calculation
  backend/src/cubejs/schema/Activities.js
  backend/src/cubejs/schema/Identities.js
  backend/src/cubejs/schema/MemberIdentities.js
  backend/src/cubejs/schema/MemberOrganizations.js
  backend/src/cubejs/schema/Members.js
  backend/src/cubejs/schema/Organizations.js
  backend/src/cubejs/schema/Sentiment.js
  backend/src/cubejs/schema/Tags.js
  backend/src/database/migrations/U1668524084__averageSentimentCalculationFix.sql
  backend/src/database/migrations/V1668524084__averageSentimentCalculationFix.sql
Labels: type:bug 🐞

#210 Html sanitization for notes and tasks
  backend/src/database/repositories/noteRepository.ts
  backend/src/database/repositories/taskRepository.ts
Labels: type:enhancement ✨, codeball:approved

#219 Add event tracking to tasks
  backend/src/api/task/taskCreate.ts
  backend/src/api/task/taskUpdate.ts
Labels: type:enhancement ✨, codeball:approved

#221 C-67: Fix labels in widget creation
  frontend/src/i18n/en.js
  frontend/src/modules/widget/components/cube/_query_builder/DimensionSelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/MeasureSelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/TimeDimensionSelect.vue
Labels: type:bug 🐞

#224 Add tooltip to CHC public page link
  frontend/src/premium/community-help-center/pages/community-help-center-page.vue
Labels: type:enhancement ✨

#223 Add conversation item hover state
  frontend/src/modules/conversation/components/conversation-item.vue
Labels: type:bug 🐞

#225 Fix members findById average sentiment calculation
  backend/src/database/repositories/memberRepository.ts
Labels: type:bug 🐞

#227 Fix redirect after conversation/activity destroy on dashboard
  frontend/src/modules/activity/store/actions.js
  frontend/src/modules/conversation/components/conversation-dropdown.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-list.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-list.vue
  frontend/src/shared/store/actions.js
Labels: type:bug 🐞

#222 Reset dashboard after tenant selection
  frontend/src/modules/dashboard/components/dashboard-active-integrations.vue
  frontend/src/modules/dashboard/components/dashboard-filters.vue
  frontend/src/modules/dashboard/components/dashboard-task.vue
  frontend/src/modules/dashboard/store/actions.js
Labels: type:bug 🐞

#228 Average sentiment exclude zeros fix
  backend/src/database/migrations/U1668615936__averageSentimentExcludeZeroFix.sql
  backend/src/database/migrations/V1668615936__averageSentimentExcludeZeroFix.sql
Labels: type:bug 🐞

#230 Slack & Discord rate limit temporary fix
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/integrations/services/integrationServiceBase.ts
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
  backend/src/serverless/integrations/usecases/slack/getChannels.ts
  backend/src/serverless/integrations/usecases/slack/getMember.ts
  backend/src/serverless/integrations/usecases/slack/getMembers.ts
  backend/src/serverless/integrations/usecases/slack/getMessages.ts
  backend/src/serverless/integrations/usecases/slack/getMessagesInThreads.ts
  backend/src/serverless/integrations/usecases/slack/getTeam.ts
Labels: type:bug 🐞, codeball:needs-careful-review

#229 Tweak tasks menu badge and active tab
  frontend/src/app.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/task/components/task-open.vue
  frontend/src/modules/task/store/actions.js
  frontend/src/modules/task/store/getters.js
Labels: type:enhancement ✨

#231 Fix merging members page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
Labels: type:bug 🐞, codeball:needs-careful-review

#232 Development frontend image for testing
  scripts/builders/frontend-dev.sh
Labels: type:enhancement ✨

#234 Improve members table scroll
  frontend/src/modules/member/components/list/member-list-table.vue
Labels: type:enhancement ✨

#235 Fix member reach tooltip height/overflow
  frontend/src/assets/scss/popover.scss
  frontend/src/modules/member/components/view/member-view-header.vue
Labels: type:bug 🐞

#237 New integrations should use the second bot token if available
  backend/config/custom-environment-variables.json
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
  backend/src/services/integrationService.ts
Labels: type:bug 🐞

#238 Fix make primary button in the merge members dialog
  frontend/src/modules/member/components/member-dropdown.vue
Labels: type:bug 🐞

#239 Organization new filters
  frontend/src/modules/organization/organization-employees-field.js
  frontend/src/modules/organization/organization-member-count-field.js
  frontend/src/modules/organization/organization-model.js
  frontend/src/shared/filter/components/filter-list-item.vue
  frontend/src/shared/filter/components/type/filter-type-number.vue
  frontend/src/shared/filter/helpers/build-api-payload.js
Labels: type:feature 🚀

#240 Fix custom scroll z-index
  frontend/src/modules/member/components/list/member-list-table.vue
Labels: type:bug 🐞

#241 Add note event tracking
  backend/src/api/note/noteCreate.ts
  backend/src/api/note/noteDestroy.ts
  backend/src/api/note/noteUpdate.ts
Labels: type:enhancement ✨, codeball:approved

#236 Oauth2 PKCE state using redis
  backend/.env.dist.composed
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/package-lock.json
  backend/package.json
  backend/src/api/auth/authSocial.ts
  backend/src/api/index.ts
  backend/src/api/integration/helpers/twitterAuthenticate.ts
  backend/src/api/integration/helpers/twitterAuthenticateCallback.ts
  backend/src/api/integration/index.ts
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/middlewares/passportStrategyMiddleware.ts
  backend/src/middlewares/redisMiddleware.ts
  backend/src/services/auth/passportStrategies/googleStrategy.ts
  backend/src/services/auth/passportStrategies/redisPKCEStore.ts
  backend/src/services/auth/passportStrategies/slackStrategy.ts
  backend/src/services/auth/passportStrategies/staticPKCEStore.ts
  backend/src/services/auth/passportStrategies/twitterStrategy.ts
  backend/src/utils/redis.ts
  scripts/builders/redis.sh
  scripts/cli
  scripts/deploy/kubernetes/.backend.env
  scripts/deploy/kubernetes/redis.yaml
  scripts/deploy/pre-built/backend.env
  scripts/deploy/pre-built/scaffold-services.yaml
  scripts/scaffold.yaml
  scripts/scaffold/redis/Dockerfile
  scripts/scaffold/redis/redis.conf
Labels: type:enhancement ✨, codeball:needs-careful-review

#243 Re-added member badge
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-badge.vue
Labels: type:bug 🐞

#242 Slack rate limit error detection and delay handling
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/integrations/types/slackTypes.ts
  backend/src/serverless/integrations/usecases/slack/getChannels.ts
  backend/src/serverless/integrations/usecases/slack/getMember.ts
  backend/src/serverless/integrations/usecases/slack/getMembers.ts
  backend/src/serverless/integrations/usecases/slack/getMessages.ts
  backend/src/serverless/integrations/usecases/slack/getMessagesInThreads.ts
  backend/src/serverless/integrations/usecases/slack/getTeam.ts
  backend/src/types/baseError.ts
  backend/src/types/integration/rateLimitError.ts
Labels: type:bug 🐞

#244 Process integration script
  backend/package-lock.json
  backend/package.json
  backend/src/bin/scripts/banner.txt
  backend/src/bin/scripts/process-integration.ts
Labels: type:enhancement ✨

#245 Github integration paging problem
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/usecases/github/graphql/organizations.ts
  backend/tsconfig.json
Labels: type:bug 🐞

#250 Fix members export action
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/store/actions.js
Labels: type:bug 🐞

#246 Refactor organization store
  frontend/src/modules/member/store/state.js
  frontend/src/modules/organization/organization-list-exporter-fields.js
  frontend/src/modules/organization/store/actions.js
  frontend/src/modules/organization/store/constants.js
  frontend/src/modules/organization/store/getters.js
  frontend/src/modules/organization/store/mutations.js
  frontend/src/modules/organization/store/state.js
Labels: type:feature 🚀, codeball:needs-careful-review

#247 Activity and organization entities new filters
  backend/src/api/components/organization/examples.yaml
  backend/src/api/components/organization/query.yaml
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/activityRepository.ts
  backend/src/database/repositories/filters/__tests__/queryParser.test.ts
  backend/src/database/repositories/filters/queryParser.ts
  backend/src/database/repositories/filters/queryTypes.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/__tests__/memberService.test.ts
Labels: type:feature 🚀, codeball:needs-careful-review

#252 Organizations list page
  frontend/public/images/crunchbase_logo.png
  frontend/public/images/linkedin_logo.png
  frontend/src/assets/scss/badge.scss
  frontend/src/assets/scss/buttons.scss
  frontend/src/i18n/en.js
  frontend/src/integrations/crunchbase/config.js
  frontend/src/integrations/crunchbase/index.js
  frontend/src/integrations/integrations-config.js
  frontend/src/integrations/linkedin/config.js
  frontend/src/modules/activity/activity-model.js
  frontend/src/modules/conversation/conversation-model.js
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/dashboard/components/organization/dashboard-organization-item.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/layout/components/workspace-dropdown.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-badge.vue
  frontend/src/modules/member/components/member-channels.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/store/actions.js
  frontend/src/modules/organization/components/list/organization-list-filter.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-tabs.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/components/organization-identities.vue
  frontend/src/modules/organization/components/organization-name.vue
  frontend/src/modules/organization/organization-employees-field.js
  frontend/src/modules/organization/organization-field.js
  frontend/src/modules/organization/organization-model.js
  frontend/src/modules/organization/organization-module.js
  frontend/src/modules/organization/organization-platform-field.js
  frontend/src/modules/organization/organization-routes.js
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-form-page.vue
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/modules/organization/pages/organization-view-page.vue
  frontend/src/modules/organization/store/actions.js
  frontend/src/modules/organization/store/constants.js
  frontend/src/modules/organization/store/state.js
  frontend/src/shared/fields/activity-date-field.js
  frontend/src/shared/filter/components/filter-list-item.vue
  frontend/src/shared/filter/components/type/filter-type-select.vue
  frontend/src/shared/filter/helpers/build-api-payload.js
  frontend/src/shared/platform/platform.vue
  frontend/src/utils/number.js
Labels: type:feature 🚀, codeball:needs-careful-review

#258 Fixing API service error logging
  backend/src/api/apiResponseHandler.ts
  backend/src/middlewares/errorMiddleware.ts
Labels: Bug

#257 Organization Form and Profile pages
  backend/src/database/migrations/U1669396956__addLocationWebsiteAndGithubToOrganizations.sql
  backend/src/database/migrations/V1669396956__addLocationWebsiteAndGithubToOrganizations.sql
  backend/src/database/models/organization.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/security/permissions.ts
  backend/src/serverless/integrations/webhooks/github.ts
  frontend/src/i18n/en.js
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/member/components/member-channels.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/modules/organization/components/form/organization-form-details.vue
  frontend/src/modules/organization/components/form/organization-form-identities.vue
  frontend/src/modules/organization/components/organization-identities.vue
  frontend/src/modules/organization/components/organization-name.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/modules/organization/components/view/organization-view-members.vue
  frontend/src/modules/organization/organization-model.js
  frontend/src/modules/organization/organization-routes.js
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-form-page.vue
  frontend/src/modules/organization/pages/organization-view-page.vue
  frontend/src/shared/form/string-array-input.vue
  frontend/src/shared/platform/platform.vue
  frontend/src/shared/shared-module.js
  frontend/src/utils/number.js
Labels: type:feature 🚀, codeball:needs-careful-review

#265 Change copy and href on /integrations page
  frontend/src/modules/integration/components/integration-list-page.vue
Labels: Improvement

#253 Re-add LogRocket
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.js
  frontend/src/store/index.js
Labels: Improvement

#268 Tenant attributes tracking
  backend/src/api/tenant/tenantCreate.ts
  backend/src/services/tenantService.ts
Labels: Bug

#266 Add links to source in member activities' list
  frontend/src/modules/member/components/view/member-view-activities.vue
Labels: Improvement

#270 Fixed an issue that occurred when fetching twitter followers.
  backend/src/serverless/integrations/services/integrations/twitterIntegrationService.ts
  backend/src/serverless/integrations/usecases/slack/getMember.ts
  backend/src/serverless/integrations/usecases/twitter/getFollowers.ts
Labels: codeball:needs-careful-review, Bug

#273 Production deploy workflow - currently deploys to staging for testing
  .github/workflows/production-deploy.yaml
Labels: Feature

#269 Fix onboarding banner copy
  frontend/src/modules/layout/components/layout.vue
Labels: codeball:approved, Bug

#263 Add event tracking to organizations
  backend/src/api/member/memberList.ts
  backend/src/api/organization/organizationCreate.ts
  backend/src/api/organization/organizationQuery.ts
  backend/src/services/tenantService.ts
Labels: codeball:needs-careful-review, Feature

#275 Production deployment workflows
  .github/actions/deploy-service/action.yaml
  .github/actions/slack-notify/action.yaml
  .github/workflows/production-deploy.yaml
  .github/workflows/staging-deploy-backend.yaml
  .github/workflows/staging-deploy-frontend.yaml
  .github/workflows/staging-deploy-premium-job-generator.yaml
  .github/workflows/staging-deploy-premium-python-backend.yaml
  .github/workflows/staging-deploy-python-worker.yaml
Labels: Feature

#287 Organizations' members empty state
  frontend/src/modules/organization/components/view/organization-view-members.vue
Labels: codeball:approved

#255 Add website, location, and github to organizations
  backend/src/database/migrations/U1669396956__addLocationWebsiteAndGithubToOrganizations.sql
  backend/src/database/migrations/V1669396956__addLocationWebsiteAndGithubToOrganizations.sql
  backend/src/database/models/organization.ts
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/webhooks/github.ts
  backend/src/services/__tests__/memberService.test.ts
Labels: codeball:needs-careful-review, Improvement

#276 Organization cache simplify enrichment
  backend/src/database/migrations/U1669737732__organizationCacheEnrichedBoolean.sql
  backend/src/database/migrations/U1669802927__organizationCacheMissingFields.sql
  backend/src/database/migrations/V1669737732__organizationCacheEnrichedBoolean.sql
  backend/src/database/migrations/V1669802927__organizationCacheMissingFields.sql
  backend/src/database/models/organizationCache.ts
  backend/src/database/repositories/__tests__/organizationCacheRepository.test.ts
  backend/src/database/repositories/organizationCacheRepository.ts
  backend/src/i18n/en.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/webhooks/github.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/__tests__/organizationService.test.ts
  backend/src/services/organizationService.ts
Labels: codeball:needs-careful-review, Improvement

#289 Fix average sentiment filter throwing a 500 error
  frontend/src/shared/fields/sentiment-field.js
  frontend/src/shared/filter/helpers/build-api-payload.js
Labels: codeball:needs-careful-review, Bug

#274 Organizations module
  frontend/public/images/crunchbase_logo.png
  frontend/public/images/linkedin_logo.png
  frontend/src/assets/scss/badge.scss
  frontend/src/assets/scss/buttons.scss
  frontend/src/i18n/en.js
  frontend/src/integrations/crunchbase/config.js
  frontend/src/integrations/crunchbase/index.js
  frontend/src/integrations/integrations-config.js
  frontend/src/integrations/linkedin/config.js
  frontend/src/modules/activity/activity-model.js
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/conversation/conversation-model.js
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/dashboard/components/organization/dashboard-organization-item.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/layout/components/workspace-dropdown.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-badge.vue
  frontend/src/modules/member/components/member-channels.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/modules/member/store/actions.js
  frontend/src/modules/organization/components/form/organization-form-details.vue
  frontend/src/modules/organization/components/form/organization-form-identities.vue
  frontend/src/modules/organization/components/list/organization-list-filter.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-tabs.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/components/organization-identities.vue
  frontend/src/modules/organization/components/organization-name.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/modules/organization/components/view/organization-view-members.vue
  frontend/src/modules/organization/organization-employees-field.js
  frontend/src/modules/organization/organization-field.js
  frontend/src/modules/organization/organization-model.js
  frontend/src/modules/organization/organization-module.js
  frontend/src/modules/organization/organization-platform-field.js
  frontend/src/modules/organization/organization-routes.js
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-form-page.vue
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/modules/organization/pages/organization-view-page.vue
  frontend/src/modules/organization/store/actions.js
  frontend/src/modules/organization/store/constants.js
  frontend/src/modules/organization/store/state.js
  frontend/src/shared/fields/activity-date-field.js
  frontend/src/shared/filter/components/filter-list-item.vue
  frontend/src/shared/filter/components/type/filter-type-select.vue
  frontend/src/shared/filter/helpers/build-api-payload.js
  frontend/src/shared/form/string-array-input.vue
  frontend/src/shared/platform/platform.vue
  frontend/src/shared/shared-module.js
  frontend/src/utils/number.js
Labels: codeball:needs-careful-review, Feature

#290 Fix range filters
  frontend/src/shared/filter/components/filter-list-item.vue
  frontend/src/shared/filter/components/type/filter-type-date.vue
Labels: codeball:needs-careful-review, Bug
