Repository CrowdDotDev/crowd.dev, pull requests merged in 2023-07, with the labels that each got.

#1058 Fix pagination mapping for view more
  frontend/src/shared/modules/filters/services/filter-query.service.ts
Labels: Bug

#1062 Fix custom reports with segments
  frontend/src/i18n/en.js
  frontend/src/modules/widget/components/cube/_query_builder/FilterComponent.vue
  frontend/src/modules/widget/components/cube/_query_builder/TimeDimensionSelect.vue
  frontend/src/modules/widget/components/cube/widget-cube-builder.vue
  frontend/src/modules/widget/components/cube/widget-cube-renderer.vue
Labels: Bug

#1060 Fixed negative sentiment filter values on members page
  frontend/src/modules/member/config/filters/avgSentiment/config.ts
Labels: Bug

#1064 Fix broken avatar
  frontend/src/shared/avatar/avatar.vue
Labels: Bug

#1069 memberId was not in some cases
  services/apps/data_sink_worker/src/service/activity.service.ts
Labels: Bug

#1068 Add segment id to automation processing
  services/apps/data_sink_worker/src/service/activity.service.ts
  services/libs/sqs/src/instances/nodejsWorker.ts
  services/libs/types/src/queue/nodejs_worker/index.ts
Labels: Bug

#1071 fixed where we update activityChannels (settings -> segments)
  services/apps/data_sink_worker/src/service/activity.service.ts
  services/apps/data_sink_worker/src/service/settings.repo.ts
Labels: Bug

#1072 don't update an activity if it was deleted
  services/apps/data_sink_worker/src/bin/restart-result.ts
  services/apps/data_sink_worker/src/repo/activity.repo.ts
  services/apps/data_sink_worker/src/repo/member.repo.ts
  services/apps/data_sink_worker/src/service/activity.service.ts
Labels: Bug

#1073 Prevent the while loop to be executing too long
  backend/src/bin/jobs/checkStuckIntegrationRuns.ts
  backend/src/database/repositories/integrationRunRepository.ts
Labels: Bug

#1074 optimize find members query
  services/apps/data_sink_worker/src/repo/member.repo.ts
Labels: Bug

#1059 Add properties for user identification analytics
  frontend/src/shared/monitoring/identify.js
Labels: Bug

#1067 Parse numbers returned from OpenSearch
  backend/src/database/repositories/memberRepository.ts
Labels: Bug

#1070 Remove img if src is not loaded
  frontend/src/modules/organization/components/organization-name.vue
  frontend/src/shared/avatar-image/avatar-image.vue
  frontend/src/shared/avatar/avatar.vue
Labels: Bug

#1077 Bugfix/no memberid when triggering sync
  services/apps/data_sink_worker/src/bin/restart-result.ts
  services/apps/data_sink_worker/src/service/activity.service.ts
  services/libs/conversations/src/repo/conversation.repo.ts
Labels: Bug

#1079 API request body size limit increase
  backend/src/api/index.ts
Labels: Bug

#1085 Fix sample tenant permissions
  frontend/src/security/permissions.js
Labels: Bug

#1080 Migrate Slack integration to the new framework
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/integrations/services/integrations/slackIntegrationService.ts
  backend/src/serverless/integrations/types/slackTypes.ts
  backend/src/services/integrationService.ts
  services/apps/integration_data_worker/src/repo/integrationData.data.ts
  services/apps/integration_data_worker/src/repo/integrationData.repo.ts
  services/apps/integration_data_worker/src/service/integrationDataService.ts
  services/apps/integration_run_worker/src/repo/integrationRun.data.ts
  services/apps/integration_run_worker/src/repo/integrationRun.repo.ts
  services/apps/integration_run_worker/src/service/integrationRunService.ts
  services/apps/integration_stream_worker/config/default.json
  services/apps/integration_stream_worker/config/production.json
  services/apps/integration_stream_worker/src/repo/integrationStream.data.ts
  services/apps/integration_stream_worker/src/repo/integrationStream.repo.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
  services/libs/integrations/src/integrations/slack/api/errorHandler.ts
  services/libs/integrations/src/integrations/slack/api/getChannels.ts
  services/libs/integrations/src/integrations/slack/api/getMember.ts
  services/libs/integrations/src/integrations/slack/api/getMembers.ts
  services/libs/integrations/src/integrations/slack/api/getMessages.ts
  services/libs/integrations/src/integrations/slack/api/getMessagesInThreads.ts
  services/libs/integrations/src/integrations/slack/api/getProfile.ts
  services/libs/integrations/src/integrations/slack/api/getTeam.ts
  services/libs/integrations/src/integrations/slack/generateStreams.ts
  services/libs/integrations/src/integrations/slack/index.ts
  services/libs/integrations/src/integrations/slack/processData.ts
  services/libs/integrations/src/integrations/slack/processStream.ts
  services/libs/integrations/src/integrations/slack/types.ts
  services/libs/integrations/src/types.ts
  services/libs/types/src/integrations.ts
Labels: Improvement

#1081 Fill `jobTitle` from member enrichment
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
Labels: Improvement

#1092 Change sso callback verification
  backend/config/custom-environment-variables.json
  backend/package-lock.json
  backend/package.json
  backend/src/api/auth/ssoCallback.ts
  backend/src/conf/configTypes.ts
Labels: Improvement

#1098 Authorization code flow
  frontend/src/modules/auth/pages/callback.vue
  frontend/src/modules/auth/store/actions.js
  frontend/src/shared/services/auth0.service.ts
  frontend/src/shared/types/LocalStorage.ts
Labels: Bug

#1103 Move to not embed sso
  frontend/package-lock.json
  frontend/package.json
  frontend/src/modules/auth/auth-routes.js
  frontend/src/modules/auth/pages/callback.vue
  frontend/src/modules/auth/pages/signin-page.vue
  frontend/src/modules/auth/store/actions.js
  frontend/src/shared/services/auth0.service.ts
Labels: Bug

#1100 Prevent null values on `firstName` and `lastName` properties after OAuth authentication
  backend/src/services/auth/authService.ts
Labels: Bug, Improvement

#1087 Members organizations relationship time-dependent
  frontend/src/modules/member/components/form/member-form-attributes.vue
  frontend/src/modules/member/components/form/member-form-details.vue
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/form/member-form-organizations.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/components/view/_aside/_aside-enriched.vue
  frontend/src/modules/member/components/view/_aside/_aside-organizations.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/member-model.js
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/member/types/Member.ts
  frontend/src/modules/organization/organization-field.js
  frontend/src/modules/organization/types/Organization.ts
  frontend/src/shared/form/autocomplete-one-input.vue
Labels: Feature

#1106 Fix member edit form
  frontend/src/modules/member/pages/member-form-page.vue
Labels: Bug

#1104 Members-organizations relationship linux
  backend/src/database/migrations/U1688636697__employment-history.sql
  backend/src/database/migrations/U1688653004__convert-employment-history.sql
  backend/src/database/migrations/V1688636697__employment-history.sql
  backend/src/database/migrations/V1688653004__convert-employment-history.sql
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/__tests__/activityService.test.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/memberService.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  frontend/src/modules/dashboard/components/organization/dashboard-organization-item.vue
  frontend/src/modules/lf/member/components/view/lf-member-aside-organizations.vue
  frontend/src/modules/member/components/form/member-form-attributes.vue
  frontend/src/modules/member/components/form/member-form-details.vue
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/form/member-form-organizations.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/components/view/_aside/_aside-enriched.vue
  frontend/src/modules/member/components/view/_aside/_aside-organizations.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/member-model.js
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/member/types/Member.ts
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/modules/organization/organization-field.js
  frontend/src/modules/organization/organization-model.js
  frontend/src/modules/organization/pages/organization-form-page.vue
  frontend/src/modules/organization/types/Organization.ts
  frontend/src/shared/form/autocomplete-one-input.vue
Labels: Feature

#1111 Fix invitation page
  frontend/src/modules/auth/auth-routes.js
  frontend/src/modules/auth/pages/invitation-page.vue
Labels: Bug

#1112 Fix git integration connection
  frontend/src/modules/integration/integration-service.js
Labels: Bug

#1114 Fix invitation flow
  backend/src/services/auth/authService.ts
Labels: Bug

#1118 Check null values in the emails list when showing merge suggestion
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
Labels: Bug

#1116 Terms and privacy
  backend/src/api/auth/authSignUp.ts
  backend/src/database/migrations/U1689235178__addTermsAndPrivacyColumn.sql
  backend/src/database/migrations/V1689235178__addTermsAndPrivacyColumn.sql
  backend/src/database/models/user.ts
  backend/src/database/repositories/userRepository.ts
  backend/src/services/auth/authService.ts
  frontend/src/i18n/en.js
  frontend/src/middleware/auth/auth-guard.js
  frontend/src/modules/auth/auth-routes.js
  frontend/src/modules/auth/auth-service.js
  frontend/src/modules/auth/pages/signup-page.vue
  frontend/src/modules/auth/pages/terms-and-privacy.vue
  frontend/src/modules/auth/store/actions.js
  frontend/src/modules/user/user-model.js
Labels: Improvement

#1078 Member list page optimize
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-merge-dialog.vue
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/modules/tag/components/tag-list.vue
  frontend/src/modules/tag/components/tag-popover.vue
Labels: Improvement

#1122 Fix merging of members through Actions button
  frontend/src/modules/member/components/list/member-list-toolbar.vue
Labels: Bug

#1126 Custom reports widget settings
  frontend/src/i18n/en.js
  frontend/src/modules/widget/components/cube/_query_builder/DimensionSelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/FilterComponent.vue
  frontend/src/modules/widget/components/cube/_query_builder/MeasureSelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/TimeDimensionSelect.vue
  frontend/src/modules/widget/components/cube/widget-cube-builder.vue
  frontend/src/modules/widget/components/cube/widget-cube-renderer.vue
  frontend/src/modules/widget/components/cube/widget-cube.vue
Labels: Bug

#1128 Sentiment click router fix
  frontend/src/modules/dashboard/components/activity/dashboard-activity-sentiment.vue
Labels: Bug

#1120 Improvement/migrate discord
  backend/src/bin/discord-ws.ts
  backend/src/database/repositories/integrationRepository.ts
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
  backend/src/serverless/integrations/types/discordTypes.ts
  backend/src/services/integrationService.ts
  services/apps/integration_stream_worker/config/custom-environment-variables.json
  services/apps/integration_stream_worker/src/repo/incomingWebhook.repo.ts
  services/apps/integration_stream_worker/src/repo/integrationStream.repo.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
  services/libs/integrations/src/integrations/discord/api/errorHandler.ts
  services/libs/integrations/src/integrations/discord/api/getChannel.ts
  services/libs/integrations/src/integrations/discord/api/getChannels.ts
  services/libs/integrations/src/integrations/discord/api/getMember.ts
  services/libs/integrations/src/integrations/discord/api/getMembers.ts
  services/libs/integrations/src/integrations/discord/api/getMessage.ts
  services/libs/integrations/src/integrations/discord/api/getMessages.ts
  services/libs/integrations/src/integrations/discord/api/getThreads.ts
  services/libs/integrations/src/integrations/discord/externalTypes.ts
  services/libs/integrations/src/integrations/discord/generateStreams.ts
  services/libs/integrations/src/integrations/discord/index.ts
  services/libs/integrations/src/integrations/discord/processData.ts
  services/libs/integrations/src/integrations/discord/processStream.ts
  services/libs/integrations/src/integrations/discord/processWebhookStream.ts
  services/libs/integrations/src/integrations/discord/types.ts
  services/libs/types/src/enums/webhooks.ts
Labels: Improvement

#1135 Support multiple streamIds in the process-stream script
  services/apps/integration_stream_worker/src/bin/process-stream.ts
Labels: Improvement

#1138 Coalesce createdById and updatedById when inserting into conversationSettings
  services/libs/conversations/src/repo/conversation.repo.ts
Labels: Bug

#1140 integration fetching on automations
  frontend/src/modules/automation/components/automation-form.vue
  frontend/src/modules/automation/pages/automation-list-page.vue
Labels: Bug

#1133 Disable new tenants creation
  frontend/src/middleware/auth/auth-guard.js
  frontend/src/modules/index.ts
  frontend/src/modules/onboard/components/onboard-community.vue
  frontend/src/modules/onboard/config/achievements.config.js
  frontend/src/modules/onboard/onboard-module.js
  frontend/src/modules/onboard/onboard-routes.js
  frontend/src/modules/onboard/pages/onboard-page.vue
Labels: Improvement

#1139 Hubspot connect & settings
  frontend/src/integrations/hubspot/components/hubspot-book-call.vue
  frontend/src/integrations/hubspot/components/hubspot-connect.vue
  frontend/src/integrations/hubspot/components/hubspot-property-map.vue
  frontend/src/integrations/hubspot/components/hubspot-settings-drawer.vue
  frontend/src/integrations/hubspot/config.js
  frontend/src/integrations/hubspot/hubspot.api.service.ts
  frontend/src/integrations/hubspot/types/HubspotEntity.ts
  frontend/src/integrations/hubspot/types/HubspotOnboard.ts
  frontend/src/integrations/hubspot/types/HubspotProperty.ts
  frontend/src/integrations/hubspot/types/MappableFields.ts
  frontend/src/modules/integration/integration-service.js
  frontend/src/modules/integration/integration-store.js
Labels: Feature

#1137 Fix broken `bulkEditTags` and refactor logic of the component
  frontend/src/modules/member/components/list/member-list-bulk-update-tags.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/modules/member/store/actions.js
  frontend/src/modules/tag/components/tag-popover.vue
Labels: Bug, Improvement

#1146 Manual sync for members and organizations
  frontend/public/icons/crowd-icons.svg
  frontend/src/assets/scss/form/dropdown.scss
  frontend/src/integrations/hubspot/hubspot.api.service.ts
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/organization/components/organization-dropdown.vue
Labels: Feature

#1148 Integrate LFX header
  frontend/index.html
  frontend/public/images/lf/logo_lfx_cm.svg
  frontend/src/app.vue
  frontend/src/middleware/auth/auth-guard.js
  frontend/src/modules/auth/auth-routes.js
  frontend/src/modules/auth/auth-service.js
  frontend/src/modules/auth/components/oauth.vue
  frontend/src/modules/auth/pages/callback.vue
  frontend/src/modules/auth/pages/forgot-password-page.vue
  frontend/src/modules/auth/pages/profile-form-page.vue
  frontend/src/modules/auth/pages/signin-page.vue
  frontend/src/modules/layout/components/account-dropdown.vue
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/lf/layout/components/lf-header.vue
  frontend/src/modules/lf/layout/components/lf-menu.vue
  frontend/src/shared/services/auth0.service.ts
Labels: Feature

#1147 Support non empty array matches for emails
  services/libs/opensearch/src/opensearchQueryParser.ts
  services/libs/types/src/opensearch.ts
Labels: Improvement

#1156 Fix several undefined errors in incoming data in Github integration
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/services/memberService.ts
  services/libs/integrations/src/integrations/activityTypes.ts
Labels: Bug

#1165 Add twitter to automation platform list
  frontend/src/modules/automation/components/filter-options/new-activity-filter-options.vue
  frontend/src/modules/automation/components/filter-options/new-member-filter-options.vue
Labels: Bug

#1159 Add hubspot to scale plan
  frontend/src/featureFlag/index.js
  frontend/src/integrations/hubspot/components/hubspot-connect.vue
  frontend/src/integrations/hubspot/config.js
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/modules/settings/pages/plans-page.vue
  frontend/src/modules/settings/settings-pricing-plans.js
  frontend/src/security/plans.js
Labels: Feature

#1168 Fix edit form fill
  frontend/src/modules/automation/components/automation-form.vue
Labels: Bug

#1178 Cubejs schema updates for preaggregations
  backend/src/cubejs/schema/Members.js
Labels: Bug

#1180 Cubejs joinedAt dimension with unix timestamp form
  backend/src/cubejs/schema/Members.js
  frontend/src/modules/widget/widget-queries.js
  scripts/services/frontend.yaml
Labels: Bug

#1182 Cubejs joinedAtUnixTs now uses number lt filter
  frontend/src/modules/widget/widget-queries.js
Labels: Bug

#1183 Cubejs joinedAt filter is stringified before sending to api
  frontend/src/modules/widget/widget-queries.js
Labels: Bug

#1176 Fix `vite` hmr and FE docker build context path
  frontend/package-lock.json
  frontend/package.json
Labels: Bug

#1186 Prevent `falsy` values from being included in member emails
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
Labels: Bug

#1193 Weekly analytics e-mails with segments
  backend/src/database/utils/getUserContext.ts
  backend/src/serverless/microservices/nodejs/analytics/workers/weeklyAnalyticsEmailsWorker.ts
Labels: Bug

#1194 Email already sent check in weekly analytics emails worker
  backend/src/serverless/microservices/nodejs/analytics/workers/weeklyAnalyticsEmailsWorker.ts
Labels: Bug

#1195 Display fixes for weekly analytics emails
  backend/src/bin/scripts/send-weekly-analytics-email.ts
  backend/src/serverless/microservices/nodejs/analytics/workers/weeklyAnalyticsEmailsWorker.ts
  backend/src/services/activityDisplayService.ts
Labels: Bug

#1197 Hubspot integration improvements
  backend/src/services/integrationService.ts
  services/apps/integration_sync_worker/src/service/member.sync.service.ts
  services/libs/integrations/src/integrations/premium/hubspot/field-mapper/hubspotFieldMapper.ts
  services/libs/integrations/src/integrations/premium/hubspot/field-mapper/mapperFactory.ts
  services/libs/integrations/src/integrations/premium/hubspot/field-mapper/memberFieldMapper.ts
  services/libs/integrations/src/integrations/premium/hubspot/generateStreams.ts
  services/libs/integrations/src/integrations/premium/hubspot/processData.ts
  services/libs/integrations/src/integrations/premium/hubspot/processStream.ts
  services/libs/integrations/src/integrations/premium/hubspot/processSyncRemote.ts
  services/libs/integrations/src/integrations/premium/hubspot/types.ts
  services/libs/integrations/src/types.ts
Labels: Bug

#1198 Hubspot integration identities mapping fix
  services/libs/integrations/src/integrations/premium/hubspot/api/batchCreateMembers.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchUpdateMembers.ts
  services/libs/types/src/members.ts
Labels: Bug

#1190 Suggest primary member in merge based on identities & attributes
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
Labels: Bug
