Repository CrowdDotDev/crowd.dev, pull requests merged in 2023-06, with the labels that each got.

#927 Fixing a few issues with unleash and new services
  backend/src/api/member/memberExport.ts
  backend/src/api/premium/enrichment/memberEnrich.ts
  backend/src/api/premium/enrichment/memberEnrichBulk.ts
  backend/src/bin/scripts/unleash-init.ts
  backend/src/feature-flags/getFeatureFlagTenantContext.ts
  backend/src/feature-flags/isFeatureEnabled.ts
  backend/src/serverless/microservices/nodejs/bulk-enrichment/bulkEnrichmentWorker.ts
  backend/src/serverless/microservices/nodejs/bulk-enrichment/bulkOrganizationEnrichmentWorker.ts
  backend/src/utils/timing.ts
  scripts/cli
  scripts/scaffold/sqs/queue.conf
  services/apps/data_sink_worker/src/bin/restart-failed-results.ts
  services/libs/common/src/timing.ts
Labels: Bug

#929 fixed docker entrypoints
  services/apps/data_sink_worker/package.json
  services/apps/integration_data_worker/package.json
  services/apps/integration_run_worker/package.json
  services/apps/integration_stream_worker/package.json
Labels: Bug

#928 Process integration script fixed to work with the new integration framework
  backend/src/bin/jobs/checkStuckIntegrationRuns.ts
  backend/src/bin/scripts/process-integration.ts
  backend/src/database/repositories/integrationRunRepository.ts
  backend/src/serverless/integrations/services/integrationCheckProcessor.ts
  backend/src/serverless/integrations/services/integrationTickProcessor.ts
  backend/src/serverless/utils/integrationRunWorkerSQS.ts
  backend/src/serverless/utils/nodeWorkerSQS.ts
  backend/src/services/integrationService.ts
  services/apps/data_sink_worker/package-lock.json
  services/apps/integration_data_worker/package-lock.json
  services/apps/integration_run_worker/package-lock.json
  services/apps/integration_run_worker/src/main.ts
  services/apps/integration_run_worker/src/queue/index.ts
  services/apps/integration_run_worker/src/repo/integrationRun.data.ts
  services/apps/integration_run_worker/src/repo/integrationRun.repo.ts
  services/apps/integration_run_worker/src/repo/integrationStream.repo.ts
  services/apps/integration_run_worker/src/service/integrationRunService.ts
  services/apps/integration_stream_worker/package-lock.json
  services/apps/integration_stream_worker/src/queue/index.ts
  services/apps/integration_stream_worker/src/repo/integrationStream.data.ts
  services/apps/integration_stream_worker/src/repo/integrationStream.repo.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
  services/libs/sqs/src/instances/integrationRunWorker.ts
  services/libs/sqs/src/instances/integrationStreamWorker.ts
  services/libs/sqs/src/instances/nodejsWorker.ts
  services/libs/types/src/queue/integration_run_worker/index.ts
  services/libs/types/src/queue/integration_stream_worker/index.ts
Labels: Bug

#934 filter bot users on commits
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
Labels: Bug

#930 C-1361 - Organization profile: Name is not centered when missing other attributes
  frontend/src/modules/organization/components/view/organization-view-header.vue
Labels: Improvement

#923 Retrying error state webhooks and cleanup for orphaned ones
  backend/src/bin/jobs/checkStuckIntegrationRuns.ts
  backend/src/bin/jobs/cleanUp.ts
  backend/src/bin/scripts/process-webhook.ts
  backend/src/database/migrations/U1685449426__incomingWebhooksRetry.sql
  backend/src/database/migrations/V1685449426__incomingWebhooksRetry.sql
  backend/src/database/repositories/incomingWebhookRepository.ts
  backend/src/serverless/integrations/services/webhookProcessor.ts
Labels: Improvement

#943 Check null sentiments when calculating average sentiment
  backend/src/database/repositories/memberRepository.ts
Labels: Bug

#945 Bugfix/escape pg promise named parameter format
  services/apps/data_sink_worker/src/repo/activity.repo.ts
  services/apps/data_sink_worker/src/repo/member.repo.ts
  services/libs/database/src/repoBase.ts
Labels: Bug

#965 Keep error when delaying for a retry
  backend/openapi.json
  backend/src/api/premium/enrichment/memberEnrich.ts
  backend/src/bin/test.ts
  services/apps/integration_stream_worker/src/bin/process-stream.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
Labels: Bug

#969 Fix GitHub commits
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
Labels: Bug

#973 Add missing return in a StackOverflow functino
  services/libs/integrations/src/integrations/stackoverflow/api/getQuestionsByKeywords.ts
Labels: Bug

#971 Move HackerNews
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/integrations/services/integrations/hackerNewsIntegrationService.ts
  backend/src/services/integrationService.ts
  services/libs/integrations/src/integrations/hackernews/api/getPost.ts
  services/libs/integrations/src/integrations/hackernews/api/getPostsByKeywords.ts
  services/libs/integrations/src/integrations/hackernews/generateStreams.ts
  services/libs/integrations/src/integrations/hackernews/index.ts
  services/libs/integrations/src/integrations/hackernews/memberAttributes.ts
  services/libs/integrations/src/integrations/hackernews/processData.ts
  services/libs/integrations/src/integrations/hackernews/processStream.ts
  services/libs/integrations/src/integrations/hackernews/types.ts
  services/libs/integrations/src/integrations/loader.ts
Labels: Improvement

#976 Fix activities timestamp
  frontend/src/modules/auth/components/layout/auth-layout-side.vue
  frontend/src/utils/date.js
Labels: Bug

#811 Error logging for weekly emails worker
  backend/src/serverless/microservices/nodejs/analytics/workers/weeklyAnalyticsEmailsWorker.ts
Labels: Improvement

#982 Webpack -> Vite
  .github/workflows/test-frontend.yml
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/Dockerfile.dev
  frontend/Dockerfile.kube
  frontend/cypress.config.js
  frontend/cypress.staging.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/scripts/docker-entrypoint.sh
  frontend/src/config.js
  frontend/src/featureFlag/index.js
  frontend/src/shared/error/errors.js
  frontend/tests/e2e/auth/onboarding.js
  frontend/tests/e2e/auth/password-reset.js
  frontend/tests/e2e/auth/verifyEmail.js
  frontend/tests/e2e/test.spec.js
  frontend/vite.config.js
  frontend/vue.config.js
  scripts/cli
Labels: Improvement

#998 Fix analytics env setting
  frontend/index.html
Labels: Bug

#987 Add member and display object to activity's parent
  backend/src/database/repositories/__tests__/conversationRepository.test.ts
  backend/src/database/repositories/activityRepository.ts
Labels: Feature

#968 Activities with organizations
  backend/package-lock.json
  backend/package.json
  backend/src/database/initializers/memberEnrichmentAddOrganization.ts
  backend/src/database/migrations/U1686173729__activityOrganizations.sql
  backend/src/database/migrations/V1686173729__activityOrganizations.sql
  backend/src/database/models/activity.ts
  backend/src/database/repositories/__tests__/activityRepository.test.ts
  backend/src/database/repositories/__tests__/conversationRepository.test.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/activityRepository.ts
  backend/src/database/repositories/conversationRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/memberSegmentAffiliationRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/database/utils/segmentTestUtils.ts
  backend/src/services/__tests__/activityService.test.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/activityService.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  backend/src/services/premium/enrichment/types/memberEnrichmentTypes.ts
  backend/src/services/sampleDataService.ts
  backend/src/services/segmentService.ts
  backend/src/types/memberSegmentAffiliationTypes.ts
Labels: Feature

#1019 Custom opensearch mappings fix
  services/libs/opensearch/src/fieldTranslator.ts
  services/libs/opensearch/src/memberTranslator.ts
  services/libs/opensearch/src/models/members.ts
  services/libs/types/src/opensearch.ts
Labels: Bug

#1022 Reach opensearch sorting fix
  backend/src/cubejs/schema/Members.js
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-reach.vue
  frontend/src/shared/modules/filters/config/apiFilterRenderer/string.filter.renderer.ts
  frontend/tests/e2e/member/filter/reach.js
  services/libs/opensearch/src/memberTranslator.ts
  services/libs/opensearch/src/opensearchQueryParser.ts
Labels: Bug

#1024 Members search query emails wildcard way
  frontend/src/modules/member/config/filters/main.ts
Labels: Bug

#1010 Reduce cubejs auth requests in dashboard
  frontend/index.html
  frontend/src/modules/dashboard/pages/dashboard-page.vue
Labels: Improvement

#1006 Add enterprise plan
  backend/src/database/migrations/U1687261112__addEnterprisePlan.sql
  backend/src/database/migrations/V1687261112__addEnterprisePlan.sql
  backend/src/database/models/tenant.ts
  backend/src/database/repositories/tenantRepository.ts
  backend/src/feature-flags/isFeatureEnabled.ts
  backend/src/security/permissions.ts
  backend/src/security/plans.ts
  frontend/src/modules/automation/pages/automation-list-page.vue
  frontend/src/modules/member/member-enrichment.js
  frontend/src/modules/member/member-export-limit.js
Labels: Feature

#1017 Refactor segments filters
  frontend/src/modules/activity/config/filters/projects/ProjectsFilter.vue
  frontend/src/modules/activity/config/filters/projects/config.ts
  frontend/src/modules/conversation/config/filters/projects/ProjectsFilter.vue
  frontend/src/modules/conversation/config/filters/projects/config.ts
  frontend/src/modules/dashboard/components/activity/dashboard-activity-sentiment.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-types.vue
  frontend/src/modules/dashboard/components/dashboard-count.vue
  frontend/src/modules/dashboard/components/dashboard-widget-chart.vue
  frontend/src/modules/dashboard/store/actions.js
  frontend/src/modules/dashboard/store/state.js
  frontend/src/modules/lf/segments/components/filter/lf-project-filter-button.vue
  frontend/src/modules/lf/segments/components/filter/lf-project-filter.vue
  frontend/src/modules/lf/segments/components/filter/lf-radio-cascader.vue
  frontend/src/modules/lf/segments/types/Filters.ts
  frontend/src/modules/lf/utils/filters.ts
  frontend/src/modules/member/config/filters/projects/ProjectsFilter.vue
  frontend/src/modules/member/config/filters/projects/config.ts
  frontend/src/modules/organization/config/filters/projects/ProjectsFilter.vue
  frontend/src/modules/organization/config/filters/projects/config.ts
  frontend/src/modules/report/pages/report-view-page-public.vue
  frontend/src/modules/report/pages/templates/report-template-page.vue
  frontend/src/modules/widget/components/activity/widget-activities-kpi.vue
  frontend/src/modules/widget/components/activity/widget-activities-platform.vue
  frontend/src/modules/widget/components/activity/widget-activities-type-list.vue
  frontend/src/modules/widget/components/activity/widget-new-activities.vue
  frontend/src/modules/widget/components/activity/widget-total-activities.vue
  frontend/src/modules/widget/components/member/widget-active-leaderboard-members.vue
  frontend/src/modules/widget/components/member/widget-active-members-kpi.vue
  frontend/src/modules/widget/components/member/widget-active-members.vue
  frontend/src/modules/widget/components/member/widget-total-members.vue
  frontend/src/modules/widget/components/product-community-fit/widget-benchmark.vue
  frontend/src/modules/widget/components/product-community-fit/widget-monthly-active-contributors.vue
  frontend/src/shared/axios/auth-axios.js
  frontend/src/utils/segments.js
Labels: Feature

#1030 Fix reports dropdown
  frontend/src/modules/report/components/report-dropdown.vue
Labels: Bug

#1028 Fix saved views bug and date filter
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/shared/modules/filters/components/Filter.vue
  frontend/src/shared/modules/filters/components/filterTypes/DateFilter.vue
Labels: Bug

#1032 Re add eagle eye page
  frontend/src/modules/dashboard/pages/dashboard-page.vue
  frontend/src/modules/index.ts
  frontend/src/modules/layout/layout-page-content.js
  frontend/src/modules/lf/layout/components/lf-menu.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-platforms-drawers.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-platforms.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-published-date.vue
  frontend/src/premium/eagle-eye/components/form/eagle-eye-settings-include.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-drawer.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-list.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-loading-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-loading-state.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-result-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings-drawer.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-tabs.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-banner.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-footer.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-intro-step.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-keywords-step.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-platforms-step.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-summary-step.vue
  frontend/src/premium/eagle-eye/constants/eagle-eye-date-published.json
  frontend/src/premium/eagle-eye/constants/eagle-eye-platforms.json
  frontend/src/premium/eagle-eye/eagle-eye-module.js
  frontend/src/premium/eagle-eye/eagle-eye-permissions.js
  frontend/src/premium/eagle-eye/eagle-eye-routes.js
  frontend/src/premium/eagle-eye/eagle-eye-service.js
  frontend/src/premium/eagle-eye/eagle-eye-storage.js
  frontend/src/premium/eagle-eye/pages/eagle-eye-onboard-page.vue
  frontend/src/premium/eagle-eye/pages/eagle-eye-page-wrapper.vue
  frontend/src/premium/eagle-eye/pages/eagle-eye-page.vue
  frontend/src/premium/eagle-eye/store/actions.js
  frontend/src/premium/eagle-eye/store/constants.js
  frontend/src/premium/eagle-eye/store/getters.js
  frontend/src/premium/eagle-eye/store/index.js
  frontend/src/premium/eagle-eye/store/mutations.js
  frontend/src/premium/eagle-eye/store/state.js
  frontend/src/shared/form/element-change.js
  frontend/src/shared/loading/page-loader.vue
Labels: Feature

#1037 Bug fixes for filter ranges
  frontend/src/shared/modules/filters/config/itemLabelRenderer/number.label.renderer.ts
  frontend/src/shared/modules/filters/config/queryUrlParser/date.parser.ts
  frontend/src/shared/modules/filters/config/queryUrlParser/number.parser.ts
Labels: Bug

#1018 Auth0 auth
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/src/api/auth/index.ts
  backend/src/api/auth/ssoCallback.ts
  backend/src/conf/configTypes.ts
  backend/src/conf/index.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/tenantRepository.ts
  backend/src/database/repositories/userRepository.ts
  backend/src/services/auth/authService.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/scripts/docker-entrypoint.sh
  frontend/src/config.js
  frontend/src/middleware/auth/auth-guard.js
  frontend/src/modules/auth/auth-routes.js
  frontend/src/modules/auth/auth-service.js
  frontend/src/modules/auth/components/oauth.vue
  frontend/src/modules/auth/pages/callback.vue
  frontend/src/modules/auth/pages/email-unverified-page.vue
  frontend/src/modules/auth/pages/forgot-password-page.vue
  frontend/src/modules/auth/pages/logout.vue
  frontend/src/modules/auth/pages/profile-form-page.vue
  frontend/src/modules/auth/pages/signin-page.vue
  frontend/src/modules/auth/pages/signup-page.vue
  frontend/src/modules/auth/store/actions.js
  frontend/src/shared/services/auth0.service.ts
  frontend/src/shared/types/LocalStorage.ts
Labels: Feature

#1034 C-1380 - Member photo is not covering dedicated area properly
  frontend/src/shared/avatar/avatar.vue
Labels: Bug

#1043 Fix auth on tenant change
  frontend/src/modules/dashboard/pages/dashboard-page.vue
Labels: Bug

#1042 QA issues
  frontend/src/modules/activity/pages/activity-list-page.vue
  frontend/src/modules/automation/store/actions.js
  frontend/src/modules/conversation/components/conversation-dropdown.vue
  frontend/src/modules/dashboard/components/dashboard-project-group.vue
  frontend/src/modules/layout/layout-page-content.js
  frontend/src/modules/lf/layout/components/lf-menu-project-group-selection.vue
  frontend/src/modules/lf/layout/components/lf-menu.vue
  frontend/src/modules/lf/lf-permissions.js
  frontend/src/modules/lf/lf-routes.js
  frontend/src/modules/lf/segments/components/filter/lf-project-filter-button.vue
  frontend/src/modules/lf/segments/components/lf-project-groups-dropdown.vue
  frontend/src/modules/lf/segments/components/lf-projects-dropdown.vue
  frontend/src/modules/lf/segments/components/lf-sub-projects-dropdown.vue
  frontend/src/modules/lf/segments/components/lf-sub-projects-list-dropdown.vue
  frontend/src/modules/lf/segments/components/view/lf-project-groups-table.vue
  frontend/src/modules/lf/segments/components/view/lf-projects-table.vue
  frontend/src/modules/lf/segments/pages/lf-project-groups-list-page.vue
  frontend/src/modules/lf/segments/pages/lf-project-groups-page.vue
  frontend/src/modules/lf/segments/pages/lf-projects-page.vue
  frontend/src/modules/lf/segments/store/actions.js
  frontend/src/modules/lf/segments/store/getters.ts
  frontend/src/modules/report/components/report-dropdown.vue
  frontend/src/modules/report/components/report-share-button.vue
  frontend/src/modules/report/pages/report-list-page.vue
  frontend/src/modules/settings/settings-permissions.js
  frontend/src/modules/user/components/list/user-list-table.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-drawer.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-loading-state.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-banner.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-footer.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-summary-step.vue
  frontend/src/premium/eagle-eye/eagle-eye-routes.js
  frontend/src/premium/eagle-eye/pages/eagle-eye-onboard-page.vue
  frontend/src/router/index.js
  frontend/src/security/permissions.js
Labels: Bug

#1046 Active members with opensearch
  backend/src/api/member/memberActiveList.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/segmentRepository.ts
  backend/src/services/memberService.ts
  services/apps/search_sync_worker/package.json
  services/apps/search_sync_worker/src/bin/delete-index.ts
  services/apps/search_sync_worker/src/service/opensearch.service.ts
  services/libs/opensearch/src/models/members.ts
  services/libs/opensearch/src/opensearchQueryParser.ts
  services/libs/types/src/enums/opensearch.ts
Labels: Feature

#1048 Add fallback query to GitHub integration commits
  backend/src/database/repositories/memberRepository.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/usecases/github/graphql/pullRequestCommitsNoAdditions.ts
Labels: Bug

#1049 Add sso endpoint
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/src/api/auth/index.ts
  backend/src/api/auth/ssoCallback.ts
  backend/src/conf/configTypes.ts
  backend/src/conf/index.ts
  backend/src/database/migrations/U1687886017__addEnterprisePlan.sql
  backend/src/database/migrations/V1687886017__addEnterprisePlan.sql
  backend/src/database/models/tenant.ts
  backend/src/database/repositories/tenantRepository.ts
  backend/src/database/repositories/userRepository.ts
  backend/src/feature-flags/isFeatureEnabled.ts
  backend/src/security/permissions.ts
  backend/src/security/plans.ts
  backend/src/services/auth/authService.ts
Labels: Feature

#1047 Fix pagination
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/shared/modules/filters/services/filter-api.service.ts
Labels: Bug

#1053 Fix changeFiles in GitHub commits query
  backend/src/serverless/integrations/usecases/github/graphql/pullRequestCommits.ts
  backend/src/serverless/integrations/usecases/github/graphql/pullRequestCommitsNoAdditions.ts
Labels: Bug

#1015 Add rate limiting to Reddit integration
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
  services/libs/integrations/package-lock.json
  services/libs/integrations/src/integrations/reddit/api/getComments.ts
  services/libs/integrations/src/integrations/reddit/api/getMoreComments.ts
  services/libs/integrations/src/integrations/reddit/api/getPosts.ts
  services/libs/integrations/src/integrations/reddit/api/handleRateLimit.ts
  services/libs/integrations/src/types.ts
  services/libs/redis/src/cache.ts
  services/libs/redis/src/index.ts
  services/libs/redis/src/rateLimiter.ts
  services/libs/types/src/caching.ts
Labels: Improvement
