Repository CrowdDotDev/crowd.dev, pull requests merged in 2023-03, with the labels that each got.

#578 Eagle-eye onboarding flow
  frontend/src/app.vue
  frontend/src/modules/auth/store/actions.js
  frontend/src/modules/onboard/components/onboard-community.vue
  frontend/src/modules/onboard/components/onboard-integrations.vue
  frontend/src/modules/onboard/pages/onboard-page.vue
Labels: Feature

#588 Cascading to member enrichment cache on member delete
  backend/src/database/migrations/U1677596354__fixOnDeleteCascadeMemberEnrichment.sql
  backend/src/database/migrations/V1677596354__fixOnDeleteCascadeMemberEnrichment.sql
Labels: Bug

#577 Members opening in new tab
  frontend/src/modules/activity/components/activity-content.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/tag/components/tag-list.vue
Labels: Improvement

#594 Allow to reenrich members
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/shared/dialog/confirm-dialog.js
Labels: Improvement

#593 Allow editing multi select fields
  frontend/src/modules/member/components/form/member-form-attributes.vue
  frontend/src/modules/member/member-service.js
  frontend/src/shared/form/autocomplete-many-input.vue
Labels: Improvement

#601 Add waiting approval status
  frontend/src/modules/dashboard/components/dashboard-active-integrations.vue
  frontend/src/modules/integration/components/integration-list-item.vue
Labels: Bug

#606 Feature/onboarding guides
  backend/src/database/migrations/U1677836093__addReasonForUsingCrowd.sql
  backend/src/database/migrations/V1677836093__addReasonForUsingCrowd.sql
  backend/src/database/models/tenant.ts
  backend/src/database/repositories/tenantRepository.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/eagle-eye/modal-banner.jpg
  frontend/public/images/logo/crowd-mini.svg
  frontend/src/assets/scss/form/radio.scss
  frontend/src/modules/auth/store/getters.js
  frontend/src/modules/dashboard/components/dashboard-guides.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-eagle-eye-modal.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-item.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-modal.vue
  frontend/src/modules/dashboard/pages/dashboard-page.vue
  frontend/src/modules/dashboard/services/quickstart-guide.service.js
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/onboard/components/onboard-community.vue
  frontend/src/modules/onboard/components/onboard-integrations-connect.vue
  frontend/src/modules/onboard/components/onboard-integrations.vue
  frontend/src/modules/onboard/config/achievements.config.js
  frontend/src/modules/onboard/pages/onboard-page.vue
  frontend/src/modules/tenant/tenant-model.js
  frontend/src/shared/dialog/confirm-dialog.js
  frontend/src/shared/dialog/dialog.vue
Labels: Feature

#608 Show multiple organizations in members profile
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/shared/form/autocomplete-many-input.vue
Labels: Bug

#613 Slack commands admin tool
  backend/config/custom-environment-variables.json
  backend/package-lock.json
  backend/package.json
  backend/src/api/index.ts
  backend/src/api/slack/command.ts
  backend/src/api/slack/index.ts
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/database/repositories/tenantRepository.ts
  backend/src/services/slackCommandService.ts
  backend/src/types/slackTypes.ts
Labels: Improvement

#619 Fix formbricks integration
  frontend/scripts/docker-entrypoint.sh
  frontend/src/assets/scss/layout.scss
  frontend/src/config.js
  frontend/src/modules/dashboard/pages/dashboard-page.vue
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/tenant/store/actions.js
  frontend/src/modules/tenant/store/getters.js
  frontend/src/modules/tenant/store/mutations.js
  frontend/src/modules/tenant/store/state.js
Labels: Bug

#605 isOrganization as a default member attribute
  backend/src/api/member/memberActiveList.ts
  backend/src/cubejs/schema/Members.js
  backend/src/database/attributes/member/default.ts
  backend/src/database/attributes/member/linkedin.ts
  backend/src/database/initializers/entities/2023-03-03-add-isOrganization-to-default-member-attributes.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/types/memberTypes.ts
  backend/src/services/__tests__/tenantService.test.ts
Labels: Feature

#600 Remove members that are organizations from members list
  frontend/src/modules/dashboard/dashboard.cube.js
  frontend/src/modules/member/member-service.js
  frontend/src/modules/widget/widget-queries.js
Labels: Bug

#616 Alerting for faulty integrations
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/src/bin/jobs/index.ts
  backend/src/bin/jobs/integrationDataChecker.ts
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/microservices/nodejs/integration-data-checker/integrationDataCheckerSettings.ts
  backend/src/serverless/microservices/nodejs/integration-data-checker/integrationDataCheckerTypes.ts
  backend/src/serverless/microservices/nodejs/integration-data-checker/integrationDataCheckerWorker.ts
  backend/src/serverless/microservices/nodejs/messageTypes.ts
  backend/src/serverless/microservices/nodejs/workerFactory.ts
  backend/src/utils/slackAlerts.ts
  frontend/src/modules/dashboard/components/dashboard-active-integrations.vue
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/modules/integration/components/integration-list-page.vue
  frontend/src/modules/integration/integration-store.js
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/tenant/store/getters.js
Labels: Improvement

#598 Fix of member's emails not being updated
  frontend/src/modules/member/components/member-manage-identities-drawer.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
Labels: Bug

#599 Moved user management to free tier
  backend/src/api/user/userCreate.ts
  backend/src/api/user/userDestroy.ts
  backend/src/api/user/userEdit.ts
  backend/src/api/user/userImport.ts
  backend/src/services/user/userCreator.ts
  backend/src/services/user/userDestroyer.ts
  backend/src/services/user/userEditor.ts
  backend/src/services/user/userImporter.ts
  frontend/src/middleware/auth/auth-guard.js
  frontend/src/middleware/auth/not-empty-tenant-guard.js
  frontend/src/middleware/auth/permission-guard.js
  frontend/src/modules/activity/activity-permissions.js
  frontend/src/modules/auth/pages/forgot-password-page.vue
  frontend/src/modules/auth/pages/password-reset-page.vue
  frontend/src/modules/auth/pages/profile-form-page.vue
  frontend/src/modules/auth/pages/signin-page.vue
  frontend/src/modules/auth/pages/signup-page.vue
  frontend/src/modules/automation/automation-permissions.js
  frontend/src/modules/conversation/conversation-permissions.js
  frontend/src/modules/index.js
  frontend/src/modules/member/member-permissions.js
  frontend/src/modules/organization/organization-permissions.js
  frontend/src/modules/report/report-permissions.js
  frontend/src/modules/settings/pages/settings-page.vue
  frontend/src/modules/settings/settings-permissions.js
  frontend/src/modules/tag/tag-permissions.js
  frontend/src/modules/task/task-model.js
  frontend/src/modules/task/task-permissions.js
  frontend/src/modules/tenant/tenant-permissions.js
  frontend/src/modules/user/components/form/user-form.vue
  frontend/src/modules/user/components/list/user-list-table.vue
  frontend/src/modules/user/components/list/user-list-toolbar.vue
  frontend/src/modules/user/components/user-dropdown.vue
  frontend/src/modules/user/components/user-invite-autocomplete.vue
  frontend/src/modules/user/pages/user-edit-page.vue
  frontend/src/modules/user/pages/user-list-page.vue
  frontend/src/modules/user/pages/user-new-page.vue
  frontend/src/modules/user/permission-checker.js
  frontend/src/modules/user/user-destroy-store.js
  frontend/src/modules/user/user-field.js
  frontend/src/modules/user/user-form-store.js
  frontend/src/modules/user/user-list-exporter-fields.js
  frontend/src/modules/user/user-list-store.js
  frontend/src/modules/user/user-model.js
  frontend/src/modules/user/user-module.js
  frontend/src/modules/user/user-permissions.js
  frontend/src/modules/user/user-routes.js
  frontend/src/modules/user/user-service.js
  frontend/src/modules/user/user-store.js
  frontend/src/modules/user/user-view-store.js
  frontend/src/premium/eagle-eye/eagle-eye-permissions.js
  frontend/src/premium/user/user-module.js
  frontend/src/premium/user/user-store.js
  frontend/src/shared/list/list-item-relation-to-one.vue
  frontend/src/shared/view/view-item-relation-to-many.vue
  frontend/src/shared/view/view-item-relation-to-one.vue
Labels: Improvement

#622 Mark as team organization
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/organizationRepository.ts
Labels: Feature

#623 Move settings button
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings.vue
Labels: Improvement

#621 Fix members search pagination
  frontend/src/modules/activity/store/actions.js
  frontend/src/premium/eagle-eye/store/mutations.js
  frontend/src/shared/store/actions.js
  frontend/src/shared/store/mutations.js
Labels: Bug

#630 Sort eagle eye feed
  frontend/src/premium/eagle-eye/components/list/eagle-eye-list.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-tabs.vue
  frontend/src/premium/eagle-eye/store/mutations.js
  frontend/src/premium/eagle-eye/store/state.js
  frontend/src/shared/form/inline-select-input.vue
Labels: Improvement

#628 Getting installed repositories with pagination
  backend/src/serverless/integrations/usecases/github/rest/getInstalledRepositories.ts
Labels: Bug

#635 Type issues quickstart guides
  frontend/src/modules/dashboard/components/dashboard-guides.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-eagle-eye-modal.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-modal.vue
  frontend/src/modules/dashboard/pages/dashboard-page.vue
  frontend/src/modules/integration/integration-store.js
  frontend/src/modules/layout/components/workspace-dropdown.vue
  frontend/src/modules/onboard/components/onboard-community.vue
  frontend/src/shared/filter/components/filter-list-item.vue
Labels: Bug

#638 Fix eagle eye drawers & thumbnail width
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-drawer.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-result-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings-drawer.vue
  frontend/src/shared/image/image.vue
Labels: Bug

#644 Tweak copy in Eagle Eye CTA
  frontend/src/modules/layout/pages/paywall-page.vue
  frontend/tailwind.config.js
Labels: Improvement

#642 Update pricing page with Eagle eye
  frontend/scripts/docker-entrypoint.sh
  frontend/src/config.js
  frontend/src/modules/settings/pages/plans-page.vue
  frontend/src/security/permissions.js
  frontend/src/security/plans.js
Labels: Improvement

#641 Better sample data on the backend
  backend/src/database/initializers/sample-data.json
  backend/src/services/sampleDataService.ts
Labels: Improvement

#646 New approach to handle sample data in frontend
  backend/src/types/quickstartGuideTypes.ts
  frontend/scripts/docker-entrypoint.sh
  frontend/src/assets/scss/form/dropdown.scss
  frontend/src/config.js
  frontend/src/middleware/auth/auth-guard.js
  frontend/src/middleware/auth/permission-guard.js
  frontend/src/modules/activity/activity-permissions.js
  frontend/src/modules/activity/activity-service.js
  frontend/src/modules/activity/components/activity-dropdown.vue
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/auth/auth-current-tenant.js
  frontend/src/modules/conversation/components/conversation-details.vue
  frontend/src/modules/conversation/components/conversation-dropdown.vue
  frontend/src/modules/conversation/conversation-permissions.js
  frontend/src/modules/conversation/conversation-service.js
  frontend/src/modules/dashboard/components/dashboard-guides.vue
  frontend/src/modules/integration/integration-store.js
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-enrichment.vue
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/member/components/view/_aside/_aside-custom-attributes.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
  frontend/src/modules/member/components/view/member-view-notes.vue
  frontend/src/modules/member/member-permissions.js
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/notes/components/note-dropdown.vue
  frontend/src/modules/notes/note-permissions.js
  frontend/src/modules/notes/note-service.js
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/organization/organization-permissions.js
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/modules/tag/components/tag-list.vue
  frontend/src/modules/tenant/store/getters.js
  frontend/src/modules/tenant/tenant-service.js
  frontend/src/modules/user/permission-checker.js
  frontend/src/modules/widget/widget-service.js
  frontend/src/premium/community-help-center/components/community-help-center-conversation-drawer.vue
  frontend/src/premium/community-help-center/components/community-help-center-settings.vue
  frontend/src/premium/community-help-center/components/community-help-center-toolbar.vue
  frontend/src/security/permissions.js
  frontend/src/shared/axios/auth-axios.js
Labels: Improvement

#643 Members query optimization
  backend/src/api/member/memberQuery.ts
  backend/src/database/migrations/U1678698341__identities-to-member-materialized-view.sql
  backend/src/database/migrations/V1678698341__identities-to-member-materialized-view.sql
  backend/src/database/repositories/filters/__tests__/rawQueryParser.test.ts
  backend/src/database/repositories/filters/queryTypes.ts
  backend/src/database/repositories/filters/rawQueryParser.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/memberService.ts
  backend/src/types/integrationEnums.ts
  backend/src/utils/logging.ts
  frontend/src/modules/dashboard/store/actions.js
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/pages/member-list-page.vue
  scripts/cli
  scripts/scaffold.yaml
Labels: Improvement

#647 Fix regex safari
  frontend/.eslintrc.js
  frontend/src/modules/activity/components/activity-content.vue
Labels: Bug

#648 Report last year date range
  frontend/src/modules/widget/components/cube/_query_builder/DateRangeSelect.vue
Labels: Bug

#652 hasSampleData updated for crowd-hosted edition as well
  backend/src/services/sampleDataService.ts
Labels: Bug

#651 Onboarding events
  backend/src/api/eventTracking/eventTrack.ts
  backend/src/api/eventTracking/index.ts
  backend/src/api/index.ts
  backend/src/services/eventTrackingService.ts
  backend/src/types/eventTrackingTypes.ts
  frontend/src/modules/dashboard/components/dashboard-guides.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-eagle-eye-modal.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-item.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-modal.vue
  frontend/src/modules/event-tracking/services/event-tracking-service.js
Labels: Improvement

#654 Fix filters using OR operators
  frontend/src/modules/activity/activity-service.js
  frontend/src/modules/activity/store/actions.js
  frontend/src/modules/activity/store/constants.js
  frontend/src/modules/conversation/conversation-service.js
  frontend/src/modules/dashboard/store/actions.js
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/store/constants.js
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/store/constants.js
  frontend/src/modules/organization/store/state.js
  frontend/src/modules/widget/widget-queries.js
  frontend/src/shared/fields/search-field.js
  frontend/src/shared/filter/helpers/build-api-payload.js
Labels: Bug

#650 Logos & avatars on member, organization & platform dropdowns
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  frontend/public/images/integrations/circle.png
  frontend/public/images/integrations/heartbeat.png
  frontend/src/jsons/onboard-platforms.json
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/automation/components/webhooks/webhook-form.vue
  frontend/src/modules/dashboard/components/dashboard-filters.vue
  frontend/src/modules/member/components/form/member-form-details.vue
  frontend/src/modules/member/components/member-selection-dropdown.vue
  frontend/src/modules/onboard/components/onboard-community.vue
  frontend/src/modules/report/components/templates/report-template-filters.vue
  frontend/src/modules/task/components/task-form.vue
  frontend/src/shared/filter/components/filter-list-item.vue
  frontend/src/shared/filter/components/type/filter-type-select-multi.vue
  frontend/src/shared/form/autocomplete-one-input.vue
Labels: Improvement

#657 Public reports viewedBy exception
  backend/src/api/report/reportFind.ts
Labels: Bug

#653 Organization members page is still using the old members query
  backend/src/database/repositories/memberRepository.ts
  frontend/src/modules/organization/components/view/organization-view-members.vue
Labels: Improvement

#658 Set report widgets only if sent in the payload
  backend/src/database/repositories/reportRepository.ts
Labels: Bug

#659 changed log level for some logs from info to debug
  backend/src/bin/discord-ws.ts
Labels: Improvement

#662 Fix onboarding event property name
  frontend/src/modules/dashboard/components/dashboard-guides.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-eagle-eye-modal.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-item.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-modal.vue
Labels: Bug

#660 Merging members in transaction
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/utils/sequelizeTestUtils.ts
  backend/src/services/memberService.ts
Labels: Bug

#664 Fix timestamp instead of createdAt
  frontend/src/modules/member/components/view/member-view-header.vue
Labels: Bug

#632 Members emails as arrays
  frontend/src/assets/scss/badge.scss
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-manage-identities-drawer.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/components/view/_aside/_aside-custom-attributes.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
  frontend/src/modules/member/member-list-exporter-fields.js
  frontend/src/modules/member/member-model.js
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/member/store/actions.js
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/organization-identities.vue
  frontend/src/modules/tag/components/tag-list.vue
  frontend/src/shared/attributes/get-attributes-model.js
Labels: Improvement

#672 Member emails as arrays
  backend/src/database/migrations/U1679059477__memberEmailArray.sql
  backend/src/database/migrations/V1679059477__memberEmailArray.sql
  backend/src/database/models/member.ts
  backend/src/database/repositories/__tests__/memberAttributeSettingsRepository.test.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/filters/__tests__/rawQueryParser.test.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/slackIntegrationService.ts
  backend/src/serverless/integrations/types/messageTypes.ts
  backend/src/serverless/integrations/webhooks/__tests__/github.test.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/memberService.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
Labels: Improvement

#674 Fix emails as arrays issues
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  backend/src/services/quickstartGuideService.ts
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-enrichment.vue
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details-identities.vue
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/member/member-model.js
  frontend/src/modules/task/components/task-form.vue
  frontend/src/modules/task/task-model.js
  frontend/src/shared/avatar/avatar.vue
  frontend/src/shared/filter/helpers/build-api-payload.js
Labels: Bug

#676 Bug/stackoverflow keywords input
  frontend/src/integrations/stackoverflow/components/stackoverflow-connect-drawer.vue
Labels: Bug

#678 Python workers fixes after migrating to array type emails
  backend/src/serverless/microservices/python/crowd-backend/crowd/backend/models/member.py
  backend/src/serverless/microservices/python/crowd-backend/crowd/backend/repository/keys.py
  backend/src/serverless/microservices/python/crowd-backend/crowd/backend/repository/repository.py
  backend/src/serverless/microservices/python/crowd-check-merge-members/crowd/check_merge_members/merge_suggestions.py
Labels: Bug

#677 Enable onboarding integration processing to last multiple days because of rate limits
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/types/mq/nodeWorkerIntegrationProcessMessage.ts
Labels: Bug

#679 Fix duplicated queries
  frontend/src/integrations/stackoverflow/components/activity/stackoverflow-activity-content.vue
  frontend/src/integrations/stackoverflow/components/activity/stackoverflow-activity-message.vue
  frontend/src/integrations/stackoverflow/config.js
  frontend/src/modules/layout/components/layout.vue
  frontend/src/shared/filter/components/type/filter-type-search.vue
Labels: Bug

#682 Emails as arrays for CSV export
  backend/src/serverless/microservices/nodejs/csv-export/csvExportWorker.ts
Labels: Bug

#683 add new limits
  frontend/src/integrations/stackoverflow/components/stackoverflow-connect-drawer.vue
Labels: Bug

#696 Previous period label fix
  frontend/src/modules/dashboard/components/dashboard-count.vue
Labels: Improvement

#697 Fix filters dispatch & members name html
  frontend/.eslintrc.js
  frontend/src/modules/dashboard/components/task/dashboard-task-item.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-display-name.vue
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/modules/task/components/task-form.vue
  frontend/src/modules/widget/components/v2/shared/widget-members-table.vue
  frontend/src/shared/filter/components/filter-dropdown.vue
Labels: Bug

#699 Change period tooltip label
  frontend/src/modules/dashboard/components/dashboard-count.vue
Labels: Improvement

#701 Temporarly disable other guards
  frontend/src/middleware/auth/index.js
Labels: Bug

#706 Fix member enrichment
  frontend/src/modules/member/member-enrichment.js
Labels: Bug

#710 Optional Meilisearch initialization
  .github/actions/deploy-service/action.yaml
  .github/workflows/lf-production-deploy.yaml
  backend/src/middlewares/searchEngineMiddleware.ts
Labels: Bug

#707 Fix all time granularity
  frontend/src/modules/widget/components/v2/product-community-fit/widget-benchmark.vue
  frontend/src/modules/widget/components/v2/product-community-fit/widget-monthly-active-contributors.vue
Labels: Bug

#713 Forks stream disabled temporarily for github onboardings
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
Labels: Bug

#714 Job to detect stuck integration runs and fix them
  backend/src/bin/jobs/checkStuckIntegrationRuns.ts
  backend/src/bin/jobs/index.ts
  backend/src/database/repositories/integrationRunRepository.ts
  backend/src/database/repositories/integrationStreamRepository.ts
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/types/integrationRunTypes.ts
  backend/src/types/integrationStreamTypes.ts
Labels: Bug
