Repository CrowdDotDev/crowd.dev, pull requests merged in 2023-08, with the labels that each got.

#1201 Integration sync worker CI jobs for LFX
  .github/workflows/lf-production-deploy-new.yaml
Labels: Improvement

#1205 Enhancement/optimize integration tables
  backend/src/database/migrations/U1690873474__optimize-integration-tables.sql
  backend/src/database/migrations/V1690873474__optimize-integration-tables.sql
Labels: Improvement

#1209 Add icon for read-only attributes and introduce alert popover
  frontend/src/integrations/hubspot/components/hubspot-property-map.vue
  frontend/src/integrations/hubspot/components/hubspot-readonly-attr-popover.vue
  frontend/src/integrations/hubspot/components/hubspot-settings-drawer.vue
Labels: Improvement

#1206 Hubspot status fix on updating properties
  backend/src/services/integrationService.ts
Labels: Bug

#1210 Formbricks prevent sending empty data
  frontend/src/modules/auth/store/mutations.js
Labels: Bug

#1177 Support bulk edit members attribute
  frontend/src/modules/member/components/bulk/bulk-edit-attribute-dropdown.vue
  frontend/src/modules/member/components/bulk/bulk-edit-attribute-popover.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/store/actions.js
Labels: Improvement

#1225 Fix primary member selection logic in merge suggestions
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
Labels: Bug

#1217 Fix Merge member action in members page
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/view/member-view-header.vue
Labels: Bug

#1222 Fix reports timestamps
  frontend/src/modules/widget/widget-queries.js
Labels: Bug

#1228 Fix member undefined attributes
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
Labels: Bug

#1227 Organization page members fix
  frontend/src/modules/organization/pages/organization-view-page.vue
Labels: Bug

#1235 Updates hubspot frequency back to 8 hours
  services/libs/integrations/src/integrations/premium/hubspot/index.ts
Labels: Bug

#1236 Switching discord bots
  backend/src/services/integrationService.ts
Labels: Bug

#1212 Bugfix/speed up opensearch sync for manual member updates c 1933
  backend/src/services/memberService.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  services/libs/sqs/src/instances/searchSyncWorker.ts
Labels: Bug

#1253 Fix tenant storage
  frontend/src/modules/auth/auth-current-tenant.js
Labels: Bug

#1254 Bump limit for organizations enrichment to 20k in script
  backend/src/bin/scripts/enrich-members-and-organizations.ts
Labels: Improvement

#1312 Increase sink worker concurrency
  services/apps/data_sink_worker/src/main.ts
Labels: Improvement

#1313 Fix organization model
  frontend/src/modules/organization/organization-model.js
Labels: Bug

#1250 Affiliations frontend improvement
  frontend/src/assets/scss/form/date-picker.scss
  frontend/src/modules/activity/components/activity-dropdown.vue
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/member/components/form/member-form-organizations-create.vue
  frontend/src/modules/member/components/form/member-form-organizations-drawer.vue
  frontend/src/modules/member/components/form/member-form-organizations.vue
  frontend/src/modules/member/components/view/_aside/_aside-organizations.vue
  frontend/src/shared/avatar/avatar.vue
  frontend/src/shared/form/autocomplete-one-input.vue
Labels: Improvement

#1324 Cubejs activity preaggregations with partitions
  backend/src/cubejs/schema/Activities.js
Labels: Improvement

#1249 Associate organizations activities
  frontend/src/modules/activity/components/activity-header.vue
  frontend/src/modules/activity/components/activity-item.vue
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/conversation/components/conversation-details.vue
  frontend/src/modules/conversation/components/conversation-item.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-item.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-item.vue
Labels: Feature

#1320 Update organizations list sorter
  frontend/src/modules/organization/config/saved-views/views/all-organizations.ts
Labels: Bug

#1329 Add member organizations to opensearch
  backend/src/database/repositories/organizationRepository.ts
  services/apps/search_sync_worker/src/repo/member.data.ts
  services/apps/search_sync_worker/src/repo/member.repo.ts
  services/apps/search_sync_worker/src/service/member.sync.service.ts
  services/libs/opensearch/src/memberTranslator.ts
Labels: Improvement

#1328 Enhancement/organizations in opensearch c 1978
  backend/src/database/migrations/U1691485202__organization-sync-timestamp.sql
  backend/src/database/migrations/V1691485202__organization-sync-timestamp.sql
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/organizationService.ts
  frontend/src/modules/organization/config/filters/main.ts
  services/apps/data_sink_worker/src/service/member.service.ts
  services/apps/search_sync_worker/package.json
  services/apps/search_sync_worker/src/bin/cleanup-all-organizations.ts
  services/apps/search_sync_worker/src/bin/cleanup-tenant-organizations.ts
  services/apps/search_sync_worker/src/bin/sync-all-organizations.ts
  services/apps/search_sync_worker/src/bin/sync-organization.ts
  services/apps/search_sync_worker/src/bin/sync-tenant-organizations.ts
  services/apps/search_sync_worker/src/queue/index.ts
  services/apps/search_sync_worker/src/repo/member.data.ts
  services/apps/search_sync_worker/src/repo/member.repo.ts
  services/apps/search_sync_worker/src/repo/organization.data.ts
  services/apps/search_sync_worker/src/repo/organization.repo.ts
  services/apps/search_sync_worker/src/repo/segment.data.ts
  services/apps/search_sync_worker/src/repo/segment.repo.ts
  services/apps/search_sync_worker/src/service/init.service.ts
  services/apps/search_sync_worker/src/service/member.sync.service.ts
  services/apps/search_sync_worker/src/service/opensearch.service.ts
  services/apps/search_sync_worker/src/service/organization.sync.data.ts
  services/apps/search_sync_worker/src/service/organization.sync.service.ts
  services/apps/search_sync_worker/src/types.ts
  services/libs/opensearch/src/fieldTranslator.ts
  services/libs/opensearch/src/fieldTranslatorFactory.ts
  services/libs/opensearch/src/memberTranslator.ts
  services/libs/opensearch/src/models/organizations.ts
  services/libs/opensearch/src/organizationTranslator.ts
  services/libs/sqs/src/instances/searchSyncWorker.ts
  services/libs/types/src/enums/opensearch.ts
  services/libs/types/src/opensearch.ts
  services/libs/types/src/queue/search_sync_worker/index.ts
Labels: Improvement

#1330 Fallback to joinedAt_DESC when orderBy string is empty on querying organizations
  backend/src/database/repositories/organizationRepository.ts
Labels: Improvement

#1331 Fix organization query
  frontend/src/modules/dashboard/components/organization/dashboard-organization-item.vue
  frontend/src/modules/dashboard/store/actions.js
Labels: Bug

#1321 Fix members active organization
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/components/view/_aside/_aside-organizations.vue
Labels: Bug

#1332 Fix label for no organization
  frontend/src/modules/member/components/member-organizations.vue
Labels: Bug

#1341 Opensearch orgs hotfix
  services/libs/opensearch/src/fieldTranslator.ts
Labels: Bug

#1345 Search by email
  frontend/src/modules/member/config/filters/main.ts
Labels: Bug

#1344 Fix filter applying from store
  frontend/src/shared/modules/filters/components/Filter.vue
Labels: Bug

#1347 Don't enrich organizations with 0 activities
  backend/src/bin/scripts/enrich-members-and-organizations.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
  backend/src/services/premium/enrichment/types/organizationEnrichmentTypes.ts
Labels: Bug

#1349 Job title not required, date range timezone issue
  frontend/src/modules/member/components/form/member-form-organizations-create.vue
  frontend/src/modules/member/components/form/member-form-organizations-drawer.vue
  frontend/src/modules/member/components/form/member-form-organizations.vue
Labels: Bug

#1351 Fix unknown typo
  frontend/src/modules/member/components/form/member-form-organizations-drawer.vue
  frontend/src/modules/member/components/form/member-form-organizations.vue
  frontend/src/modules/member/components/view/_aside/_aside-organizations.vue
Labels: Bug

#1352 Bugfix/organization indexing c 2111
  services/apps/data_sink_worker/src/service/memberAffiliation.service.ts
  services/apps/search_sync_worker/src/bin/sync-organization.ts
  services/apps/search_sync_worker/src/queue/index.ts
  services/apps/search_sync_worker/src/repo/organization.repo.ts
  services/apps/search_sync_worker/src/service/organization.sync.service.ts
  services/libs/common/src/timing.ts
  services/libs/sqs/src/instances/searchSyncWorker.ts
Labels: Bug

#1354 Disable sort by name in members and organizations
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
Labels: Bug

#1356 fixed organization address indexing
  services/apps/search_sync_worker/src/service/opensearch.service.ts
  services/apps/search_sync_worker/src/service/organization.sync.service.ts
  services/libs/opensearch/src/models/organizations.ts
Labels: Bug

#1362 Fix load more fetching
  frontend/src/modules/activity/components/activity-timeline.vue
Labels: Bug

#1363 Fix auto assign member to existing organization based on email domain
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/memberService.ts
  backend/src/services/organizationService.ts
Labels: Bug

#1367 Handle max byte limit during OpenSearch member Indexing
  backend/src/services/aws.ts
  services/apps/search_sync_worker/src/service/member.sync.service.ts
  services/libs/common/src/byteLength.ts
  services/libs/common/src/index.ts
  services/libs/sentiment/src/sentiment.ts
Labels: Improvement

#1369 Fix identities showing
  frontend/src/modules/member/components/member-identities.vue
Labels: Bug

#1371 Fix lf feature flags
  frontend/src/app.vue
  frontend/src/featureFlag/index.js
  frontend/src/modules/auth/auth-current-tenant.js
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/premium/eagle-eye/pages/eagle-eye-onboard-page.vue
Labels: Bug

#1375 Consistent timestamps throughout the app
  frontend/src/modules/activity/config/filters/date/options.ts
  frontend/src/modules/conversation/config/filters/dateStarted/options.ts
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-list.vue
  frontend/src/modules/dashboard/components/dashboard-activities.vue
  frontend/src/modules/dashboard/components/dashboard-count.vue
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/dashboard/dashboard.cube.js
  frontend/src/modules/dashboard/store/actions.js
  frontend/src/modules/widget/components/activity/widget-activities-kpi.vue
  frontend/src/modules/widget/components/activity/widget-total-activities.vue
  frontend/src/modules/widget/components/member/widget-active-members-kpi.vue
  frontend/src/modules/widget/components/member/widget-total-members.vue
  frontend/src/modules/widget/components/shared/widget-area.vue
  frontend/src/modules/widget/widget-queries.js
  frontend/src/shared/modules/filters/config/apiFilterRenderer/date.filter.renderer.ts
Labels: Improvement

#1380 Production performance
  backend/src/database/migrations/U1692786381__unique-activity-index.sql
  backend/src/database/migrations/U1692800745__index-subprojects-by-tenant.sql
  backend/src/database/migrations/U1692803447__conversation-slug-index.sql
  backend/src/database/migrations/V1692786381__unique-activity-index.sql
  backend/src/database/migrations/V1692800745__index-subprojects-by-tenant.sql
  backend/src/database/migrations/V1692803447__conversation-slug-index.sql
  backend/src/database/repositories/incomingWebhookRepository.ts
  backend/src/serverless/integrations/services/webhookProcessor.ts
  backend/src/serverless/utils/nodeWorkerSQS.ts
  services/apps/data_sink_worker/src/queue/index.ts
  services/apps/data_sink_worker/src/repo/activity.repo.ts
  services/apps/data_sink_worker/src/repo/member.repo.ts
  services/apps/data_sink_worker/src/service/dataSink.service.ts
  services/apps/data_sink_worker/src/service/member.service.ts
  services/apps/data_sink_worker/src/service/settings.repo.ts
  services/apps/integration_data_worker/src/repo/integrationData.repo.ts
  services/apps/integration_data_worker/src/service/integrationDataService.ts
  services/apps/integration_run_worker/package.json
  services/apps/integration_run_worker/src/bin/onboard-integration.ts
  services/apps/integration_run_worker/src/bin/trigger-stream-processed.ts
  services/apps/integration_run_worker/src/service/integrationRunService.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
  services/libs/conversations/src/repo/conversation.repo.ts
  services/libs/database/src/connection.ts
  services/libs/integrations/src/integrations/devto/index.ts
  services/libs/integrations/src/integrations/slack/index.ts
  services/libs/sqs/src/client.ts
  services/libs/sqs/src/instances/dataSinkWorker.ts
  services/libs/sqs/src/instances/integrationRunWorker.ts
  services/libs/sqs/src/queue.ts
Labels: Bug, Improvement

#1381 Bugfix/member organization filter should include dates c 2025
  backend/src/database/repositories/memberRepository.ts
  services/apps/search_sync_worker/src/repo/organization.repo.ts
  services/apps/search_sync_worker/src/service/member.sync.service.ts
  services/apps/search_sync_worker/src/types.ts
  services/libs/opensearch/src/models/members.ts
  services/libs/types/src/enums/opensearch.ts
Labels: Bug

#1383 Display manually created organizations and members
  backend/src/database/migrations/U1693120114__trackManuallyCreatedOrgsAndMembers.sql
  backend/src/database/migrations/V1693120114__trackManuallyCreatedOrgsAndMembers.sql
  backend/src/database/models/member.ts
  backend/src/database/models/organization.ts
  backend/src/database/models/organizationCache.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/__tests__/organizationCacheRepository.test.ts
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/organizationCacheRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/__tests__/memberService.test.ts
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/organization/pages/organization-form-page.vue
  services/apps/search_sync_worker/src/repo/member.data.ts
  services/apps/search_sync_worker/src/repo/member.repo.ts
  services/apps/search_sync_worker/src/repo/organization.data.ts
  services/apps/search_sync_worker/src/repo/organization.repo.ts
  services/apps/search_sync_worker/src/service/init.service.ts
  services/apps/search_sync_worker/src/service/member.sync.service.ts
  services/apps/search_sync_worker/src/service/organization.sync.service.ts
  services/libs/opensearch/src/models/members.ts
  services/libs/opensearch/src/models/organizations.ts
  services/libs/types/src/members.ts
Labels: Improvement

#1385 don't use deduplication id for streamProcessed events
  services/libs/sqs/src/instances/integrationRunWorker.ts
Labels: Bug

#1390 Bugfix/sync script optimization
  backend/src/database/migrations/U1693124397__searchSyncedAt-index-fix.sql
  backend/src/database/migrations/V1693124397__searchSyncedAt-index-fix.sql
  services/apps/integration_run_worker/src/bin/trigger-all-onboardings.ts
  services/apps/integration_run_worker/src/repo/integrationRun.repo.ts
  services/apps/integration_run_worker/src/service/integrationRunService.ts
  services/apps/integration_stream_worker/src/repo/integrationStream.repo.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
  services/apps/search_sync_worker/src/bin/cleanup-all-activities.ts
  services/apps/search_sync_worker/src/bin/cleanup-all-members.ts
  services/apps/search_sync_worker/src/bin/cleanup-all-organizations.ts
  services/apps/search_sync_worker/src/bin/cleanup-tenant-activities.ts
  services/apps/search_sync_worker/src/bin/cleanup-tenant-members.ts
  services/apps/search_sync_worker/src/bin/cleanup-tenant-organizations.ts
  services/apps/search_sync_worker/src/bin/sync-activity.ts
  services/apps/search_sync_worker/src/bin/sync-all-activities.ts
  services/apps/search_sync_worker/src/bin/sync-all-members.ts
  services/apps/search_sync_worker/src/bin/sync-all-organizations.ts
  services/apps/search_sync_worker/src/bin/sync-member.ts
  services/apps/search_sync_worker/src/bin/sync-organization.ts
  services/apps/search_sync_worker/src/bin/sync-tenant-activities.ts
  services/apps/search_sync_worker/src/bin/sync-tenant-members.ts
  services/apps/search_sync_worker/src/bin/sync-tenant-organizations.ts
  services/apps/search_sync_worker/src/repo/activity.repo.ts
  services/apps/search_sync_worker/src/repo/member.repo.ts
  services/apps/search_sync_worker/src/service/activity.sync.service.ts
  services/apps/search_sync_worker/src/service/member.sync.service.ts
Labels: Improvement

#1389 Add disclaimer to dashboard and reports
  frontend/src/modules/dashboard/components/dashboard-filters.vue
  frontend/src/modules/dashboard/pages/dashboard-page.vue
  frontend/src/modules/report/pages/report-view-page-public.vue
  frontend/src/modules/report/pages/templates/report-template-page.vue
Labels: Improvement

#1392 Change hardcoded limit in organization enrichment script
  backend/package.json
  backend/src/bin/scripts/enrich-members-and-organizations.ts
  backend/src/bin/scripts/enrich-organizations-synchronous.ts
  backend/src/database/repositories/memberRepository.ts
Labels: Improvement

#1393 Refactor location attribute formatting in organization enrichment
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
Labels: Improvement

#1394 Fix organizations enrichment issues
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
  frontend/src/modules/organization/components/form/organization-form-details.vue
  frontend/src/modules/organization/config/enrichment/revenueRange.ts
Labels: Bug

#1396 Fix update of custom attributes
  frontend/src/shared/attributes/get-parsed-attributes.js
Labels: Bug

#1399 Update getPayingTenant sql query
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#1397 Fix filter operator
  frontend/src/modules/member/config/saved-views/views/slipping-away.ts
Labels: Bug

#1401 Move timestamps to ISO strings in lists
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/shared/modules/filters/config/apiFilterRenderer/date.filter.renderer.ts
Labels: Improvement

#1404 Calculate number of activities for an organization correctly
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#1406 Fix `displayName` sorter in members and organizations list
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  services/libs/opensearch/src/opensearchQueryParser.ts
Labels: Bug
