Repository CrowdDotDev/crowd.dev, pull requests merged in 2023-09, with the labels that each got.

#1407 Fix handling of nested fields in OpenSearch query
  services/libs/opensearch/src/fieldTranslator.ts
  services/libs/opensearch/src/opensearchQueryParser.ts
Labels: Bug

#1412 Normalize `website` while creating organization
  backend/src/services/organizationService.ts
  services/apps/data_sink_worker/src/service/organization.service.ts
  services/libs/common/src/index.ts
  services/libs/common/src/websiteNormalizer.ts
Labels: Improvement

#1413 Improve `websiteNormalizer` with public suffix list
  services/libs/common/package-lock.json
  services/libs/common/package.json
  services/libs/common/src/websiteNormalizer.ts
Labels: Improvement

#1384 C-2161 - Optimize handling of segments activity channels
  backend/package-lock.json
  backend/src/database/migrations/U1692866303__segmentActivityChannels.sql
  backend/src/database/migrations/V1692866303__segmentActivityChannels.sql
  backend/src/database/repositories/segmentRepository.ts
  backend/src/services/__tests__/activityService.test.ts
  services/apps/data_sink_worker/src/service/settings.repo.ts
Labels: Improvement

#1411 Improvements
  frontend/src/modules/organization/components/view/organization-view-members.vue
  frontend/src/modules/organization/pages/organization-view-page.vue
Labels: Improvement

#1422 Segments missing activity types for the display service
  backend/src/database/repositories/segmentRepository.ts
Labels: Bug

#1425 fixed member filtering by organization ids
  backend/src/database/repositories/memberRepository.ts
Labels: Bug

#1420 Fixed fetching organization data aggregates when segments are enabled
  backend/src/api/organization/organizationFind.ts
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/organizationService.ts
Labels: Bug

#1423 Refactor organizations requests
  frontend/src/modules/activity/components/activity-header.vue
  frontend/src/modules/dashboard/components/organization/dashboard-organization-item.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/components/view/organization-view-members.vue
  frontend/src/modules/organization/config/filters/projects/ProjectsFilter.vue
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-form-page.vue
  frontend/src/modules/organization/pages/organization-view-page.vue
  frontend/src/modules/organization/store/pinia/actions.ts
  frontend/src/utils/segments.js
Labels: Bug

#1434 Set github alert modal
  frontend/src/integrations/github/components/github-connect.vue
  frontend/src/shared/dialog/confirm-dialog.js
Labels: Improvement

#1435 Slack bot alert
  frontend/public/images/integrations/slack-bot.png
  frontend/src/integrations/slack/components/slack-connect.vue
  frontend/src/modules/integration/components/integration-list-page.vue
  frontend/src/shared/dialog/confirm-dialog.js
Labels: Improvement

#1416 Add last synced information to integrations
  frontend/src/modules/integration/components/integration-list-item.vue
Labels: Improvement

#1440 Organization merge
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/organization/components/organization-merge-dialog.vue
  frontend/src/modules/organization/components/organization-selection-dropdown.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/modules/organization/organization-service.js
Labels: Feature

#1443 Fix creation of parent and grandparent segment documents for members/orgs
  backend/src/database/repositories/organizationRepository.ts
  services/apps/search_sync_worker/src/service/member.sync.service.ts
  services/apps/search_sync_worker/src/service/organization.sync.service.ts
Labels: Bug

#1448 Organiaztion support multiple identities
  frontend/src/integrations/crunchbase/config.js
  frontend/src/modules/organization/components/form/organization-form-identities.vue
  frontend/src/modules/organization/components/organization-identities.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/organization-model.js
  frontend/src/modules/organization/pages/organization-form-page.vue
Labels: Feature

#1449 Change crowd.dev copies to LFX
  frontend/docs/custom-logos.md
  frontend/src/i18n/en.js
  frontend/src/i18n/es.js
  frontend/src/i18n/pt-BR.js
  frontend/src/integrations/discourse/components/discourse-connect-drawer.vue
  frontend/src/integrations/github/components/github-connect.vue
  frontend/src/integrations/hackernews/components/hackerNews-connect-drawer.vue
  frontend/src/integrations/hubspot/components/hubspot-readonly-attr-popover.vue
  frontend/src/integrations/hubspot/components/hubspot-settings-drawer.vue
  frontend/src/integrations/n8n/components/n8n-connect-drawer.vue
  frontend/src/integrations/n8n/config.js
  frontend/src/integrations/zapier/components/zapier-connect-drawer.vue
  frontend/src/integrations/zapier/config.js
  frontend/src/modules/automation/components/executions/automation-execution.vue
  frontend/src/modules/automation/config/automation-types/slack/slack-action.vue
  frontend/src/modules/integration/components/integration-list-page.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/settings/settings-pricing-plans.js
  frontend/src/modules/tenant/tenant-model.js
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-keywords-step.vue
  frontend/tests/e2e/auth/data.json
Labels: Improvement

#1465 Detect stream type and process accordingly
  services/apps/integration_stream_worker/src/repo/incomingWebhook.repo.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
Labels: Bug

#1466 trigger process webhook stream with webhook id
  services/apps/integration_data_worker/src/service/integrationDataService.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
Labels: Bug

#1467 Force typescript for org enrich config
  frontend/src/modules/organization/config/enrichment/affiliatedProfiles.ts
  frontend/src/modules/organization/config/enrichment/allSubsidiaries.ts
  frontend/src/modules/organization/config/enrichment/alternativeDomains.ts
  frontend/src/modules/organization/config/enrichment/alternativeNames.ts
  frontend/src/modules/organization/config/enrichment/averageEmployeeTenure.ts
  frontend/src/modules/organization/config/enrichment/averageTenureByLevel.ts
  frontend/src/modules/organization/config/enrichment/averageTenureByRole.ts
  frontend/src/modules/organization/config/enrichment/directSubsidiaries.ts
  frontend/src/modules/organization/config/enrichment/employeeChurnRate.ts
  frontend/src/modules/organization/config/enrichment/employeeCount.ts
  frontend/src/modules/organization/config/enrichment/employeeCountByCountry.ts
  frontend/src/modules/organization/config/enrichment/employeeCountByMonth.ts
  frontend/src/modules/organization/config/enrichment/employeeGrowthRate.ts
  frontend/src/modules/organization/config/enrichment/founded.ts
  frontend/src/modules/organization/config/enrichment/gicsSector.ts
  frontend/src/modules/organization/config/enrichment/grossAdditionsByMonth.ts
  frontend/src/modules/organization/config/enrichment/grossDeparturesByMonth.ts
  frontend/src/modules/organization/config/enrichment/headcount.ts
  frontend/src/modules/organization/config/enrichment/immediateParent.ts
  frontend/src/modules/organization/config/enrichment/index.ts
  frontend/src/modules/organization/config/enrichment/industry.ts
  frontend/src/modules/organization/config/enrichment/lastEnrichedAt.ts
  frontend/src/modules/organization/config/enrichment/revenueRange.ts
  frontend/src/modules/organization/config/enrichment/tags.ts
  frontend/src/modules/organization/config/enrichment/type.ts
  frontend/src/modules/organization/config/enrichment/ultimateParent.ts
  frontend/src/modules/organization/types/Attributes.ts
Labels: Improvement

#1458 Organization identities and merging
  backend/src/api/organization/index.ts
  backend/src/api/organization/organizationCreate.ts
  backend/src/api/organization/organizationMerge.ts
  backend/src/database/migrations/U1693899411__organizationIdentities.sql
  backend/src/database/migrations/V1693899411__organizationIdentities.sql
  backend/src/database/models/organization.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/serverless/microservices/nodejs/bulk-enrichment/enrichMemberOrganizationsWorker.ts
  backend/src/services/helpers/mergeFunctions.ts
  backend/src/services/memberService.ts
  backend/src/services/organizationService.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
  backend/src/services/premium/enrichment/types/organizationEnrichmentTypes.ts
  frontend/src/integrations/crunchbase/config.js
  frontend/src/modules/organization/components/form/organization-form-identities.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/organization/components/organization-identities.vue
  frontend/src/modules/organization/components/organization-merge-dialog.vue
  frontend/src/modules/organization/components/organization-selection-dropdown.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/modules/organization/organization-model.js
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-form-page.vue
  frontend/src/shared/platform/platform-list.vue
  frontend/src/shared/platform/platform-popover.vue
  frontend/src/shared/platform/platform.vue
  services/apps/data_sink_worker/src/repo/organization.data.ts
  services/apps/data_sink_worker/src/repo/organization.repo.ts
  services/apps/data_sink_worker/src/service/member.service.ts
  services/apps/data_sink_worker/src/service/organization.service.ts
  services/apps/search_sync_worker/src/queue/index.ts
  services/apps/search_sync_worker/src/repo/activity.repo.ts
  services/apps/search_sync_worker/src/repo/member.repo.ts
  services/apps/search_sync_worker/src/repo/organization.data.ts
  services/apps/search_sync_worker/src/repo/organization.repo.ts
  services/apps/search_sync_worker/src/service/activity.sync.service.ts
  services/apps/search_sync_worker/src/service/member.sync.service.ts
  services/apps/search_sync_worker/src/service/organization.sync.service.ts
  services/libs/integrations/src/integrations/github/processData.ts
  services/libs/integrations/src/integrations/premium/hubspot/field-mapper/memberFieldMapper.ts
  services/libs/integrations/src/integrations/premium/hubspot/field-mapper/organizationFieldMapper.ts
  services/libs/opensearch/src/models/organizations.ts
  services/libs/opensearch/src/organizationTranslator.ts
  services/libs/sqs/src/instances/searchSyncWorker.ts
  services/libs/types/src/organizations.ts
  services/libs/types/src/queue/search_sync_worker/index.ts
Labels: Feature

#1472 intersecting roles fix on org merge
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#1477 Fix unleash context checking
  frontend/src/featureFlag/index.js
Labels: Bug

#1484 Url removed from partial organization updates
  services/apps/data_sink_worker/src/repo/organization.data.ts
  services/apps/data_sink_worker/src/service/organization.service.ts
Labels: Bug

#1482 Fix rendering of custom platforms in org list
  frontend/src/modules/organization/components/organization-identities.vue
Labels: Bug

#1483 Bugfix/integrations
  backend/src/database/repositories/incomingWebhookRepository.ts
  backend/src/database/repositories/segmentRepository.ts
  services/apps/integration_stream_worker/src/bin/process-stream.ts
  services/libs/integrations/src/integrations/devto/api/articles.ts
  services/libs/integrations/src/integrations/reddit/api/getComments.ts
  services/libs/integrations/src/integrations/reddit/api/getMoreComments.ts
  services/libs/integrations/src/integrations/slack/api/getChannels.ts
Labels: Bug

#1157 Role based access frontend
  frontend/src/i18n/en.js
  frontend/src/modules/auth/pages/email-unverified-page.vue
  frontend/src/modules/auth/pages/forgot-password-page.vue
  frontend/src/modules/auth/pages/password-reset-page.vue
  frontend/src/modules/auth/pages/verify-email-page.vue
  frontend/src/modules/dashboard/components/dashboard-project-group.vue
  frontend/src/modules/index.ts
  frontend/src/modules/integration/integration-routes.js
  frontend/src/modules/lf/layout/components/lf-menu-project-group-selection.vue
  frontend/src/modules/lf/layout/components/lf-menu.vue
  frontend/src/modules/lf/lf-routes.js
  frontend/src/modules/lf/segments/components/view/lf-search-input.vue
  frontend/src/modules/lf/segments/pages/lf-admin-panel-page.vue
  frontend/src/modules/lf/segments/pages/lf-project-groups-list-page.vue
  frontend/src/modules/lf/segments/pages/lf-project-groups-page.vue
  frontend/src/modules/lf/segments/pages/lf-projects-page.vue
  frontend/src/modules/lf/segments/store/actions.js
  frontend/src/modules/settings/components/plan-modal.vue
  frontend/src/modules/settings/pages/plans-page.vue
  frontend/src/modules/settings/pages/settings-page.vue
  frontend/src/modules/settings/settings-pricing-plans.js
  frontend/src/modules/user/components/form/user-form.vue
  frontend/src/modules/user/components/list/user-list-table.vue
  frontend/src/modules/user/components/list/user-list-toolbar.vue
  frontend/src/modules/user/components/user-dropdown.vue
  frontend/src/modules/user/pages/user-edit-page.vue
  frontend/src/modules/user/pages/user-list-page.vue
  frontend/src/modules/user/pages/user-new-page.vue
  frontend/src/modules/user/user-destroy-store.js
  frontend/src/modules/user/user-form-store.js
  frontend/src/modules/user/user-list-exporter-fields.js
  frontend/src/modules/user/user-list-store.js
  frontend/src/modules/user/user-model.js
  frontend/src/modules/user/user-module.js
  frontend/src/modules/user/user-permissions.js
  frontend/src/modules/user/user-routes.js
  frontend/src/modules/user/user-service.js
  frontend/src/modules/user/user-store.js
  frontend/src/modules/user/user-view-store.js
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-result-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-intro-step.vue
  frontend/src/premium/eagle-eye/eagle-eye-permissions.js
  frontend/src/security/permissions.js
  frontend/src/security/roles.js
  frontend/src/shared/exporter/exporter-schema.js
  frontend/src/shared/exporter/exporter.js
  frontend/src/shared/fields/enumerator-field.js
  frontend/src/shared/fields/images-field.js
  frontend/src/shared/form/fields/roles-field.js
  frontend/src/utils/segments.js
Labels: Feature

#1493 Fix identities management
  frontend/src/modules/organization/components/form/organization-form-identities.vue
  frontend/src/modules/organization/components/organization-identities.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/pages/organization-form-page.vue
Labels: Bug

#1500 Missing indexes, script improvements, fixes
  backend/src/bin/jobs/memberScoreCoordinator.ts
  backend/src/bin/nodejs-worker.ts
  backend/src/database/migrations/U1694760454__segment-activity-channels-missing-index.sql
  backend/src/database/migrations/V1694760454__segment-activity-channels-missing-index.sql
  services/apps/data_sink_worker/package.json
  services/apps/data_sink_worker/src/bin/process-results.ts
  services/apps/integration_run_worker/src/bin/onboard-integration.ts
  services/apps/search_sync_worker/src/service/organization.sync.service.ts
Labels: Bug, Improvement

#1501 Add segments to organization merge endpoints
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/organization/components/organization-merge-dialog.vue
  frontend/src/modules/organization/components/organization-selection-dropdown.vue
Labels: Bug

#1504 Remove member org enrichment that was using clearbit.
  backend/src/bin/jobs/checkStuckIntegrationRuns.ts
  backend/src/bin/nodejs-worker.ts
  backend/src/serverless/microservices/nodejs/bulk-enrichment/enrichMemberOrganizationsWorker.ts
  backend/src/serverless/microservices/nodejs/workerFactory.ts
  backend/src/serverless/utils/nodeWorkerSQS.ts
  services/apps/data_sink_worker/src/service/member.service.ts
  services/libs/sqs/src/instances/nodejsWorker.ts
  services/libs/types/src/queue/nodejs_worker/index.ts
Labels: Bug, Improvement

#1509 Add script for mapping individual member to organization
  services/apps/data_sink_worker/package.json
  services/apps/data_sink_worker/src/bin/map-member-to-org.ts
  services/apps/data_sink_worker/src/bin/map-tenant-members-to-org.ts
  services/apps/data_sink_worker/src/repo/member.data.ts
Labels: Improvement

#1511 Retry after DNS error for SQS
  backend/src/bin/nodejs-worker.ts
  services/libs/sqs/package-lock.json
  services/libs/sqs/package.json
  services/libs/sqs/src/client.ts
Labels: Bug, Improvement

#1503 Hubspot integration sync errors & better error handling
  services/apps/data_sink_worker/src/service/member.service.ts
  services/apps/data_sink_worker/src/service/organization.service.ts
  services/apps/integration_sync_worker/src/errors.ts
  services/apps/integration_sync_worker/src/service/member.sync.service.ts
  services/apps/integration_sync_worker/src/service/organization.sync.service.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchUpdateMembers.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchUpdateOrganizations.ts
Labels: Bug

#1488 removed processing state for integration.streams
  services/apps/integration_stream_worker/src/repo/integrationStream.repo.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
  services/libs/types/src/enums/integrations.ts
Labels: Bug

#1512 Checking primary key maps in while creating/updating in hubspot
  services/libs/integrations/src/integrations/premium/hubspot/api/batchCreateMembers.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchCreateOrganizations.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchUpdateMembers.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchUpdateOrganizations.ts
Labels: Bug

#1514 Prevent duplicate organization creation via `website` check
  backend/src/services/organizationService.ts
  services/apps/data_sink_worker/src/service/organization.service.ts
Labels: Improvement

#1459 Update docs for list conversation
  backend/openapi.json
  backend/src/api/conversation/conversationList.ts
  backend/src/documentation/openapi.json
Labels: Improvement

#1526 Fix member error if no suggestions
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
Labels: Bug

#1527 Integration bugfixes
  scripts/services/docker/Dockerfile.script_executor
  services/apps/integration_stream_worker/package.json
  services/apps/integration_stream_worker/src/bin/process-all-streams.ts
  services/apps/integration_stream_worker/src/bin/process-all-webhooks.ts
  services/apps/integration_stream_worker/src/bin/process-webhook.ts
  services/apps/integration_stream_worker/src/bin/trigger-all-failed-webhooks.ts
  services/apps/integration_stream_worker/src/bin/trigger-webhook.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
  services/libs/database/src/connection.ts
  services/libs/integrations/src/integrations/github/processStream.ts
  services/libs/sqs/src/instances/integrationStreamWorker.ts
Labels: Bug

#1525 Update `updatedAt` timestamp after a integration check
  services/apps/integration_run_worker/src/repo/integrationRun.repo.ts
Labels: Bug

#1518 Improve Log rocket logging
  frontend/src/app.vue
  frontend/src/integrations/hubspot/components/hubspot-connect.vue
  frontend/src/integrations/linkedin/components/linkedin-connect.vue
  frontend/src/main.ts
  frontend/src/modules/auth/auth-current-tenant.js
  frontend/src/modules/automation/config/automation-types/hubspot/config.ts
  frontend/src/modules/automation/pages/automation-list-page.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-item.vue
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/modules/layout/pages/paywall-page.vue
  frontend/src/modules/member/member-enrichment.js
  frontend/src/modules/user/types/User.ts
  frontend/src/premium/eagle-eye/pages/eagle-eye-onboard-page.vue
  frontend/src/premium/eagle-eye/pages/eagle-eye-page-wrapper.vue
  frontend/src/shared/error/errors.js
  frontend/src/shared/modules/filters/components/FilterDropdown.vue
  frontend/src/shared/monitoring/identify.js
  frontend/src/utils/featureFlag/index.js
  frontend/src/utils/logRocket/index.ts
Labels: Improvement

#1529 Using throttler while fetching hubspot contact associations
  services/libs/integrations/src/integrations/premium/hubspot/api/contactAssociations.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/contacts.ts
Labels: Bug

#1531 Discard organizations without name when getting contact associations
  services/libs/integrations/src/integrations/premium/hubspot/api/contacts.ts
Labels: Bug

#1532 Stricter throttler options for hubspot
  services/libs/integrations/src/integrations/premium/hubspot/processStream.ts
Labels: Bug

#1537 Fix organization dropdown for affilation form
  frontend/src/modules/lf/member/components/form/lf-member-form-affiliations.vue
Labels: Bug

#1481 Normalize existing website column of organization
  backend/src/database/migrations/U1694533080__normalizeOrgWebsiteColumn.sql
  backend/src/database/migrations/V1694533080__normalizeOrgWebsiteColumn.sql
  backend/src/database/repositories/organizationRepository.ts
  services/apps/data_sink_worker/src/repo/organization.repo.ts
Labels: Improvement

#1538 Synchronous stream processing in hubspot
  services/libs/integrations/src/integrations/premium/hubspot/api/contacts.ts
  services/libs/integrations/src/integrations/premium/hubspot/generateStreams.ts
  services/libs/integrations/src/integrations/premium/hubspot/processStream.ts
  services/libs/integrations/src/integrations/premium/hubspot/types.ts
Labels: Improvement

#1510 Create organization using website if not found
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/memberService.ts
  backend/src/services/organizationService.ts
  services/apps/data_sink_worker/package-lock.json
  services/apps/data_sink_worker/package.json
  services/apps/data_sink_worker/src/repo/organization.repo.ts
  services/apps/data_sink_worker/src/service/member.service.ts
  services/apps/data_sink_worker/src/service/organization.service.ts
  services/libs/common/src/emailDomainValidator.ts
  services/libs/common/src/index.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchCreateOrganizations.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/contacts.ts
Labels: Improvement

#1540 Not sanitizing URLs that doesn't start with http when getting organization domain
  services/libs/integrations/src/integrations/premium/hubspot/api/utils/getOrganizationDomain.ts
Labels: Bug

#1517 Repo module
  frontend/src/integrations/github/components/github-connect.vue
  frontend/src/integrations/github/components/github-settings-drawer.vue
  frontend/src/integrations/github/components/github-settings.vue
  frontend/src/modules/integration/components/integration-connect.vue
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/modules/integration/integration-service.js
  frontend/src/modules/integration/integration-store.js
  frontend/src/shared/form/form-item.vue
Labels: Feature

#1543 Repo mapping for non lfx
  frontend/src/modules/integration/integration-service.js
  frontend/src/modules/integration/integration-store.js
Labels: Improvement

#1544 Fix search not displaying when entering query
  frontend/src/modules/lf/layout/components/lf-menu-project-group-selection.vue
  frontend/src/modules/lf/segments/components/lf-sub-projects-list-modal.vue
Labels: Bug

#1536 Add custom date ranges to custom reports
  frontend/src/assets/scss/form/date-picker.scss
  frontend/src/modules/report/components/report-grid-layout.vue
  frontend/src/modules/widget/components/cube/_query_builder/DateRangeSelect.vue
  frontend/src/modules/widget/components/cube/widget-cube-builder.vue
Labels: Improvement

#1546 Exponential backoff in throttler and changing visibility timeout for long running streams
  services/apps/integration_stream_worker/src/queue/index.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
  services/libs/common/src/requestThrottler.ts
  services/libs/integrations/src/integrations/nango.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/addContactsToList.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchCreateMembers.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchCreateOrganizations.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchUpdateMembers.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchUpdateOrganizations.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/companies.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/companyById.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/contactAssociations.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/contactById.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/contacts.ts
  services/libs/integrations/src/integrations/premium/hubspot/processStream.ts
  services/libs/integrations/src/integrations/premium/hubspot/processSyncRemote.ts
  services/libs/integrations/src/types.ts
  services/libs/sqs/src/client.ts
  services/libs/sqs/src/queue.ts
Labels: Bug

#1549 Fix organization csv export
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
Labels: Bug

#1554 Fix form page freezing
  frontend/src/modules/member/pages/member-form-page.vue
Labels: Bug

#1552 Postgres replication identity fixes
  backend/src/database/migrations/U1695667633__entitySegmentsReplicationIdentitiesFix.sql
  backend/src/database/migrations/V1695667633__entitySegmentsReplicationIdentitiesFix.sql
Labels: Bug

#1555 Fix autocomplete many input
  frontend/src/shared/form/autocomplete-many-input.vue
Labels: Bug

#1542 Auto merge member on identity conflict during enrichment
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
Labels: Bug

#1545 Put organization handles to config
  frontend/src/integrations/crunchbase/config.js
  frontend/src/integrations/devto/config.js
  frontend/src/integrations/discord/config.js
  frontend/src/integrations/discourse/config.js
  frontend/src/integrations/facebook/config.js
  frontend/src/integrations/git/config.js
  frontend/src/integrations/github/config.js
  frontend/src/integrations/groupsio/config.js
  frontend/src/integrations/hackernews/config.js
  frontend/src/integrations/hubspot/config.js
  frontend/src/integrations/linkedin/config.js
  frontend/src/integrations/make/config.js
  frontend/src/integrations/n8n/config.js
  frontend/src/integrations/reddit/config.js
  frontend/src/integrations/slack/config.js
  frontend/src/integrations/stackoverflow/config.js
  frontend/src/integrations/twitter/config.js
  frontend/src/integrations/zapier/config.js
  frontend/src/modules/organization/components/organization-identities.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
Labels: Bug

#1558 Fix activities and conversations pagination
  frontend/src/modules/activity/components/activity-list.vue
  frontend/src/modules/conversation/components/conversation-list.vue
Labels: Bug

#1559 Single quote sanitization when finding organization identities
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#1564 Move certain platform identities to buttons in slack notifications
  backend/src/serverless/microservices/nodejs/automation/workers/slack/newActivityBlocks.ts
  backend/src/serverless/microservices/nodejs/automation/workers/slack/newMemberBlocks.ts
Labels: Improvement

#1528 Enhancement/organization premium data points c 2178
  services/apps/integration_sync_worker/src/repo/organization.repo.ts
  services/apps/search_sync_worker/src/repo/organization.data.ts
  services/apps/search_sync_worker/src/repo/organization.repo.ts
  services/apps/search_sync_worker/src/service/init.service.ts
  services/apps/search_sync_worker/src/service/opensearch.service.ts
  services/apps/search_sync_worker/src/service/organization.sync.service.ts
  services/libs/integrations/src/integrations/premium/hubspot/field-mapper/organizationFieldMapper.ts
  services/libs/opensearch/src/models/organizations.ts
  services/libs/types/src/organizations.ts
Labels: Improvement

#1569 Saving lastSyncedPayload to syncRemote tables for easier debugging
  backend/src/database/migrations/U1695885001__lastSyncedPayloadForSyncRemoteTables.sql
  backend/src/database/migrations/V1695885001__lastSyncedPayloadForSyncRemoteTables.sql
  services/apps/integration_sync_worker/src/repo/member.repo.ts
  services/apps/integration_sync_worker/src/repo/organization.repo.ts
  services/apps/integration_sync_worker/src/service/member.sync.service.ts
  services/apps/integration_sync_worker/src/service/organization.sync.service.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchCreateMembers.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchCreateOrganizations.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchUpdateMembers.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchUpdateOrganizations.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/types.ts
  services/libs/integrations/src/integrations/premium/hubspot/processSyncRemote.ts
Labels: Improvement

#1575 Organization findById update in integration sync worker
  services/apps/integration_sync_worker/src/repo/organization.repo.ts
  services/apps/integration_sync_worker/src/service/organization.sync.service.ts
Labels: Bug

#1576 Process old streams/data/results
  services/apps/data_sink_worker/src/jobs/processOldResults.ts
  services/apps/data_sink_worker/src/main.ts
  services/apps/data_sink_worker/src/repo/dataSink.repo.ts
  services/apps/data_sink_worker/src/service/dataSink.service.ts
  services/apps/integration_data_worker/src/jobs/processOldData.ts
  services/apps/integration_data_worker/src/main.ts
  services/apps/integration_data_worker/src/repo/integrationData.repo.ts
  services/apps/integration_data_worker/src/service/integrationDataService.ts
  services/apps/integration_stream_worker/src/jobs/processOldStreams.ts
  services/apps/integration_stream_worker/src/main.ts
  services/apps/integration_stream_worker/src/repo/integrationStream.data.ts
  services/apps/integration_stream_worker/src/repo/integrationStream.repo.ts
  services/apps/integration_stream_worker/src/service/integrationStreamService.ts
  services/libs/redis/src/mutex.ts
Labels: Improvement
