Repository CrowdDotDev/crowd.dev, pull requests merged in 2023-10, with the labels that each got.

#1608 Hubspot integration partial stream parsing
  services/libs/common/src/requestThrottler.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/companies.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/contacts.ts
Labels: Bug

#1605 Organizations merge suggestions
  backend/src/api/organization/index.ts
  backend/src/api/organization/organizationNotMerge.ts
  backend/src/api/tenant/index.ts
  backend/src/api/tenant/tenantOrganizationsToMerge.ts
  backend/src/database/migrations/U1695972877__organizationMergeSuggestions.sql
  backend/src/database/migrations/V1695972877__organizationMergeSuggestions.sql
  backend/src/database/repositories/organizationRepository.ts
  backend/src/serverless/microservices/nodejs/merge-suggestions/mergeSuggestionsWorker.ts
  backend/src/services/organizationService.ts
  backend/src/services/tenantService.ts
  frontend/src/modules/organization/organization-routes.js
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
  services/apps/search_sync_worker/src/repo/organization.data.ts
  services/apps/search_sync_worker/src/repo/organization.repo.ts
  services/apps/search_sync_worker/src/service/init.service.ts
  services/apps/search_sync_worker/src/service/organization.sync.service.ts
  services/libs/types/src/enums/organizations.ts
  services/libs/types/src/organizations.ts
Labels: Feature

#1604 Discourse getUser bugfix
  backend/package.json
  backend/src/bin/scripts/process-webhook.ts
  backend/src/bin/scripts/trigger-webhook.ts
  backend/src/serverless/integrations/services/integrations/discourseIntegrationService.ts
  backend/src/serverless/integrations/usecases/discourse/getUser.ts
  scripts/services/docker/Dockerfile.script_executor
Labels: Bug

#1452 feat: added time frame granularity to urls for reports
  frontend/src/modules/report/components/templates/report-template-filters.vue
  frontend/src/modules/widget/components/activity/widget-activities-leaderboard.vue
  frontend/src/modules/widget/components/activity/widget-activities-platform.vue
  frontend/src/modules/widget/components/activity/widget-new-activities.vue
  frontend/src/modules/widget/components/activity/widget-total-activities.vue
  frontend/src/modules/widget/components/member/widget-active-leaderboard-members.vue
  frontend/src/modules/widget/components/member/widget-active-members.vue
  frontend/src/modules/widget/components/member/widget-total-members.vue
  frontend/src/modules/widget/components/product-community-fit/widget-benchmark.vue
  frontend/src/modules/widget/components/product-community-fit/widget-monthly-active-contributors.vue
  frontend/src/modules/widget/widget-utility.js
Labels: 🙋 Bounty claim

#1630 Add function to fetch active organizations in the last year
  backend/src/bin/scripts/enrich-organizations-synchronous.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/serverless/microservices/nodejs/bulk-enrichment/bulkOrganizationEnrichmentWorker.ts
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
Labels: Improvement

#1633 Auto merge organization on website conflict during enrichment
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
Labels: Bug

#1578 New onboarding flow
  backend/src/api/tenant/tenantCreate.ts
  frontend/public/images/integrations/onboard/onboard-github-preview.png
  frontend/src/app.vue
  frontend/src/integrations/devto/config.js
  frontend/src/integrations/discord/config.js
  frontend/src/integrations/discourse/components/discourse-connect-drawer.vue
  frontend/src/integrations/discourse/config.js
  frontend/src/integrations/git/components/git-connect-drawer.vue
  frontend/src/integrations/git/config.js
  frontend/src/integrations/github/components/github-connect.vue
  frontend/src/integrations/github/config.js
  frontend/src/integrations/groupsio/components/groupsio-connect-drawer.vue
  frontend/src/integrations/hackernews/config.js
  frontend/src/integrations/n8n/config.js
  frontend/src/integrations/reddit/config.js
  frontend/src/integrations/slack/config.js
  frontend/src/integrations/stackoverflow/config.js
  frontend/src/integrations/zapier/config.js
  frontend/src/jsons/onboard-platforms.json
  frontend/src/jsons/tenant-community-size.json
  frontend/src/middleware/auth/auth-guard.js
  frontend/src/modules/auth/pages/invitation-page.vue
  frontend/src/modules/auth/store/actions.js
  frontend/src/modules/dashboard/components/dashboard-guides.vue
  frontend/src/modules/dashboard/components/guide/dashboard-guide-eagle-eye-modal.vue
  frontend/src/modules/layout/components/workspace-dropdown.vue
  frontend/src/modules/onboard/components/onboard-community.vue
  frontend/src/modules/onboard/components/onboard-integration-item.vue
  frontend/src/modules/onboard/components/onboard-invite-colleagues-step.vue
  frontend/src/modules/onboard/components/onboard-sync-data-step.vue
  frontend/src/modules/onboard/components/onboard-user-array-input.vue
  frontend/src/modules/onboard/components/onboard-workspace-details-step.vue
  frontend/src/modules/onboard/config/achievements.config.js
  frontend/src/modules/onboard/config/steps/index.ts
  frontend/src/modules/onboard/config/steps/invite-colleagues.ts
  frontend/src/modules/onboard/config/steps/sync-data.ts
  frontend/src/modules/onboard/config/steps/workspace-details.ts
  frontend/src/modules/onboard/onboard-routes.js
  frontend/src/modules/onboard/pages/onboard-book-a-demo-page.vue
  frontend/src/modules/onboard/pages/onboard-page.vue
  frontend/src/modules/onboard/types/OnboardStepsConfig.ts
  frontend/src/modules/tenant/components/tenant-created-modal.vue
  frontend/src/modules/tenant/components/tenant-list-drawer.vue
  frontend/src/modules/tenant/components/tenant-new-form.vue
  frontend/src/modules/tenant/store/actions.js
  frontend/src/modules/user/types/Roles.ts
  frontend/src/router/index.js
  frontend/tailwind.config.js
Labels: Improvement

#1627 Pricing pages and paywalls
  frontend/index.html
  frontend/src/modules/automation/automation-limit.js
  frontend/src/modules/layout/pages/paywall-page.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-enrichment.vue
  frontend/src/modules/member/member-enrichment.js
  frontend/src/modules/member/member-export-limit.js
  frontend/src/modules/member/store/actions.js
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/settings/components/plan-modal.vue
  frontend/src/modules/settings/pages/plans-page.vue
  frontend/src/modules/settings/pages/settings-page.vue
  frontend/src/modules/settings/settings-pricing-plans.js
  frontend/src/security/plans-limits.ts
  frontend/src/utils/featureFlag/index.js
Labels: Improvement

#1618 Update trial logic after onboarding
  backend/src/database/repositories/tenantRepository.ts
  backend/src/services/__tests__/tenantService.test.ts
Labels: Improvement

#1622 Update Feature Flags for new plans
  backend/src/api/conversation/conversationSettingsUpdate.ts
  backend/src/bin/scripts/unleash-init.ts
  backend/src/feature-flags/isFeatureEnabled.ts
  backend/src/types/common.ts
Labels: Improvement

#1638 Fix members links
  backend/src/serverless/microservices/nodejs/automation/workers/slack/newActivityBlocks.ts
  backend/src/serverless/microservices/nodejs/automation/workers/slack/newMemberBlocks.ts
  backend/src/services/quickstartGuideService.ts
Labels: Bug

#1639 Improve organization merge during enrichment
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
Labels: Bug

#1640 Support redirect
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/member-routes.js
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/organization/pages/organization-list-page.vue
Labels: Bug

#1641 Update automations limitation logic for new pricing plans
  backend/src/database/repositories/automationRepository.ts
Labels: Improvement

#1643 Fix invite issue on loggedin users
  backend/src/database/repositories/userRepository.ts
Labels: Bug

#1644 Fix invitation signin checking
  frontend/src/modules/auth/pages/invitation-page.vue
Labels: Bug

#1649 Organization merge suggestion improvements
  backend/src/bin/scripts/generate-merge-suggestions.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/serverless/microservices/nodejs/merge-suggestions/mergeSuggestionsWorker.ts
  backend/src/services/organizationService.ts
Labels: Improvement

#1651 Reload tenants on tenant create
  frontend/src/modules/tenant/components/tenant-new-form.vue
Labels: Bug

#1652 Hide user dropdown for current user
  frontend/src/modules/user/components/list/user-list-table.vue
  frontend/src/modules/user/components/list/user-list-toolbar.vue
Labels: Bug

#1650 Fix widget number icon
  frontend/src/modules/widget/components/widget-number.vue
Labels: Bug

#1654 Fix analytics user identification
  frontend/src/app.vue
  frontend/src/modules/layout/components/layout.vue
Labels: Bug

#1655 No merge array existence check before parsing the suggestion query
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#1657 Fix object being passed to analytics
  frontend/src/app.vue
Labels: Bug

#1658 Fix member and activity count in organization find
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#1659 Better score normalization organization merge suggestions
  backend/package.json
  backend/src/bin/jobs/mergeSuggestions.ts
  backend/src/bin/scripts/generate-merge-suggestions.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/organizationService.ts
  services/apps/search_sync_worker/src/service/organization.sync.service.ts
Labels: Improvement

#1661 Pass the existing transaction to merge organizations on enrichment
  backend/src/services/IServiceOptions.ts
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
Labels: Bug

#1667 No org merge suggestion button
  frontend/src/modules/organization/pages/organization-list-page.vue
Labels: Bug

#1668 refactor to remove the check integrations step on nodejs-worker
  backend/src/bin/jobs/checkStuckIntegrationRuns.ts
  backend/src/bin/nodejs-worker.ts
  backend/src/bin/scripts/continue-run.ts
  backend/src/bin/scripts/process-integration.ts
  backend/src/bin/worker/integrations.ts
  backend/src/database/repositories/integrationRunRepository.ts
  backend/src/serverless/integrations/services/integrationCheckProcessor.ts
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/integrations/services/integrationRunProcessor.ts
  backend/src/serverless/integrations/services/integrationServiceBase.ts
  backend/src/serverless/integrations/services/integrationTickProcessor.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/services/integrationService.ts
  backend/src/types/integrationRunTypes.ts
  backend/src/types/mq/nodeWorkerIntegrationCheckMessage.ts
Labels: Integration 🔌, Improvement

#1671 added back process.exit otherwise services don't die
  services/libs/tracing/src/tracer.ts
Labels: Bug

#1673 fixes and improvements for transaction handling in member and org merge
  backend/src/database/repositories/activityRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/database/repositories/sequelizeRepository.ts
  backend/src/database/repositories/tagRepository.ts
  backend/src/services/memberService.ts
  backend/src/services/organizationService.ts
Labels: Bug

#1688 Fix devto validation blocking onboarding
  frontend/src/integrations/devto/components/devto-connect-drawer.vue
Labels: Bug

#1672 Hubspot resolve duplicate identities with incoming data
  services/apps/data_sink_worker/src/repo/organization.repo.ts
  services/apps/data_sink_worker/src/service/member.service.ts
Labels: Bug

#1692 Post processing edit distances for more precise similarity scores
  backend/package-lock.json
  backend/package.json
  backend/src/database/repositories/organizationRepository.ts
  services/apps/search_sync_worker/src/repo/organization.repo.ts
Labels: Improvement

#1699 Fix organizations update
  frontend/src/modules/organization/components/form/organization-form-identities.vue
  frontend/src/modules/organization/pages/organization-form-page.vue
Labels: Bug

#1689 Fix joined on custom platform
  frontend/src/modules/dashboard/components/dashboard-members.vue
Labels: Bug

#1687 Fix custom identity display for organizations
  frontend/src/modules/organization/components/view/organization-view-aside.vue
Labels: Bug

#1665 Add git identity editing
  frontend/src/modules/member/components/form/member-form-identities.vue
Labels: Improvement

#1697 Init proposal for new service framework
  scripts/scaffold.yaml
  scripts/scaffold/temporal/Dockerfile
  services/apps/template_consumer/.eslintrc.cjs
  services/apps/template_consumer/.prettierignore
  services/apps/template_consumer/.prettierrc.cjs
  services/apps/template_consumer/package-lock.json
  services/apps/template_consumer/package.json
  services/apps/template_consumer/src/main.ts
  services/apps/template_consumer/tsconfig.json
  services/apps/template_worker/.eslintrc.cjs
  services/apps/template_worker/.prettierignore
  services/apps/template_worker/.prettierrc.cjs
  services/apps/template_worker/package-lock.json
  services/apps/template_worker/package.json
  services/apps/template_worker/src/activities.ts
  services/apps/template_worker/src/activities/greet.ts
  services/apps/template_worker/src/main.ts
  services/apps/template_worker/src/workflows.ts
  services/apps/template_worker/src/workflows/greet.ts
  services/apps/template_worker/tsconfig.json
  services/archetypes/consumer/.eslintrc.cjs
  services/archetypes/consumer/.prettierignore
  services/archetypes/consumer/.prettierrc.cjs
  services/archetypes/consumer/package-lock.json
  services/archetypes/consumer/package.json
  services/archetypes/consumer/src/index.ts
  services/archetypes/consumer/tsconfig.json
  services/archetypes/standard/.eslintrc.cjs
  services/archetypes/standard/.prettierignore
  services/archetypes/standard/.prettierrc.cjs
  services/archetypes/standard/package-lock.json
  services/archetypes/standard/package.json
  services/archetypes/standard/src/index.ts
  services/archetypes/standard/tsconfig.json
  services/archetypes/worker/.eslintrc.cjs
  services/archetypes/worker/.prettierignore
  services/archetypes/worker/.prettierrc.cjs
  services/archetypes/worker/package-lock.json
  services/archetypes/worker/package.json
  services/archetypes/worker/src/index.ts
  services/archetypes/worker/tsconfig.json
  services/libs/logging/package-lock.json
  services/libs/tracing/package-lock.json
  services/libs/tracing/package.json
  services/libs/tracing/src/tracer.ts
  services/scripts/clear_lib_packages.sh
  services/scripts/install_lib_packages.sh
  services/scripts/lint_libs.sh
Labels: Improvement

#1701 Pagination and total_count improvements in organization merge suggestions
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#1707 More preventive identity set on organization update
  backend/src/api/organization/organizationUpdate.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/organizationService.ts
Labels: Bug

#1714 Batch activity updates while merging organizations
  backend/src/database/repositories/organizationRepository.ts
Labels: Improvement

#1700 Fix organization model
  frontend/src/modules/organization/organization-model.js
Labels: Bug

#1676 Improve custom reports performance
  frontend/src/i18n/en.js
  frontend/src/modules/report/components/report-create-dialog.vue
  frontend/src/modules/report/components/report-form.vue
  frontend/src/modules/report/components/report-grid-layout.vue
  frontend/src/modules/report/report-charts.js
  frontend/src/modules/report/report-model.js
  frontend/src/modules/widget/components/cube/widget-cube-builder.vue
  frontend/src/modules/widget/components/cube/widget-cube-renderer.vue
  frontend/src/modules/widget/components/cube/widget-cube.vue
  frontend/src/modules/widget/components/widget-number.vue
  frontend/src/modules/widget/components/widget-table.vue
  frontend/src/modules/widget/components/widget.vue
  frontend/src/modules/widget/widget-field.js
Labels: Bug, Improvement

#1720 Split init and start logic in services
  services/apps/template_consumer/package-lock.json
  services/apps/template_consumer/package.json
  services/apps/template_consumer/src/main.ts
  services/apps/template_worker/package-lock.json
  services/apps/template_worker/package.json
  services/apps/template_worker/src/main.ts
  services/archetypes/consumer/src/index.ts
  services/archetypes/standard/src/index.ts
  services/archetypes/worker/src/index.ts
Labels: Improvement

#1736 Query fix for org sync in search sync worker
  services/apps/search_sync_worker/src/repo/organization.repo.ts
Labels: Bug

#1311 Support for custom views in backend
  backend/src/api/activity/activityQuery.ts
  backend/src/api/conversation/conversationQuery.ts
  backend/src/api/customViews/customViewCreate.ts
  backend/src/api/customViews/customViewDestroy.ts
  backend/src/api/customViews/customViewQuery.ts
  backend/src/api/customViews/customViewUpdate.ts
  backend/src/api/customViews/customViewUpdateBulk.ts
  backend/src/api/customViews/index.ts
  backend/src/api/eagleEyeContent/eagleEyeContentQuery.ts
  backend/src/api/index.ts
  backend/src/api/integration/integrationQuery.ts
  backend/src/api/member/memberQuery.ts
  backend/src/api/member/memberUpdateBulk.ts
  backend/src/api/microservice/microserviceQuery.ts
  backend/src/api/note/noteQuery.ts
  backend/src/api/report/reportQuery.ts
  backend/src/api/tag/tagQuery.ts
  backend/src/api/task/taskQuery.ts
  backend/src/api/widget/widgetQuery.ts
  backend/src/database/migrations/U1695657964__customViews.sql
  backend/src/database/migrations/V1695657964__customViews.sql
  backend/src/database/models/customView.ts
  backend/src/database/models/customViewOrder.ts
  backend/src/database/models/index.ts
  backend/src/database/repositories/customViewRepository.ts
  backend/src/security/permissions.ts
  backend/src/services/customViewService.ts
  backend/src/services/tenantService.ts
  backend/src/types/customView/index.ts
  backend/src/types/customView/member.ts
  backend/src/types/customView/organization.ts
  services/libs/types/src/customView.ts
  services/libs/types/src/enums/customViews.ts
  services/libs/types/src/index.ts
Labels: Feature

#1705 Custom views
  frontend/components.d.ts
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/scss/tooltip.scss
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/member/config/saved-views/main.ts
  frontend/src/modules/member/config/saved-views/settings/bot/MemberBotSetting.vue
  frontend/src/modules/member/config/saved-views/settings/bot/config.ts
  frontend/src/modules/member/config/saved-views/settings/common/includeFilterRenderer.ts
  frontend/src/modules/member/config/saved-views/settings/common/types/IncludeEnum.ts
  frontend/src/modules/member/config/saved-views/settings/organization/config.ts
  frontend/src/modules/member/config/saved-views/settings/teamMember/MemberTeamMemberSetting.vue
  frontend/src/modules/member/config/saved-views/settings/teamMember/config.ts
  frontend/src/modules/member/config/saved-views/views/all-contacts.ts
  frontend/src/modules/member/config/saved-views/views/influential.ts
  frontend/src/modules/member/config/saved-views/views/most-engaged.ts
  frontend/src/modules/member/config/saved-views/views/new-and-active.ts
  frontend/src/modules/member/config/saved-views/views/slipping-away.ts
  frontend/src/modules/member/config/saved-views/views/team-members.ts
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/member/store/pinia/state.ts
  frontend/src/modules/organization/config/saved-views/main.ts
  frontend/src/modules/organization/config/saved-views/settings/common/includeFilterRenderer.ts
  frontend/src/modules/organization/config/saved-views/settings/teamOrganization.ts
  frontend/src/modules/organization/config/saved-views/settings/teamOrganization/OrganizationTeamOrganizationSetting.vue
  frontend/src/modules/organization/config/saved-views/settings/teamOrganization/config.ts
  frontend/src/modules/organization/config/saved-views/views/all-organizations.ts
  frontend/src/modules/organization/config/saved-views/views/most-members.ts
  frontend/src/modules/organization/config/saved-views/views/new-and-active.ts
  frontend/src/modules/organization/config/saved-views/views/team-organizations.ts
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/modules/organization/store/pinia/state.ts
  frontend/src/shared/form/form-item.vue
  frontend/src/shared/modules/filters/components/FilterItem.vue
  frontend/src/shared/modules/filters/components/filterTypes/BooleanFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/DateFilter.vue
  frontend/src/shared/modules/filters/config/apiFilterRenderer/date.filter.renderer.ts
  frontend/src/shared/modules/filters/config/constants/date.constants.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/date.label.renderer.ts
  frontend/src/shared/modules/filters/types/FilterTimeOptions.ts
  frontend/src/shared/modules/saved-views/components/SavedViewManagement.vue
  frontend/src/shared/modules/saved-views/components/SavedViews.vue
  frontend/src/shared/modules/saved-views/components/forms/SavedViewForm.vue
  frontend/src/shared/modules/saved-views/services/saved-views.service.ts
  frontend/src/shared/modules/saved-views/types/SavedViewsConfig.ts
  frontend/src/utils/featureFlag/index.js
Labels: Feature

#1742 Fix custom views listing
  backend/src/database/repositories/customViewRepository.ts
Labels: Bug

#1743 Disable bot settings if team member filtering
  frontend/src/modules/member/config/saved-views/settings/bot/MemberBotSetting.vue
  frontend/src/shared/modules/saved-views/components/forms/SavedViewForm.vue
Labels: Bug

#1728 Update automations limitation
  backend/src/api/auth/authMe.ts
  backend/src/api/automation/index.ts
  backend/src/database/repositories/automationRepository.ts
  backend/src/feature-flags/getFeatureFlagTenantContext.ts
  backend/src/services/automationService.ts
  frontend/src/modules/automation/components/automation-toggle.vue
  frontend/src/modules/automation/pages/automation-list-page.vue
  frontend/src/modules/automation/store/actions.js
Labels: Improvement

#1740 Merge organizations destroy toMerge completely
  backend/package.json
  backend/src/bin/scripts/merge-organizations.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/organizationService.ts
  services/apps/data_sink_worker/src/service/organization.service.ts
Labels: Bug

#1666 Set `displayName` for orgs from work experiences and enrichment
  backend/src/services/organizationService.ts
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
  services/libs/types/src/organizations.ts
Labels: Improvement

#1754 Primary is set before merging
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
Labels: Bug

#1752 Add Custom views tracking
  frontend/src/shared/modules/saved-views/components/SavedViewManagement.vue
  frontend/src/shared/modules/saved-views/components/forms/SavedViewForm.vue
Labels: Improvement

#1761 view not updating
  frontend/src/shared/modules/filters/components/partials/string/FilterInput.vue
  frontend/src/shared/modules/saved-views/components/SavedViews.vue
Labels: Bug

#1764 Add custom filters and fix string filter parsing
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/shared/modules/filters/components/filterTypes/StringFilter.vue
  frontend/src/shared/modules/filters/config/itemLabelRenderer/string.label.renderer.ts
  frontend/src/shared/modules/filters/types/filterTypes/StringFilterConfig.ts
  frontend/src/shared/modules/saved-views/components/SavedViews.vue
  frontend/src/shared/modules/saved-views/components/forms/SavedViewForm.vue
Labels: Bug

#1759 Fix enriched organization filter in organizations
  frontend/src/modules/organization/config/filters/enrichedOrganization/config.ts
  services/libs/opensearch/src/models/organizations.ts
Labels: Bug

#1760 Organizations keeping existing website on integration updates
  services/apps/data_sink_worker/src/service/organization.service.ts
Labels: Improvement

#1770 Longer query timeout for refreshing materialized views
  backend/src/bin/jobs/refreshMaterializedViewsForCube.ts
  backend/src/database/databaseConnection.ts
  backend/src/database/initializers/create.ts
  backend/src/database/models/index.ts
Labels: Improvement

#1771 Menu redesign
  frontend/src/modules/auth/pages/profile-form-page.vue
  frontend/src/modules/automation/automation-module.js
  frontend/src/modules/automation/automation-routes.js
  frontend/src/modules/automation/components/automation-list.vue
  frontend/src/modules/automation/pages/automation-page.vue
  frontend/src/modules/dashboard/components/dashboard-task.vue
  frontend/src/modules/dashboard/pages/dashboard-page.vue
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/layout/components/menu-v2.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/layout/components/menu/menu-header.vue
  frontend/src/modules/layout/components/menu/menu-links.vue
  frontend/src/modules/layout/components/menu/menu-support.vue
  frontend/src/modules/layout/components/menu/menu-workspace.vue
  frontend/src/modules/layout/components/menu/workspace/menu-workspace-card.vue
  frontend/src/modules/layout/components/menu/workspace/menu-workspace-popover.vue
  frontend/src/modules/layout/config/links/activities.ts
  frontend/src/modules/layout/config/links/api-keys.ts
  frontend/src/modules/layout/config/links/automations.ts
  frontend/src/modules/layout/config/links/changelog.ts
  frontend/src/modules/layout/config/links/community.ts
  frontend/src/modules/layout/config/links/contact-us.ts
  frontend/src/modules/layout/config/links/contacts.ts
  frontend/src/modules/layout/config/links/documentation.ts
  frontend/src/modules/layout/config/links/eagle-eye.ts
  frontend/src/modules/layout/config/links/home.ts
  frontend/src/modules/layout/config/links/integrations.ts
  frontend/src/modules/layout/config/links/organizations.ts
  frontend/src/modules/layout/config/links/plans-billing.ts
  frontend/src/modules/layout/config/links/reports.ts
  frontend/src/modules/layout/config/links/share-feedback.ts
  frontend/src/modules/layout/config/links/users-permissions.ts
  frontend/src/modules/layout/config/menu.ts
  frontend/src/modules/layout/types/MenuLink.ts
  frontend/src/modules/settings/pages/settings-page.vue
  frontend/src/modules/settings/settings-routes.js
  frontend/src/modules/tenant/types/TenantModel.ts
  frontend/src/shared/avatar/avatar.vue
  frontend/src/shared/avatar/squared-avatar.vue
  frontend/src/utils/featureFlag/index.js
Labels: Improvement

#1781 Custom views cleanup
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/layout/components/menu-v2.vue
  frontend/src/modules/member/config/saved-views/main.ts
  frontend/src/modules/member/config/saved-views/views/influential.ts
  frontend/src/modules/member/config/saved-views/views/most-engaged.ts
  frontend/src/modules/member/config/saved-views/views/new-and-active.ts
  frontend/src/modules/member/config/saved-views/views/slipping-away.ts
  frontend/src/modules/member/config/saved-views/views/team-members.ts
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/organization/config/saved-views/main.ts
  frontend/src/modules/organization/config/saved-views/views/most-members.ts
  frontend/src/modules/organization/config/saved-views/views/new-and-active.ts
  frontend/src/modules/organization/config/saved-views/views/team-organizations.ts
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/shared/modules/saved-views/components/SavedViews.vue
  frontend/src/utils/featureFlag/index.js
Labels: Improvement

#1751 Restrict custom view updates/deletions to owner
  backend/src/database/repositories/customViewRepository.ts
Labels: Improvement

#1758 Existing website on enriching organizations won't use enrichment data points
  backend/package.json
  backend/src/bin/scripts/fix-auto-merged-orgs.ts
  backend/src/bin/scripts/get-member-enrichment-data.ts
  backend/src/bin/scripts/get-organization-enrichment-data.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
Labels: Bug

#1784 Merging existing tags error when data.tags is not present
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#1787 Handling errors while refreshing materialized views gracefully
  backend/package.json
  backend/src/bin/jobs/refreshMaterializedViews.ts
  backend/src/bin/jobs/refreshMaterializedViewsForCube.ts
  backend/src/bin/scripts/refresh-materialized-views.ts
Labels: Bug

#1791 Force database to reinitilizate with longer query timeout for refresh materialized view jobs
  backend/src/bin/jobs/refreshMaterializedViewsForCube.ts
  backend/src/database/databaseConnection.ts
Labels: Bug

#1794 Add missing tasks button and fix tasks routes
  frontend/src/modules/dashboard/components/dashboard-task.vue
  frontend/src/modules/task/task-routes.js
Labels: Bug

#1797 Developer mode MVP
  frontend/src/modules/layout/components/menu/workspace/menu-workspace-popover.vue
  frontend/src/modules/user/store/pinia/actions.ts
  frontend/src/modules/user/store/pinia/index.ts
  frontend/src/modules/user/store/pinia/state.ts
  frontend/src/shared/modules/filters/components/Filter.vue
  frontend/src/utils/featureFlag/index.js
Labels: Feature

#1792 Organization finding cache - also checking by name sent in payload
  backend/src/services/organizationService.ts
Labels: Bug
