Repository CrowdDotDev/crowd.dev, pull requests merged in 2023-05, with the labels that each got.

#823 Bugfix/activities platform
  backend/src/database/repositories/activityRepository.ts
  frontend/src/modules/widget/components/activity/widget-activities-platform-content.vue
Labels: Bug

#824 Update Zapier integraition instructions
  frontend/src/integrations/zapier/components/zapier-connect-drawer.vue
Labels: Bug

#809 Better integration resilience
  backend/src/bin/jobs/checkStuckIntegrationRuns.ts
  backend/src/bin/nodejs-worker.ts
  backend/src/database/repositories/integrationRepository.ts
  backend/src/database/repositories/integrationRunRepository.ts
  backend/src/database/repositories/integrationStreamRepository.ts
Labels: Bug

#827 Memory optimizations for integration processing
  backend/src/bin/discord-ws.ts
  backend/src/bin/jobs/checkStuckIntegrationRuns.ts
  backend/src/bin/scripts/process-integration.ts
  backend/src/bin/worker/integrations.ts
  backend/src/database/repositories/__tests__/integrationRepository.test.ts
  backend/src/database/repositories/__tests__/microserviceRepository.test.ts
  backend/src/database/repositories/integrationRepository.ts
  backend/src/database/repositories/integrationRunRepository.ts
  backend/src/database/repositories/integrationStreamRepository.ts
  backend/src/database/repositories/microserviceRepository.ts
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/integrations/services/integrationServiceBase.ts
  backend/src/serverless/integrations/services/integrations/devtoIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/slackIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/twitterIntegrationService.ts
  backend/src/types/integration/stepResult.ts
  backend/src/utils/paginationProcessing.ts
Labels: Bug, Improvement

#832 Enhancement/add missing member query indexes c 1311
  backend/src/database/migrations/U1683277017__missing-members-indexes.sql
  backend/src/database/migrations/V1683277017__missing-members-indexes.sql
Labels: Improvement

#830 Incoming Webhook fixes and LinkedIn integration optimization
  backend/src/bin/jobs/checkStuckIntegrationRuns.ts
  backend/src/bin/jobs/cleanUp.ts
  backend/src/bin/jobs/cleanUpIntegrationRuns.ts
  backend/src/bin/jobs/index.ts
  backend/src/database/repositories/incomingWebhookRepository.ts
  backend/src/database/repositories/integrationRunRepository.ts
  backend/src/serverless/integrations/services/integrationRunProcessor.ts
  backend/src/serverless/integrations/services/integrations/premium/linkedinIntegrationService.ts
  backend/src/serverless/integrations/usecases/linkedin/getCommentComments.ts
  backend/src/serverless/integrations/usecases/linkedin/getPostComments.ts
  backend/src/serverless/integrations/usecases/linkedin/getPostReactions.ts
  backend/src/types/webhooks.ts
Labels: Bug, Improvement

#839 Github webhook errors
  backend/src/bin/scripts/process-webhook.ts
  backend/src/database/repositories/incomingWebhookRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/usecases/github/graphql/teams.ts
  backend/src/serverless/integrations/usecases/github/graphql/types.ts
  backend/src/services/activityDisplayService.ts
  backend/src/services/aws.ts
  backend/src/types/webhooks.ts
Labels: Bug

#818 bug: Fixed url encoding
  frontend/src/shared/axios/auth-axios.js
Labels: Bug

#840 Automations bug fixes & improvements
  backend/src/api/automation/automationSlackCallback.ts
  backend/src/database/repositories/automationRepository.ts
  backend/src/serverless/microservices/nodejs/automation/workers/slack/newActivityBlocks.ts
  backend/src/serverless/microservices/nodejs/automation/workers/slack/newMemberBlocks.ts
  frontend/src/modules/automation/components/automation-dropdown.vue
  frontend/src/modules/automation/components/list/automation-list-table.vue
  frontend/src/modules/automation/pages/automation-list-page.vue
Labels: Bug

#790 Member filter tests
  .github/workflows/test-frontend.yml
  frontend/.eslintrc.js
  frontend/package.json
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-channels.vue
  frontend/src/modules/member/components/member-engagement-level.vue
  frontend/src/shared/filter/components/filter-dropdown.vue
  frontend/src/shared/filter/components/filter-list-item.vue
  frontend/src/shared/filter/components/type/filter-type-boolean.vue
  frontend/src/shared/filter/components/type/filter-type-date.vue
  frontend/src/shared/filter/components/type/filter-type-number.vue
  frontend/src/shared/filter/components/type/filter-type-search.vue
  frontend/src/shared/filter/components/type/filter-type-select-group.vue
  frontend/src/shared/filter/components/type/filter-type-select-multi.vue
  frontend/src/shared/filter/components/type/filter-type-select.vue
  frontend/src/shared/form/include-toggle.vue
  frontend/src/shared/form/inline-select-input.vue
  frontend/src/shared/pagination/pagination-sorter.vue
  frontend/tests/e2e/auth.spec.js
  frontend/tests/e2e/auth/index.js
  frontend/tests/e2e/member/filter/active-on.js
  frontend/tests/e2e/member/filter/activity-type.js
  frontend/tests/e2e/member/filter/avg-sentiment.js
  frontend/tests/e2e/member/filter/custom-attributes.js
  frontend/tests/e2e/member/filter/engagement-level.js
  frontend/tests/e2e/member/filter/enriched-member.js
  frontend/tests/e2e/member/filter/identities.js
  frontend/tests/e2e/member/filter/joined-date.js
  frontend/tests/e2e/member/filter/last-activity-date.js
  frontend/tests/e2e/member/filter/no-of-activities.js
  frontend/tests/e2e/member/filter/no-of-open-source-contributions.js
  frontend/tests/e2e/member/filter/reach.js
  frontend/tests/e2e/member/filter/search.js
  frontend/tests/e2e/member/filters.js
  frontend/tests/e2e/member/index.js
  frontend/tests/e2e/test.spec.js
  frontend/tests/support/commands.js
Labels: Improvement

#837 Mark/Unmark as bot & exclude bot members from search
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/store/constants.js
  frontend/src/modules/widget/components/cube/widget-cube-renderer.vue
  frontend/src/shared/cube/cube-render.vue
Labels: Bug

#845 isTeamMember check fix for new activity automation
  backend/src/serverless/microservices/nodejs/automation/workers/__tests__/newActivityWorker.test.ts
  backend/src/serverless/microservices/nodejs/automation/workers/newActivityWorker.ts
Labels: Bug

#841 Fix type errors
  frontend/src/modules/activity/activity-type-field.js
  frontend/src/modules/activity/components/activity-list.vue
  frontend/src/modules/activity/components/type/activity-type-list-drawer.vue
  frontend/src/modules/automation/pages/automation-list-page.vue
  frontend/src/modules/conversation/components/conversation-details.vue
  frontend/src/modules/conversation/components/conversation-footer-wrapper.vue
  frontend/src/modules/conversation/components/conversation-item.vue
  frontend/src/modules/conversation/components/conversation-list.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-item.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-types.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-item.vue
  frontend/src/modules/dashboard/components/dashboard-guides.vue
  frontend/src/modules/layout/components/account-dropdown.vue
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/layout/components/workspace-dropdown.vue
  frontend/src/modules/member/components/member-identities.vue
  frontend/src/modules/member/components/member-last-activity.vue
  frontend/src/modules/member/components/view/_aside/_aside-custom-attributes-array-renderer.vue
  frontend/src/modules/member/components/view/member-view-contributions.vue
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/modules/tag/components/tag-list.vue
  frontend/src/modules/tenant/store/getters.js
  frontend/src/modules/user/permission-checker.js
  frontend/src/modules/widget/components/cube/widget-cube.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-drawer.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-result-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings-drawer.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings.vue
  frontend/src/premium/eagle-eye/pages/eagle-eye-page-wrapper.vue
  frontend/src/shared/fields/activity-channels-field.js
  frontend/src/shared/platform/platform.vue
Labels: Bug

#846 Twitter zapier connect flow
  frontend/public/images/integrations/twitter-zapier.jpg
  frontend/src/assets/scss/dialogs.scss
  frontend/src/integrations/twitter/components/twitter-connect-drawer.vue
  frontend/src/integrations/twitter/components/twitter-connect-modal.vue
  frontend/src/integrations/twitter/components/twitter-connect.vue
  frontend/src/shared/dialog/dialog.vue
Labels: Improvement

#847 Fix activity types display in dashboard
  frontend/src/modules/dashboard/components/activity/dashboard-activity-types.vue
  frontend/src/modules/dashboard/pages/dashboard-page.vue
Labels: Bug

#850 Replaced nango cli with curl call
  scripts/nango-integrations.sh
Labels: Bug

#819 [C-145] [issue-298] Change all tab title to match page titles
  frontend/src/app.vue
  frontend/src/modules/activity/activity-routes.js
  frontend/src/modules/auth/auth-routes.js
  frontend/src/modules/integration/integration-routes.js
  frontend/src/modules/member/member-routes.js
  frontend/src/modules/onboard/onboard-routes.js
  frontend/src/modules/organization/organization-routes.js
  frontend/src/modules/report/report-routes.js
  frontend/src/modules/settings/settings-routes.js
  frontend/src/modules/task/task-routes.js
  frontend/src/premium/community-help-center/community-help-center-routes.js
  frontend/src/premium/eagle-eye/eagle-eye-routes.js
Labels: Improvement, Contributor

#849 Activity types and platform lowercase for historical data
  backend/src/database/migrations/U1683792045__lowerCaseActivityTypeAndPlatform.sql
  backend/src/database/migrations/V1683792045__lowerCaseActivityTypeAndPlatform.sql
Labels: Bug

#856 Fix slack webhook overriding
  backend/src/database/repositories/settingsRepository.ts
  backend/src/services/settingsService.ts
Labels: Bug

#855 Soft-delete integrations when removing them
  backend/src/database/repositories/integrationRepository.ts
Labels: Improvement

#825 Feature/c 867 organization enrichment
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/package-lock.json
  backend/package.json
  backend/src/bin/jobs/index.ts
  backend/src/bin/jobs/organizationEnricher.ts
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/database/initializers/sample-data.json
  backend/src/database/migrations/U1682865647__enrichOrganizationCacheWithMissingFields.sql
  backend/src/database/migrations/U1682865663__enrichOrganizationWithMissingFields.sql
  backend/src/database/migrations/V1682865647__enrichOrganizationCacheWithMissingFields.sql
  backend/src/database/migrations/V1682865663__enrichOrganizationWithMissingFields.sql
  backend/src/database/models/organization.ts
  backend/src/database/models/organizationCache.ts
  backend/src/database/repositories/__tests__/organizationCacheRepository.test.ts
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/__tests__/tenantRepository.test.ts
  backend/src/database/repositories/organizationCacheRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/database/repositories/tenantRepository.ts
  backend/src/feature-flags/isFeatureEnabled.ts
  backend/src/serverless/microservices/nodejs/bulk-enrichment/bulkOrganizationEnrichmentWorker.ts
  backend/src/serverless/microservices/nodejs/messageTypes.ts
  backend/src/serverless/microservices/nodejs/workerFactory.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
  backend/src/services/premium/enrichment/types/organizationEnrichmentTypes.ts
  backend/src/types/common.ts
  backend/src/types/integrationEnums.ts
  backend/src/utils/renameKeys.ts
  frontend/src/modules/conversation/components/conversation-details.vue
Labels: Feature

#864 Organization enrichment frontend
  frontend/src/assets/scss/badge.scss
  frontend/src/modules/organization/components/form/organization-form-attributes.vue
  frontend/src/modules/organization/components/form/organization-form-item.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/organization-headline..vue
  frontend/src/modules/organization/components/view/_aside/_aside-enriched.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/modules/organization/config/organization-enrichment-attributes.js
  frontend/src/modules/organization/organization-model.js
  frontend/src/modules/organization/pages/organization-form-page.vue
  frontend/src/modules/organization/pages/organization-view-page.vue
  frontend/src/modules/settings/settings-pricing-plans.js
  frontend/src/shared/filter/helpers/build-api-payload.js
  frontend/src/shared/tags/tags.vue
Labels: Feature

#869 Fix activity type filter for empty types
  frontend/src/modules/activity/activity-type-field.js
Labels: Bug

#871 Update organizations default sorter
  frontend/src/modules/organization/store/state.js
Labels: Improvement

#873 Filter relation management & query and store sync
  frontend/src/assets/scss/form/dropdown.scss
  frontend/src/modules/activity/config/filters/activityType/config.ts
  frontend/src/modules/activity/config/filters/channel/config.ts
  frontend/src/modules/activity/config/filters/date/config.ts
  frontend/src/modules/activity/config/filters/member/config.ts
  frontend/src/modules/activity/config/filters/platform/config.ts
  frontend/src/modules/activity/config/filters/sentiment/config.ts
  frontend/src/modules/member/config/filters/activeOn/config.ts
  frontend/src/modules/member/config/filters/activityType/config.ts
  frontend/src/modules/member/config/filters/avgSentiment/config.ts
  frontend/src/modules/member/config/filters/engagementLevel/config.ts
  frontend/src/modules/member/config/filters/enrichedMember/config.ts
  frontend/src/modules/member/config/filters/identities/config.ts
  frontend/src/modules/member/config/filters/joinedDate/config.ts
  frontend/src/modules/member/config/filters/lastActivityDate/config.ts
  frontend/src/modules/member/config/filters/main.ts
  frontend/src/modules/member/config/filters/noOfActivities/config.ts
  frontend/src/modules/member/config/filters/noOfOSSContributions/config.ts
  frontend/src/modules/member/config/filters/reach/config.ts
  frontend/src/modules/member/config/filters/tags/config.ts
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/member/store/pinia/actions.ts
  frontend/src/modules/member/store/pinia/getters.ts
  frontend/src/modules/member/store/pinia/index.ts
  frontend/src/modules/member/store/pinia/state.ts
  frontend/src/modules/organization/config/filters/activeOn/config.ts
  frontend/src/modules/organization/config/filters/joinedDate/config.ts
  frontend/src/modules/organization/config/filters/lastActivityDate/config.ts
  frontend/src/modules/organization/config/filters/noOfActivities/config.ts
  frontend/src/modules/organization/config/filters/noOfMembers/config.ts
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/shared/modules/filters/components/Filter.vue
  frontend/src/shared/modules/filters/components/FilterDropdown.vue
  frontend/src/shared/modules/filters/components/FilterItem.vue
  frontend/src/shared/modules/filters/components/FilterSearch.vue
  frontend/src/shared/modules/filters/components/filterTypes/BooleanFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/DateFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/MultiSelectFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/NumberFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/SelectFilter.vue
  frontend/src/shared/modules/filters/config/queryUrlParser/boolean.parser.ts
  frontend/src/shared/modules/filters/config/queryUrlParser/date.parser.ts
  frontend/src/shared/modules/filters/config/queryUrlParser/multiselect.parser.ts
  frontend/src/shared/modules/filters/config/queryUrlParser/number.parser.ts
  frontend/src/shared/modules/filters/config/queryUrlParser/select.parser.ts
  frontend/src/shared/modules/filters/config/queryUrlParserByType.ts
  frontend/src/shared/modules/filters/services/filter-api.service.ts
  frontend/src/shared/modules/filters/services/filter-query.service.ts
  frontend/src/shared/modules/filters/types/FilterConfig.ts
  frontend/src/shared/modules/filters/types/FilterQuery.ts
  frontend/src/shared/modules/filters/types/filterTypes/BooleanFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/CustomFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/DateFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/MultiSelectFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/NumberFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/SearchFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/SelectFilterConfig.ts
Labels: Improvement

#879 Add slack notifier env values to env.dist.local
  backend/.env.dist.local
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
Labels: Bug

#880 Saved views
  frontend/src/modules/member/config/filters/activeOn/config.ts
  frontend/src/modules/member/config/filters/activityType/config.ts
  frontend/src/modules/member/config/filters/avgSentiment/config.ts
  frontend/src/modules/member/config/filters/engagementLevel/config.ts
  frontend/src/modules/member/config/filters/enrichedMember/config.ts
  frontend/src/modules/member/config/filters/identities/config.ts
  frontend/src/modules/member/config/filters/joinedDate/config.ts
  frontend/src/modules/member/config/filters/lastActivityDate/config.ts
  frontend/src/modules/member/config/filters/noOfActivities/config.ts
  frontend/src/modules/member/config/filters/noOfOSSContributions/config.ts
  frontend/src/modules/member/config/filters/reach/config.ts
  frontend/src/modules/member/config/filters/tags/config.ts
  frontend/src/modules/member/config/saved-views/main.ts
  frontend/src/modules/member/config/saved-views/settings/bot.ts
  frontend/src/modules/member/config/saved-views/settings/common/includeFilterRenderer.ts
  frontend/src/modules/member/config/saved-views/settings/organization.ts
  frontend/src/modules/member/config/saved-views/settings/teamMember.ts
  frontend/src/modules/member/config/saved-views/settings/types/IncludeEnum.ts
  frontend/src/modules/member/config/saved-views/views/all-members.ts
  frontend/src/modules/member/config/saved-views/views/influential.ts
  frontend/src/modules/member/config/saved-views/views/most-engaged.ts
  frontend/src/modules/member/config/saved-views/views/new-and-active.ts
  frontend/src/modules/member/config/saved-views/views/slipping-away.ts
  frontend/src/modules/member/config/saved-views/views/team-members.ts
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/shared/modules/filters/components/Filter.vue
  frontend/src/shared/modules/filters/components/FilterItem.vue
  frontend/src/shared/modules/filters/config/apiFilterRenderer/boolean.filter.renderer.ts
  frontend/src/shared/modules/filters/config/apiFilterRenderer/date.filter.renderer.ts
  frontend/src/shared/modules/filters/config/apiFilterRenderer/multiselect.filter.renderer.ts
  frontend/src/shared/modules/filters/config/apiFilterRenderer/number.filter.renderer.ts
  frontend/src/shared/modules/filters/config/apiFilterRenderer/select.filter.renderer.ts
  frontend/src/shared/modules/filters/config/apiFilterRendererByType.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/boolean.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/date.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/multiselect.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/number.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/select.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRendererByType.ts
  frontend/src/shared/modules/filters/config/queryUrlParserByType.ts
  frontend/src/shared/modules/filters/services/filter-api.service.ts
  frontend/src/shared/modules/filters/services/filter-query.service.ts
  frontend/src/shared/modules/filters/types/FilterConfig.ts
  frontend/src/shared/modules/saved-views/components/SavedViews.vue
  frontend/src/shared/modules/saved-views/types/SavedViewsConfig.ts
Labels: Feature

#882 Improvement/c 1369 organization enrichment add identities
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
  backend/src/services/premium/enrichment/types/organizationEnrichmentTypes.ts
  backend/src/types/integrationEnums.ts
Labels: Improvement

#884 Remove organization profiles and render as identities
  frontend/public/images/integrations/facebook.png
  frontend/src/assets/scss/buttons.scss
  frontend/src/integrations/facebook/config.js
  frontend/src/integrations/facebook/index.js
  frontend/src/integrations/integrations-config.js
  frontend/src/modules/organization/components/form/organization-form-identities.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/organization-identities.vue
  frontend/src/modules/organization/components/view/_aside/_aside-enriched.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/config/organization-enrichment-attributes.js
  frontend/src/shared/platform/platform.vue
Labels: Bug, Improvement

#888 Trim activity display in slack automation
  backend/src/serverless/microservices/nodejs/automation/workers/slack/newActivityBlocks.ts
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
Labels: Improvement

#892 Automations paywall
  frontend/src/modules/automation/pages/automation-list-page.vue
  frontend/src/modules/automation/store/actions.js
Labels: Bug

#894 Fix slackWebhook Typos
  backend/src/database/repositories/settingsRepository.ts
Labels: Bug

#896 Hubspot book a call
  frontend/public/images/integrations/hubspot.png
  frontend/src/integrations/hubspot/components/hubspot-book-call.vue
  frontend/src/integrations/hubspot/config.js
  frontend/src/integrations/hubspot/index.js
  frontend/src/integrations/integrations-config.js
  frontend/src/modules/integration/components/integration-connect.vue
Labels: Feature

#897 Boolean base filter
  frontend/src/modules/member/config/filters/enrichedMember/config.ts
  frontend/src/modules/member/config/filters/joinedDate/config.ts
  frontend/src/modules/member/config/filters/lastActivityDate/config.ts
  frontend/src/shared/modules/filters/components/FilterItem.vue
  frontend/src/shared/modules/filters/components/filterTypes/BooleanFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/DateFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/MultiSelectFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/NumberFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/SelectFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/StringFilter.vue
  frontend/src/shared/modules/filters/components/partials/FilterIncludeSwitch.vue
  frontend/src/shared/modules/filters/components/partials/select/FilterSelectOption.vue
  frontend/src/shared/modules/filters/config/apiFilterRenderer/boolean.filter.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/boolean.label.renderer.ts
Labels: Feature

#900 Select filter options
  frontend/src/modules/member/config/filters/activeOn/config.ts
  frontend/src/modules/member/config/filters/activityType/config.ts
  frontend/src/modules/member/config/filters/avgSentiment/config.ts
  frontend/src/modules/member/config/filters/engagementLevel/config.ts
  frontend/src/modules/member/config/filters/enrichedMember/config.ts
  frontend/src/modules/member/config/filters/identities/config.ts
  frontend/src/modules/member/config/filters/joinedDate/config.ts
  frontend/src/modules/member/config/filters/lastActivityDate/config.ts
  frontend/src/modules/member/config/filters/noOfActivities/config.ts
  frontend/src/modules/member/config/filters/noOfOSSContributions/config.ts
  frontend/src/modules/member/config/filters/reach/config.ts
  frontend/src/modules/member/config/filters/tags/config.ts
  frontend/src/shared/modules/filters/components/FilterItem.vue
  frontend/src/shared/modules/filters/components/filterTypes/BooleanFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/MultiSelectFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/NumberFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/SelectFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/StringFilter.vue
  frontend/src/shared/modules/filters/components/partials/select/FilterSelectOption.vue
  frontend/src/shared/modules/filters/config/apiFilterRenderer/select.filter.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/select.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRendererByType.ts
  frontend/src/shared/modules/filters/services/custom-attributes.service.ts
  frontend/src/shared/modules/filters/types/filterTypes/BooleanFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/CustomFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/DateFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/MultiSelectFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/NumberFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/SelectFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/StringFilterConfig.ts
Labels: Feature

#898 Github issue closed support and improvements
  backend/src/bin/scripts/continue-run.ts
  backend/src/bin/scripts/process-integration.ts
  backend/src/serverless/integrations/services/integrationRunProcessor.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/usecases/github/graphql/issues.ts
  backend/src/serverless/integrations/webhooks/__tests__/events.ts
  backend/src/serverless/integrations/webhooks/__tests__/github.test.ts
  backend/src/services/activityService.ts
  backend/src/services/memberService.ts
  backend/src/types/mq/nodeWorkerIntegrationProcessMessage.ts
Labels: Improvement

#895 Support segments in CubeJS
  backend/src/api/cubejs/cubeJsAuth.ts
  backend/src/cubejs/cube.js
  backend/src/cubejs/schema/MemberSegments.js
  backend/src/cubejs/schema/Members.js
  backend/src/cubejs/schema/OrganizationSegments.js
  backend/src/cubejs/schema/Organizations.js
  backend/src/cubejs/schema/Segments.js
  backend/src/serverless/microservices/nodejs/analytics/workers/weeklyAnalyticsEmailsWorker.ts
  backend/src/services/cubejs/cubeJsService.ts
  frontend/src/i18n/en.js
  frontend/src/modules/widget/components/cube/_query_builder/DimensionSelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/FilterComponent.vue
Labels: Feature

#903 Segments bugfixes
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/database/utils/getUserContext.ts
  backend/src/serverless/integrations/services/integrationProcessor.ts
Labels: Bug

#904 Fix z-index for tables
  frontend/src/assets/scss/table.scss
Labels: Bug

#902 Design align filters
  frontend/src/modules/activity/config/filters/activityType/config.ts
  frontend/src/modules/activity/config/filters/channel/config.ts
  frontend/src/modules/activity/config/filters/date/config.ts
  frontend/src/modules/activity/config/filters/member/config.ts
  frontend/src/modules/activity/config/filters/platform/config.ts
  frontend/src/modules/activity/config/filters/sentiment/config.ts
  frontend/src/modules/member/config/filters/activeOn/config.ts
  frontend/src/modules/member/config/filters/activityType/config.ts
  frontend/src/modules/member/config/filters/avgSentiment/config.ts
  frontend/src/modules/member/config/filters/engagementLevel/config.ts
  frontend/src/modules/member/config/filters/enrichedMember/config.ts
  frontend/src/modules/member/config/filters/identities/config.ts
  frontend/src/modules/member/config/filters/joinedDate/config.ts
  frontend/src/modules/member/config/filters/lastActivityDate/config.ts
  frontend/src/modules/member/config/filters/noOfActivities/config.ts
  frontend/src/modules/member/config/filters/noOfOSSContributions/config.ts
  frontend/src/modules/member/config/filters/reach/config.ts
  frontend/src/modules/member/config/filters/tags/config.ts
  frontend/src/modules/organization/config/filters/activeOn/config.ts
  frontend/src/modules/organization/config/filters/joinedDate/config.ts
  frontend/src/modules/organization/config/filters/lastActivityDate/config.ts
  frontend/src/modules/organization/config/filters/noOfActivities/config.ts
  frontend/src/modules/organization/config/filters/noOfMembers/config.ts
  frontend/src/shared/modules/filters/components/Filter.vue
  frontend/src/shared/modules/filters/components/FilterDropdown.vue
  frontend/src/shared/modules/filters/components/FilterItem.vue
  frontend/src/shared/modules/filters/components/filterTypes/BooleanFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/DateFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/MultiSelectFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/NumberFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/SelectFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/StringFilter.vue
  frontend/src/shared/modules/filters/components/partials/FilterIncludeSwitch.vue
  frontend/src/shared/modules/filters/components/partials/FilterInlineSelect.vue
  frontend/src/shared/modules/filters/components/partials/string/FilterInput.vue
  frontend/src/shared/modules/filters/config/itemLabelRenderer/boolean.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/date.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/multiselect.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/number.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/select.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/string.label.renderer.ts
  frontend/src/shared/modules/filters/services/custom-attributes.service.ts
  frontend/src/shared/modules/filters/types/FilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/MultiSelectFilterConfig.ts
Labels: Improvement

#906 Member enrichment upsert by existing platform instead of GitHub
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
Labels: Bug

#834 GitHub Commit Data
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/database/repositories/conversationRepository.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/usecases/github/graphql/pullRequestCommits.ts
  frontend/src/modules/conversation/components/conversation-details-footer.vue
  frontend/src/modules/conversation/components/conversation-details.vue
  frontend/src/modules/conversation/components/conversation-footer-wrapper.vue
  frontend/src/modules/conversation/components/conversation-item-footer.vue
  frontend/src/modules/conversation/components/conversation-item.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-item.vue
  premium/community-help-center/components/conversation.vue
Labels: Feature

#909 Number base filter
  frontend/src/assets/scss/form/dropdown.scss
  frontend/src/shared/form/form-errors.vue
  frontend/src/shared/form/form-item.vue
  frontend/src/shared/modules/filters/components/Filter.vue
  frontend/src/shared/modules/filters/components/FilterDropdown.vue
  frontend/src/shared/modules/filters/components/filterTypes/NumberFilter.vue
  frontend/src/shared/modules/filters/components/partials/FilterInlineSelect.vue
  frontend/src/shared/modules/filters/components/partials/string/FilterInput.vue
  frontend/src/shared/modules/filters/config/apiFilterRenderer/number.filter.renderer.ts
  frontend/src/shared/modules/filters/config/constants/number.constants.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/number.label.renderer.ts
  frontend/src/shared/modules/filters/config/queryUrlParser/number.parser.ts
  frontend/src/shared/modules/filters/services/filter-api.service.ts
  frontend/src/shared/modules/filters/services/filter-query.service.ts
  frontend/src/shared/modules/filters/types/FilterOperator.ts
  frontend/src/shared/modules/filters/types/filterTypes/NumberFilterConfig.ts
Labels: Feature

#910 Prepare inbody rendering for segments
  frontend/src/modules/member/config/filters/main.ts
  frontend/src/modules/member/config/filters/projects/config.ts
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/shared/modules/filters/components/FilterDropdown.vue
  frontend/src/shared/modules/filters/services/filter-api.service.ts
  frontend/src/shared/modules/filters/types/FilterConfig.ts
  frontend/src/shared/modules/filters/types/FilterQuery.ts
Labels: Feature

#917 fix github webhook early return
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
Labels: Bug

#916 Date base filter
  frontend/src/assets/scss/form/date-picker.scss
  frontend/src/modules/member/config/saved-views/views/new-and-active.ts
  frontend/src/modules/member/config/saved-views/views/slipping-away.ts
  frontend/src/plugins/sanitize.js
  frontend/src/shared/modules/filters/components/filterTypes/DateFilter.vue
  frontend/src/shared/modules/filters/config/apiFilterRenderer/date.filter.renderer.ts
  frontend/src/shared/modules/filters/config/constants/date.constants.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/date.label.renderer.ts
  frontend/src/shared/modules/filters/config/queryUrlParser/date.parser.ts
  frontend/src/shared/modules/filters/services/filter-query.service.ts
  frontend/src/shared/modules/filters/types/filterTypes/DateFilterConfig.ts
Labels: Feature

#919 fix github commit data env vars
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  frontend/src/modules/conversation/components/conversation-details.vue
Labels: Bug

#914 Control integration error banner display
  frontend/src/modules/dashboard/components/dashboard-active-integrations.vue
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/modules/integration/integration-store.js
  frontend/src/utils/date.js
Labels: Improvement
