Repository CrowdDotDev/crowd.dev, pull requests merged in 2023-12, with the labels that each got.

#1915 Improve organization merge suggestions with lowercase normalizer
  services/apps/search_sync_worker/package.json
  services/apps/search_sync_worker/src/bin/set-alias-to-index.ts
  services/apps/search_sync_worker/src/service/opensearch.service.ts
  services/apps/search_sync_worker/src/types.ts
Labels: Improvement

#1918 Fix enrich error
  frontend/src/main.ts
  frontend/src/modules/auth/store/actions.js
  frontend/src/modules/auth/store/mutations.js
  frontend/src/modules/member/member-enrichment.js
  frontend/src/modules/tenant/tenant-service.js
Labels: Bug

#1919 Add index info scripts to search-sync-worker
  services/apps/search_sync_worker/package.json
  services/apps/search_sync_worker/src/bin/get-index-info.ts
  services/apps/search_sync_worker/src/bin/remove-alias.ts
  services/apps/search_sync_worker/src/service/opensearch.service.ts
Labels: Improvement

#1920 Fix tenant setting and blank screen
  backend/src/api/auth/authMe.ts
  frontend/src/modules/auth/store/actions.js
  frontend/src/modules/auth/store/mutations.js
Labels: Bug

#1904 Segment aware opensearch syncs
  services/apps/search_sync_worker/package-lock.json
  services/apps/search_sync_worker/package.json
  services/apps/search_sync_worker/src/bin/cleanup-all-activities.ts
  services/apps/search_sync_worker/src/bin/cleanup-all-members.ts
  services/apps/search_sync_worker/src/bin/cleanup-all-organizations.ts
  services/apps/search_sync_worker/src/bin/cleanup-tenant-activities.ts
  services/apps/search_sync_worker/src/bin/cleanup-tenant-members.ts
  services/apps/search_sync_worker/src/bin/cleanup-tenant-organizations.ts
  services/apps/search_sync_worker/src/bin/create-alias.ts
  services/apps/search_sync_worker/src/bin/create-versioned-index.ts
  services/apps/search_sync_worker/src/bin/delete-index.ts
  services/apps/search_sync_worker/src/bin/get-doc-count.ts
  services/apps/search_sync_worker/src/bin/get-index-info.ts
  services/apps/search_sync_worker/src/bin/reindex.ts
  services/apps/search_sync_worker/src/bin/remove-alias.ts
  services/apps/search_sync_worker/src/bin/sync-activity.ts
  services/apps/search_sync_worker/src/bin/sync-all-activities.ts
  services/apps/search_sync_worker/src/bin/sync-all-members.ts
  services/apps/search_sync_worker/src/bin/sync-all-organizations.ts
  services/apps/search_sync_worker/src/bin/sync-member.ts
  services/apps/search_sync_worker/src/bin/sync-organization.ts
  services/apps/search_sync_worker/src/bin/sync-tenant-activities.ts
  services/apps/search_sync_worker/src/bin/sync-tenant-members.ts
  services/apps/search_sync_worker/src/bin/sync-tenant-organizations.ts
  services/apps/search_sync_worker/src/bin/update-mappings.ts
  services/apps/search_sync_worker/src/main.ts
  services/apps/search_sync_worker/src/queue/index.ts
  services/apps/search_sync_worker/src/repo/activity.data.ts
  services/apps/search_sync_worker/src/repo/activity.repo.ts
  services/apps/search_sync_worker/src/repo/member.data.ts
  services/apps/search_sync_worker/src/repo/member.repo.ts
  services/apps/search_sync_worker/src/repo/organization.data.ts
  services/apps/search_sync_worker/src/repo/organization.repo.ts
  services/apps/search_sync_worker/src/repo/segment.data.ts
  services/apps/search_sync_worker/src/repo/segment.repo.ts
  services/apps/search_sync_worker/src/service/activity.sync.service.ts
  services/apps/search_sync_worker/src/service/init.service.ts
  services/apps/search_sync_worker/src/service/member.sync.data.ts
  services/apps/search_sync_worker/src/service/member.sync.service.ts
  services/apps/search_sync_worker/src/service/opensearch.data.ts
  services/apps/search_sync_worker/src/service/opensearch.service.ts
  services/apps/search_sync_worker/src/service/organization.sync.data.ts
  services/apps/search_sync_worker/src/service/organization.sync.service.ts
  services/libs/opensearch/src/repo/member.data.ts
  services/libs/opensearch/src/repo/member.repo.ts
  services/libs/opensearch/src/repo/organization.data.ts
  services/libs/opensearch/src/repo/organization.repo.ts
  services/libs/opensearch/src/service/init.service.ts
  services/libs/opensearch/src/service/member.sync.service.ts
  services/libs/opensearch/src/service/opensearch.service.ts
  services/libs/opensearch/src/service/organization.sync.service.ts
Labels: Improvement

#1927 Payload consistency between frontend and API for members.findById
  backend/src/api/member/memberFind.ts
  backend/src/database/repositories/memberRepository.ts
Labels: Bug

#1930 Fix dockerfiles build
  scripts/services/docker/Dockerfile.automations_worker
  scripts/services/docker/Dockerfile.data_sink_worker
  scripts/services/docker/Dockerfile.emails_worker
  scripts/services/docker/Dockerfile.integration_data_worker
  scripts/services/docker/Dockerfile.integration_run_worker
  scripts/services/docker/Dockerfile.integration_stream_worker
  scripts/services/docker/Dockerfile.integration_sync_worker
  scripts/services/docker/Dockerfile.search_sync_api
  scripts/services/docker/Dockerfile.search_sync_worker
  scripts/services/docker/Dockerfile.webhook_api
Labels: Bug

#1938 Lf main merge bug fixes
  backend/src/middlewares/segmentMiddleware.ts
  backend/src/serverless/utils/serviceSQS.ts
  frontend/src/modules/activity/activity-service.js
  frontend/src/modules/activity/components/activity-form-drawer.vue
  frontend/src/modules/activity/config/filters/activityType/ActivityTypeFilter.vue
  frontend/src/modules/activity/store/pinia/actions.ts
  frontend/src/modules/activity/store/type/actions.js
  frontend/src/modules/automation/components/automation-list.vue
  frontend/src/modules/lf/layout/components/lf-menu.vue
  frontend/src/modules/member/components/member-dropdown-content.vue
  frontend/src/modules/member/components/member-enrichment.vue
  frontend/src/modules/member/config/filters/activityType/ActivityTypeFilter.vue
Labels: Bug

#1945 Support incident status in public status endpoint
  frontend/src/modules/layout/components/system-status/system-status.vue
  frontend/src/modules/layout/types/SystemStatus.ts
Labels: Improvement

#1948 Fix contributors default sorter
  frontend/src/modules/member/components/list/member-list-table.vue
Labels: Bug

#1950 Essential free plan cancelation banner
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/tenant/store/getters.js
Labels: Improvement

#1939 Better organization existence checks and organizations without activities now synced to opensearch
  backend/package.json
  backend/src/bin/scripts/generate-merge-suggestions-synchronous.ts
  backend/src/bin/scripts/merge-similar-organizations.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/organizationService.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  frontend/src/modules/organization/config/saved-views/main.ts
  frontend/src/modules/organization/config/saved-views/settings/hasActivities/config.ts
  frontend/src/modules/organization/config/saved-views/views/all-organizations.ts
  services/libs/opensearch/src/repo/organization.repo.ts
Labels: Improvement

#1966 Fix member copy and banner validation
  frontend/src/modules/member/components/member-enrichment.vue
  frontend/src/modules/tenant/store/getters.js
Labels: Bug

#1969 Fix identity display name in merge dialog
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
Labels: Bug

#1972 Fix pre-selected remote filters
  frontend/src/modules/activity/config/filters/organizations/config.ts
  frontend/src/modules/member/config/filters/organizations/config.ts
  frontend/src/modules/organization/config/filters/organizations/config.ts
Labels: Bug

#1975 Fix contacts query search in organization profile
  frontend/src/modules/organization/components/view/organization-view-members.vue
Labels: Bug

#1952 Serve organization profiles from OpenSearch
  backend/src/api/organization/organizationFind.ts
  backend/src/bin/scripts/unleash-init.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/organizationService.ts
  services/libs/opensearch/src/repo/organization.repo.ts
  services/libs/types/src/enums/featureFlags.ts
Labels: Improvement

#1954 Serve contact profiles from OpenSearch
  backend/src/api/member/memberFind.ts
  backend/src/api/premium/enrichment/memberEnrich.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/memberService.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  services/libs/opensearch/src/models/members.ts
  services/libs/opensearch/src/repo/member.data.ts
  services/libs/opensearch/src/repo/member.repo.ts
  services/libs/opensearch/src/service/init.service.ts
  services/libs/opensearch/src/service/member.sync.service.ts
Labels: Improvement

#1977 Fix contacts query search in organization profile (#1975)
  frontend/src/modules/organization/components/view/organization-view-members.vue
Labels: Bug

#1976 Fix activities display in activities list
  frontend/src/modules/activity/components/activity-header.vue
  frontend/src/modules/lf/utils/filters.ts
Labels: Bug

#1986 Update email domains blacklist
  services/libs/common/src/emailDomainValidator.ts
Labels: Improvement

#1987 Fix organization OpenSearch translator
  services/libs/opensearch/src/models/organizations.ts
  services/libs/opensearch/src/organizationTranslator.ts
  services/libs/opensearch/src/repo/organization.data.ts
  services/libs/opensearch/src/repo/organization.repo.ts
  services/libs/opensearch/src/service/init.service.ts
  services/libs/opensearch/src/service/organization.sync.service.ts
Labels: Bug

#1941 Enrichment sneak peak
  frontend/public/icons/crowd-icons.svg
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/view/_aside/_aside-custom-attributes.vue
  frontend/src/modules/member/components/view/_aside/_aside-enriched.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/components/view/member-view-contributions-cta.vue
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/view/_aside/_aside-enriched.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/modules/organization/config/enrichment/employeeGrowthRate.ts
  frontend/src/modules/organization/config/enrichment/founded.ts
  frontend/src/modules/organization/config/enrichment/headcount.ts
  frontend/src/modules/organization/config/enrichment/index.ts
  frontend/src/modules/organization/config/enrichment/industry.ts
  frontend/src/modules/organization/config/enrichment/revenueRange.ts
  frontend/src/modules/organization/config/enrichment/tags.ts
  frontend/src/shared/modules/enrichment/components/enrichment-sneak-peak-content.vue
  frontend/src/shared/modules/enrichment/components/enrichment-sneak-peak.vue
  frontend/src/shared/modules/enrichment/constants/sneak-peak-popover.ts
  frontend/src/shared/modules/enrichment/types/SneakPeakPopover.ts
  scripts/cli
Labels: Improvement

#1970 Add async feedback to organizations merge
  backend/src/serverless/microservices/nodejs/org-merge/orgMergeWorker.ts
  backend/src/services/organizationService.ts
  frontend/src/modules/auth/auth-socket.js
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/components/organization-merge-dialog.vue
  frontend/src/modules/organization/components/organization-selection-dropdown.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
  frontend/src/modules/organization/store/pinia/actions.ts
  frontend/src/modules/organization/store/pinia/state.ts
Labels: Improvement

#1989 Fix display of attributes in contacts
  frontend/src/modules/member/components/view/_aside/_aside-custom-attributes.vue
Labels: Bug

#1988 Fix incorrect activities count when filtering
  backend/src/database/repositories/activityRepository.ts
Labels: Bug

#1993 Fix null attribute
  frontend/src/shared/modules/filters/services/custom-attributes.service.ts
Labels: Bug

#1992 Fix reach display
  frontend/src/modules/member/components/member-reach.vue
Labels: Bug

#1982 Add sub-projects filter to activities timeline in profiles
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/organization/components/view/organization-view-members.vue
Labels: Feature

#1995 Index member `reach` as object in OpenSearch
  services/libs/opensearch/src/memberTranslator.ts
  services/libs/opensearch/src/models/members.ts
  services/libs/opensearch/src/repo/member.data.ts
  services/libs/opensearch/src/repo/member.repo.ts
  services/libs/opensearch/src/service/init.service.ts
  services/libs/opensearch/src/service/member.sync.service.ts
  services/libs/types/src/opensearch.ts
Labels: Improvement

#1973 Pricing changes
  backend/config/custom-environment-variables.json
  backend/src/api/auth/authSignUp.ts
  backend/src/api/auth/authSocial.ts
  backend/src/api/tenant/index.ts
  backend/src/api/tenant/tenantPaymentConfirmation.ts
  backend/src/bin/jobs/downgradeExpiredPlans.ts
  backend/src/bin/jobs/index.ts
  backend/src/conf/configTypes.ts
  backend/src/database/migrations/U1702549602__optionalPlan.sql
  backend/src/database/migrations/V1702549602__optionalPlan.sql
  backend/src/database/models/tenant.ts
  backend/src/database/repositories/tenantRepository.ts
  backend/src/serverless/integrations/workers/stripeWebhookWorker.ts
  backend/src/services/auth/authService.ts
  backend/src/services/stripeService.ts
  backend/src/services/tenantService.ts
  frontend/scripts/docker-entrypoint.sh
  frontend/src/config.js
  frontend/src/middleware/auth/auth-guard.js
  frontend/src/modules/auth/auth-service.js
  frontend/src/modules/auth/store/actions.js
  frontend/src/modules/auth/store/mutations.js
  frontend/src/modules/layout/components/menu/menu-workspace.vue
  frontend/src/modules/layout/components/menu/workspace/menu-workspace-card.vue
  frontend/src/modules/layout/components/menu/workspace/menu-workspace-popover.vue
  frontend/src/modules/onboard/onboard-routes.js
  frontend/src/modules/onboard/pages/onboard-page.vue
  frontend/src/modules/onboard/pages/onboard-payment-success.vue
  frontend/src/modules/onboard/pages/onboard-plans-page.vue
  frontend/src/modules/settings/components/plans-list.vue
  frontend/src/modules/settings/pages/plans-page.vue
  frontend/src/modules/settings/settings-pricing-plans.js
  frontend/src/modules/tenant/components/tenant-new-form.vue
  frontend/src/security/plans.js
  frontend/src/shared/dialog/dialog.vue
  frontend/src/utils/date.js
Labels: Improvement
