Repository CrowdDotDev/crowd.dev, pull requests merged in 2023-02, with the labels that each got.

#477 Bulk enrichment error messages
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  frontend/src/modules/auth/auth-socket.js
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/member-enrichment.js
Labels: Bug

#465 Hide bot activity
  backend/src/database/attributes/member/default.ts
  backend/src/database/attributes/member/enums.ts
  backend/src/database/initializers/entities/2023-01-23-add-isBot-to-member-attributes.ts
  backend/src/services/__tests__/tenantService.test.ts
  frontend/src/assets/scss/badge.scss
  frontend/src/modules/activity/activity-service.js
  frontend/src/modules/member/components/member-badge.vue
  frontend/src/modules/member/components/member-dropdown.vue
Labels: Improvement

#461 Report detailed drawers
  backend/src/api/member/memberActiveList.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/types/memberTypes.ts
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/store/actions.js
  frontend/src/modules/report/pages/templates/report-member-template.vue
  frontend/src/modules/report/templates/template-report-charts.js
  frontend/src/modules/report/tooltip.js
  frontend/src/modules/widget/components/v2/shared/widget-area.vue
  frontend/src/modules/widget/components/v2/shared/widget-drawer.vue
  frontend/src/modules/widget/components/v2/shared/widget-empty.vue
  frontend/src/modules/widget/components/v2/shared/widget-members-table.vue
  frontend/src/modules/widget/components/v2/widget-active-leaderboard-members.vue
  frontend/src/modules/widget/components/v2/widget-active-members-area.vue
  frontend/src/modules/widget/components/v2/widget-active-members.vue
  frontend/src/modules/widget/components/v2/widget-total-members.vue
  frontend/src/modules/widget/widget-constants.js
  frontend/src/modules/widget/widget-queries.js
  frontend/src/shared/drawer/drawer.vue
  frontend/src/shared/filter/components/filter-list-item.vue
  frontend/src/utils/date.js
  frontend/src/utils/string.js
Labels: Feature

#479 Weekly emails receipt history
  backend/package.json
  backend/src/bin/jobs/weeklyAnalyticsEmailsCoordinator.ts
  backend/src/bin/scripts/send-weekly-analytics-email.ts
  backend/src/cubejs/metrics/activeMembers.ts
  backend/src/cubejs/metrics/activeOrganizations.ts
  backend/src/cubejs/metrics/newActivities.ts
  backend/src/cubejs/metrics/newConversations.ts
  backend/src/cubejs/metrics/newMembers.ts
  backend/src/cubejs/metrics/newOrganizations.ts
  backend/src/database/migrations/U1675166504__weeklyAnalyticsEmailsHistory.sql
  backend/src/database/migrations/V1675166504__weeklyAnalyticsEmailsHistory.sql
  backend/src/database/repositories/__tests__/memberEnrichmentCacheRepository.test.ts
  backend/src/database/repositories/__tests__/weeklyAnalyticsEmailsHistoryRepository.test.ts
  backend/src/database/repositories/weeklyAnalyticsEmailsHistoryRepository.ts
  backend/src/serverless/microservices/nodejs/analytics/workers/weeklyAnalyticsEmailsWorker.ts
  backend/src/types/weeklyAnalyticsEmailsHistoryTypes.ts
Labels: Bug

#480 Bugfix/typescript errors
  .github/workflows/CI-node.yaml
  backend/src/api/index.ts
  backend/src/api/report/reportDestroy.ts
  backend/src/api/widget/widgetDestroy.ts
  backend/src/serverless/integrations/types/iteratorTypes.ts
  backend/src/serverless/integrations/usecases/chat/getChannels.ts
  backend/src/serverless/integrations/usecases/chat/getThreads.ts
Labels: Improvement

#481 Sample data now has LinkedIn
  backend/src/database/initializers/sample-data.json
Labels: Improvement

#484 Share button visible on custom reports page
  frontend/src/modules/report/components/report-dropdown.vue
  frontend/src/modules/report/components/report-share-button.vue
  frontend/src/modules/report/pages/report-form-page.vue
  frontend/src/modules/report/pages/report-view-page.vue
Labels: Improvement

#488 Fix global attributes not showing in Edit attributes drawer
  frontend/src/modules/member/components/form/member-form-attributes.vue
Labels: Bug

#491 Fix reach filter
  frontend/src/shared/filter/components/filter-list-item.vue
Labels: Bug

#497 Fix sample data permissions
  backend/src/api/tenant/tenantDeleteSampleData.ts
  backend/src/api/tenant/tenantGenerateSampleData.ts
  frontend/src/modules/layout/components/layout.vue
Labels: Bug

#496 Eagle eye onboarding
  frontend/public/images/eagle-eye/banner.png
  frontend/public/images/eagle-eye/onboard-discover.png
  frontend/public/images/eagle-eye/onboard-engage.png
  frontend/public/images/eagle-eye/onboard-grow.png
  frontend/public/images/integrations/kaggle.png
  frontend/public/images/integrations/producthunt.png
  frontend/src/assets/scss/buttons.scss
  frontend/src/modules/layout/layout-page-content.js
  frontend/src/modules/layout/pages/paywall-page.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-banner.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-footer.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-intro.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-keywords.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-platforms.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-summary.vue
  frontend/src/premium/eagle-eye/eagle-eye-constants.js
  frontend/src/premium/eagle-eye/eagle-eye-routes.js
  frontend/src/premium/eagle-eye/eagle-eye-service.js
  frontend/src/premium/eagle-eye/pages/eagle-eye-onboard-page.vue
  frontend/src/premium/eagle-eye/store/actions.js
  frontend/src/premium/eagle-eye/store/mutations.js
  frontend/src/premium/eagle-eye/store/state.js
Labels: Feature

#514 Move organizations to essential/free tier.
  backend/src/feature-flags/ensureFlagUpdated.ts
  backend/src/serverless/integrations/workers/stripeWebhookWorker.ts
  backend/src/types/common.ts
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/dashboard/components/organization/dashboard-organization-item.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/organization/organization-routes.js
Labels: Feature

#508 add demo link to Readme
  README.md
Labels: Improvement

#516 Removed left server activity type for filters
  backend/src/types/prettyActivityTypes.ts
  frontend/src/i18n/en.js
  frontend/src/jsons/activity-types.json
Labels: Bug

#507 First version of eagle eye feed
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/scss/layout.scss
  frontend/src/jsons/eagle-eye-sources.json
  frontend/src/main.js
  frontend/src/modules/conversation/components/conversation-reply.vue
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/task/components/task-item.vue
  frontend/src/modules/tenant/store/getters.js
  frontend/src/premium/eagle-eye/components/eagle-eye-counter.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-filter.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-list-item.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-list.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-search.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-sorter.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-tabs.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-list.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-loading-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-loading-state.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-result-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-tabs.vue
  frontend/src/premium/eagle-eye/eagle-eye-service.js
  frontend/src/premium/eagle-eye/eagle-eye-storage.js
  frontend/src/premium/eagle-eye/pages/eagle-eye-page.vue
  frontend/src/premium/eagle-eye/store/actions.js
  frontend/src/premium/eagle-eye/store/getters.js
  frontend/src/premium/eagle-eye/store/mutations.js
  frontend/src/premium/eagle-eye/store/state.js
  frontend/src/shared/form/inline-select-input.vue
  frontend/src/shared/image/image.vue
  frontend/src/shared/shared-module.js
  frontend/tailwind.config.js
Labels: Feature

#517 Eagle eye feed settings drawer
  frontend/src/assets/scss/form/form.scss
  frontend/src/assets/scss/form/radio.scss
  frontend/src/premium/eagle-eye/components/list/eagle-eye-result-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings-drawer.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-platforms.vue
  frontend/src/premium/eagle-eye/constants/eagle-eye-date-published.json
  frontend/src/premium/eagle-eye/constants/eagle-eye-platforms.json
  frontend/src/premium/eagle-eye/eagle-eye-constants.js
  frontend/src/premium/eagle-eye/pages/eagle-eye-onboard-page.vue
  frontend/src/premium/eagle-eye/pages/eagle-eye-page.vue
  frontend/src/premium/eagle-eye/store/actions.js
Labels: Feature

#523 Organizations in essential plan
  backend/src/security/permissions.ts
Labels: Bug

#524 Make eagle eye form components reusable
  frontend/src/premium/eagle-eye/components/eagle-eye-platforms.vue
  frontend/src/premium/eagle-eye/components/eagle-eye-published-date.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings-drawer.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-intro-step.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-keywords-step.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-platforms-step.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-platforms.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-summary-step.vue
  frontend/src/premium/eagle-eye/eagle-eye-storage.js
  frontend/src/premium/eagle-eye/pages/eagle-eye-onboard-page.vue
  frontend/src/premium/eagle-eye/pages/eagle-eye-page.vue
  frontend/src/premium/eagle-eye/store/actions.js
  frontend/src/premium/eagle-eye/store/getters.js
  frontend/src/premium/eagle-eye/store/mutations.js
  frontend/src/premium/eagle-eye/store/state.js
Labels: Improvement

#526 Fix settings update action
  frontend/src/premium/eagle-eye/store/actions.js
Labels: Bug

#527 Fixed discord message activity URL building.
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
Labels: Bug

#533 Fix Export to CSV functionality
  backend/src/serverless/utils/nodeWorkerSQS.ts
  frontend/src/modules/member/store/actions.js
Labels: Bug

#532 Preventing rapid fire of the same messages over discord websockets
  backend/src/bin/discord-ws.ts
Labels: Bug

#536 Eagle eye drawers fixes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/scss/form/select.scss
  frontend/src/premium/eagle-eye/components/eagle-eye-platforms-drawers.vue
  frontend/src/premium/eagle-eye/components/form/eagle-eye-settings-include.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-drawer.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings-drawer.vue
  frontend/src/premium/eagle-eye/components/onboard/eagle-eye-platforms-step.vue
  frontend/src/premium/eagle-eye/eagle-eye-routes.js
  frontend/src/premium/eagle-eye/pages/eagle-eye-onboard-page.vue
  frontend/src/shared/form/form-change.js
  frontend/src/shared/form/form-item.vue
Labels: Bug

#537 Eagle eye content wrong results with offset and limit
  backend/src/database/repositories/eagleEyeContentRepository.ts
Labels: Bug

#538 Fix discord websocket message duplication issue when server has both crowd.dev apps connected
  backend/src/bin/discord-ws.ts
Labels: Bug

#539 Fix feed settings saving issues
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-drawer.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings-drawer.vue
Labels: Bug

#540 Fix email digest disable button state
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-drawer.vue
  frontend/src/shared/form/element-change.js
Labels: Bug

#535 Fix issues raised in eagle eye feed
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-list.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-loading-state.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-result-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings.vue
  frontend/src/premium/eagle-eye/eagle-eye-service.js
  frontend/src/premium/eagle-eye/pages/eagle-eye-page.vue
  frontend/src/premium/eagle-eye/store/actions.js
  frontend/src/premium/eagle-eye/store/getters.js
  frontend/src/premium/eagle-eye/store/mutations.js
  frontend/src/premium/eagle-eye/store/state.js
Labels: Bug

#547 fixed incorrect parameters
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
Labels: Bug

#541 Added filter for team members
  frontend/src/modules/dashboard/store/actions.js
Labels: Bug

#543 Added missing identities
  frontend/src/modules/member/components/form/member-form-identities.vue
Labels: Bug

#546 Eagle eye email digest drawer on update
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-drawer.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings-drawer.vue
  frontend/src/premium/eagle-eye/pages/eagle-eye-onboard-page.vue
  frontend/src/premium/eagle-eye/store/actions.js
Labels: Bug

#545 Eagle eye email digest
  backend/config/custom-environment-variables.json
  backend/src/bin/jobs/eagleEyeEmailDigestTicks.ts
  backend/src/bin/jobs/index.ts
  backend/src/bin/scripts/send-weekly-analytics-email.ts
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/database/migrations/U1676555340__recurringEmailsHistory.sql
  backend/src/database/migrations/V1676555340__recurringEmailsHistory.sql
  backend/src/database/repositories/__tests__/recurringEmailsHistoryRepository.test.ts
  backend/src/database/repositories/recurringEmailsHistoryRepository.ts
  backend/src/database/utils/getUserContext.ts
  backend/src/security/permissions.ts
  backend/src/serverless/microservices/nodejs/analytics/workers/weeklyAnalyticsEmailsWorker.ts
  backend/src/serverless/microservices/nodejs/eagle-eye-email-digest/eagleEyeEmailDigestWorker.ts
  backend/src/serverless/microservices/nodejs/messageTypes.ts
  backend/src/serverless/microservices/nodejs/workerFactory.ts
  backend/src/services/eagleEyeSettingsService.ts
  backend/src/services/emailSender.ts
  backend/src/types/eagleEyeTypes.ts
  backend/src/types/recurringEmailsHistoryTypes.ts
  backend/src/types/weeklyAnalyticsEmailsHistoryTypes.ts
Labels: Feature

#550 Email digest local timezone
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-drawer.vue
Labels: Feature

#551 Eagle eye 24h local time
  .github/workflows/lint-frontend.yml
  frontend/src/premium/eagle-eye/components/list/eagle-eye-email-digest-drawer.vue
Labels: Bug

#548 AI replies for EagleEye
  backend/src/api/eagleEyeContent/eagleEyeContentReply.ts
  backend/src/api/eagleEyeContent/eagleEyeContentTrack.ts
  backend/src/api/eagleEyeContent/index.ts
  backend/src/i18n/en.ts
  backend/src/services/eagleEyeContentService.ts
  backend/src/services/eagleEyeSettingsService.ts
  backend/src/types/eagleEyeTypes.ts
  frontend/src/premium/eagle-eye/components/list/eagle-eye-loading-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-result-card.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings-drawer.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-settings.vue
  frontend/src/premium/eagle-eye/eagle-eye-service.js
  frontend/src/premium/eagle-eye/pages/eagle-eye-onboard-page.vue
  frontend/src/shared/dialog/dialog.vue
Labels: Feature

#552 Sendgrid webhooks for Eagle Eye digest
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/package-lock.json
  backend/package.json
  backend/src/api/eagleEyeContent/eagleEyeContentTrack.ts
  backend/src/api/index.ts
  backend/src/api/webhooks/index.ts
  backend/src/api/webhooks/sendgrid.ts
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/serverless/integrations/workers/sendgridWebhookWorker.ts
  backend/src/serverless/integrations/workers/stripeWebhookWorker.ts
  backend/src/serverless/microservices/nodejs/eagle-eye-email-digest/eagleEyeEmailDigestWorker.ts
  backend/src/serverless/microservices/nodejs/workerFactory.ts
  backend/src/services/eagleEyeContentService.ts
  backend/src/services/emailSender.ts
  backend/src/types/integrationEnums.ts
  backend/src/types/webhooks.ts
Labels: Feature

#558 Fixing guild id being passed incorrectly in some cases.
  backend/src/bin/discord-ws.ts
  backend/src/services/eagleEyeContentService.ts
  backend/src/types/integrationEnums.ts
Labels: Bug

#559 Removed trial label from organizations page
  frontend/src/modules/organization/pages/organization-list-page.vue
Labels: Bug

#561 Autocomplete organizations members edit
  frontend/src/assets/scss/form/select.scss
  frontend/src/modules/member/components/form/member-form-details.vue
  frontend/src/modules/member/member-array-attributes-field.js
  frontend/src/modules/member/member-model.js
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/organization/organization-field.js
  frontend/src/shared/form/autocomplete-many-input.vue
Labels: Improvement

#563 Community help center - send delete task even document doesn't exist
  backend/src/search-engine/repositories/indexable.ts
Labels: Bug

#564 Fixed the fuzzy match in the Hacker News integration
  backend/src/serverless/integrations/usecases/hackerNews/getPostsByKeywords.ts
Labels: Bug

#566 Slack emoji rendering
  frontend/src/assets/scss/content.scss
  frontend/src/modules/activity/components/activity-content.vue
Labels: Improvement

#571 Custom report duplicate
  backend/src/api/report/index.ts
  backend/src/api/report/reportDuplicate.ts
  backend/src/database/repositories/reportRepository.ts
  backend/src/services/reportService.ts
  frontend/src/modules/report/components/report-dropdown.vue
  frontend/src/modules/report/pages/report-form-page.vue
  frontend/src/modules/report/report-service.js
Labels: Improvement

#573 Action for merging members
  frontend/src/modules/member/components/list/member-list-toolbar.vue
Labels: Improvement

#560 C-667 - Home rebuild
  backend/src/database/repositories/taskRepository.ts
  frontend/src/integrations/integrations-config.js
  frontend/src/modules/activity/components/activity-content.vue
  frontend/src/modules/activity/components/activity-sentiment.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-count.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-list.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-sentiment.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-types.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-list.vue
  frontend/src/modules/dashboard/components/dashboard-active-integrations.vue
  frontend/src/modules/dashboard/components/dashboard-activities.vue
  frontend/src/modules/dashboard/components/dashboard-count.vue
  frontend/src/modules/dashboard/components/dashboard-empty-state.vue
  frontend/src/modules/dashboard/components/dashboard-filters.vue
  frontend/src/modules/dashboard/components/dashboard-header.vue
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/dashboard/components/dashboard-task.vue
  frontend/src/modules/dashboard/components/dashboard-widget-chart.vue
  frontend/src/modules/dashboard/components/dashboard-widget-header.vue
  frontend/src/modules/dashboard/components/member/dashboard-member-item.vue
  frontend/src/modules/dashboard/components/organization/dashboard-organization-item.vue
  frontend/src/modules/dashboard/components/shared/dashboard-badge.vue
  frontend/src/modules/dashboard/components/shared/dashboard-tab.vue
  frontend/src/modules/dashboard/components/task/dashboard-task-item.vue
  frontend/src/modules/dashboard/components/task/dashboard-task-suggested.vue
  frontend/src/modules/dashboard/dashboard.cube.js
  frontend/src/modules/dashboard/pages/dashboard-page.vue
  frontend/src/modules/dashboard/store/actions.js
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/member/components/member-display-name.vue
  frontend/src/modules/member/member-model.js
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/organization/organization-model.js
  frontend/src/modules/organization/organization-routes.js
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/modules/report/components/report-grid-layout.vue
  frontend/src/modules/report/report-charts.js
  frontend/src/modules/report/templates/template-report-charts.js
  frontend/src/modules/task/components/task-dropdown.vue
  frontend/src/modules/task/components/task-item.vue
  frontend/src/modules/widget/components/cube/widget-cube-renderer.vue
  frontend/src/modules/widget/components/v2/shared/widget-area.vue
  frontend/src/shared/store/actions.js
  frontend/tailwind.config.js
  scripts/cli
Labels: Feature

#570 Organization endpoints only returns organizations with members
  backend/src/cubejs/schema/Organizations.js
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/__tests__/organizationService.test.ts
Labels: Bug

#576 Cumulative measures all time date range
  backend/src/cubejs/cube.js
Labels: Bug

#572 Allow to hide/show attributes
  frontend/src/modules/member/components/form/member-form-attributes.vue
  frontend/src/modules/member/components/list/member-list-filter.vue
  frontend/src/modules/member/components/member-manage-attributes-drawer.vue
  frontend/src/modules/member/components/view/_aside/_aside-custom-attributes.vue
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/shared/fields/get-custom-attributes.js
Labels: Improvement

#579 Sentiment exceptions result in empty sentiment object
  backend/src/services/activityService.ts
Labels: Bug

#580 Fixed filtering members by username on any platform
  backend/src/database/repositories/filters/queryParser.ts
  backend/src/database/repositories/memberRepository.ts
Labels: Bug

#583 save twitter tokens after refresh
  backend/src/serverless/integrations/services/integrations/twitterIntegrationService.ts
Labels: Bug

#584 handle no mentions returned
  backend/src/serverless/integrations/usecases/twitter/errorHandler.ts
  backend/src/serverless/integrations/usecases/twitter/getPostsByMention.ts
Labels: Bug

#585 handle error if user has no twitter followers
  backend/src/serverless/integrations/usecases/twitter/getFollowers.ts
Labels: Bug

#581 Replace partners logos
  frontend/public/images/auth/crowdsec.png
  frontend/public/images/auth/dragonfly.png
  frontend/public/images/auth/kernai.png
  frontend/public/images/auth/meilisearch.png
  frontend/public/images/auth/openbb.png
  frontend/public/images/auth/partners.png
  frontend/public/images/auth/zenml.png
  frontend/src/modules/auth/components/layout/auth-layout-side.vue
Labels: Improvement

#587 Add limit to autocomplete member's dropdown
  frontend/src/modules/member/components/member-autocomplete-input.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-selection-dropdown.vue
  frontend/src/modules/member/member-module.js
  frontend/src/modules/tag/components/tag-autocomplete-input.vue
  frontend/src/shared/form/autocomplete-one-input.vue
  frontend/src/shared/form/platform-autocomplete-input.vue
Labels: Improvement
