Repository CrowdDotDev/crowd.dev, pull requests merged in 2023-01, with the labels that each got.

#360 Bots and team members excluded by default from cubejs
  backend/src/cubejs/cube.js
  backend/src/cubejs/schema/Activities.js
  backend/src/cubejs/schema/Members.js
  backend/src/cubejs/schema/Sentiment.js
  frontend/src/i18n/en.js
  frontend/src/modules/widget/components/cube/_query_builder/DimensionSelect.vue
Labels: Improvement

#386 Cubejs preaggregations dimension updates
  backend/src/cubejs/schema/Activities.js
  backend/src/cubejs/schema/Members.js
  backend/src/cubejs/schema/Organizations.js
  backend/src/services/__tests__/tenantService.test.ts
Labels: Improvement

#388 Edge case of merge members with similar activities resulting 500 error
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/memberService.ts
Labels: Bug

#391 Bugfix/comprehend text too big
  backend/src/services/aws.ts
Labels: Bug

#394 Engagement score was weighting too much activities at the beginning of the month
  backend/src/serverless/microservices/python/crowd-members-score/crowd/members_score/members_score.py
Labels: Bug

#392 Improved copy for widget tooltips
  frontend/src/i18n/en.js
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/dashboard/dashboard.cube.js
  frontend/src/modules/report/report-charts.js
  frontend/src/modules/widget/components/cube/widget-cube.vue
Labels: Improvement

#396 Fixed hashtags not being saved
  backend/src/api/integration/helpers/twitterAuthenticate.ts
  backend/src/services/auth/passportStrategies/redisPKCEStore.ts
  backend/src/services/integrationService.ts
Labels: Bug

#397 Don't log github webhook event type not supported as error
  backend/src/serverless/integrations/webhooks/__tests__/github.test.ts
  backend/src/serverless/integrations/webhooks/github.ts
  backend/src/serverless/integrations/workers/githubWebhookWorker.ts
  backend/src/types/integration/notSupportedError.ts
Labels: Bug

#401 Prevent duplicate automation executions
  backend/package-lock.json
  backend/package.json
  backend/src/database/migrations/U1673002934__automation-eventid-index.sql
  backend/src/database/migrations/V1673002934__automation-eventid-index.sql
  backend/src/database/repositories/automationExecutionRepository.ts
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
  backend/src/serverless/microservices/nodejs/automation/workers/__tests__/newActivityWorker.test.ts
  backend/src/serverless/microservices/nodejs/automation/workers/__tests__/newMemberWorker.test.ts
  backend/src/serverless/microservices/nodejs/automation/workers/newActivityWorker.ts
  backend/src/serverless/microservices/nodejs/automation/workers/newMemberWorker.ts
  backend/src/serverless/microservices/nodejs/package-lock.json
  backend/src/serverless/microservices/nodejs/package.json
  backend/src/serverless/microservices/nodejs/tsconfig.json
Labels: Improvement

#402 Fix merging members twice
  frontend/src/modules/member/components/member-dropdown.vue
Labels: Bug

#383 EagleEye exact keyword matching
  backend/src/database/migrations/U1672933725__eagleEyeContentsAddExactMatchKeyword.sql
  backend/src/database/migrations/V1672933725__eagleEyeContentsAddExactMatchKeyword.sql
  backend/src/database/models/eagleEyeContent.ts
  backend/src/database/repositories/eagleEyeContentRepository.ts
  backend/src/database/repositories/filters/queryParser.ts
  backend/src/i18n/en.ts
  backend/src/services/eagleEyeContentService.ts
  frontend/src/premium/eagle-eye/components/eagle-eye-search.vue
  frontend/src/premium/eagle-eye/eagle-eye-service.js
  frontend/src/shared/filter/helpers/build-api-payload.js
  frontend/src/shared/form/keywords-input.vue
  premium/eagle-eye/crowd-eagle-eye/crowd/eagle_eye/search.py
Labels: Improvement

#407 Wrong hash generated for star activities
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/microservices/nodejs/automation/workers/newActivityWorker.ts
Labels: Bug

#410 Truncate tenant name in workspace-dropdown
  frontend/src/modules/layout/components/workspace-dropdown.vue
  frontend/tailwind.config.js
Labels: Bug

#411 Add formbricks feedback
  frontend/src/config.js
  frontend/src/i18n/en.js
  frontend/src/modules/layout/components/menu.vue
Labels: Feature

#415 Fix the user invite dialog disappearing after invite
  frontend/src/premium/user/pages/user-new-page.vue
Labels: Bug

#412 Always trigger onboarding when connecting twitter.
  backend/src/services/integrationService.ts
Labels: Bug

#421 Filter members by activity type
  backend/src/database/migrations/U1673347364__activityTypesForMembers.sql
  backend/src/database/migrations/V1673347364__activityTypesForMembers.sql
  backend/src/database/repositories/__tests__/conversationRepository.test.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/integrationService.ts
  frontend/src/i18n/en.js
  frontend/src/modules/activity/activity-type-field.js
  frontend/src/modules/member/member-model.js
  frontend/src/premium/user/pages/user-new-page.vue
  frontend/src/shared/filter/helpers/build-api-payload.js
Labels: Improvement

#409 Typo in upgrade button
  frontend/src/modules/settings/pages/plans-page.vue
Labels: Bug

#413 Enhancement/websockets
  backend/package-lock.json
  backend/package.json
  backend/src/api/auth/authMe.ts
  backend/src/api/index.ts
  backend/src/api/member/memberExport.ts
  backend/src/api/websockets/index.ts
  backend/src/api/websockets/namespace.ts
  backend/src/api/websockets/types.ts
  backend/src/bin/api.ts
  backend/src/bin/worker/integrations.ts
  backend/src/database/repositories/tenantUserRepository.ts
  backend/src/feature-flags/setTenantProperties.ts
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/services/auth/passportStrategies/redisPKCEStore.ts
  backend/src/services/auth/passportStrategies/twitterStrategy.ts
  backend/src/types/mq/apiMessageBase.ts
  backend/src/types/mq/apiWebsocketMessage.ts
  backend/src/utils/redis/index.ts
  backend/src/utils/redis/pubSub.ts
  backend/src/utils/redis/pubSubBus.ts
  backend/src/utils/redis/pubSubEmitter.ts
  backend/src/utils/redis/pubSubReceiver.ts
  backend/src/utils/redis/redisCache.ts
  frontend/.env.dist.local
  frontend/package-lock.json
  frontend/package.json
  frontend/scripts/docker-entrypoint.sh
  frontend/src/config.js
  frontend/src/modules/auth/auth-socket.js
  frontend/src/modules/auth/store/actions.js
Labels: Feature, Improvement

#398 Template based reports backend updates
  backend/src/api/report/reportCreate.ts
  backend/src/api/report/reportUpdate.ts
  backend/src/cubejs/schema/Members.js
  backend/src/database/initializers/entities/2023-01-11-add-members-reports-to-tenants.ts
  backend/src/database/migrations/U1673527315__templateReportUpdates.sql
  backend/src/database/migrations/V1673527315__templateReportUpdates.sql
  backend/src/database/models/memberActivityAggregatesMV.ts
  backend/src/database/models/report.ts
  backend/src/database/repositories/__tests__/conversationRepository.test.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/__tests__/reportRepository.test.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/reportRepository.ts
  backend/src/i18n/en.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/tenantService.ts
Labels: Feature

#418 Members reports
  backend/src/api/report/reportDestroy.ts
  backend/src/api/report/reportFind.ts
  backend/src/api/widget/widgetDestroy.ts
  backend/src/database/repositories/__tests__/conversationRepository.test.ts
  frontend/public/icons/crowd-icons.svg
  frontend/src/modules/dashboard/components/dashboard-filters.vue
  frontend/src/modules/dashboard/store/actions.js
  frontend/src/modules/dashboard/store/mutations.js
  frontend/src/modules/dashboard/store/state.js
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/report/components/report-create-dialog.vue
  frontend/src/modules/report/components/report-list-table.vue
  frontend/src/modules/report/components/report-share-button.vue
  frontend/src/modules/report/components/templates/report-template-dropdown.vue
  frontend/src/modules/report/components/templates/report-template-item.vue
  frontend/src/modules/report/pages/report-form-page.vue
  frontend/src/modules/report/pages/report-list-page.vue
  frontend/src/modules/report/pages/report-view-page-public.vue
  frontend/src/modules/report/pages/templates/report-member-template.vue
  frontend/src/modules/report/pages/templates/report-template-page.vue
  frontend/src/modules/report/report-charts.js
  frontend/src/modules/report/report-routes.js
  frontend/src/modules/report/templates/template-report-charts.js
  frontend/src/modules/report/templates/template-reports.js
  frontend/src/modules/report/tooltip.js
  frontend/src/modules/widget/components/v2/shared/widget-area.vue
  frontend/src/modules/widget/components/v2/shared/widget-empty.vue
  frontend/src/modules/widget/components/v2/shared/widget-error.vue
  frontend/src/modules/widget/components/v2/shared/widget-granularity.vue
  frontend/src/modules/widget/components/v2/shared/widget-insight.vue
  frontend/src/modules/widget/components/v2/shared/widget-kpi.vue
  frontend/src/modules/widget/components/v2/shared/widget-loading.vue
  frontend/src/modules/widget/components/v2/shared/widget-members-table.vue
  frontend/src/modules/widget/components/v2/shared/widget-period.vue
  frontend/src/modules/widget/components/v2/shared/widget-title.vue
  frontend/src/modules/widget/components/v2/widget-active-leaderboard-members.vue
  frontend/src/modules/widget/components/v2/widget-active-members-area.vue
  frontend/src/modules/widget/components/v2/widget-active-members.vue
  frontend/src/modules/widget/components/v2/widget-total-members.vue
  frontend/src/modules/widget/widget-constants.js
  frontend/src/modules/widget/widget-queries.js
  frontend/src/plugins/chartkick.js
  frontend/src/shared/svg/svg.vue
  frontend/src/utils/number.js
  frontend/src/utils/reports.js
Labels: Feature

#424 Fix home dashboard and reports
  frontend/src/modules/dashboard/components/dashboard-count.vue
  frontend/src/modules/dashboard/dashboard.cube.js
  frontend/src/modules/report/pages/report-view-page-public.vue
  frontend/src/modules/report/pages/report-view-page.vue
  frontend/src/modules/widget/components/v2/widget-active-members.vue
  frontend/src/modules/widget/components/v2/widget-total-members.vue
Labels: Bug

#426 Multi-select attribute type for members
  backend/src/api/integration/__tests__/integrationProtectedFields.test.ts
  backend/src/api/microservice/__tests__/microserviceProtectedFields.test.ts
  backend/src/database/attributes/types.ts
  backend/src/database/migrations/U1673857723__multiSelectAndEnrichment.sql
  backend/src/database/migrations/V1673857723__multiSelectAndEnrichment.sql
  backend/src/database/models/member.ts
  backend/src/database/models/memberAttributeSettings.ts
  backend/src/database/models/settings.ts
  backend/src/database/repositories/__tests__/memberAttributeSettingsRepository.test.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/memberAttributeSettingsRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/settingsRepository.ts
  backend/src/database/repositories/types/memberAttributeSettingsTypes.ts
  backend/src/services/__tests__/memberAttributeSettingsService.test.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/memberAttributeSettingsService.ts
  backend/src/services/memberService.ts
  backend/src/types/integrationEnums.ts
Labels: Feature

#428 Add title on members list view
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-organizations.vue
Labels: Bug

#430 Fix organization urls
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/utils/string.js
Labels: Bug

#419 Stripe payment integration
  backend/package-lock.json
  backend/package.json
  backend/src/api/index.ts
  backend/src/api/webhooks/index.ts
  backend/src/api/webhooks/stripe.ts
  backend/src/bin/jobs/downgradeExpiredPlans.ts
  backend/src/bin/jobs/index.ts
  backend/src/database/migrations/U1673446803__tenantStripePaymentFields.sql
  backend/src/database/migrations/V1673446803__tenantStripePaymentFields.sql
  backend/src/database/models/tenant.ts
  backend/src/feature-flags/ensureFlagUpdated.ts
  backend/src/serverless/integrations/workers/stripeWebhookWorker.ts
  backend/src/serverless/microservices/nodejs/workerFactory.ts
  backend/src/services/__tests__/tenantService.test.ts
  frontend/scripts/docker-entrypoint.sh
  frontend/src/config.js
  frontend/src/modules/auth/auth-socket.js
  frontend/src/modules/settings/pages/plans-page.vue
Labels: Feature

#432 Refactor auth/doInit
  frontend/src/app.vue
  frontend/src/modules/auth/store/actions.js
Labels: Bug

#436 Replaced isEnriched (bool) by lastEnriched (timestamp)
  backend/src/database/migrations/U1674065473__isEnrichedToLastEnriched.sql
  backend/src/database/migrations/V1674065473__isEnrichedToLastEnriched.sql
  backend/src/database/models/member.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/__tests__/memberService.test.ts
Labels: Feature

#439 Added a contributions column to members
  backend/src/database/migrations/U1674113789__contributionsToMembers.sql
  backend/src/database/migrations/V1674113789__contributionsToMembers.sql
  backend/src/database/models/member.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/__tests__/memberService.test.ts
Labels: Feature

#425 Add global filters
  backend/src/cubejs/cube.js
  frontend/src/modules/report/components/report-grid-layout.vue
  frontend/src/modules/report/components/templates/report-template-filters.vue
  frontend/src/modules/report/pages/report-view-page-public.vue
  frontend/src/modules/report/pages/report-view-page.vue
  frontend/src/modules/report/pages/templates/report-member-template.vue
  frontend/src/modules/report/pages/templates/report-template-page.vue
  frontend/src/modules/report/templates/template-reports.js
  frontend/src/modules/widget/components/cube/widget-cube-renderer.vue
  frontend/src/modules/widget/components/v2/widget-active-leaderboard-members.vue
  frontend/src/modules/widget/components/v2/widget-active-members-area.vue
  frontend/src/modules/widget/components/v2/widget-active-members.vue
  frontend/src/modules/widget/components/v2/widget-total-members.vue
  frontend/src/modules/widget/widget-queries.js
  frontend/src/shared/cube/cube-render.vue
  frontend/src/shared/filter/components/filter-list-item.vue
Labels: Feature

#427 Activity filters using member attributes
  backend/src/database/repositories/__tests__/activityRepository.test.ts
  backend/src/database/repositories/activityRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/utils/sequelizeFilterUtils.ts
  backend/src/services/activityService.ts
  frontend/src/modules/activity/activity-service.js
Labels: Improvement

#437 Refactor public page UI
  frontend/public/images/logo/crowd-white.svg
  frontend/src/modules/report/pages/report-view-page-public.vue
Labels: Improvement

#440 Make email independent from identities
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-channels.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/pages/member-form-page.vue
Labels: Improvement

#443 Show todays value graphs differently
  frontend/src/i18n/en.js
  frontend/src/modules/report/report-charts.js
  frontend/src/modules/report/templates/template-report-charts.js
  frontend/src/modules/widget/components/cube/_query_builder/FilterComponent.vue
  frontend/src/modules/widget/components/v2/shared/widget-area.vue
  frontend/src/plugins/chartkick.js
Labels: Improvement

#445 Keep getting redirected from auth/signup to augh/signin when just logged out
  frontend/src/modules/auth/store/actions.js
Labels: Bug

#451 Added images for comments and organization logos
  backend/src/serverless/integrations/services/integrations/premium/linkedinIntegrationService.ts
  backend/src/serverless/integrations/types/linkedinTypes.ts
  backend/src/serverless/integrations/usecases/linkedin/getCommentComments.ts
  backend/src/serverless/integrations/usecases/linkedin/getOrganizations.ts
  backend/src/serverless/integrations/usecases/linkedin/getPostComments.ts
Labels: Improvement

#449 Find active members endpoint
  backend/src/api/member/index.ts
  backend/src/api/member/memberActiveList.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/types/memberTypes.ts
  backend/src/i18n/en.ts
  backend/src/serverless/integrations/usecases/linkedin/getMember.ts
  backend/src/services/memberService.ts
Labels: Feature

#450 Member enrichment feature flagging
  CHANGELOG.md
  backend/config/default.json
  backend/src/api/auth/authMe.ts
  backend/src/api/member/memberExport.ts
  backend/src/api/premium/enrichment/index.ts
  backend/src/api/premium/enrichment/memberEnrich.ts
  backend/src/api/premium/enrichment/memberEnrichBulk.ts
  backend/src/feature-flags/ensureFlagUpdated.ts
  backend/src/feature-flags/setTenantProperties.ts
  backend/src/i18n/en.ts
  backend/src/serverless/microservices/nodejs/bulk-enrichment/bulkEnrichmentWorker.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  backend/src/services/premium/enrichment/types/memberEnrichmentTypes.ts
  backend/src/types/common.ts
  frontend/src/modules/member/components/member-channels.vue
Labels: Feature

#459 Member enrichment cache
  backend/src/database/migrations/U1674663701__memberEnrichmentCache.sql
  backend/src/database/migrations/V1674663701__memberEnrichmentCache.sql
  backend/src/database/repositories/__tests__/memberEnrichmentCache.test.ts
  backend/src/database/repositories/memberEnrichmentCacheRepository.ts
  backend/src/database/utils/sequelizeTestUtils.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  backend/src/services/premium/enrichment/types/memberEnrichmentTypes.ts
Labels: Feature

#466 Disable filter button in custom reports for unsupported measures
  frontend/src/modules/widget/components/cube/_query_builder/FilterComponent.vue
Labels: Bug

#457 Member enrichment actions
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  frontend/public/icons/crowd-icons.svg
  frontend/src/assets/scss/toast.scss
  frontend/src/modules/auth/auth-socket.js
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-enrichment.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/member-enrichment.js
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/store/actions.js
  frontend/src/shared/message/message.js
Labels: Feature

#453 Member enrichment form and display info
  backend/src/serverless/integrations/services/integrations/premium/linkedinIntegrationService.ts
  backend/src/serverless/integrations/types/linkedinTypes.ts
  backend/src/serverless/integrations/usecases/linkedin/getCommentComments.ts
  backend/src/serverless/integrations/usecases/linkedin/getOrganizations.ts
  backend/src/serverless/integrations/usecases/linkedin/getPostComments.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/icons/crowd-icons.svg
  frontend/src/assets/scss/form/select.scss
  frontend/src/i18n/en.js
  frontend/src/integrations/linkedin/components/activity/linkedin-activity-content.vue
  frontend/src/integrations/linkedin/components/activity/linkedin-activity-message.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/member/components/form/member-form-attributes.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/components/view/_aside/_aside-custom-attributes-array-renderer.vue
  frontend/src/modules/member/components/view/_aside/_aside-custom-attributes.vue
  frontend/src/modules/member/components/view/_aside/_aside-enriched.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/modules/settings/settings-pricing-plans.js
  frontend/src/shared/fields/array-field.js
  frontend/src/shared/fields/get-custom-attributes.js
  frontend/src/utils/date.js
Labels: Feature

#452 Member enrichment
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/src/api/auth/authMe.ts
  backend/src/api/index.ts
  backend/src/api/member/memberExport.ts
  backend/src/api/premium/enrichment/index.ts
  backend/src/api/premium/enrichment/memberEnrich.ts
  backend/src/api/premium/enrichment/memberEnrichBulk.ts
  backend/src/config/configTypes.ts
  backend/src/config/index.ts
  backend/src/database/attributes/attribute.ts
  backend/src/database/attributes/member/enums.ts
  backend/src/database/migrations/U1674663701__memberEnrichmentCache.sql
  backend/src/database/migrations/V1674663701__memberEnrichmentCache.sql
  backend/src/database/repositories/__tests__/memberEnrichmentCache.test.ts
  backend/src/database/repositories/memberEnrichmentCacheRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/types/memberAttributeSettingsTypes.ts
  backend/src/database/utils/sequelizeTestUtils.ts
  backend/src/feature-flags/ensureFlagUpdated.ts
  backend/src/feature-flags/setTenantProperties.ts
  backend/src/i18n/en.ts
  backend/src/serverless/integrations/types/messageTypes.ts
  backend/src/serverless/microservices/nodejs/bulk-enrichment/bulkEnrichmentWorker.ts
  backend/src/serverless/microservices/nodejs/messageTypes.ts
  backend/src/serverless/microservices/nodejs/workerFactory.ts
  backend/src/serverless/utils/nodeWorkerSQS.ts
  backend/src/services/memberService.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  backend/src/services/premium/enrichment/types/memberEnrichmentTypes.ts
  backend/src/types/common.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/icons/crowd-icons.svg
  frontend/src/assets/scss/form/select.scss
  frontend/src/assets/scss/toast.scss
  frontend/src/main.js
  frontend/src/modules/auth/auth-socket.js
  frontend/src/modules/member/components/form/member-form-attributes.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-enrichment.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/components/view/_aside/_aside-custom-attributes-array-renderer.vue
  frontend/src/modules/member/components/view/_aside/_aside-custom-attributes.vue
  frontend/src/modules/member/components/view/_aside/_aside-enriched.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/components/view/member-view-contributions.vue
  frontend/src/modules/member/member-enrichment.js
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/modules/member/store/actions.js
  frontend/src/modules/settings/settings-pricing-plans.js
  frontend/src/shared/fields/array-field.js
  frontend/src/shared/fields/get-custom-attributes.js
  frontend/src/shared/message/message.js
  frontend/src/utils/date.js
Labels: Feature

#476 Non existing member attributes in settings
  backend/src/api/member/memberExport.ts
  backend/src/api/premium/enrichment/memberEnrich.ts
  backend/src/api/premium/enrichment/memberEnrichBulk.ts
  backend/src/feature-flags/setTenantProperties.ts
  backend/src/serverless/microservices/nodejs/bulk-enrichment/bulkEnrichmentWorker.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/memberService.ts
  backend/src/utils/timing.ts
Labels: Bug
