Repository CrowdDotDev/crowd.dev, pull requests merged in 2023-04, with the labels that each got.

#700 Appending appHost to all dynamic template variables
  backend/src/services/emailSender.ts
Labels: Improvement

#708 Null values for raw query parser
  backend/src/database/repositories/filters/rawQueryParser.ts
Labels: Improvement

#704 Obsolete GitHub action removed
  .github/workflows/DB-sync-migrations.yaml
Labels: Improvement

#709 Support Enriched member filter
  frontend/src/modules/member/member-model.js
  frontend/src/shared/filter/components/type/filter-type-boolean.vue
  frontend/src/shared/filter/helpers/build-api-payload.js
Labels: Improvement

#716 Fix organizations form layout
  frontend/src/modules/organization/pages/organization-form-page.vue
Labels: Bug

#717 Fix csv export and automations modals copy
  frontend/src/modules/automation/automation-limit.js
  frontend/src/modules/automation/pages/automation-list-page.vue
  frontend/src/modules/member/member-export-limit.js
  frontend/src/modules/member/store/actions.js
Labels: Bug

#718 Only use posts that have publishedAt property set.
  backend/src/serverless/integrations/usecases/linkedin/getOrganizationPosts.ts
Labels: Bug

#715 Merge members redesign
  backend/src/api/member/index.ts
  backend/src/api/member/memberOrganizationAutocomplete.ts
  backend/src/database/repositories/memberRepository.ts
  frontend/.eslintrc.js
  frontend/src/assets/scss/buttons.scss
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-merge-dialog.vue
  frontend/src/modules/member/components/member-selection-dropdown.vue
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/tag/components/tag-list.vue
  frontend/src/modules/widget/components/v2/member/widget-total-members.vue
  frontend/src/shared/avatar/avatar.vue
  frontend/src/shared/fields/url-field.js
  frontend/src/shared/filter/components/type/filter-type-select-filter.vue
  frontend/tailwind.config.js
Labels: Improvement

#726 Fix discord channels semantics
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
  backend/src/types/activityTypes.ts
Labels: Bug

#725 Organization table open in new tab
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/organization/components/organization-name.vue
Labels: Improvement

#730 Fix filters behaviour in reports and list pages
  frontend/src/modules/report/pages/report-view-page-public.vue
  frontend/src/modules/report/pages/templates/report-template-page.vue
  frontend/src/shared/filter/helpers/different-util.js
Labels: Bug

#731 Fix displaying of activity types
  frontend/src/modules/activity/components/activity-form-drawer.vue
  frontend/src/modules/activity/components/type/activity-type-list-drawer.vue
  frontend/src/shared/avatar/avatar.vue
Labels: Bug

#729 Fixed member joinedAt being overwritten for the Slack and Twitter integrations
  backend/src/services/__tests__/activityService.test.ts
  backend/src/services/activityService.ts
  backend/src/services/memberService.ts
Labels: Bug

#733 Issue when deleting sample data on onboarding integration
  backend/src/api/eagleEyeContent/eagleEyeContentTrack.ts
  backend/src/api/integration/helpers/redditValidator.ts
  backend/src/api/integration/helpers/stackOverflowValidator.ts
  backend/src/api/integration/helpers/stackOverflowVolume.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/serverless/integrations/services/integrationProcessor.ts
  backend/src/services/eventTrackingService.ts
  backend/src/services/memberService.ts
  backend/src/services/sampleDataService.ts
  backend/src/services/tenantService.ts
Labels: Bug

#739 Feature/zapier frontend
  frontend/src/assets/scss/typography.scss
  frontend/src/integrations/zapier/components/zapier-connect-drawer.vue
  frontend/src/integrations/zapier/components/zapier-connect.vue
  frontend/src/integrations/zapier/config.js
  frontend/src/modules/integration/components/integration-list-item.vue
Labels: Feature

#740 change copy for zapier connect button
  frontend/src/modules/integration/components/integration-list-item.vue
Labels: Bug

#738 Fix organizations activeOn filter
  frontend/src/modules/organization/organization-platform-field.js
  frontend/src/shared/filter/components/type/filter-type-number.vue
  frontend/src/shared/filter/helpers/build-api-payload.js
Labels: Bug

#728 Auth & onboarding test improvement
  frontend/src/middleware/auth/unauth-guard.js
  frontend/src/modules/auth/pages/signin-page.vue
  frontend/src/modules/auth/pages/signup-page.vue
  frontend/tests/e2e/auth.spec.js
  frontend/tests/e2e/auth/forgot-password.js
  frontend/tests/e2e/auth/google-signup.js
  frontend/tests/e2e/auth/logout.js
  frontend/tests/e2e/auth/onboarding.js
  frontend/tests/e2e/auth/password-reset.js
  frontend/tests/e2e/auth/signin.js
  frontend/tests/e2e/auth/signup-existing.js
  frontend/tests/e2e/auth/signup.js
  frontend/tests/e2e/auth/verifyEmail.js
  frontend/tests/support/commands.js
Labels: Improvement

#742 Max warnings eslint
  frontend/package.json
Labels: Improvement

#749 Fix/zapier UI tweaks
  frontend/src/integrations/zapier/components/zapier-connect-drawer.vue
  frontend/src/integrations/zapier/config.js
Labels: Improvement

#727 Add channel filter
  frontend/src/modules/activity/activity-model.js
  frontend/src/modules/activity/activity-type-field.js
  frontend/src/modules/conversation/conversation-model.js
  frontend/src/shared/fields/activity-channels-field.js
  frontend/src/shared/filter/components/type/filter-type-select-group.vue
  frontend/src/shared/filter/helpers/build-api-payload.js
  frontend/src/utils/string.js
Labels: Improvement

#744 Toast message for 500 errors
  frontend/src/modules/layout/layout-routes.js
  frontend/src/shared/error/errors.js
Labels: Bug

#754 Merging duplicated members scripts
  backend/src/bin/scripts/merge-duplicated-members.ts
  backend/src/bin/scripts/merge-members.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/serverless/integrations/services/integrations/redditIntegrationService.ts
  backend/src/services/memberService.ts
Labels: Feature

#756 Migrate to new formbricks
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/scripts/docker-entrypoint.sh
  frontend/src/config.js
  frontend/src/main.js
  frontend/src/modules/auth/store/mutations.js
  frontend/src/modules/dashboard/components/dashboard-guides.vue
  frontend/src/modules/layout/components/account-dropdown.vue
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/tenant/store/actions.js
  frontend/src/modules/tenant/store/getters.js
  frontend/src/modules/tenant/store/mutations.js
  frontend/src/modules/tenant/store/state.js
  frontend/src/plugins/formbricks.js
Labels: Bug

#737 Redundant type sanitization on creating activity types
  backend/src/services/settingsService.ts
Labels: Improvement

#769 Fix displaying of activity types
  frontend/package-lock.json
  frontend/package.json
  frontend/src/i18n/en.js
  frontend/src/modules/dashboard/components/activity/dashboard-activity-types.vue
  frontend/src/modules/layout/components/menu.vue
  frontend/src/modules/member/member-model.js
  frontend/src/shared/filter/components/type/filter-type-select-group.vue
Labels: Bug

#777 Fix copy and colors for open source filter
  frontend/src/assets/scss/table.scss
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/view/member-view-contributions.vue
Labels: Bug

#759 Pull request conversation UI
  backend/src/database/repositories/__tests__/conversationRepository.test.ts
  backend/src/database/repositories/conversationRepository.ts
  backend/src/types/activityTypes.ts
  frontend/public/index.html
  frontend/src/i18n/en.js
  frontend/src/jsons/activity-types.json
  frontend/src/main.js
  frontend/src/modules/activity/activity-service.js
  frontend/src/modules/activity/components/activity-content.vue
  frontend/src/modules/activity/components/activity-icon.vue
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/conversation/components/conversation-details-footer.vue
  frontend/src/modules/conversation/components/conversation-details.vue
  frontend/src/modules/conversation/components/conversation-drawer.vue
  frontend/src/modules/conversation/components/conversation-footer-wrapper.vue
  frontend/src/modules/conversation/components/conversation-footer.vue
  frontend/src/modules/conversation/components/conversation-item.vue
  frontend/src/modules/conversation/components/conversation-reply.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-item.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-item.vue
  frontend/src/shared/avatar/avatar.vue
Labels: Feature

#783 Enhancement/merge duplicated members with extra identities c 1216
  backend/src/bin/scripts/merge-duplicated-members.ts
  backend/src/database/migrations/U1681893786__member-extra-identities.sql
  backend/src/database/migrations/V1681893786__member-extra-identities.sql
  backend/src/database/repositories/memberRepository.ts
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
Labels: Bug

#735 Feature/member identities c 1026
  backend/package-lock.json
  backend/src/api/apiResponseHandler.ts
  backend/src/cubejs/package-lock.json
  backend/src/cubejs/package.json
  backend/src/cubejs/schema/Identities.js
  backend/src/cubejs/schema/MemberIdentities.js
  backend/src/cubejs/schema/Members.js
  backend/src/database/migrations/U1680601075__member-identities.sql
  backend/src/database/migrations/U1681467668__member-identities-alter-tables.sql
  backend/src/database/migrations/V1680601075__member-identities.sql
  backend/src/database/migrations/V1681467668__member-identities-alter-tables.sql
  backend/src/database/models/activity.ts
  backend/src/database/models/index.ts
  backend/src/database/models/member.ts
  backend/src/database/models/memberActivityAggregatesMV.ts
  backend/src/database/models/memberIdentity.ts
  backend/src/database/repositories/__tests__/activityRepository.test.ts
  backend/src/database/repositories/__tests__/conversationRepository.test.ts
  backend/src/database/repositories/__tests__/memberEnrichmentCacheRepository.test.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/__tests__/taskRepository.test.ts
  backend/src/database/repositories/activityRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/database/repositories/tenantRepository.ts
  backend/src/database/repositories/types/memberTypes.ts
  backend/src/serverless/dbOperations/__tests__/operationsWorker.test.ts
  backend/src/serverless/integrations/services/integrations/devtoIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/hackerNewsIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/premium/linkedinIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/redditIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/slackIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/stackOverflowIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/twitterIntegrationService.ts
  backend/src/serverless/integrations/types/messageTypes.ts
  backend/src/serverless/integrations/webhooks/__tests__/github.test.ts
  backend/src/services/__tests__/activityService.test.ts
  backend/src/services/__tests__/conversationService.test.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/__tests__/tenantService.test.ts
  backend/src/services/activityService.ts
  backend/src/services/conversationService.ts
  backend/src/services/memberService.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  backend/src/utils/timing.ts
  backend/src/utils/uuid.ts
Labels: Improvement

#793 Bugfix/member upsert doesn't always work when called from integrations
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/__tests__/taskRepository.test.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/types/memberTypes.ts
  backend/src/serverless/integrations/services/integrations/discordIntegrationService.ts
  backend/src/serverless/integrations/services/integrations/twitterIntegrationService.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/activityService.ts
  backend/src/services/memberService.ts
Labels: Bug

#798 Added migration for missing indexes
  backend/src/database/migrations/U1682249232__missing-indexes.sql
  backend/src/database/migrations/V1682249232__missing-indexes.sql
Labels: Bug

#796 Github forks stream re-enabled
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
Labels: Bug

#792 fix: `# of Activities` of active members change based on the time frame
  frontend/src/modules/dashboard/store/actions.js
Labels: Bug, Contributor

#789 Add number of activities column to all member views
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/store/state.js
Labels: Improvement, Contributor

#781 Fix count values on platform selection on the home page
  frontend/src/modules/dashboard/components/dashboard-widget-header.vue
  frontend/src/modules/dashboard/store/actions.js
Labels: Bug, Contributor

#776 Members report drawers timeframe
  frontend/src/modules/widget/components/v2/member/widget-active-members-area.vue
  frontend/src/modules/widget/components/v2/product-community-fit/widget-monthly-active-contributors.vue
Labels: Bug

#801 Update formbricks version
  frontend/package-lock.json
  frontend/package.json
Labels: Bug

#803 optimized members materialized view
  backend/src/database/migrations/U1682340963__optimized-members-mv.sql
  backend/src/database/migrations/V1682340963__optimized-members-mv.sql
Labels: Bug

#797 Brought merge suggestions to Node.js
  backend/src/bin/jobs/index.ts
  backend/src/bin/jobs/mergeSuggestions.ts
  backend/src/database/initializers/entities/2022-04-05-add-microservices.ts
  backend/src/database/initializers/seed-test-data.ts
  backend/src/database/migrations/U1682098472__fuzzy-postgres.sql
  backend/src/database/migrations/U1682100889__members-to-merge-similarity.sql
  backend/src/database/migrations/V1682098472__fuzzy-postgres.sql
  backend/src/database/migrations/V1682100889__members-to-merge-similarity.sql
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/__tests__/microserviceRepository.test.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/types/memberTypes.ts
  backend/src/database/utils/keys/microserviceTypes.ts
  backend/src/serverless/dbOperations/__tests__/operationsWorker.test.ts
  backend/src/serverless/dbOperations/operations.ts
  backend/src/serverless/dbOperations/operationsWorker.ts
  backend/src/serverless/microservices/nodejs/merge-suggestions/mergeSuggestionsWorker.ts
  backend/src/serverless/microservices/nodejs/workerFactory.ts
  backend/src/serverless/microservices/python/Dockerfile.kube
  backend/src/serverless/microservices/python/crowd-backend/crowd/backend/enums/services.py
  backend/src/serverless/microservices/python/crowd-check-merge-members/crowd/check_merge_members/__init__.py
  backend/src/serverless/microservices/python/crowd-check-merge-members/crowd/check_merge_members/merge_suggestions.py
  backend/src/serverless/microservices/python/crowd-check-merge-members/crowd/check_merge_members/merge_suggestions_simple.py
  backend/src/serverless/microservices/python/crowd-check-merge-members/crowd/check_merge_members/merge_suggestions_worker.py
  backend/src/serverless/microservices/python/crowd-check-merge-members/crowd/check_merge_members/test/test_check_merge_premium.py
  backend/src/serverless/microservices/python/crowd-check-merge-members/crowd/check_merge_members/test/test_members_list.py
  backend/src/serverless/microservices/python/crowd-check-merge-members/setup.py
  backend/src/serverless/microservices/python/python_worker.py
  backend/src/serverless/microservices/python/requirements.txt
  backend/src/serverless/microservices/python/serverless/handler_scheduled.py
  backend/src/serverless/microservices/python/serverless/requirements.txt
  backend/src/serverless/microservices/python/serverless/serverless.dev.yml
  backend/src/serverless/microservices/python/serverless/serverless.yml
  backend/src/serverless/types/workerTypes.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/__tests__/microserviceService.test.ts
  backend/src/services/__tests__/tenantService.test.ts
  backend/src/services/memberService.ts
  backend/src/services/tenantService.ts
  backend/src/services/user/__tests__/permissionChecker.test.ts
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
Labels: Feature

#787 Multiple members identities
  backend/src/database/migrations/U1682354033__multiple-usernames-per-platform.sql
  backend/src/database/migrations/V1682354033__multiple-usernames-per-platform.sql
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/types/memberTypes.ts
  backend/src/i18n/en.ts
  backend/src/serverless/dbOperations/__tests__/operationsWorker.test.ts
  backend/src/serverless/integrations/types/messageTypes.ts
  backend/src/services/__tests__/activityService.test.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/memberService.ts
  frontend/src/assets/scss/buttons.scss
  frontend/src/integrations/devto/config.js
  frontend/src/integrations/discord/config.js
  frontend/src/integrations/github/config.js
  frontend/src/integrations/hackernews/config.js
  frontend/src/integrations/linkedin/config.js
  frontend/src/integrations/reddit/config.js
  frontend/src/integrations/slack/config.js
  frontend/src/integrations/stackoverflow/config.js
  frontend/src/integrations/twitter/config.js
  frontend/src/integrations/zapier/config.js
  frontend/src/main.js
  frontend/src/modules/activity/activity-type-field.js
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-channels.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-enrichment.vue
  frontend/src/modules/member/components/member-identities.vue
  frontend/src/modules/member/components/member-manage-identities-drawer.vue
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
  frontend/src/modules/member/member-model.js
  frontend/src/modules/organization/components/view/organization-view-members.vue
  frontend/src/modules/widget/components/v2/shared/widget-members-table.vue
  frontend/src/shared/fields/json-field.js
  frontend/src/shared/platform/platform-list.vue
  frontend/src/shared/platform/platform-popover.vue
  frontend/src/shared/platform/platform-svg-icon.vue
  frontend/src/shared/platform/platform.vue
  frontend/src/utils/string.js
Labels: Feature

#808 Creating custom activities from the frontend was not working because we were missing a username field
  backend/src/services/activityService.ts
Labels: Bug

#734 GitHub pull request events
  backend/src/database/migrations/U1680699288__addObjectMemberActivities.sql
  backend/src/database/migrations/U1681815008__addObjectMemberUsernameToActivities.sql
  backend/src/database/migrations/V1680699288__addObjectMemberActivities.sql
  backend/src/database/migrations/V1681815008__addObjectMemberUsernameToActivities.sql
  backend/src/database/models/activity.ts
  backend/src/database/repositories/__tests__/activityRepository.test.ts
  backend/src/database/repositories/__tests__/conversationRepository.test.ts
  backend/src/database/repositories/__tests__/memberRepository.test.ts
  backend/src/database/repositories/activityRepository.ts
  backend/src/database/repositories/conversationRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/serverless/integrations/grid/githubGrid.ts
  backend/src/serverless/integrations/services/integrations/githubIntegrationService.ts
  backend/src/serverless/integrations/types/messageTypes.ts
  backend/src/serverless/integrations/usecases/github/graphql/pullRequestReviewThreadComments.ts
  backend/src/serverless/integrations/usecases/github/graphql/pullRequestReviewThreads.ts
  backend/src/serverless/integrations/usecases/github/graphql/pullRequests.ts
  backend/src/serverless/integrations/webhooks/__tests__/github.test.ts
  backend/src/services/__tests__/activityService.test.ts
  backend/src/services/__tests__/conversationService.test.ts
  backend/src/services/__tests__/memberService.test.ts
  backend/src/services/activityDisplayService.ts
  backend/src/services/activityService.ts
  backend/src/services/memberService.ts
  backend/src/types/activityTypes.ts
  frontend/public/index.html
  frontend/src/i18n/en.js
  frontend/src/integrations/integrations-config.js
  frontend/src/integrations/other/config.js
  frontend/src/integrations/other/index.js
  frontend/src/jsons/activity-types.json
  frontend/src/modules/activity/activity-service.js
  frontend/src/modules/activity/activity-type-field.js
  frontend/src/modules/activity/components/activity-content.vue
  frontend/src/modules/activity/components/activity-icon.vue
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/automation/components/webhooks/webhook-form.vue
  frontend/src/modules/conversation/components/conversation-details-footer.vue
  frontend/src/modules/conversation/components/conversation-details.vue
  frontend/src/modules/conversation/components/conversation-drawer.vue
  frontend/src/modules/conversation/components/conversation-footer-wrapper.vue
  frontend/src/modules/conversation/components/conversation-footer.vue
  frontend/src/modules/conversation/components/conversation-item.vue
  frontend/src/modules/conversation/components/conversation-reply.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-item.vue
  frontend/src/modules/dashboard/components/conversations/dashboard-conversation-item.vue
  frontend/src/shared/avatar/avatar.vue
  frontend/src/shared/filter/components/type/filter-type-select-group.vue
Labels: Improvement

#814 Removed filtering by is_latest when getting existing member
  backend/src/database/repositories/memberRepository.ts
Labels: Bug

#815 Fix new badge in dashboard for active members
  backend/src/database/repositories/memberRepository.ts
Labels: Bug

#816 Fix merge suggestions failing due to new unique index
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/types/memberTypes.ts
  backend/src/serverless/microservices/nodejs/merge-suggestions/mergeSuggestionsWorker.ts
  backend/src/services/memberService.ts
Labels: Bug

#817 Fix members list display for null emails
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
Labels: Bug

#810 Activities cumulative count with cubejs
  backend/src/cubejs/schema/Activities.js
  backend/src/cubejs/schema/Members.js
Labels: Feature
