Repository CrowdDotDev/crowd.dev, pull requests merged in 2024-03, with the labels that each got.

#2242 Organization unmerge endpoints
  backend/src/api/organization/index.ts
  backend/src/api/organization/organizationUnmerge.ts
  backend/src/api/organization/organizationUnmergePreview.ts
  backend/src/database/repositories/memberOrganizationRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/mergeActionsRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/memberOrganizationService.ts
  backend/src/services/memberService.ts
  backend/src/services/organizationService.ts
  frontend/src/modules/auth/auth-socket.js
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/organization/components/form/organization-form-identities.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/organization-actions.vue
  frontend/src/modules/organization/components/organization-dropdown-content.vue
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/organization/components/organization-manage-identities-drawer.vue
  frontend/src/modules/organization/components/organization-unmerge-dialog.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/components/view/_aside/_aside-identities.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-view-page.vue
  pnpm-lock.yaml
  services/apps/entity_merging_worker/src/activities.ts
  services/apps/entity_merging_worker/src/activities/members.ts
  services/apps/entity_merging_worker/src/activities/organizations.ts
  services/apps/entity_merging_worker/src/workflows.ts
  services/apps/entity_merging_worker/src/workflows/all.ts
  services/apps/profiles_worker/src/activities.ts
  services/apps/profiles_worker/src/activities/organization/organizationUpdate.ts
  services/apps/profiles_worker/src/types/organization.ts
  services/apps/profiles_worker/src/workflows.ts
  services/apps/profiles_worker/src/workflows/organization/organizationUpdate.ts
  services/apps/search_sync_api/src/routes/organization.ts
  services/libs/common/src/utils.ts
  services/libs/data-access-layer/src/old/apps/data_sink_worker/repo/organization.data.ts
  services/libs/data-access-layer/src/old/apps/entity_merging_worker/index.ts
  services/libs/data-access-layer/src/old/apps/entity_merging_worker/orgs.ts
  services/libs/data-access-layer/src/old/apps/profiles_worker/orgs.ts
  services/libs/opensearch/src/apiClient.ts
  services/libs/opensearch/src/repo/organization.data.ts
  services/libs/opensearch/src/repo/organization.repo.ts
  services/libs/types/src/enums/index.ts
  services/libs/types/src/enums/members.ts
  services/libs/types/src/enums/merging.ts
  services/libs/types/src/enums/temporal.ts
  services/libs/types/src/index.ts
  services/libs/types/src/members.ts
  services/libs/types/src/merging.ts
  services/libs/types/src/organizations.ts
Labels: Feature

#2247 Fix org filter
  frontend/src/modules/member/config/filters/organizations/config.ts
  frontend/src/shared/modules/filters/components/filterTypes/MultiSelectAsyncFilter.vue
  frontend/src/shared/modules/filters/types/filterTypes/MultiSelectAsyncFilterConfig.ts
Labels: Bug

#2249 Increase `startToClose` for `organizationUpdate` activity - only try linking to cache when a cache id is found
  services/apps/entity_merging_worker/src/activities/organizations.ts
  services/apps/profiles_worker/src/workflows/organization/organizationUpdate.ts
Labels: Bug

#2250 Fix blank merge dialog in organizations
  frontend/src/modules/member/components/member-merge-dialog.vue
  frontend/src/modules/organization/components/organization-merge-dialog.vue
Labels: Bug

#2248 LF Organization unmerge endpoints
  backend/src/api/organization/index.ts
  backend/src/api/organization/organizationUnmerge.ts
  backend/src/api/organization/organizationUnmergePreview.ts
  backend/src/database/repositories/memberOrganizationRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/mergeActionsRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/memberOrganizationService.ts
  backend/src/services/memberService.ts
  backend/src/services/organizationService.ts
  frontend/src/modules/auth/auth-socket.js
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/organization/components/form/organization-form-identities.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/organization-actions.vue
  frontend/src/modules/organization/components/organization-dropdown-content.vue
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/organization/components/organization-manage-identities-drawer.vue
  frontend/src/modules/organization/components/organization-unmerge-dialog.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/components/view/_aside/_aside-identities.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-view-page.vue
  pnpm-lock.yaml
  services/apps/entity_merging_worker/src/activities.ts
  services/apps/entity_merging_worker/src/activities/members.ts
  services/apps/entity_merging_worker/src/activities/organizations.ts
  services/apps/entity_merging_worker/src/workflows.ts
  services/apps/entity_merging_worker/src/workflows/all.ts
  services/apps/profiles_worker/src/activities.ts
  services/apps/profiles_worker/src/activities/organization/organizationUpdate.ts
  services/apps/profiles_worker/src/types/organization.ts
  services/apps/profiles_worker/src/workflows.ts
  services/apps/profiles_worker/src/workflows/organization/organizationUpdate.ts
  services/apps/search_sync_api/src/routes/organization.ts
  services/libs/common/src/utils.ts
  services/libs/data-access-layer/src/old/apps/data_sink_worker/repo/organization.data.ts
  services/libs/data-access-layer/src/old/apps/entity_merging_worker/index.ts
  services/libs/data-access-layer/src/old/apps/entity_merging_worker/orgs.ts
  services/libs/data-access-layer/src/old/apps/profiles_worker/orgs.ts
  services/libs/opensearch/src/apiClient.ts
  services/libs/opensearch/src/repo/organization.data.ts
  services/libs/opensearch/src/repo/organization.repo.ts
  services/libs/types/src/enums/index.ts
  services/libs/types/src/enums/members.ts
  services/libs/types/src/enums/merging.ts
  services/libs/types/src/enums/temporal.ts
  services/libs/types/src/index.ts
  services/libs/types/src/members.ts
  services/libs/types/src/merging.ts
  services/libs/types/src/organizations.ts
Labels: Feature

#2273 Hubspot weak identities fix on parsing dynamic data
  services/libs/integrations/src/integrations/premium/hubspot/field-mapper/memberFieldMapper.ts
Labels: Bug

#2219 Configure envs to be optional for the self-hosted edition
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/src/api/auth/authSignUp.ts
  backend/src/api/index.ts
  backend/src/api/integration/index.ts
  backend/src/conf/configTypes.ts
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
  frontend/scripts/docker-entrypoint.sh
  frontend/src/config.js
  frontend/src/integrations/bigquery/config.js
  frontend/src/integrations/census/config.js
  frontend/src/integrations/devto/config.js
  frontend/src/integrations/discord/config.js
  frontend/src/integrations/discourse/config.js
  frontend/src/integrations/github/config.js
  frontend/src/integrations/hackernews/config.js
  frontend/src/integrations/hubspot/config.js
  frontend/src/integrations/linkedin/config.js
  frontend/src/integrations/n8n/config.js
  frontend/src/integrations/reddit/config.js
  frontend/src/integrations/salesforce/config.js
  frontend/src/integrations/segment/config.js
  frontend/src/integrations/slack/config.js
  frontend/src/integrations/snowflake/config.js
  frontend/src/integrations/stackoverflow/config.js
  frontend/src/integrations/twitter/config.js
  frontend/src/integrations/zapier/config.js
  frontend/src/modules/index.ts
  frontend/src/modules/integration/components/integration-list.vue
  frontend/src/modules/onboard/components/onboard-sync-data-step.vue
  services/libs/common/src/i18n/en.ts
Labels: Improvement

#2281 Fix discord and stackoverflow integration for self-hostable
  frontend/src/config.js
  frontend/src/integrations/stackoverflow/config.js
Labels: Bug

#2276 Scheduled affiliation checks
  backend/src/database/migrations/U1709793196__addAffiliationsLastChecked.sql
  backend/src/database/migrations/V1709793196__addAffiliationsLastChecked.sql
  pnpm-lock.yaml
  services/apps/profiles_worker/package.json
  services/apps/profiles_worker/src/activities.ts
  services/apps/profiles_worker/src/activities/common.ts
  services/apps/profiles_worker/src/schedules/triggerRecalculateAffiliationsOfNewRolesForEachTenant.ts
  services/apps/profiles_worker/src/types/member.ts
  services/apps/profiles_worker/src/workflows.ts
  services/apps/profiles_worker/src/workflows/member/recalculateAffiliationsForNewRoles.ts
  services/apps/profiles_worker/src/workflows/member/triggerRecalculateAffiliationsForEachTenant.ts
  services/libs/data-access-layer/src/old/apps/profiles_worker/index.ts
  services/libs/data-access-layer/src/old/apps/profiles_worker/types.ts
  services/libs/types/src/common.ts
Labels: Improvement

#2292 removed old unused columns from members table
  backend/src/bin/scripts/unmerge-members.ts
  backend/src/database/migrations/U1710494493__remove-old-member-columns.sql
  backend/src/database/migrations/V1710494493__remove-old-member-columns.sql
Labels: Improvement

#2289 Affiliation check using continue as new
  services/apps/profiles_worker/src/activities/common.ts
  services/apps/profiles_worker/src/types/member.ts
  services/apps/profiles_worker/src/workflows.ts
  services/apps/profiles_worker/src/workflows/member/recalculateAffiliationsForNewRoles.ts
  services/libs/data-access-layer/src/old/apps/profiles_worker/index.ts
Labels: Improvement

#2298 Return count of suggestions for members in both segments
  backend/src/database/repositories/memberRepository.ts
Labels: Bug

#2264 Audit logs dashboard
  frontend/src/modules/lf/config/audit-logs/filters/action/config.ts
  frontend/src/modules/lf/config/audit-logs/filters/action/options.ts
  frontend/src/modules/lf/config/audit-logs/filters/actionDate/config.ts
  frontend/src/modules/lf/config/audit-logs/filters/entityId/config.ts
  frontend/src/modules/lf/config/audit-logs/filters/entityType/config.ts
  frontend/src/modules/lf/config/audit-logs/filters/entityType/options.ts
  frontend/src/modules/lf/config/audit-logs/filters/main.ts
  frontend/src/modules/lf/config/audit-logs/filters/status/config.ts
  frontend/src/modules/lf/config/audit-logs/filters/status/options.ts
  frontend/src/modules/lf/config/audit-logs/filters/user/config.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/index.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/integrations-connect.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/integrations-reconnect.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/members-create.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/members-edit-identities.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/members-edit-manual-affiliation.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/members-edit-organizations.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/members-edit-profile.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/members-merge.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/organizations-create.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/organizations-edit-identities.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/organizations-edit-profile.ts
  frontend/src/modules/lf/config/audit-logs/log-rendering/organizations-merge.ts
  frontend/src/modules/lf/segments/components/logs/log.drawer.vue
  frontend/src/modules/lf/segments/components/logs/sections/log-changes.vue
  frontend/src/modules/lf/segments/components/logs/sections/log-json.vue
  frontend/src/modules/lf/segments/components/logs/sections/log-properties.vue
  frontend/src/modules/lf/segments/lf-segments-service.js
  frontend/src/modules/lf/segments/pages/lf-admin-panel-page.vue
  frontend/src/modules/lf/segments/pages/lf-audit-logs-page.vue
  frontend/src/modules/lf/segments/types/AuditLog.ts
  frontend/src/modules/organization/organization-service.js
  frontend/src/shared/modules/filters/components/Filter.vue
  frontend/src/shared/modules/filters/components/FilterDropdown.vue
  frontend/src/shared/modules/filters/components/filterTypes/MultiSelectAsyncFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/SelectAsyncFilter.vue
  frontend/src/shared/modules/filters/components/filterTypes/StringFilter.vue
  frontend/src/shared/modules/filters/components/partials/select/FilterSelectOption.vue
  frontend/src/shared/modules/filters/config/apiFilterRendererByType.ts
  frontend/src/shared/modules/filters/config/filterComponentByType.ts
  frontend/src/shared/modules/filters/config/itemLabelRenderer/selectasync.label.renderer.ts
  frontend/src/shared/modules/filters/config/itemLabelRendererByType.ts
  frontend/src/shared/modules/filters/config/queryUrlParserByType.ts
  frontend/src/shared/modules/filters/services/filter-api.service.ts
  frontend/src/shared/modules/filters/types/FilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/MultiSelectAsyncFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/SelectAsyncFilterConfig.ts
  frontend/src/shared/modules/filters/types/filterTypes/StringFilterConfig.ts
  scripts/cli
Labels: Feature

#2305 initialize `acc[platform]` as an array instead of object in member update
  backend/src/services/memberService.ts
Labels: Bug

#2309 Fix export to CSV in reports - LF
  frontend/src/modules/widget/components/member/widget-active-leaderboard-members.vue
  frontend/src/modules/widget/components/member/widget-active-members-kpi.vue
  frontend/src/modules/widget/components/member/widget-active-members.vue
  frontend/src/modules/widget/components/member/widget-total-members.vue
  frontend/src/modules/widget/components/product-community-fit/widget-monthly-active-contributors.vue
Labels: Bug

#2301 Add default configs to lists
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/config/saved-views/main.ts
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/config/saved-views/main.ts
  frontend/src/shared/modules/default-filters/components/default-filters.vue
  frontend/src/shared/modules/filters/config/defaultFilterRenderer/member.defaultFilter.renderer.ts
  frontend/src/shared/modules/filters/config/defaultFilterRenderer/organization.defaultFilter.renderer.ts
  frontend/src/shared/modules/saved-views/types/SavedViewsConfig.ts
  frontend/src/shared/pagination/pagination-sorter.vue
Labels: Bug

#2302 Add default configs to lists - LF
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/dashboard/components/dashboard-upgrade-plan-widget.vue
  frontend/src/modules/layout/config/links/contacts.ts
  frontend/src/modules/member/components/form/member-form-organizations-drawer.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-engagement-level.vue
  frontend/src/modules/member/components/member-find-github-drawer.vue
  frontend/src/modules/member/components/view/_aside/_aside-enrichment.vue
  frontend/src/modules/member/config/saved-views/main.ts
  frontend/src/modules/member/config/saved-views/settings/bot/MemberBotSetting.vue
  frontend/src/modules/member/config/saved-views/settings/teamMember/MemberTeamMemberSetting.vue
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/config/saved-views/main.ts
  frontend/src/shared/modules/default-filters/components/default-filters.vue
  frontend/src/shared/modules/filters/config/defaultFilterRenderer/member.defaultFilter.renderer.ts
  frontend/src/shared/modules/filters/config/defaultFilterRenderer/organization.defaultFilter.renderer.ts
  frontend/src/shared/modules/saved-views/types/SavedViewsConfig.ts
  frontend/src/shared/pagination/pagination-sorter.vue
Labels: Bug

#2318 Merge suggestions with new identities
  services/apps/merge_suggestions_worker/src/activities/member-merge-suggestions/getMergeSuggestions.ts
  services/apps/merge_suggestions_worker/src/types.ts
  services/apps/merge_suggestions_worker/src/utils.ts
Labels: Improvement

#2321 Syncing primary member to opensearch again after moving activities completes
  services/apps/entity_merging_worker/src/workflows/all.ts
Labels: Bug

#2324 Add devmode and option to switch tenants
  frontend/src/modules/auth/services/auth.service.ts
  frontend/src/modules/auth/store/auth.actions.ts
  frontend/src/modules/lf/segments/components/dev/devmode.vue
  frontend/src/modules/lf/segments/pages/lf-admin-panel-page.vue
Labels: Improvement
