Repository CrowdDotDev/crowd.dev, pull requests merged in 2024-04, with the labels that each got.

#2327 Identities verify management
  frontend/public/icons/crowd-icons.svg
  frontend/src/modules/member/components/form/member-form-emails-item.vue
  frontend/src/modules/member/components/form/member-form-emails.vue
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities-extra.vue
  frontend/src/shared/modules/identities/components/identities-vertical-list-members.vue
  frontend/src/shared/modules/identities/components/identities-vertical-list.vue
  frontend/src/shared/modules/identities/config/useMemberIdentities.ts
Labels: Improvement

#2334 Fix contributor refresh error
  frontend/src/modules/member/components/member-dropdown-content.vue
Labels: Bug

#2272 Support organizations and members cross-segments search
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/memberService.ts
  frontend/src/assets/scss/form/select.scss
  frontend/src/modules/activity/components/activity-form-drawer.vue
  frontend/src/modules/activity/config/filters/member/config.ts
  frontend/src/modules/activity/config/filters/organizations/config.ts
  frontend/src/modules/member/components/bulk/bulk-edit-attribute-popover.vue
  frontend/src/modules/member/components/form/member-form-organizations-create.vue
  frontend/src/modules/member/components/member-selection-dropdown.vue
  frontend/src/modules/member/member-field.js
  frontend/src/modules/member/member-service.js
  frontend/src/modules/organization/components/organization-selection-dropdown.vue
  frontend/src/modules/organization/config/filters/organizations/config.ts
  frontend/src/modules/organization/organization-field.js
  frontend/src/modules/organization/organization-service.js
  frontend/src/utils/segments.js
  services/libs/opensearch/src/models/members.ts
  services/libs/opensearch/src/models/organizations.ts
  services/libs/opensearch/src/repo/member.data.ts
  services/libs/opensearch/src/repo/organization.data.ts
  services/libs/opensearch/src/service/init.service.ts
  services/libs/opensearch/src/service/member.sync.service.ts
  services/libs/opensearch/src/service/organization.sync.service.ts
Labels: Improvement

#2338 Support more attributes in Organizations CSV export
  services/apps/exports_worker/src/activities/organizations.ts
Labels: Improvement

#2340 Support more attributes in Organizations CSV export
  services/apps/exports_worker/src/activities/organizations.ts
Labels: Improvement

#2322 LFID enrichment
  backend/src/bin/scripts/merge-duplicated-organizations.ts
  backend/src/bin/scripts/merge-organizations.ts
  backend/src/bin/scripts/merge-similar-organizations.ts
  backend/src/database/repositories/__tests__/noteRepository.test.ts
  backend/src/database/repositories/__tests__/organizationRepository.test.ts
  backend/src/database/repositories/__tests__/taskRepository.test.ts
  pnpm-lock.yaml
  scripts/services/docker/Dockerfile.members_enrichment_worker
  services/apps/premium/members_enrichment_worker/package.json
  services/apps/premium/members_enrichment_worker/src/activities.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/authenticateLFAuth0.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/enrichLFAuth0.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/getEnrichmentLFAuth0.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/getLFIDEnrichableMembers.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/githubIdentities.ts
  services/apps/premium/members_enrichment_worker/src/main.ts
  services/apps/premium/members_enrichment_worker/src/schedules.ts
  services/apps/premium/members_enrichment_worker/src/schedules/getMembersToEnrich.ts
  services/apps/premium/members_enrichment_worker/src/types/lfid-enrichment.ts
  services/apps/premium/members_enrichment_worker/src/workflows.ts
  services/apps/premium/members_enrichment_worker/src/workflows/lf-auth0/enrichMemberWithLFAuth0.ts
  services/apps/premium/members_enrichment_worker/src/workflows/lf-auth0/findAndSaveGithubSourceIds.ts
  services/apps/premium/members_enrichment_worker/src/workflows/lf-auth0/getEnrichmentData.ts
  services/apps/premium/members_enrichment_worker/src/workflows/lf-auth0/getMembersForLFIDEnrichment.ts
  services/libs/data-access-layer/src/old/apps/premium/members_enrichment_worker/index.ts
  services/libs/integrations/src/integrations/github/tokenRotator.ts
  services/libs/integrations/src/integrations/index.ts
  services/libs/types/src/enums/platforms.ts
Labels: Feature

#2343 Identities and emails drawers & Dropdown component
  frontend/src/modules/member/components/form/email/member-form-email-item.vue
  frontend/src/modules/member/components/form/identity/member-form-identity-item.vue
  frontend/src/modules/member/components/member-manage-emails-drawer.vue
  frontend/src/modules/member/components/member-manage-identities-drawer.vue
  frontend/src/modules/member/types/Member.ts
  frontend/src/modules/organization/components/form/email/organization-form-email-item.vue
  frontend/src/modules/organization/components/form/identity/organization-form-identity-item.vue
  frontend/src/modules/organization/components/organization-manage-emails-drawer.vue
  frontend/src/modules/organization/components/organization-manage-identities-drawer.vue
  frontend/src/modules/organization/types/Organization.ts
  frontend/src/shared/modules/identities/config/useMemberIdentities.ts
  frontend/src/ui-kit/dropdown/Dropdown.stories.ts
  frontend/src/ui-kit/dropdown/Dropdown.vue
  frontend/src/ui-kit/dropdown/DropdownItem.stories.ts
  frontend/src/ui-kit/dropdown/DropdownItem.vue
  frontend/src/ui-kit/dropdown/DropdownSeparator.vue
  frontend/src/ui-kit/dropdown/dropdown.scss
  frontend/src/ui-kit/dropdown/types/DropdownItemType.ts
  frontend/src/ui-kit/dropdown/types/DropdownPlacement.ts
  frontend/src/ui-kit/index.scss
Labels: Improvement

#2357 docs: how to create the dev app and permissions needed for integrations
  technical-docs/integrations.md
Labels: Improvement

#2348 Improve Git activities UI
  frontend/.storybook/storybook.scss
  frontend/index.html
  frontend/src/assets/scss/drawer.scss
  frontend/src/main.ts
  frontend/src/modules/activity/components/activity-dropdown.vue
  frontend/src/modules/activity/components/activity-header.vue
  frontend/src/modules/activity/components/activity-item.vue
  frontend/src/modules/activity/components/activity-link.vue
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/activity/config/display/git/config.ts
  frontend/src/modules/activity/config/display/git/git-activity-content.vue
  frontend/src/modules/activity/config/display/git/git-activity-header-content.vue
  frontend/src/modules/activity/config/display/git/git-activity-link.vue
  frontend/src/modules/activity/config/display/git/git-attributes.vue
  frontend/src/modules/activity/config/display/main.ts
  frontend/src/modules/conversation/components/conversation-attributes.vue
  frontend/src/modules/conversation/components/conversation-drawer.vue
  frontend/src/modules/conversation/components/conversation-dropdown.vue
  frontend/src/modules/conversation/components/conversation-footer-wrapper.vue
  frontend/src/modules/conversation/components/conversation-item-footer.vue
  frontend/src/modules/conversation/components/conversation-item.vue
  frontend/src/modules/conversation/config/display/git/config.ts
  frontend/src/modules/conversation/config/display/git/git-conversation-drawer-content.vue
  frontend/src/modules/conversation/config/display/git/git-conversation-drawer-header-content.vue
  frontend/src/modules/conversation/config/display/git/git-conversation-replies.vue
  frontend/src/modules/conversation/config/display/git/git-conversation-starter.vue
  frontend/src/modules/conversation/config/display/main.ts
  frontend/src/modules/conversation/types/DisplayConfig.ts
  frontend/src/modules/dashboard/components/activity/dashboard-activity-item.vue
  frontend/src/shared/drawer/drawer.vue
  frontend/src/shared/modules/activity/components/activity-display.vue
  frontend/src/shared/modules/activity/components/activity-member-organization.vue
  frontend/src/shared/modules/activity/types/Activity.ts
  frontend/src/shared/modules/activity/types/DisplayConfig.ts
  frontend/src/shared/modules/conversation/components/conversation-display.vue
  frontend/src/shared/modules/conversation/components/conversation-drawer-display.vue
  frontend/src/shared/modules/conversation/types/Conversation.ts
  frontend/src/shared/modules/conversation/types/DisplayConfig.ts
  services/apps/data_sink_worker/src/service/activity.service.ts
  services/libs/integrations/src/integrations/activityTypes.ts
  services/libs/types/src/activities.ts
Labels: Improvement

#2368 fix: duplicate orgs showing up in autocomplete
  backend/src/services/organizationService.ts
  frontend/src/modules/member/components/form/member-form-organizations-create.vue
Labels: Improvement

#2358 Emails with platforms
  frontend/src/modules/member/components/form/email/member-form-email-item.vue
  frontend/src/modules/member/components/member-manage-emails-drawer.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities-extra.vue
  frontend/src/shared/modules/identities/config/useMemberIdentities.ts
Labels: Improvement

#2356 Merge suggestion improvements
  frontend/config/styles/components/button.scss
  frontend/public/icons/crowd-icons.svg
  frontend/src/modules/member/components/member-merge-suggestions-dialog.vue
  frontend/src/modules/member/components/member-merge-suggestions.vue
  frontend/src/modules/member/components/suggestions/member-merge-similarity.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/organization/components/organization-merge-suggestions-dialog.vue
  frontend/src/modules/organization/components/organization-merge-suggestions.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
  frontend/src/shared/avatar/avatar.vue
  frontend/src/ui-kit/index.scss
  frontend/src/ui-kit/table/Table.stories.ts
  frontend/src/ui-kit/table/Table.vue
  frontend/src/ui-kit/table/table.scss
Labels: Improvement

#2377 Remove hubspot
  frontend/src/integrations/integrations-config.js
  frontend/src/modules/automation/components/automation-list.vue
  frontend/src/modules/automation/config/automation-types/index.ts
  frontend/src/modules/dashboard/components/dashboard-upgrade-plan-widget.vue
  frontend/src/modules/member/components/member-dropdown-content.vue
  frontend/src/modules/organization/components/organization-dropdown-content.vue
Labels: Improvement

#2379 Merge suggestions API endpoint filters
  backend/src/api/tenant/index.ts
  backend/src/api/tenant/tenantMembersToMerge.ts
  backend/src/api/tenant/tenantOrganizationsToMerge.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/types/mergeSuggestionTypes.ts
  frontend/.eslintrc.js
  frontend/src/modules/member/components/member-actions.vue
  frontend/src/modules/member/components/member-merge-suggestions.vue
  frontend/src/modules/member/components/suggestions/filters/merge-suggestions-confidence-filter.vue
  frontend/src/modules/member/components/suggestions/filters/merge-suggestions-projects-filter.vue
  frontend/src/modules/member/components/suggestions/filters/merge-suggestions-search.vue
  frontend/src/modules/member/components/suggestions/member-merge-similarity.vue
  frontend/src/modules/member/components/suggestions/merge-suggestions-filters.vue
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/organization/components/organization-actions.vue
  frontend/src/modules/organization/components/organization-merge-suggestions.vue
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
  frontend/src/shared/avatar/avatar.vue
  frontend/src/shared/modules/identities/components/emails-vertical-list.vue
  frontend/src/ui-kit/checkbox/Checkbox.vue
  frontend/src/ui-kit/table/TableHead.vue
Labels: Feature, Improvement
