Repository CrowdDotDev/crowd.dev, pull requests merged in 2024-09, with the labels that each got.

#2600 Fall back to identity extraction when no identities are left after excluding secondary backup member identities
  backend/src/services/memberService.ts
Labels: Bug

#2601 Organization email editing
  frontend/src/modules/organization/components/details/email/organization-details-email-item.vue
  frontend/src/modules/organization/components/details/organization-details-emails.vue
  frontend/src/modules/organization/components/edit/email/organization-email-add.vue
  frontend/src/modules/organization/components/edit/email/organization-email-edit.vue
Labels: Improvement

#2602 GDPR request for erasure and recreate prevention
  backend/src/database/migrations/U1725465684__createRequestedForErasureMemberIdentities.sql
  backend/src/database/migrations/V1725465684__createRequestedForErasureMemberIdentities.sql
  services/apps/data_sink_worker/src/service/activity.service.ts
  services/libs/data-access-layer/src/old/apps/data_sink_worker/repo/requestedForErasureMemberIdentities.repo.ts
Labels: Feature

#2605 Unaffiliated filter fix
  frontend/src/modules/member/config/filters/main.ts
  frontend/src/modules/member/config/filters/unaffiliated/config.ts
  frontend/src/modules/member/config/saved-views/views/unaffiliated.ts
Labels: Improvement

#2612 Refresh user on unmerge identity
  frontend/src/modules/member/components/member-unmerge-dialog.vue
  frontend/src/modules/organization/components/organization-unmerge-dialog.vue
Labels: Improvement

#2615 Align main menu for lf design
  frontend/src/assets/scss/index.scss
  frontend/src/assets/scss/layout/_menu.scss
  frontend/src/assets/scss/layout/index.scss
  frontend/src/assets/scss/tooltip.scss
  frontend/src/modules/layout/components/layout.vue
  frontend/src/modules/layout/components/menu/menu-link.vue
  frontend/src/modules/layout/components/menu/menu.vue
  frontend/src/modules/lf/layout/components/lf-menu-project-group-selection.vue
  frontend/src/modules/lf/layout/components/lf-menu.vue
  frontend/src/ui-kit/icon/Icon.vue
  frontend/tailwind.config.js
Labels: Improvement

#2623 Remove timeout for refreshDashboardCacheDaily workflow
  services/apps/cache_worker/src/schedules/refreshDashboardCacheDaily.ts
Labels: Bug

#2619 Unify sources across the app
  frontend/src/integrations/integrations-config.js
  frontend/src/modules/contributor/components/details/attributes/contributor-attribute-source.vue
  frontend/src/modules/contributor/components/details/identity/contributor-details-identity-item.vue
  frontend/src/modules/organization/components/details/domains/organization-details-domain-item.vue
  frontend/src/modules/organization/components/details/email/organization-details-email-item.vue
  frontend/src/modules/organization/components/details/identity/organization-details-identity-item.vue
  frontend/src/modules/organization/components/details/overview/attributes/organization-attribute-source.vue
  frontend/src/shared/helpers/attribute.helpers.ts
Labels: Improvement

#2629 Maintainers data
  backend/src/database/migrations/U1727428673__maintainers-mv.sql
  backend/src/database/migrations/V1727428673__maintainers-mv.sql
  backend/src/database/repositories/member/memberAffiliationsRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/member/memberAffiliationsService.ts
  frontend/package.json
  frontend/src/modules/contributor/components/details/overview/contributor-details-community.vue
  frontend/src/modules/contributor/components/details/overview/contributor-details-maintainer.vue
  frontend/src/modules/contributor/components/details/overview/contributor-details-projects.vue
  frontend/src/modules/contributor/components/details/overview/project/contributor-details-projects-affiliation.vue
  frontend/src/modules/contributor/components/details/overview/project/contributor-details-projects-maintainer-item.vue
  frontend/src/modules/contributor/components/details/overview/project/contributor-details-projects-maintainer.vue
  frontend/src/modules/contributor/components/details/overview/project/contributor-details-projects-sorting.vue
  frontend/src/modules/contributor/types/Contributor.ts
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/config/filters/role/config.ts
  frontend/src/modules/member/config/filters/role/options.ts
  frontend/src/modules/member/types/Member.ts
  frontend/src/ui-kit/table/Table.vue
  services/libs/data-access-layer/src/maintainers/index.ts
Labels: Feature
