Repository CrowdDotDev/crowd.dev, pull requests merged in 2024-11, with the labels that each got.

#2669 Fix autocomplete sorting
  backend/src/services/organizationService.ts
  frontend/src/modules/member/member-service.js
  frontend/src/modules/organization/components/shared/organization-select.vue
  frontend/src/modules/organization/organization-service.js
Labels: Bug

#2671 Fix activity pagination, load more functionality
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/contributor/components/details/contributor-details-activities.vue
  frontend/src/modules/contributor/pages/contributor-details.page.vue
  frontend/src/modules/data-quality/components/member/data-quality-member-issues.vue
  frontend/src/modules/data-quality/components/member/data-quality-member-merge-suggestions.vue
  frontend/src/modules/data-quality/components/organization/data-quality-organization-merge-suggestions.vue
  frontend/src/modules/data-quality/pages/data-quality.page.vue
  frontend/src/modules/organization/components/details/organization-details-activities.vue
  frontend/src/modules/organization/pages/organization-details.page.vue
  frontend/src/ui-kit/scrollcontroll/ScrollControll.vue
Labels: Bug

#2672 Users admin tab
  backend/src/database/repositories/userRepository.ts
  frontend/src/modules/admin/models/User.model.ts
  frontend/src/modules/admin/pages/users.page.vue
  frontend/src/modules/admin/services/users.service.ts
  frontend/src/modules/lf/segments/pages/lf-admin-panel-page.vue
  frontend/src/ui-kit/search/Search.vue
Labels: Improvement

#2670 Improvement/stricter serp api enrichment filter
  services/apps/premium/members_enrichment_worker/src/activities.ts
  services/apps/premium/members_enrichment_worker/src/activities/enrichment.ts
  services/apps/premium/members_enrichment_worker/src/activities/getMembers.ts
  services/apps/premium/members_enrichment_worker/src/schedules/getMembersToEnrich.ts
  services/apps/premium/members_enrichment_worker/src/sources/clearbit/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/progai/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/serp/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/serp/types.ts
  services/apps/premium/members_enrichment_worker/src/types.ts
  services/apps/premium/members_enrichment_worker/src/workflows/enrichMember.ts
  services/apps/premium/members_enrichment_worker/src/workflows/getMembersToEnrich.ts
  services/libs/data-access-layer/src/activities/sql.ts
  services/libs/data-access-layer/src/old/apps/premium/members_enrichment_worker/index.ts
  services/libs/redis/src/cache.ts
  services/libs/types/src/premium/enrichment.ts
Labels: Improvement

#2673 Affiliation apply to all projects
  frontend/src/modules/contributor/components/edit/affilations/contributor-affilations-edit-item.vue
  frontend/src/modules/contributor/components/edit/affilations/contributor-affilations-edit.vue
Labels: Improvement

#2678 Crustdata linkedin enrichment
  services/apps/premium/members_enrichment_worker/src/factory.ts
  services/apps/premium/members_enrichment_worker/src/main.ts
  services/apps/premium/members_enrichment_worker/src/sources/crustdata/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/crustdata/types.ts
  services/apps/premium/members_enrichment_worker/src/sources/progai-linkedin-scraper/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/progai-linkedin-scraper/types.ts
  services/apps/premium/members_enrichment_worker/src/types.ts
  services/apps/premium/members_enrichment_worker/src/workflows/getMembersToEnrich.ts
  services/libs/types/src/enums/enrichment.ts
  services/libs/types/src/enums/members.ts
  services/libs/types/src/enums/organizations.ts
Labels: Feature

#2681 Cascade on dropping `membersGlobalActivityCount` for dependent mvs
  backend/src/database/migrations/R__memberEnrichmentMaterializedViews.sql
Labels: Bug

#2682 Enrichment monitoring fixes
  backend/src/database/migrations/R__memberEnrichmentMaterializedViews.sql
  services/apps/premium/members_enrichment_worker/src/activities.ts
  services/apps/premium/members_enrichment_worker/src/activities/enrichment.ts
  services/apps/premium/members_enrichment_worker/src/activities/getMembers.ts
  services/apps/premium/members_enrichment_worker/src/schedules/getMembersToEnrich.ts
  services/apps/premium/members_enrichment_worker/src/sources/clearbit/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/crustdata/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/progai-linkedin-scraper/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/progai/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/serp/service.ts
  services/apps/premium/members_enrichment_worker/src/types.ts
  services/apps/premium/members_enrichment_worker/src/workflows/enrichMember.ts
  services/apps/premium/members_enrichment_worker/src/workflows/getMembersToEnrich.ts
  services/libs/data-access-layer/src/old/apps/premium/members_enrichment_worker/index.ts
Labels: Bug

#2686 Admin integration status page
  backend/src/api/integration/index.ts
  backend/src/api/integration/integrationGlobal.ts
  backend/src/api/integration/integrationGlobalStatus.ts
  backend/src/database/repositories/integrationRepository.ts
  backend/src/services/integrationService.ts
  frontend/src/modules/admin/modules/integration/components/integration-list.vue
  frontend/src/modules/admin/modules/integration/components/status/integration-platform-select.vue
  frontend/src/modules/admin/modules/integration/config/status/connecting.ts
  frontend/src/modules/admin/modules/integration/config/status/done.ts
  frontend/src/modules/admin/modules/integration/config/status/error.ts
  frontend/src/modules/admin/modules/integration/config/status/index.ts
  frontend/src/modules/admin/modules/integration/config/status/not-connected.ts
  frontend/src/modules/admin/modules/integration/config/status/waiting-approval.ts
  frontend/src/modules/admin/modules/integration/config/status/waiting-for-action.ts
  frontend/src/modules/admin/modules/integration/pages/integration-list.page.vue
  frontend/src/modules/admin/modules/integration/pages/integration-status.page.vue
  frontend/src/modules/admin/modules/users/services/users.service.ts
  frontend/src/modules/lf/segments/pages/lf-admin-panel-page.vue
  frontend/src/ui-kit/tabs/Tabs.vue
  services/libs/data-access-layer/src/integrations/index.ts
Labels: Improvement

#2700 Refactor and reuse `setAttributesDefaultValues` in enrichment
  services/apps/data_sink_worker/src/service/memberAttribute.service.ts
  services/apps/premium/members_enrichment_worker/src/activities.ts
  services/apps/premium/members_enrichment_worker/src/activities/enrichment.ts
  services/apps/premium/members_enrichment_worker/src/sources/crustdata/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/progai/service.ts
  services/apps/premium/members_enrichment_worker/src/utils/common.ts
  services/apps/premium/members_enrichment_worker/src/workflows/enrichMember.ts
  services/apps/premium/members_enrichment_worker/src/workflows/processMemberSources.ts
  services/libs/common/src/index.ts
  services/libs/common/src/member.ts
  services/libs/common/src/utils.ts
Labels: Bug

#2688 Member enrichment llm lfx 1712
  backend/src/bin/scripts/unmerge-members.ts
  backend/src/database/migrations/R__memberEnrichmentMaterializedViews.sql
  backend/src/database/migrations/U1731052735__llm-prompt-history.sql
  backend/src/database/migrations/U1731484783__drop-member-deprecated-columns.sql
  backend/src/database/migrations/U1732695786__member-organization-unique-indexes-with-deletedAt.sql
  backend/src/database/migrations/V1731052735__llm-prompt-history.sql
  backend/src/database/migrations/V1731484783__drop-member-deprecated-columns.sql
  backend/src/database/migrations/V1732695786__member-organization-unique-indexes-with-deletedAt.sql
  pnpm-lock.yaml
  services/apps/data_sink_worker/src/service/memberAttribute.service.ts
  services/apps/data_sink_worker/src/service/organization.service.ts
  services/apps/premium/members_enrichment_worker/package.json
  services/apps/premium/members_enrichment_worker/src/activities.ts
  services/apps/premium/members_enrichment_worker/src/activities/enrichment.ts
  services/apps/premium/members_enrichment_worker/src/activities/getMembers.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/authenticateLFAuth0.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/enrichLFAuth0.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/getEnrichmentLFAuth0.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/getLFIDEnrichableMembers.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/githubIdentities.ts
  services/apps/premium/members_enrichment_worker/src/activities/syncEnrichedData.ts
  services/apps/premium/members_enrichment_worker/src/bin/onboarding.ts
  services/apps/premium/members_enrichment_worker/src/main.ts
  services/apps/premium/members_enrichment_worker/src/schedules/getMembersToEnrich.ts
  services/apps/premium/members_enrichment_worker/src/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/clearbit/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/crustdata/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/progai/service.ts
  services/apps/premium/members_enrichment_worker/src/types.ts
  services/apps/premium/members_enrichment_worker/src/utils/common.ts
  services/apps/premium/members_enrichment_worker/src/workflows.ts
  services/apps/premium/members_enrichment_worker/src/workflows/enrichMember.ts
  services/apps/premium/members_enrichment_worker/src/workflows/processMemberSources.ts
  services/archetypes/worker/src/index.ts
  services/libs/common/src/index.ts
  services/libs/common/src/member.ts
  services/libs/common/src/utils.ts
  services/libs/common_services/package.json
  services/libs/common_services/src/repos/llmPromptHistory.repo.ts
  services/libs/common_services/src/services/index.ts
  services/libs/common_services/src/services/llm.service.ts
  services/libs/data-access-layer/src/members/base.ts
  services/libs/data-access-layer/src/members/contributions.ts
  services/libs/data-access-layer/src/members/index.ts
  services/libs/data-access-layer/src/members/others.ts
  services/libs/data-access-layer/src/old/apps/premium/members_enrichment_worker/index.ts
  services/libs/data-access-layer/src/organizations/attributesConfig.ts
  services/libs/data-access-layer/src/organizations/organizations.ts
  services/libs/types/src/enums/activities.ts
  services/libs/types/src/enums/enrichment.ts
  services/libs/types/src/enums/index.ts
  services/libs/types/src/enums/llm.ts
  services/libs/types/src/enums/organizations.ts
  services/libs/types/src/index.ts
  services/libs/types/src/llm.ts
  services/libs/types/src/premium/enrichment.ts
Labels: Feature
