Repository CrowdDotDev/crowd.dev, pull requests merged in 2024-01, with the labels that each got.

#1997 fix organization manual `website` update and handle error
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/__tests__/tenantService.test.ts
  frontend/src/modules/organization/pages/organization-form-page.vue
  services/libs/common/src/i18n/en.ts
  services/libs/common/src/websiteNormalizer.ts
Labels: Bug

#2008 Fix 404 error in profile for organizations from member enrichment
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#2009 Fix generic boolean filter
  frontend/src/shared/modules/filters/config/apiFilterRenderer/boolean.filter.renderer.ts
Labels: Bug

#2012 Fix tenant identity
  backend/src/api/tenant/tenantUpdate.ts
  backend/src/segment/identifyTenant.ts
Labels: Bug

#2018 Common actions and merge suggestions on member pages
  frontend/src/modules/member/components/member-actions.vue
  frontend/src/modules/member/components/member-dropdown-content.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/view/member-view-header.vue
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/modules/organization/components/organization-actions.vue
  frontend/src/modules/organization/components/organization-dropdown-content.vue
  frontend/src/modules/organization/components/organization-dropdown.vue
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
  frontend/src/modules/organization/pages/organization-view-page.vue
Labels: Improvement

#2011 Change layout for merge suggestions
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
Labels: Improvement

#2023 Refactor identities display
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/scss/buttons.scss
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-display-name.vue
  frontend/src/modules/member/components/member-identities.vue
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/member/components/view/_aside/_aside-enriched.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities-extra.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
  frontend/src/modules/member/components/view/_aside/_aside-organizations.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/organization/components/form/organization-form-identities.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/organization-identities.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/components/view/_aside/_aside-identities-extra.vue
  frontend/src/modules/organization/components/view/_aside/_aside-identities.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/components/view/organization-view-members.vue
  frontend/src/modules/organization/types/Organization.ts
  frontend/src/modules/widget/components/member/widget-active-leaderboard-members.vue
  frontend/src/modules/widget/components/shared/widget-members-table-row.vue
  frontend/src/modules/widget/components/shared/widget-members-table.vue
  frontend/src/shared/modules/identities/components/identities-horizontal-list-members.vue
  frontend/src/shared/modules/identities/components/identities-horizontal-list-organizations.vue
  frontend/src/shared/modules/identities/components/identities-horizontal-list.vue
  frontend/src/shared/modules/identities/components/identities-vertical-list-members.vue
  frontend/src/shared/modules/identities/components/identities-vertical-list-organizations.vue
  frontend/src/shared/modules/identities/components/identities-vertical-list.vue
  frontend/src/shared/modules/identities/config/identitiesOrder/member/index.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/member/list.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/member/profile.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/member/suggestions.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/organization/index.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/organization/list.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/organization/profile.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/organization/suggestions.ts
  frontend/src/shared/modules/identities/config/useMemberIdentities.ts
  frontend/src/shared/modules/identities/config/useOrganizationIdentities.ts
  frontend/src/shared/modules/platform/components/platform-icon.vue
  frontend/src/shared/modules/platform/components/platform-img.vue
  frontend/src/shared/modules/platform/components/platform-svg.vue
  frontend/src/shared/modules/platform/components/platform.vue
  frontend/src/shared/modules/platform/types/Platform.ts
  frontend/src/shared/platform/platform-list.vue
  frontend/src/shared/platform/platform-popover.vue
  frontend/src/shared/platform/platform-svg-icon.vue
  frontend/src/shared/platform/platform.vue
  frontend/src/shared/shared-module.js
Labels: Improvement

#2032 Fix identities overflow
  frontend/src/shared/modules/identities/components/identities-vertical-list.vue
Labels: Bug

#2031 Improve identities display linux
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/scss/buttons.scss
  frontend/src/modules/dashboard/components/dashboard-project-group-drawer.vue
  frontend/src/modules/lf/segments/components/view/lf-projects-table.vue
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-display-name.vue
  frontend/src/modules/member/components/member-identities.vue
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/member/components/view/_aside/_aside-enriched.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities-extra.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
  frontend/src/modules/member/components/view/_aside/_aside-organizations.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/organization/components/form/organization-form-identities.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/organization-identities.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/components/view/_aside/_aside-identities-extra.vue
  frontend/src/modules/organization/components/view/_aside/_aside-identities.vue
  frontend/src/modules/organization/components/view/organization-view-aside.vue
  frontend/src/modules/organization/components/view/organization-view-members.vue
  frontend/src/modules/organization/pages/organization-form-page.vue
  frontend/src/modules/organization/types/Organization.ts
  frontend/src/modules/widget/components/member/widget-active-leaderboard-members.vue
  frontend/src/modules/widget/components/shared/widget-members-table-row.vue
  frontend/src/modules/widget/components/shared/widget-members-table.vue
  frontend/src/shared/modules/identities/components/identities-horizontal-list-members.vue
  frontend/src/shared/modules/identities/components/identities-horizontal-list-organizations.vue
  frontend/src/shared/modules/identities/components/identities-horizontal-list.vue
  frontend/src/shared/modules/identities/components/identities-vertical-list-members.vue
  frontend/src/shared/modules/identities/components/identities-vertical-list-organizations.vue
  frontend/src/shared/modules/identities/components/identities-vertical-list.vue
  frontend/src/shared/modules/identities/config/identitiesOrder/member/index.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/member/list.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/member/profile.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/member/suggestions.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/organization/index.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/organization/list.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/organization/profile.ts
  frontend/src/shared/modules/identities/config/identitiesOrder/organization/suggestions.ts
  frontend/src/shared/modules/identities/config/useMemberIdentities.ts
  frontend/src/shared/modules/identities/config/useOrganizationIdentities.ts
  frontend/src/shared/modules/platform/components/platform-icon.vue
  frontend/src/shared/modules/platform/components/platform-img.vue
  frontend/src/shared/modules/platform/components/platform-svg.vue
  frontend/src/shared/modules/platform/components/platform.vue
  frontend/src/shared/modules/platform/types/Platform.ts
  frontend/src/shared/platform/platform-list.vue
  frontend/src/shared/platform/platform-popover.vue
  frontend/src/shared/platform/platform-svg-icon.vue
  frontend/src/shared/platform/platform.vue
  frontend/src/shared/shared-module.js
Labels: Improvement

#2029 Fix `lastActivity` not showing up in contributors list
  backend/src/database/repositories/memberEnrichmentCacheRepository.ts
  backend/src/database/repositories/memberRepository.ts
  services/apps/entity_merging_worker/src/main.ts
  services/libs/types/src/enums/featureFlags.ts
Labels: Bug

#2036 Replace parent segment with leaf segments for member `lastActivity`
  backend/src/database/repositories/memberRepository.ts
Labels: Improvement

#2040 Merge suggestion preview
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
  frontend/src/shared/modules/identities/components/identities-vertical-list.vue
Labels: Improvement

#2041 UX improvements on merge actions
  frontend/src/modules/member/components/member-actions.vue
  frontend/src/modules/member/components/member-dropdown-content.vue
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/modules/organization/components/organization-actions.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
  frontend/src/modules/organization/pages/organization-view-page.vue
Labels: Improvement

#2021 Improve affiliations success message
  frontend/src/modules/member/components/form/member-form-organizations-drawer.vue
  frontend/src/shared/store/actions.js
Labels: Improvement

#2030 Improve merge feedback message
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-merge-dialog.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/components/organization-merge-dialog.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
Labels: Improvement

#2045 Fix modal on github onboarding
  frontend/src/integrations/github/components/github-connect.vue
  frontend/src/modules/integration/components/integration-connect.vue
  frontend/src/modules/onboard/components/onboard-invite-colleagues-step.vue
  frontend/src/modules/onboard/config/steps/invite-colleagues.ts
  frontend/src/modules/onboard/config/steps/sync-data.ts
  frontend/src/modules/onboard/pages/onboard-page.vue
  frontend/src/modules/onboard/types/OnboardStepsConfig.ts
Labels: Bug

#2048 Fix merge suggestions loading
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
Labels: Improvement

#1911 Remove all enrich manual actions
  frontend/public/icons/crowd-icons.svg
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-dropdown-content.vue
  frontend/src/modules/member/components/member-enrichment.vue
  frontend/src/modules/member/components/view/_aside/_aside-enrichment.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
Labels: Feature

#2055 Fix identities drawer update, activity type filter and platform filter
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/activity/config/filters/activityType/ActivityTypeFilter.vue
  frontend/src/modules/lf/layout/components/lf-menu-project-group-selection.vue
  frontend/src/modules/member/components/member-manage-identities-drawer.vue
  frontend/src/modules/member/config/filters/activityType/ActivityTypeFilter.vue
  frontend/src/modules/organization/components/organization-actions.vue
Labels: Bug

#2065 Refactor merge toast messages
  frontend/src/modules/auth/auth-socket.js
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-merge-dialog.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/components/organization-merge-dialog.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
  frontend/src/shared/modules/merge/config/member/apiErrorMessage.ts
  frontend/src/shared/modules/merge/config/member/loadingMessage.ts
  frontend/src/shared/modules/merge/config/member/successMessage.ts
  frontend/src/shared/modules/merge/config/organization/apiErrorMessage.ts
  frontend/src/shared/modules/merge/config/organization/loadingMessage.ts
  frontend/src/shared/modules/merge/config/organization/socketErrorMessage.ts
  frontend/src/shared/modules/merge/config/organization/successMessage.ts
  frontend/src/shared/modules/merge/config/useMemberMergeMessage.ts
  frontend/src/shared/modules/merge/config/useOrganizationMergeMessage.ts
  frontend/src/shared/modules/merge/types/MemberMessage.ts
  frontend/src/shared/modules/merge/types/OrganizationMessage.ts
Labels: Improvement

#2061 Clean up profile
  frontend/src/app.vue
  frontend/src/assets/scss/buttons.scss
  frontend/src/assets/scss/tags.scss
  frontend/src/modules/lf/member/components/view/lf-member-aside-sub-projects.vue
  frontend/src/modules/member/components/member-engagement-level.vue
  frontend/src/modules/member/components/member-last-activity.vue
  frontend/src/modules/member/components/view/_aside/_aside-custom-attributes.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities-extra.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities.vue
  frontend/src/modules/member/components/view/_aside/_aside-organizations.vue
  frontend/src/modules/member/types/Member.ts
  frontend/src/modules/organization/components/view/organization-view-members.vue
  frontend/src/modules/tag/components/tag-list.vue
  frontend/src/premium/eagle-eye/components/list/eagle-eye-list.vue
  frontend/src/shared/modules/entities/Entities.vue
  frontend/tailwind.config.js
Labels: Improvement

#2066 Update member `findByIdOpenSearch` to support search without segments
  backend/src/database/repositories/memberRepository.ts
Labels: Improvement

#2071 Improved org enrichment
  backend/src/services/premium/enrichment/organizationEnrichmentService.ts
  backend/src/types/enrichmentTypes.ts
  services/apps/premium/organizations_enrichment_worker/src/activities.ts
  services/apps/premium/organizations_enrichment_worker/src/activities/organizationEnrichment.ts
  services/apps/premium/organizations_enrichment_worker/src/repos/organization.repo.ts
  services/apps/premium/organizations_enrichment_worker/src/workflows/entrichTenantOrganizations.ts
Labels: Improvement

#2073 Make sure name-website combination is unique in organizationCacheIdentities table
  backend/src/database/migrations/U1705060063__org-cache-identities-unique-key.sql
  backend/src/database/migrations/V1705060063__org-cache-identities-unique-key.sql
  services/apps/data_sink_worker/package.json
  services/apps/data_sink_worker/src/bin/fix-org-cache-identities-duplicates.ts
Labels: Bug

#2078 Fixed org cache identity insert query typo
  backend/src/database/repositories/organizationCacheRepository.ts
Labels: Bug

#2079 Fix load of array attributes without value
  frontend/src/shared/fields/get-custom-attributes.js
Labels: Bug

#2086 Dashboard caching
  .github/workflows/lf-staging-deploy-cache-worker.yaml
  .github/workflows/staging-deploy-cache-worker.yaml
  backend/package.json
  backend/src/api/dashboard/dashboardGet.ts
  backend/src/api/dashboard/index.ts
  backend/src/api/index.ts
  backend/src/bin/jobs/refreshMaterializedViewsForCube.ts
  backend/src/bin/scripts/cache-dashboard.ts
  backend/src/database/migrations/R__cubejs-materialized-views.sql
  backend/src/database/migrations/U1704923216__dashboardCacheLastRefreshedAt.sql
  backend/src/database/migrations/V1704923216__dashboardCacheLastRefreshedAt.sql
  backend/src/services/dashboardService.ts
  pnpm-lock.yaml
  scripts/builders/cache-worker.env
  scripts/services/cache-worker.yaml
  scripts/services/docker/Dockerfile.cache_worker
  scripts/services/docker/Dockerfile.cache_worker.dockerignore
  services/apps/cache_worker/.eslintrc.cjs
  services/apps/cache_worker/.prettierignore
  services/apps/cache_worker/.prettierrc.cjs
  services/apps/cache_worker/package.json
  services/apps/cache_worker/src/activities.ts
  services/apps/cache_worker/src/activities/dashboard-cache/refreshDashboardCache.ts
  services/apps/cache_worker/src/activities/getTenantSegmentInfo.ts
  services/apps/cache_worker/src/enums.ts
  services/apps/cache_worker/src/main.ts
  services/apps/cache_worker/src/repo/activity.repo.ts
  services/apps/cache_worker/src/repo/integration.repo.ts
  services/apps/cache_worker/src/repo/segment.repo.ts
  services/apps/cache_worker/src/repo/tenant.repo.ts
  services/apps/cache_worker/src/types.ts
  services/apps/cache_worker/src/workflows.ts
  services/apps/cache_worker/src/workflows/refreshDashboardCache.ts
  services/apps/cache_worker/src/workflows/spawnDashboardCacheRefreshForAllTenants.ts
  services/apps/cache_worker/tsconfig.json
  services/archetypes/worker/src/index.ts
  services/libs/cubejs/src/app/Dockerfile
  services/libs/cubejs/src/dimensions.ts
  services/libs/cubejs/src/enums.ts
  services/libs/cubejs/src/index.ts
  services/libs/cubejs/src/measures.ts
  services/libs/cubejs/src/metrics/activeMembers.ts
  services/libs/cubejs/src/metrics/activeOrganizations.ts
  services/libs/cubejs/src/metrics/newActivities.ts
  services/libs/cubejs/src/metrics/newConversations.ts
  services/libs/cubejs/src/metrics/newMembers.ts
  services/libs/cubejs/src/metrics/newOrganizations.ts
  services/libs/cubejs/src/service.ts
  services/libs/cubejs/src/types.ts
  services/libs/types/src/enums/dashboard.ts
  services/libs/types/src/enums/index.ts
  services/libs/types/src/temporal/cache.ts
  services/libs/types/src/temporal/index.ts
Labels: Feature

#2083 Implement merge suggestions btn permissions
  frontend/src/modules/member/components/member-actions.vue
  frontend/src/modules/member/components/member-dropdown-content.vue
  frontend/src/modules/member/member-permissions.js
  frontend/src/modules/member/member-routes.js
  frontend/src/modules/member/pages/member-list-page.vue
  frontend/src/modules/organization/components/organization-actions.vue
  frontend/src/modules/organization/components/organization-dropdown-content.vue
  frontend/src/modules/organization/organization-permissions.js
  frontend/src/modules/organization/organization-routes.js
  frontend/src/modules/organization/pages/organization-list-page.vue
  frontend/src/security/permissions.js
Labels: Improvement

#2091 Fix segments permissions
  backend/src/database/repositories/segmentRepository.ts
  backend/src/services/user/permissionChecker.ts
  frontend/src/middleware/auth/segment-guard.js
  frontend/src/modules/dashboard/components/dashboard-project-group.vue
  frontend/src/modules/dashboard/pages/dashboard-page.vue
  frontend/src/modules/integration/integration-routes.js
  frontend/src/modules/lf/layout/components/lf-banners.vue
  frontend/src/modules/lf/layout/components/lf-menu-project-group-selection.vue
  frontend/src/modules/lf/lf-routes.js
  frontend/src/modules/lf/segments/components/form/lf-project-form.vue
  frontend/src/modules/lf/segments/components/form/lf-sub-project-form.vue
  frontend/src/modules/lf/segments/components/lf-project-groups-dropdown.vue
  frontend/src/modules/lf/segments/components/lf-projects-dropdown.vue
  frontend/src/modules/lf/segments/components/lf-sub-projects-dropdown.vue
  frontend/src/modules/lf/segments/components/view/lf-projects-table.vue
  frontend/src/modules/lf/segments/lf-segments-service.js
  frontend/src/modules/lf/segments/pages/lf-project-groups-list-page.vue
  frontend/src/modules/lf/segments/pages/lf-projects-page.vue
  frontend/src/modules/lf/segments/store/actions.js
  frontend/src/modules/lf/segments/store/state.ts
  frontend/src/utils/segments.js
Labels: Bug

#2075 Dashboard optimize
  frontend/src/modules/dashboard/components/activity/dashboard-activity-sentiment.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-types.vue
  frontend/src/modules/dashboard/components/dashboard-activities.vue
  frontend/src/modules/dashboard/components/dashboard-count.vue
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/dashboard/components/dashboard-widget-chart.vue
  frontend/src/modules/dashboard/dashboard.chart.js
  frontend/src/modules/dashboard/dashboard.cube.js
  frontend/src/modules/dashboard/services/dashboard.api.service.ts
  frontend/src/modules/dashboard/store/actions.js
  frontend/src/modules/dashboard/store/getters.js
  frontend/src/modules/dashboard/store/state.js
  frontend/src/modules/dashboard/types/DashboardCubeData.ts
  frontend/tailwind.config.js
Labels: Improvement

#2077 Edit member ctas
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/organization/pages/organization-form-page.vue
Labels: Improvement

#2095 Enhancement/activities endpoints improvement lfx 569
  backend/src/api/activity/activityQuery.ts
  backend/src/bin/jobs/refreshMaterializedViewsForCube.ts
  backend/src/database/repositories/activityRepository.ts
  backend/src/services/activityService.ts
  frontend/src/modules/activity/activity-service.js
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/activity/config/filters/member/config.ts
  frontend/src/modules/activity/config/filters/organizations/config.ts
  frontend/src/modules/activity/config/filters/platform/config.ts
  frontend/src/modules/activity/config/filters/sentiment/config.ts
Labels: Improvement

#2094 UX improvements on lists
  frontend/src/assets/scss/table.scss
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-actions.vue
  frontend/src/modules/member/components/member-emails.vue
  frontend/src/modules/member/components/member-job-title.vue
  frontend/src/modules/member/components/member-last-activity.vue
  frontend/src/modules/member/components/member-organizations-vertical.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/organization-actions.vue
  frontend/src/modules/organization/components/organization-name.vue
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/modules/tag/components/tag-list.vue
  frontend/src/shared/tag/tag-list.vue
Labels: Improvement

#2106 Fix sentiment dashboard
  frontend/src/modules/dashboard/components/activity/dashboard-activity-sentiment.vue
Labels: Bug

#2096 index using async req to search-sync-worker
  pnpm-lock.yaml
  services/apps/premium/organizations_enrichment_worker/package.json
  services/apps/premium/organizations_enrichment_worker/src/activities/organizationEnrichment.ts
  services/apps/premium/organizations_enrichment_worker/src/main.ts
  services/apps/premium/organizations_enrichment_worker/src/workflows/enrichOrganization.ts
  services/archetypes/worker/package.json
  services/archetypes/worker/src/index.ts
  services/libs/common_services/src/services/emitters/searchSyncWorker.emitter.ts
  services/libs/common_services/src/services/priority.service.ts
  services/libs/sqs/src/prioritization.ts
Labels: Improvement

#2117 member_segments_mv, refreshing of the materialized view and usage in query for merge suggestions
  backend/src/bin/jobs/mergeSuggestions.ts
  backend/src/bin/jobs/refreshMaterializedViews.ts
  backend/src/bin/jobs/refreshMaterializedViewsForCube.ts
  backend/src/database/migrations/R__member_segments_mv.sql
  backend/src/database/repositories/memberRepository.ts
  services/apps/merge_suggestions_worker/src/schedules/memberMergeSuggestions.ts
  services/apps/premium/members_enrichment_worker/src/schedules/getMembersToEnrich.ts
  services/apps/premium/organizations_enrichment_worker/src/schedules/organizationEnrichment.ts
Labels: Improvement

#2129 Improve contact `findByIdOpensearch` to support search without segment
  backend/src/database/repositories/memberRepository.ts
Labels: Bug

#2130 Remove invite admin button
  frontend/src/integrations/github/components/github-connect.vue
Labels: Bug

#2131 Active organizations endpoint using activity index, cubejs new members update
  backend/src/api/organization/index.ts
  backend/src/api/organization/organizationActiveList.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/database/repositories/types/organizationTypes.ts
  backend/src/services/organizationService.ts
  services/libs/cubejs/src/app/schema/MemberIdentities.js
  services/libs/cubejs/src/app/schema/Members.js
  services/libs/cubejs/src/enums.ts
  services/libs/cubejs/src/metrics/newMembers.ts
  services/libs/opensearch/src/repo/activity.data.ts
  services/libs/opensearch/src/repo/activity.repo.ts
  services/libs/opensearch/src/service/activity.sync.service.ts
  services/libs/opensearch/src/service/init.service.ts
Labels: Bug

#2146 Improve merge success message
  backend/src/services/organizationService.ts
  frontend/src/modules/auth/auth-socket.js
  frontend/src/modules/member/components/list/member-list-toolbar.vue
  frontend/src/modules/member/components/member-merge-dialog.vue
  frontend/src/modules/member/components/member-merge-suggestions.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/components/organization-merge-dialog.vue
  frontend/src/modules/organization/components/organization-merge-suggestions.vue
  services/apps/entity_merging_worker/src/activities/organizations.ts
  services/apps/entity_merging_worker/src/workflows/all.ts
Labels: Improvement

#2147 Improve merge success message - lfx
  backend/src/services/organizationService.ts
  frontend/src/modules/auth/auth-socket.js
  frontend/src/shared/modules/merge/config/member/apiErrorMessage.ts
  frontend/src/shared/modules/merge/config/organization/apiErrorMessage.ts
  services/apps/entity_merging_worker/src/activities/organizations.ts
  services/apps/entity_merging_worker/src/workflows/all.ts
Labels: Improvement

#2142 Custom reports quick wins
  frontend/src/i18n/en.js
  frontend/src/modules/activity/components/activity-timeline.vue
  frontend/src/modules/widget/components/cube/_query_builder/DimensionSelect.vue
  frontend/src/modules/widget/components/cube/_query_builder/FilterComponent.vue
  frontend/src/modules/widget/components/cube/widget-cube.vue
Labels: Improvement

#2139 Engagement level labels added to members cube as a separate dimension
  services/libs/cubejs/src/app/schema/Members.js
Labels: Improvement

#2148 Bugfix/new orgs identity platform filter fix
  services/libs/cubejs/src/app/schema/OrganizationIdentities.js
  services/libs/cubejs/src/app/schema/Organizations.js
  services/libs/cubejs/src/enums.ts
  services/libs/cubejs/src/metrics/newOrganizations.ts
  services/libs/opensearch/src/models/organizations.ts
Labels: Bug

#2150 Fix organization name and add additional attributes in CSV export
  backend/src/services/memberService.ts
  services/libs/opensearch/src/memberTranslator.ts
  services/libs/opensearch/src/repo/member.data.ts
  services/libs/opensearch/src/repo/member.repo.ts
  services/libs/opensearch/src/service/init.service.ts
  services/libs/opensearch/src/service/member.sync.service.ts
Labels: Bug

#2153 Fix url unique
  backend/src/database/repositories/__tests__/tenantRepository.test.ts
  backend/src/database/repositories/tenantRepository.ts
Labels: Bug

#2151 Remove contacts enrichment tracking
  backend/src/services/premium/enrichment/memberEnrichmentService.ts
Labels: Improvement

#2154 Hubspot sync errors
  services/apps/integration_sync_worker/src/repo/organization.repo.ts
  services/apps/integration_sync_worker/src/service/member.sync.service.ts
  services/libs/common/src/requestThrottler.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/batchCreateMembers.ts
  services/libs/integrations/src/integrations/premium/hubspot/api/types.ts
  services/libs/integrations/src/integrations/premium/hubspot/field-mapper/memberFieldMapper.ts
  services/libs/integrations/src/integrations/premium/hubspot/processSyncRemote.ts
Labels: Bug

#2152 Button ui kit & colors variables
  frontend/.eslintrc.js
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/.storybook/storybook.scss
  frontend/.tailwind/colorConverter.js
  frontend/config/styles/components/button.scss
  frontend/config/styles/components/index.scss
  frontend/config/styles/index.scss
  frontend/config/styles/utilities/_colors.scss
  frontend/config/styles/utilities/index.scss
  frontend/config/styles/variables/_colors.scss
  frontend/config/styles/variables/_shadows.scss
  frontend/config/styles/variables/index.scss
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/scss/helpers/_mixins.scss
  frontend/src/assets/scss/helpers/index.scss
  frontend/src/assets/scss/index.scss
  frontend/src/modules/automation/config/automation-types/slack/slack-action.vue
  frontend/src/shared/ui-kit/button/Button.stories.ts
  frontend/src/shared/ui-kit/button/Button.vue
  frontend/src/shared/ui-kit/button/button.scss
  frontend/src/shared/ui-kit/button/types/ButtonNativeType.ts
  frontend/src/shared/ui-kit/button/types/ButtonSize.ts
  frontend/src/shared/ui-kit/button/types/ButtonType.ts
  frontend/src/shared/ui-kit/index.scss
  frontend/tailwind.config.js
Labels: Improvement

#2156 Add profile link to merge suggestions
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
Labels: Improvement

#2160 Added a unique index to organizationCacheIdentities.name column
  backend/src/database/migrations/U1706692519__org-cache-identity-unique-name.sql
  backend/src/database/migrations/V1706692519__org-cache-identity-unique-name.sql
  backend/src/database/repositories/organizationCacheRepository.ts
  services/apps/data_sink_worker/src/bin/fix-org-cache-identities-duplicates.ts
  services/apps/data_sink_worker/src/repo/organization.repo.ts
  services/apps/data_sink_worker/src/service/member.service.ts
Labels: Bug

#2161 Improve throttler for Hubspot requests
  services/libs/integrations/src/integrations/premium/hubspot/processStream.ts
Labels: Improvement
