Repository CrowdDotDev/crowd.dev, pull requests merged in 2024-02, with the labels that each got.

#2159 Ui kit checkbox
  frontend/.storybook/storybook.scss
  frontend/config/styles/components/card.scss
  frontend/config/styles/components/checkbox.scss
  frontend/config/styles/components/index.scss
  frontend/config/styles/variables/_font.scss
  frontend/config/styles/variables/index.scss
  frontend/package.json
  frontend/src/shared/ui-kit/checkbox/Checkbox.stories.ts
  frontend/src/shared/ui-kit/checkbox/Checkbox.vue
  frontend/src/shared/ui-kit/checkbox/checkbox.scss
  frontend/src/shared/ui-kit/checkbox/types/CheckboxSize.ts
  frontend/src/shared/ui-kit/index.scss
Labels: Improvement

#2163 Bug fixing profile drawers
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities-extra.vue
  frontend/src/modules/organization/components/view/_aside/_aside-identities-extra.vue
Labels: Bug

#2167 Update tenants purge script
  backend/src/bin/scripts/purge-tenants-and-data.ts
Labels: Improvement

#2174 Prevent adding empty-username identities on member update
  backend/src/database/repositories/memberRepository.ts
Labels: Bug

#2179 Ui kit input, password input, field, field message
  frontend/.eslintrc.js
  frontend/config/styles/components/field-message.scss
  frontend/config/styles/components/field.scss
  frontend/config/styles/components/index.scss
  frontend/config/styles/components/input.scss
  frontend/src/shared/ui-kit/checkbox/Checkbox.stories.ts
  frontend/src/shared/ui-kit/checkbox/Checkbox.vue
  frontend/src/shared/ui-kit/checkbox/checkbox.scss
  frontend/src/shared/ui-kit/field-message/FieldMessage.stories.ts
  frontend/src/shared/ui-kit/field-message/FieldMessage.vue
  frontend/src/shared/ui-kit/field-message/constants/fieldMessageTypeData.ts
  frontend/src/shared/ui-kit/field-message/field-message.scss
  frontend/src/shared/ui-kit/field-message/types/FieldMessageType.ts
  frontend/src/shared/ui-kit/field-messages/FieldMessages.stories.ts
  frontend/src/shared/ui-kit/field-messages/FieldMessages.vue
  frontend/src/shared/ui-kit/field/Field.stories.ts
  frontend/src/shared/ui-kit/field/Field.vue
  frontend/src/shared/ui-kit/field/field.scss
  frontend/src/shared/ui-kit/index.scss
  frontend/src/shared/ui-kit/input-password/InputPassword.stories.ts
  frontend/src/shared/ui-kit/input-password/InputPassword.vue
  frontend/src/shared/ui-kit/input/Input.stories.ts
  frontend/src/shared/ui-kit/input/Input.vue
  frontend/src/shared/ui-kit/input/input.scss
Labels: Improvement

#2180 Ui kit radio
  frontend/config/styles/components/index.scss
  frontend/config/styles/components/radio.scss
  frontend/src/shared/ui-kit/index.scss
  frontend/src/shared/ui-kit/radio/Radio.stories.ts
  frontend/src/shared/ui-kit/radio/Radio.vue
  frontend/src/shared/ui-kit/radio/radio.scss
  frontend/src/shared/ui-kit/radio/types/RadioSize.ts
Labels: Improvement

#2182 Ui kit switch
  frontend/config/styles/components/index.scss
  frontend/config/styles/components/switch.scss
  frontend/src/shared/ui-kit/index.scss
  frontend/src/shared/ui-kit/switch/Switch.stories.ts
  frontend/src/shared/ui-kit/switch/Switch.vue
  frontend/src/shared/ui-kit/switch/switch.scss
  frontend/src/shared/ui-kit/switch/types/SwitchSize.ts
Labels: Improvement

#2172 Getting `min(activity.timestamp)` for organization `joinedAt` in materialized view
  backend/src/database/migrations/R__cubejs-materialized-views.sql
Labels: Bug

#2189 Ui kit badge
  frontend/config/styles/components/badge.scss
  frontend/config/styles/components/index.scss
  frontend/src/assets/scss/index.scss
  frontend/src/ui-kit/badge/Badge.stories.ts
  frontend/src/ui-kit/badge/Badge.vue
  frontend/src/ui-kit/badge/badge.scss
  frontend/src/ui-kit/badge/types/BadgeSize.ts
  frontend/src/ui-kit/badge/types/BadgeType.ts
  frontend/src/ui-kit/button/Button.stories.ts
  frontend/src/ui-kit/button/Button.vue
  frontend/src/ui-kit/button/button.scss
  frontend/src/ui-kit/button/types/ButtonNativeType.ts
  frontend/src/ui-kit/button/types/ButtonSize.ts
  frontend/src/ui-kit/button/types/ButtonType.ts
  frontend/src/ui-kit/card/Card.stories.ts
  frontend/src/ui-kit/card/Card.vue
  frontend/src/ui-kit/card/card.scss
  frontend/src/ui-kit/checkbox/Checkbox.stories.ts
  frontend/src/ui-kit/checkbox/Checkbox.vue
  frontend/src/ui-kit/checkbox/checkbox.scss
  frontend/src/ui-kit/checkbox/types/CheckboxSize.ts
  frontend/src/ui-kit/field-message/FieldMessage.stories.ts
  frontend/src/ui-kit/field-message/FieldMessage.vue
  frontend/src/ui-kit/field-message/constants/fieldMessageTypeData.ts
  frontend/src/ui-kit/field-message/field-message.scss
  frontend/src/ui-kit/field-message/types/FieldMessageType.ts
  frontend/src/ui-kit/field-messages/FieldMessages.stories.ts
  frontend/src/ui-kit/field-messages/FieldMessages.vue
  frontend/src/ui-kit/field/Field.stories.ts
  frontend/src/ui-kit/field/Field.vue
  frontend/src/ui-kit/field/field.scss
  frontend/src/ui-kit/index.scss
  frontend/src/ui-kit/input-password/InputPassword.stories.ts
  frontend/src/ui-kit/input-password/InputPassword.vue
  frontend/src/ui-kit/input/Input.stories.ts
  frontend/src/ui-kit/input/Input.vue
  frontend/src/ui-kit/input/input.scss
  frontend/src/ui-kit/radio/Radio.stories.ts
  frontend/src/ui-kit/radio/Radio.vue
  frontend/src/ui-kit/radio/radio.scss
  frontend/src/ui-kit/radio/types/RadioSize.ts
  frontend/src/ui-kit/switch/Switch.stories.ts
  frontend/src/ui-kit/switch/Switch.vue
  frontend/src/ui-kit/switch/switch.scss
  frontend/src/ui-kit/switch/types/SwitchSize.ts
Labels: Improvement

#2186 Fix organization updating
  frontend/src/modules/organization/components/form/organization-form-identities.vue
Labels: Bug

#2190 Ui kit spinner
  frontend/config/styles/components/index.scss
  frontend/config/styles/components/spinner.scss
  frontend/src/ui-kit/index.scss
  frontend/src/ui-kit/spinner/Spinner.stories.ts
  frontend/src/ui-kit/spinner/Spinner.vue
  frontend/src/ui-kit/spinner/spinner.scss
Labels: Improvement

#2187 Optimized organization enrichment
  backend/src/database/migrations/U1706788189__org-cache-enrichement.sql
  backend/src/database/migrations/V1706788189__org-cache-enrichement.sql
  backend/src/database/repositories/organizationCacheRepository.ts
  services/apps/premium/organizations_enrichment_worker/src/activities.ts
  services/apps/premium/organizations_enrichment_worker/src/activities/enrichment.ts
  services/apps/premium/organizations_enrichment_worker/src/activities/organizationEnrichment.ts
  services/apps/premium/organizations_enrichment_worker/src/activities/tenantUpdate.ts
  services/apps/premium/organizations_enrichment_worker/src/main.ts
  services/apps/premium/organizations_enrichment_worker/src/repos/organization.repo.ts
  services/apps/premium/organizations_enrichment_worker/src/repos/tenant.repo.ts
  services/apps/premium/organizations_enrichment_worker/src/schedules.ts
  services/apps/premium/organizations_enrichment_worker/src/schedules/organizationEnrichment.ts
  services/apps/premium/organizations_enrichment_worker/src/types/common.ts
  services/apps/premium/organizations_enrichment_worker/src/workflows.ts
  services/apps/premium/organizations_enrichment_worker/src/workflows/enrichOrganization.ts
  services/apps/premium/organizations_enrichment_worker/src/workflows/enrichOrganizationCache.ts
  services/apps/premium/organizations_enrichment_worker/src/workflows/entrichTenantOrganizations.ts
  services/apps/premium/organizations_enrichment_worker/src/workflows/triggerOrganizationCacheEnrichment.ts
  services/apps/premium/organizations_enrichment_worker/src/workflows/triggerTenantOrganizationEnrichment.ts
  services/apps/premium/organizations_enrichment_worker/src/workflows/triggerUpdateTenantOrganizations.ts
  services/apps/premium/organizations_enrichment_worker/src/workflows/updateTenantOrganization.ts
Labels: Improvement

#2192 Fix identities creation
  frontend/src/modules/member/components/form/member-form-identities.vue
Labels: Bug

#2191 fix: admin segment check in `permissionChecker`
  backend/src/services/user/permissionChecker.ts
  frontend/components.d.ts
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/store/actions.js
  frontend/src/modules/tag/components/tag-popover.vue
  frontend/src/modules/tag/tag-service.js
  frontend/src/security/permissions.js
  frontend/src/shared/axios/auth-axios.js
Labels: Bug

#2208 Add organization name and logo along with roles when returning roles within unmerge preview
  backend/src/database/repositories/memberOrganizationRepository.ts
  services/libs/types/src/organizations.ts
Labels: Improvement

#2214 Organization export
  frontend/package-lock.json
  frontend/package.json
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/organization-service.js
  frontend/src/shared/pagination/pagination-sorter.vue
Labels: Feature

#2211 Unmerge contact
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/memberService.ts
  frontend/src/assets/scss/form/select.scss
  frontend/src/modules/auth/auth-socket.js
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/member/components/member-actions.vue
  frontend/src/modules/member/components/member-dropdown-content.vue
  frontend/src/modules/member/components/member-dropdown.vue
  frontend/src/modules/member/components/member-manage-identities-drawer.vue
  frontend/src/modules/member/components/member-unmerge-dialog.vue
  frontend/src/modules/member/components/suggestions/member-merge-suggestions-details.vue
  frontend/src/modules/member/components/suggestions/member-organizations-list.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/member-service.js
  frontend/src/modules/member/pages/member-form-page.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/shared/dialog/dialog.vue
  services/apps/entity_merging_worker/src/activities/members.ts
  services/apps/entity_merging_worker/src/workflows/all.ts
  services/apps/search_sync_api/src/routes/member.ts
  services/libs/data-access-layer/src/old/apps/entity_merging_worker/index.ts
  services/libs/data-access-layer/src/old/apps/entity_merging_worker/types.ts
  services/libs/opensearch/src/apiClient.ts
  services/libs/opensearch/src/repo/member.data.ts
  services/libs/opensearch/src/repo/member.repo.ts
  services/libs/opensearch/src/service/member.sync.service.ts
  services/libs/types/src/members.ts
Labels: Feature

#2218 Unmerge preview endpoint fixes
  backend/src/database/migrations/R__cubejs-materialized-views.sql
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/memberService.ts
Labels: Bug

#2202 Checking `toMerge` member also in segments when returning merge suggestions
  backend/src/database/repositories/memberRepository.ts
Labels: Improvement

#2222 LF organization export
  frontend/package-lock.json
  frontend/package.json
  frontend/src/modules/member/components/list/member-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-table.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/organization-service.js
  frontend/src/shared/pagination/pagination-sorter.vue
Labels: Improvement

#2228 Remove oss contributions graph
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.ts
  frontend/src/modules/member/components/view/member-view-contributions-cta.vue
  frontend/src/modules/member/components/view/member-view-contributions.vue
  frontend/src/modules/member/pages/member-view-page.vue
  frontend/src/shared/pagination/pagination-sorter.vue
Labels: Improvement

#2230 fix: deduplicate memberOrgs in OpenSearch considering roles and periods
  services/libs/opensearch/src/service/member.sync.service.ts
Labels: Bug
