Repository CrowdDotDev/crowd.dev, pull requests merged in 2024-10, with the labels that each got.

#2624 Capture old and new states along with error in audit logs
  backend/src/database/migrations/U1727101659__trackErrorInAuditlogs.sql
  backend/src/database/migrations/V1727101659__trackErrorInAuditlogs.sql
  backend/src/services/memberService.ts
  services/libs/audit-logs/src/svc.ts
  services/libs/data-access-layer/src/audit_logs/repo.ts
Labels: Improvement

#2625 Refactor memberIdentities to capture audit logs
  backend/src/database/repositories/member/memberIdentityRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/member/memberIdentityService.ts
  backend/src/services/memberService.ts
Labels: Improvement

#2634 support actionType filter in auditlogs
  backend/src/database/migrations/U1728473951__auditLogsFilterIndex.sql
  backend/src/database/migrations/V1728473951__auditLogsFilterIndex.sql
  frontend/src/modules/lf/config/audit-logs/filters/action/config.ts
  frontend/src/modules/lf/config/audit-logs/filters/action/options.ts
  frontend/src/modules/lf/config/audit-logs/filters/main.ts
  services/libs/data-access-layer/src/audit_logs/repo.ts
Labels: Improvement

#2644 Success page for non direct connect
  frontend/public/images/logo/lfx.svg
  frontend/src/app.vue
  frontend/src/modules/auth/services/auth.service.ts
  frontend/src/modules/auth/store/auth.actions.ts
  frontend/src/modules/integration/integration-routes.js
  frontend/src/modules/integration/pages/integration-list-page.vue
  frontend/src/modules/integration/pages/integration-success-page.vue
  frontend/src/modules/lf/segments/pages/lf-admin-panel-page.vue
  frontend/tailwind.config.js
Labels: Improvement

#2611 Depricate chartkick
  frontend/package-lock.json
  frontend/package.json
  frontend/src/config/charts/configs/dashboard.area.chart.ts
  frontend/src/config/charts/helpers/tooltip.js
  frontend/src/config/charts/index.ts
  frontend/src/config/charts/plugins/backgroundChart.plugin.ts
  frontend/src/config/charts/plugins/updateTicksLabelsPosition.plugin.ts
  frontend/src/config/charts/plugins/verticalHoverLine.plugin.ts
  frontend/src/config/charts/plugins/verticalTodayBlock.plugin.ts
  frontend/src/main.ts
  frontend/src/modules/dashboard/components/dashboard-activities.vue
  frontend/src/modules/dashboard/components/dashboard-filters.vue
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/dashboard/components/dashboard-widget-chart.vue
  frontend/src/modules/dashboard/components/widget/widget-period.vue
  frontend/src/modules/dashboard/constants/period-constants.js
  frontend/src/modules/dashboard/store/actions.js
  frontend/src/modules/dashboard/store/mutations.js
  frontend/src/modules/dashboard/store/state.js
  frontend/src/modules/report/templates/template-chart-config.js
  frontend/src/modules/report/templates/template-chart-default-config.js
  frontend/src/modules/widget/components/shared/widget-area.vue
  frontend/src/modules/widget/components/shared/widget-empty.vue
  frontend/src/plugins/chartkick-custom-plugins.js
  frontend/src/plugins/chartkick-custom-scales.js
  frontend/src/plugins/chartkick.js
  frontend/src/plugins/index.js
  frontend/src/shared/plugins/marked.js
  frontend/src/shared/plugins/sanitize.js
  frontend/src/ui-kit/chart/Chart.vue
Labels: Improvement

#2655 Start affiliation recalculation on memberOrganization changes
  .github/workflows/CI-node.yaml
  backend/src/database/repositories/member/memberOrganizationsRepository.ts
  backend/src/services/member/memberOrganizationsService.ts
  backend/src/services/memberAffiliationService.ts
  backend/src/services/memberService.ts
  services/libs/opensearch/src/service/member.sync.service.ts
  services/libs/questdb/src/sql.ts
  services/libs/types/src/organizations.ts
Labels: Bug

#2658 Bump typescript to 5.6.3
  .github/actions/node/package.json
  backend/package.json
  pnpm-lock.yaml
  services/apps/activities_worker/package.json
  services/apps/automations_worker/package.json
  services/apps/cache_worker/package.json
  services/apps/data_sink_worker/package.json
  services/apps/emails_worker/package.json
  services/apps/entity_merging_worker/package.json
  services/apps/exports_worker/package.json
  services/apps/integration_run_worker/package.json
  services/apps/integration_stream_worker/package.json
  services/apps/integration_sync_worker/package.json
  services/apps/merge_suggestions_worker/package.json
  services/apps/premium/members_enrichment_worker/package.json
  services/apps/premium/organizations_enrichment_worker/package.json
  services/apps/profiles_worker/package.json
  services/apps/script_executor_worker/package.json
  services/apps/search_sync_api/package.json
  services/apps/search_sync_worker/package.json
  services/apps/template_consumer/package.json
  services/apps/template_worker/package.json
  services/apps/temporal_codec_server/package.json
  services/apps/webhook_api/package.json
  services/archetypes/consumer/package.json
  services/archetypes/standard/package.json
  services/archetypes/worker/package.json
  services/libs/audit-logs/package.json
  services/libs/common/package.json
  services/libs/common_services/package.json
  services/libs/conversations/package.json
  services/libs/data-access-layer/package.json
  services/libs/database/package.json
  services/libs/feature-flags/package.json
  services/libs/feature-flags/src/index.ts
  services/libs/integrations/package.json
  services/libs/logging/package.json
  services/libs/logging/src/logger.ts
  services/libs/opensearch/package.json
  services/libs/questdb/package.json
  services/libs/queue/package.json
  services/libs/redis/package.json
  services/libs/redis/src/client.ts
  services/libs/redis/src/pubsub.ts
  services/libs/sentiment/package.json
  services/libs/telemetry/package.json
  services/libs/temporal/package.json
  services/libs/tracing/package.json
  services/libs/types/package.json
Labels: Improvement

#2652 People enrichment with multiple sources
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/src/database/migrations/U1728381599__addSourceToMemberEnrichmentCache.sql
  backend/src/database/migrations/V1728381599__addSourceToMemberEnrichmentCache.sql
  backend/src/database/repositories/memberEnrichmentCacheRepository.ts
  backend/src/services/sampleDataService.ts
  pnpm-lock.yaml
  services/apps/premium/members_enrichment_worker/package.json
  services/apps/premium/members_enrichment_worker/src/activities.ts
  services/apps/premium/members_enrichment_worker/src/activities/enrichment.ts
  services/apps/premium/members_enrichment_worker/src/activities/getEnrichmentData.ts
  services/apps/premium/members_enrichment_worker/src/activities/getMembers.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/authenticateLFAuth0.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/getEnrichmentLFAuth0.ts
  services/apps/premium/members_enrichment_worker/src/activities/lf-auth0/githubIdentities.ts
  services/apps/premium/members_enrichment_worker/src/activities/normalizeEnrichedMember.ts
  services/apps/premium/members_enrichment_worker/src/factory.ts
  services/apps/premium/members_enrichment_worker/src/main.ts
  services/apps/premium/members_enrichment_worker/src/schedules/getMembersToEnrich.ts
  services/apps/premium/members_enrichment_worker/src/sources/clearbit/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/clearbit/types.ts
  services/apps/premium/members_enrichment_worker/src/sources/lfid/types.ts
  services/apps/premium/members_enrichment_worker/src/sources/progai/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/progai/types.ts
  services/apps/premium/members_enrichment_worker/src/types.ts
  services/apps/premium/members_enrichment_worker/src/types/enrichment.ts
  services/apps/premium/members_enrichment_worker/src/utils/common.ts
  services/apps/premium/members_enrichment_worker/src/utils/normalize.ts
  services/apps/premium/members_enrichment_worker/src/workflows/enrichMember.ts
  services/apps/premium/members_enrichment_worker/src/workflows/getMembersToEnrich.ts
  services/apps/premium/members_enrichment_worker/src/workflows/lf-auth0/enrichMemberWithLFAuth0.ts
  services/apps/premium/members_enrichment_worker/src/workflows/lf-auth0/findAndSaveGithubSourceIds.ts
  services/apps/premium/members_enrichment_worker/src/workflows/lf-auth0/getEnrichmentData.ts
  services/apps/premium/members_enrichment_worker/src/workflows/lf-auth0/getMembersForLFIDEnrichment.ts
  services/libs/data-access-layer/src/old/apps/premium/members_enrichment_worker/index.ts
  services/libs/data-access-layer/src/old/apps/premium/members_enrichment_worker/normalize.ts
  services/libs/types/src/enums/enrichment.ts
  services/libs/types/src/enums/index.ts
  services/libs/types/src/enums/members.ts
  services/libs/types/src/enums/organizations.ts
  services/libs/types/src/enums/platforms.ts
  services/libs/types/src/index.ts
  services/libs/types/src/members.ts
  services/libs/types/src/premium/enrichment.ts
  services/libs/types/src/premium/index.ts
Labels: Feature

#2659 Fix logical error in `fetchMembersForEnrichment`
  services/libs/data-access-layer/src/old/apps/premium/members_enrichment_worker/index.ts
Labels: Bug

#2664 Serp linkedin finder enrichment source
  services/apps/premium/members_enrichment_worker/src/activities.ts
  services/apps/premium/members_enrichment_worker/src/activities/getMembers.ts
  services/apps/premium/members_enrichment_worker/src/factory.ts
  services/apps/premium/members_enrichment_worker/src/main.ts
  services/apps/premium/members_enrichment_worker/src/sources/clearbit/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/progai/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/serp/service.ts
  services/apps/premium/members_enrichment_worker/src/sources/serp/tests.ts
  services/apps/premium/members_enrichment_worker/src/sources/serp/types.ts
  services/apps/premium/members_enrichment_worker/src/types.ts
  services/apps/premium/members_enrichment_worker/src/workflows/enrichMember.ts
  services/apps/premium/members_enrichment_worker/src/workflows/getMembersToEnrich.ts
  services/libs/data-access-layer/src/old/apps/premium/members_enrichment_worker/index.ts
  services/libs/types/src/enums/enrichment.ts
  services/libs/types/src/premium/enrichment.ts
Labels: Feature
