Repository CrowdDotDev/crowd.dev, pull requests merged in 2024-06, with the labels that each got.

#2445 Organization LF membership UI
  frontend/src/modules/activity/components/activity-header.vue
  frontend/src/modules/activity/config/filters/organizations/OrganizationsFilter.vue
  frontend/src/modules/activity/config/filters/organizations/config.ts
  frontend/src/modules/dashboard/components/organization/dashboard-organization-item.vue
  frontend/src/modules/member/components/member-organizations-vertical.vue
  frontend/src/modules/member/components/member-organizations.vue
  frontend/src/modules/member/components/view/_aside/_aside-organizations.vue
  frontend/src/modules/member/config/filters/organizations/OrganizationsFilter.vue
  frontend/src/modules/member/config/filters/organizations/config.ts
  frontend/src/modules/organization/components/lf-member/organization-lf-member-tag.vue
  frontend/src/modules/organization/components/list/organization-list-toolbar.vue
  frontend/src/modules/organization/components/organization-name.vue
  frontend/src/modules/organization/components/organization-selection-dropdown.vue
  frontend/src/modules/organization/components/suggestions/organization-merge-suggestions-details.vue
  frontend/src/modules/organization/components/view/organization-view-header.vue
  frontend/src/modules/organization/config/filters/lfxMembership/config.ts
  frontend/src/modules/organization/config/filters/main.ts
  frontend/src/modules/organization/config/filters/organizations/OrganizationsFilter.vue
  frontend/src/modules/organization/config/filters/organizations/config.ts
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
  frontend/src/modules/organization/types/Organization.ts
  frontend/src/shared/form/autocomplete-one-input.vue
  frontend/src/shared/modules/activity/components/activity-member-organization.vue
Labels: Feature

#2446 Avatar theme component
  frontend/config/styles/components/avatar.scss
  frontend/config/styles/components/index.scss
  frontend/src/ui-kit/avatar/Avatar.stories.ts
  frontend/src/ui-kit/avatar/Avatar.vue
  frontend/src/ui-kit/avatar/avatar.scss
  frontend/src/ui-kit/index.scss
Labels: Improvement

#2461 Handle unverified identities on unmerge
  backend/src/services/memberService.ts
  backend/src/services/organizationService.ts
Labels: Bug

#2425 Batch fetch merge actions when dissecting
  backend/src/database/repositories/memberRepository.ts
  backend/src/services/memberService.ts
  services/apps/script_executor_worker/src/activities.ts
  services/apps/script_executor_worker/src/activities/common.ts
  services/apps/script_executor_worker/src/activities/dissect-member/index.ts
  services/apps/script_executor_worker/src/types.ts
  services/apps/script_executor_worker/src/workflows/dissectMember.ts
  services/libs/data-access-layer/src/member_identities/index.ts
  services/libs/data-access-layer/src/old/apps/script_executor_worker/member.repo.ts
  services/libs/data-access-layer/src/old/apps/script_executor_worker/mergeAction.repo.ts
  services/libs/data-access-layer/src/old/apps/script_executor_worker/types.ts
Labels: Improvement

#2469 Fix error message for existing identity
  frontend/src/modules/contributor/components/details/contributor-details-actions.vue
  frontend/src/modules/member/components/member-manage-identities-drawer.vue
  frontend/src/modules/member/pages/member-form-page.vue
Labels: Bug

#2473 Prevent redundant identity updates on organization merging
  backend/src/services/organizationService.ts
Labels: Bug

#2479 Missing indexes for performant LLM agent queries
  backend/src/database/migrations/U1718871280__missingIndexesForLLMQueries.sql
  backend/src/database/migrations/V1718871280__missingIndexesForLLMQueries.sql
Labels: Improvement

#2483 Remove redundant Opensearch syncs when ignoring suggestions
  backend/src/services/memberService.ts
Labels: Improvement

#2484 Org merge suggestion improvements
  services/apps/merge_suggestions_worker/src/activities/organizationMergeSuggestions.ts
  services/apps/merge_suggestions_worker/src/types.ts
  services/apps/merge_suggestions_worker/src/workflows/generateOrganizationMergeSuggestions.ts
  services/libs/data-access-layer/src/orgs/index.ts
Labels: Improvement

#2475 Using organization findAndCountAll in existing transaction
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#2478 Return # of activities per project in contributor's payload
  backend/src/database/repositories/memberRepository.ts
Labels: Improvement

#2485 Contributor & Organization name and avatar editing
  frontend/config/styles/components/field-message.scss
  frontend/config/styles/components/field.scss
  frontend/src/modules/contributor/components/details/contributor-details-header.vue
  frontend/src/modules/contributor/components/details/header/contributor-details-header-profile-photo.vue
  frontend/src/modules/contributor/components/edit/contributor-edit-name.vue
  frontend/src/modules/contributor/components/edit/contributor-edit-profile-photo.vue
  frontend/src/modules/contributor/pages/contributor-details.page.vue
  frontend/src/modules/contributor/services/contributor.api.service.ts
  frontend/src/modules/contributor/store/contributor.actions.ts
  frontend/src/modules/contributor/store/contributor.getters.ts
  frontend/src/modules/contributor/store/contributor.state.ts
  frontend/src/modules/contributor/store/contributor.store.ts
  frontend/src/modules/organization/components/details/header/organization-details-header-logo.vue
  frontend/src/modules/organization/components/details/organization-details-header.vue
  frontend/src/modules/organization/components/edit/organization-edit-logo.vue
  frontend/src/modules/organization/components/edit/organization-edit-name.vue
  frontend/src/modules/organization/pages/organization-details.page.vue
  frontend/src/modules/organization/store/pinia/actions.ts
  frontend/src/ui-kit/avatar/Avatar.vue
  frontend/src/ui-kit/avatar/avatar.scss
  frontend/src/ui-kit/contenteditable/Contenteditable.stories.ts
  frontend/src/ui-kit/contenteditable/Contenteditable.vue
  frontend/src/ui-kit/field/field.scss
  frontend/src/ui-kit/img/Img.vue
  frontend/src/ui-kit/index.scss
  frontend/src/ui-kit/modal/Modal.stories.ts
  frontend/src/ui-kit/modal/Modal.vue
  frontend/src/ui-kit/modal/modal.scss
Labels: Improvement

#2489 Organization domains fixes
  frontend/src/modules/contributor/components/details/contributor-details-emails.vue
  frontend/src/modules/contributor/components/details/header/contributor-details-header-profile-photo.vue
  frontend/src/modules/contributor/components/details/overview/contributor-details-attributes.vue
  frontend/src/modules/contributor/components/edit/contributor-edit-name.vue
  frontend/src/modules/contributor/components/shared/contributor-dropdown.vue
  frontend/src/modules/contributor/pages/contributor-details.page.vue
  frontend/src/modules/contributor/types/Contributor.ts
  frontend/src/modules/member/components/form/email/member-form-email-item.vue
  frontend/src/modules/member/components/form/identity/member-form-identity-item.vue
  frontend/src/modules/member/components/member-manage-emails-drawer.vue
  frontend/src/modules/member/components/member-unmerge-dialog.vue
  frontend/src/modules/member/components/view/member-view-aside.vue
  frontend/src/modules/member/member-service.js
  frontend/src/modules/organization/components/details/header/organization-details-header-profiles.vue
  frontend/src/modules/organization/components/details/organization-details-domains.vue
  frontend/src/modules/organization/components/details/organization-details-emails.vue
  frontend/src/modules/organization/components/edit/organization-edit-name.vue
  frontend/src/modules/organization/components/form/email/organization-form-email-item.vue
  frontend/src/modules/organization/components/form/identity/organization-form-identity-item.vue
  frontend/src/modules/organization/components/organization-manage-domains-drawer.vue
  frontend/src/modules/organization/components/organization-manage-emails-drawer.vue
  frontend/src/modules/organization/components/organization-unmerge-dialog.vue
  frontend/src/modules/organization/components/shared/organization-dropdown.vue
  frontend/src/modules/organization/helpers/organization.helpers.ts
  frontend/src/modules/organization/organization-service.js
  frontend/src/modules/organization/pages/organization-details.page.vue
  frontend/src/shared/modules/platform/types/Platform.ts
Labels: Improvement
