Repository CrowdDotDev/crowd.dev, pull requests merged in 2024-05, with the labels that each got.

#2392 Add help button to lfx header
  frontend/src/app.vue
  frontend/src/modules/auth/store/auth.actions.ts
Labels: Feature

#2397 Add distinct emails to list count and fix showmore
  frontend/src/modules/member/components/list/columns/member-list-emails.vue
  frontend/src/modules/member/components/view/_aside/_aside-identities-extra.vue
Labels: Improvement

#2396 Bugfix/reduce number of docs synced bulk
  services/libs/opensearch/src/service/member.sync.service.ts
  services/libs/opensearch/src/service/organization.sync.service.ts
Labels: Bug

#2387 Integrations only allow lowercase identity values
  services/apps/data_sink_worker/src/service/member.service.ts
  services/apps/data_sink_worker/src/service/organization.service.ts
  services/libs/common/src/websiteNormalizer.ts
  services/libs/data-access-layer/src/old/apps/data_sink_worker/repo/member.repo.ts
  services/libs/data-access-layer/src/old/apps/data_sink_worker/repo/organization.repo.ts
Labels: Improvement

#2391 Script executor temporal worker & similar identities merger workflows
  pnpm-lock.yaml
  scripts/builders/script-executor-worker.env
  scripts/services/docker/Dockerfile.script_executor_worker
  scripts/services/docker/Dockerfile.script_executor_worker.dockerignore
  services/apps/script_executor_worker/package.json
  services/apps/script_executor_worker/src/activities.ts
  services/apps/script_executor_worker/src/activities/common.ts
  services/apps/script_executor_worker/src/activities/merge-members-with-similar-identities/index.ts
  services/apps/script_executor_worker/src/main.ts
  services/apps/script_executor_worker/src/types.ts
  services/apps/script_executor_worker/src/workflows.ts
  services/apps/script_executor_worker/src/workflows/findAndMergeMembersWithSamePlatformIdentitiesDifferentCapitalization.ts
  services/apps/script_executor_worker/src/workflows/findAndMergeMembersWithSameVerifiedEmailsInDifferentPlatforms.ts
  services/apps/script_executor_worker/tsconfig.json
  services/libs/data-access-layer/src/old/apps/script_executor_worker/member.repo.ts
  services/libs/data-access-layer/src/old/apps/script_executor_worker/types.ts
Labels: Feature

#2401 Bulk github repo mapping
  frontend/src/integrations/github/components/github-settings-bulk-select.vue
  frontend/src/integrations/github/components/github-settings-drawer.vue
Labels: Improvement

#2409 Data sink worker optimizations
  services/apps/data_sink_worker/src/queue/index.ts
  services/apps/data_sink_worker/src/service/activity.service.ts
  services/libs/sqs/src/client.ts
  services/libs/sqs/src/queue.ts
Labels: Improvement

#2411 Typo in suggestions query for unverified identities
  services/apps/merge_suggestions_worker/src/activities/memberMergeSuggestions.ts
Labels: Bug

#2417 Entity merging worker finishUnmergeMember fixes and improvements
  backend/src/services/memberService.ts
  services/apps/entity_merging_worker/src/activities/members.ts
  services/apps/entity_merging_worker/src/workflows/all.ts
  services/libs/data-access-layer/src/old/apps/entity_merging_worker/index.ts
  services/libs/types/src/members.ts
Labels: Bug, Improvement

#2420 Remove cube
  frontend/.env.dist.local
  frontend/package-lock.json
  frontend/package.json
  frontend/src/modules/dashboard/components/activity/dashboard-activity-sentiment.vue
  frontend/src/modules/dashboard/components/activity/dashboard-activity-types.vue
  frontend/src/modules/dashboard/components/dashboard-activities.vue
  frontend/src/modules/dashboard/components/dashboard-members.vue
  frontend/src/modules/dashboard/components/dashboard-organizations.vue
  frontend/src/modules/dashboard/components/dashboard-widget-chart.vue
  frontend/src/modules/dashboard/services/dashboard.api.service.ts
  frontend/src/modules/dashboard/store/actions.js
  frontend/src/modules/dashboard/store/getters.js
  frontend/src/modules/dashboard/store/state.js
  frontend/src/modules/dashboard/types/DashboardChartData.ts
  frontend/src/modules/report/report-charts.js
  frontend/src/modules/widget/components/shared/widget-area.vue
Labels: Improvement

#2419 Add actionBy to merge actions
  backend/src/database/migrations/U1716470828__addActionByToMergeActions.sql
  backend/src/database/migrations/V1716470828__addActionByToMergeActions.sql
  backend/src/database/repositories/mergeActionsRepository.ts
Labels: Improvement

#2422 Dissect member workflow for untangling wrongly merged members
  services/apps/script_executor_worker/src/activities.ts
  services/apps/script_executor_worker/src/activities/common.ts
  services/apps/script_executor_worker/src/activities/dissect-member/index.ts
  services/apps/script_executor_worker/src/main.ts
  services/apps/script_executor_worker/src/types.ts
  services/apps/script_executor_worker/src/workflows.ts
  services/apps/script_executor_worker/src/workflows/dissectMember.ts
  services/libs/data-access-layer/src/old/apps/entity_merging_worker/index.ts
  services/libs/data-access-layer/src/old/apps/script_executor_worker/mergeAction.repo.ts
  services/libs/data-access-layer/src/old/apps/script_executor_worker/types.ts
Labels: Improvement

#2410 use bulkRemove for OpenSearch index cleanup
  services/libs/opensearch/src/service/member.sync.service.ts
  services/libs/opensearch/src/service/opensearch.service.ts
  services/libs/opensearch/src/service/organization.sync.service.ts
Labels: Improvement

#2311 Optimize `sync-all-*` scripts with read and write host
  services/apps/search_sync_worker/src/bin/sync-all-organizations.ts
  services/libs/opensearch/src/repo/organization.repo.ts
  services/libs/opensearch/src/service/organization.sync.service.ts
Labels: Improvement

#2418 Store product data in new pg db and create endpoints
  backend/.env.dist.composed
  backend/.env.dist.local
  backend/config/custom-environment-variables.json
  backend/package.json
  backend/src/api/index.ts
  backend/src/api/product/index.ts
  backend/src/api/product/productEventCreate.ts
  backend/src/api/product/productSessionCreate.ts
  backend/src/api/product/productSessionUpdate.ts
  backend/src/conf/index.ts
  backend/src/database/repositories/IRepositoryOptions.ts
  backend/src/database/repositories/sequelizeRepository.ts
  backend/src/database/utils/sequelizeTestUtils.ts
  backend/src/middlewares/productDbMiddleware.ts
  backend/src/product/Dockerfile.flyway
  backend/src/product/flyway_migrate.sh
  backend/src/product/migrations/U1716389909__init.sql
  backend/src/product/migrations/V1716389909__init.sql
  backend/src/services/IServiceOptions.ts
  backend/src/services/productAnalyticsService.ts
  pnpm-lock.yaml
  scripts/cli
  scripts/scaffold.yaml
  services/libs/data-access-layer/src/productAnalytics/index.ts
  services/libs/types/src/index.ts
  services/libs/types/src/productAnalytics.ts
Labels: Feature

#2399 Raw suggestion tables without confidence filter for LLM consumption
  backend/src/database/migrations/U1715071755__rawSuggestionTables.sql
  backend/src/database/migrations/V1715071755__rawSuggestionTables.sql
  services/apps/merge_suggestions_worker/src/activities/memberMergeSuggestions.ts
  services/apps/merge_suggestions_worker/src/activities/organizationMergeSuggestions.ts
  services/apps/merge_suggestions_worker/src/workflows/generateMemberMergeSuggestions.ts
  services/apps/merge_suggestions_worker/src/workflows/generateOrganizationMergeSuggestions.ts
  services/libs/data-access-layer/src/old/apps/merge_suggestions_worker/memberMergeSuggestions.repo.ts
  services/libs/data-access-layer/src/old/apps/merge_suggestions_worker/organizationMergeSuggestions.repo.ts
  services/libs/types/src/enums/index.ts
  services/libs/types/src/enums/suggestions.ts
Labels: Feature

#2431 only try adding suggestions when array is not empty
  services/apps/merge_suggestions_worker/src/activities/memberMergeSuggestions.ts
  services/apps/merge_suggestions_worker/src/activities/organizationMergeSuggestions.ts
Labels: Bug

#2435 Typography alignment
  frontend/.tailwind/colorConverter.js
  frontend/config/styles/index.scss
  frontend/config/styles/utilities/_colors.scss
  frontend/config/styles/utilities/index.scss
  frontend/config/styles/variables/_colors.scss
  frontend/config/styles/variables/_font.scss
  frontend/config/styles/variables/_typography.scss
  frontend/config/styles/variables/index.scss
  frontend/src/assets/scss/typography.scss
  frontend/src/modules/auth/auth.socket.ts
  frontend/src/modules/dashboard/components/dashboard-integrations.vue
  frontend/src/modules/dashboard/pages/dashboard-page.vue
  frontend/tailwind.config.js
Labels: Improvement

#2437 Button theme component
  frontend/config/styles/components/button.scss
  frontend/src/modules/integration/components/integration-list-item.vue
  frontend/src/modules/lf/segments/components/logs/sections/log-json.vue
  frontend/src/modules/lf/segments/pages/lf-audit-logs-page.vue
  frontend/src/modules/member/components/form/email/member-form-email-item.vue
  frontend/src/modules/member/components/form/identity/member-form-identity-item.vue
  frontend/src/modules/member/components/form/member-form-emails.vue
  frontend/src/modules/member/components/form/member-form-identities.vue
  frontend/src/modules/member/components/member-merge-suggestions-dialog.vue
  frontend/src/modules/member/components/suggestions/filters/merge-suggestions-confidence-filter.vue
  frontend/src/modules/member/components/suggestions/filters/merge-suggestions-projects-filter.vue
  frontend/src/modules/member/pages/member-merge-suggestions-page.vue
  frontend/src/modules/organization/components/form/email/organization-form-email-item.vue
  frontend/src/modules/organization/components/form/identity/organization-form-identity-item.vue
  frontend/src/modules/organization/components/list/organization-common-list-table.vue
  frontend/src/modules/organization/components/organization-merge-suggestions-dialog.vue
  frontend/src/modules/organization/pages/organization-merge-suggestions-page.vue
  frontend/src/ui-kit/badge/Badge.stories.ts
  frontend/src/ui-kit/button/Button.stories.ts
  frontend/src/ui-kit/button/button.scss
  frontend/src/ui-kit/button/types/ButtonType.ts
  frontend/src/ui-kit/card/Card.stories.ts
  frontend/src/ui-kit/checkbox/Checkbox.stories.ts
  frontend/src/ui-kit/dropdown/Dropdown.stories.ts
  frontend/src/ui-kit/dropdown/DropdownItem.stories.ts
  frontend/src/ui-kit/field-message/FieldMessage.stories.ts
  frontend/src/ui-kit/field-messages/FieldMessages.stories.ts
  frontend/src/ui-kit/field/Field.stories.ts
  frontend/src/ui-kit/input-password/InputPassword.stories.ts
  frontend/src/ui-kit/input/Input.stories.ts
  frontend/src/ui-kit/radio/Radio.stories.ts
  frontend/src/ui-kit/spinner/Spinner.stories.ts
  frontend/src/ui-kit/switch/Switch.stories.ts
  frontend/src/ui-kit/table/Table.stories.ts
Labels: Improvement

#2439 Tabs theme component
  frontend/config/styles/components/index.scss
  frontend/config/styles/components/tabs.scss
  frontend/config/styles/variables/_shadows.scss
  frontend/src/ui-kit/index.scss
  frontend/src/ui-kit/tabs/Tab.vue
  frontend/src/ui-kit/tabs/Tabs.stories.ts
  frontend/src/ui-kit/tabs/Tabs.vue
  frontend/src/ui-kit/tabs/tabs.scss
  frontend/src/ui-kit/tabs/types/TabsSize.ts
Labels: Improvement

#2443 Unmerge checks organization existence before restoring the role
  backend/src/services/memberService.ts
  services/libs/data-access-layer/src/old/apps/entity_merging_worker/index.ts
Labels: Bug
