Repository CrowdDotDev/crowd.dev, pull requests merged in 2025-09, with the labels that each got.

#3343 feat: maintainer service implementation in git-integration-v2
  backend/src/database/migrations/U1756301737__addLastMaintainerRunAt.sql
  backend/src/database/migrations/U1756301963__addMaintainerFile.sql
  backend/src/database/migrations/U1756387524__addMaintainersFields.sql
  backend/src/database/migrations/U1756671476__createServiceExecutionsTable.sql
  backend/src/database/migrations/V1756301737__addLastMaintainerRunAt.sql
  backend/src/database/migrations/V1756301963__addMaintainerFile.sql
  backend/src/database/migrations/V1756387524__addMaintainersFields.sql
  backend/src/database/migrations/V1756671476__createServiceExecutionsTable.sql
  scripts/builders/git-integration.env
  scripts/services/docker/Dockerfile.git_integration
  services/apps/git_integration/pyproject.toml
  services/apps/git_integration/src/crowdgit/__init__.py
  services/apps/git_integration/src/crowdgit/activity.py
  services/apps/git_integration/src/crowdgit/database/crud.py
  services/apps/git_integration/src/crowdgit/enums.py
  services/apps/git_integration/src/crowdgit/errors.py
  services/apps/git_integration/src/crowdgit/get_bad_commits.py
  services/apps/git_integration/src/crowdgit/get_remotes.py
  services/apps/git_integration/src/crowdgit/ingest.py
  services/apps/git_integration/src/crowdgit/maintainers.py
  services/apps/git_integration/src/crowdgit/models/maintainer_info.py
  services/apps/git_integration/src/crowdgit/models/repository.py
  services/apps/git_integration/src/crowdgit/models/service_execution.py
  services/apps/git_integration/src/crowdgit/repo.py
  services/apps/git_integration/src/crowdgit/server.py
  services/apps/git_integration/src/crowdgit/server_deprecated.py
  services/apps/git_integration/src/crowdgit/services/__init__.py
  services/apps/git_integration/src/crowdgit/services/clone/clone_service.py
  services/apps/git_integration/src/crowdgit/services/commit/commit_service.py
  services/apps/git_integration/src/crowdgit/services/maintainer/bedrock.py
  services/apps/git_integration/src/crowdgit/services/maintainer/cm_database.py
  services/apps/git_integration/src/crowdgit/services/maintainer/enums.py
  services/apps/git_integration/src/crowdgit/services/maintainer/maintainer_service.py
  services/apps/git_integration/src/crowdgit/services/maintainer/process_maintainers.py
  services/apps/git_integration/src/crowdgit/services/maintainer/scraper.py
  services/apps/git_integration/src/crowdgit/services/software_value/config.go
  services/apps/git_integration/src/crowdgit/services/software_value/go.mod
  services/apps/git_integration/src/crowdgit/services/software_value/main.go
  services/apps/git_integration/src/crowdgit/services/software_value/software_value_service.py
  services/apps/git_integration/src/crowdgit/services/software_value/types.go
  services/apps/git_integration/src/crowdgit/services/utils.py
  services/apps/git_integration/src/crowdgit/settings.py
  services/apps/git_integration/src/crowdgit/worker/repository_worker.py
  services/apps/git_integration/uv.lock
Labels: Feature

#3285 feat: git integration commit service
  backend/.env.dist.composed
  backend/src/database/migrations/U1754395778__addSegmentAndIntegrationToRepositories.sql
  backend/src/database/migrations/U1754406504__deleteRepositoryIntegrations.sql
  backend/src/database/migrations/U1756301737__addLastMaintainerRunAt.sql
  backend/src/database/migrations/U1756301963__addMaintainerFile.sql
  backend/src/database/migrations/U1756387524__addMaintainersFields.sql
  backend/src/database/migrations/U1756671476__createServiceExecutionsTable.sql
  backend/src/database/migrations/V1754395778__addSegmentAndIntegrationToRepositories.sql
  backend/src/database/migrations/V1754406504__deleteRepositoryIntegrations.sql
  backend/src/database/migrations/V1756301737__addLastMaintainerRunAt.sql
  backend/src/database/migrations/V1756301963__addMaintainerFile.sql
  backend/src/database/migrations/V1756387524__addMaintainersFields.sql
  backend/src/database/migrations/V1756671476__createServiceExecutionsTable.sql
  scripts/builders/git-integration.env
  scripts/services/docker/Dockerfile.git_integration
  services/apps/git_integration/pyproject.toml
  services/apps/git_integration/src/crowdgit/__init__.py
  services/apps/git_integration/src/crowdgit/activity.py
  services/apps/git_integration/src/crowdgit/database/connection.py
  services/apps/git_integration/src/crowdgit/database/crud.py
  services/apps/git_integration/src/crowdgit/database/registry.py
  services/apps/git_integration/src/crowdgit/enums.py
  services/apps/git_integration/src/crowdgit/errors.py
  services/apps/git_integration/src/crowdgit/get_bad_commits.py
  services/apps/git_integration/src/crowdgit/get_remotes.py
  services/apps/git_integration/src/crowdgit/ingest.py
  services/apps/git_integration/src/crowdgit/maintainers.py
  services/apps/git_integration/src/crowdgit/models/clone_batch.py
  services/apps/git_integration/src/crowdgit/models/maintainer_info.py
  services/apps/git_integration/src/crowdgit/models/repository.py
  services/apps/git_integration/src/crowdgit/models/service_execution.py
  services/apps/git_integration/src/crowdgit/repo.py
  services/apps/git_integration/src/crowdgit/server.py
  services/apps/git_integration/src/crowdgit/server_deprecated.py
  services/apps/git_integration/src/crowdgit/services/__init__.py
  services/apps/git_integration/src/crowdgit/services/base/base_service.py
  services/apps/git_integration/src/crowdgit/services/clone/clone_service.py
  services/apps/git_integration/src/crowdgit/services/commit/activitymap.py
  services/apps/git_integration/src/crowdgit/services/commit/commit_service.py
  services/apps/git_integration/src/crowdgit/services/maintainer/bedrock.py
  services/apps/git_integration/src/crowdgit/services/maintainer/cm_database.py
  services/apps/git_integration/src/crowdgit/services/maintainer/enums.py
  services/apps/git_integration/src/crowdgit/services/maintainer/maintainer_service.py
  services/apps/git_integration/src/crowdgit/services/maintainer/process_maintainers.py
  services/apps/git_integration/src/crowdgit/services/maintainer/scraper.py
  services/apps/git_integration/src/crowdgit/services/queue/queue_service.py
  services/apps/git_integration/src/crowdgit/services/software_value/config.go
  services/apps/git_integration/src/crowdgit/services/software_value/go.mod
  services/apps/git_integration/src/crowdgit/services/software_value/main.go
  services/apps/git_integration/src/crowdgit/services/software_value/software_value_service.py
  services/apps/git_integration/src/crowdgit/services/software_value/types.go
  services/apps/git_integration/src/crowdgit/services/utils.py
  services/apps/git_integration/src/crowdgit/settings.py
  services/apps/git_integration/src/crowdgit/worker/repository_worker.py
  services/apps/git_integration/uv.lock
Labels: Feature

#3370 fix: add support for extracted activities in git integration v2
  services/apps/git_integration/src/crowdgit/services/commit/commit_service.py
  services/apps/git_integration/src/crowdgit/settings.py
Labels: Bug

#3377 fix: kafka connection config in git integration v2
  services/apps/git_integration/src/crowdgit/services/queue/queue_service.py
Labels: Bug

#3378 fix: on conflict constraint
  services/apps/git_integration/src/crowdgit/database/crud.py
Labels: Bug

#3397 fix: country_mapping_ds datasource placed in wrong directory
  services/libs/tinybird/datasources/country_mapping_ds.datasource
Labels: Bug

#3383 fix: persist primary organization even if role changes in affiliations
  services/libs/data-access-layer/src/member-organization-affiliation/index.ts
Labels: Bug

#3368 feat: add pipe for fetching the activities
  backend/src/database/repositories/activityRepository.ts
  backend/src/database/repositories/memberRepository.ts
  backend/src/database/repositories/organizationRepository.ts
  backend/src/services/activityService.ts
  pnpm-lock.yaml
  services/libs/data-access-layer/src/activities/sql.ts
  services/libs/data-access-layer/src/activities/tinybirdAdapter.ts
  services/libs/data-access-layer/src/members/base.ts
  services/libs/data-access-layer/src/organizations/organizations.ts
  services/libs/database/package.json
  services/libs/database/src/index.ts
  services/libs/database/src/tinybirdClient.ts
  services/libs/integrations/src/integrations/activityDisplayService.ts
  services/libs/tinybird/pipes/activities_relations_filtered.pipe
Labels: Improvement

#3434 feat: remove default filters
  frontend/src/modules/activity/store/constants.js
Labels: Improvement
