Repository CrowdDotDev/crowd.dev, pull requests merged in 2025-01, with the labels that each got.

#2738 Allow to open contributor in new tab from Identities table cells
  frontend/src/modules/member/components/list/member-list-table.vue
Labels: Bug

#2746 Remove tenants [cache-worker]
  backend/src/services/dashboardService.ts
  services/apps/cache_worker/src/activities.ts
  services/apps/cache_worker/src/activities/dashboard-cache/refreshDashboardCache.ts
  services/apps/cache_worker/src/activities/getSegmentInfo.ts
  services/apps/cache_worker/src/activities/getTenantSegmentInfo.ts
  services/apps/cache_worker/src/schedules/refreshDashboardCacheDaily.ts
  services/apps/cache_worker/src/workflows.ts
  services/apps/cache_worker/src/workflows/refreshDashboardCache.ts
  services/apps/cache_worker/src/workflows/spawnDashboardCacheRefresh.ts
  services/apps/cache_worker/src/workflows/spawnDashboardCacheRefreshForAllTenants.ts
  services/libs/data-access-layer/src/activities/sql.ts
  services/libs/data-access-layer/src/activities/types.ts
  services/libs/data-access-layer/src/members/dashboard.ts
  services/libs/data-access-layer/src/members/types.ts
  services/libs/data-access-layer/src/old/apps/cache_worker/activity.repo.ts
  services/libs/data-access-layer/src/old/apps/cache_worker/integration.repo.ts
  services/libs/data-access-layer/src/old/apps/cache_worker/segment.repo.ts
  services/libs/data-access-layer/src/old/apps/cache_worker/tenant.repo.ts
  services/libs/data-access-layer/src/old/apps/cache_worker/types.ts
  services/libs/data-access-layer/src/organizations/organizations.ts
  services/libs/types/src/dashboard/index.ts
  services/libs/types/src/temporal/cache.ts
Labels: Improvement

#2756 Remove tenants [profiles worker]
  services/apps/profiles_worker/src/activities.ts
  services/apps/profiles_worker/src/activities/common.ts
  services/apps/profiles_worker/src/main.ts
  services/apps/profiles_worker/src/schedules/triggerRecalculateAffiliationsOfNewRoles.ts
  services/apps/profiles_worker/src/types/member.ts
  services/apps/profiles_worker/src/types/organization.ts
  services/apps/profiles_worker/src/workflows.ts
  services/apps/profiles_worker/src/workflows/member/recalculateAffiliationsForNewRoles.ts
  services/apps/profiles_worker/src/workflows/member/triggerRecalculateAffiliations.ts
  services/apps/profiles_worker/src/workflows/member/triggerRecalculateAffiliationsForEachTenant.ts
  services/libs/data-access-layer/src/old/apps/profiles_worker/index.ts
Labels: Improvement

#2747 Remove tenants [activities-worker]
  services/apps/activities_worker/src/activities/createConversations.ts
  services/libs/data-access-layer/src/conversations/sql.ts
  services/libs/data-access-layer/src/conversations/types.ts
Labels: Improvement

#2724 Affiliation overrides
  backend/src/api/member/affiliation/index.ts
  backend/src/api/member/affiliation/memberAffiliationChangeOverride.ts
  backend/src/database/migrations/U1733930025__memberOrganizationAffiliationOverrides.sql
  backend/src/database/migrations/V1733930025__memberOrganizationAffiliationOverrides.sql
  backend/src/database/repositories/member/memberOrganizationAffiliationOverridesRepository.ts
  backend/src/database/repositories/member/memberOrganizationsRepository.ts
  backend/src/services/member/memberAffiliationsService.ts
  frontend/src/modules/contributor/components/details/contributor-details-work-history.vue
  frontend/src/modules/contributor/components/details/work-history/contributor-details-work-history-item.vue
  frontend/src/modules/contributor/components/edit/work-history/contributor-work-history-edit.vue
  frontend/src/modules/contributor/pages/contributor-details.page.vue
  frontend/src/modules/contributor/services/contributor.affiliations.api.service.ts
  frontend/src/modules/organization/types/Organization.ts
  frontend/src/ui-kit/index.scss
  frontend/src/ui-kit/timeline/Timeline.vue
  frontend/src/ui-kit/timeline/TimelineItem.vue
  frontend/src/ui-kit/timeline/timeline.scss
  services/apps/data_sink_worker/src/service/memberAffiliation.service.ts
  services/libs/common/src/timing.ts
  services/libs/data-access-layer/src/member_organization_affiliation_overrides/index.ts
  services/libs/data-access-layer/src/old/apps/data_sink_worker/repo/memberAffiliation.data.ts
  services/libs/data-access-layer/src/old/apps/data_sink_worker/repo/memberAffiliation.repo.ts
  services/libs/data-access-layer/src/old/apps/profiles_worker/index.ts
  services/libs/types/src/members.ts
  services/libs/types/src/organizations.ts
Labels: Feature
