Repository CrowdDotDev/crowd.dev, pull requests merged in 2025-02, with the labels that each got.

#2852 Fix activity move direction on merges
  services/apps/entity_merging_worker/src/workflows/all.ts
Labels: Bug

#2848 Activity relations
  backend/package.json
  backend/src/database/migrations/U1737705711__activityRelations.sql
  backend/src/database/migrations/V1737705711__activityRelations.sql
  backend/src/database/repositories/member/memberOrganizationAffiliationOverridesRepository.ts
  backend/src/services/member/memberAffiliationsService.ts
  services/apps/data_sink_worker/src/service/activity.service.ts
  services/apps/entity_merging_worker/src/activities.ts
  services/apps/entity_merging_worker/src/activities/members.ts
  services/apps/entity_merging_worker/src/activities/organizations.ts
  services/libs/common/src/timing.ts
  services/libs/data-access-layer/src/activities/sql.ts
  services/libs/data-access-layer/src/activities/update.ts
  services/libs/data-access-layer/src/member_organization_affiliation_overrides/index.ts
  services/libs/data-access-layer/src/old/apps/data_sink_worker/repo/activity.data.ts
  services/libs/data-access-layer/src/old/apps/entity_merging_worker/index.ts
  services/libs/data-access-layer/src/old/apps/entity_merging_worker/orgs.ts
  services/libs/data-access-layer/src/old/apps/profiles_worker/index.ts
Labels: Feature

#2779 member aggs sync improvements
  backend/src/database/migrations/V1738589807__remove-tenantId-and-modify-indexes-on-indexed-entities.sql
  backend/src/services/searchSyncService.ts
  pnpm-lock.yaml
  services/apps/script_executor_worker/package.json
  services/apps/script_executor_worker/src/activities.ts
  services/apps/script_executor_worker/src/activities/sync/member.ts
  services/apps/script_executor_worker/src/main.ts
  services/apps/script_executor_worker/src/types.ts
  services/apps/script_executor_worker/src/workflows.ts
  services/apps/script_executor_worker/src/workflows/syncMembers.ts
  services/apps/search_sync_api/src/routes/member.ts
  services/apps/search_sync_api/src/routes/organization.ts
  services/apps/search_sync_worker/src/bin/sync-all-members.ts
  services/apps/search_sync_worker/src/bin/sync-all-organizations.ts
  services/apps/search_sync_worker/src/bin/sync-tenant-members.ts
  services/apps/search_sync_worker/src/bin/sync-tenant-organizations.ts
  services/apps/search_sync_worker/src/queue/index.ts
  services/libs/common_services/src/services/emitters/searchSyncWorker.emitter.ts
  services/libs/data-access-layer/package.json
  services/libs/data-access-layer/src/members/segments.ts
  services/libs/data-access-layer/src/old/apps/script_executor_worker/member.repo.ts
  services/libs/opensearch/src/apiClient.ts
  services/libs/opensearch/src/repo/indexing.data.ts
  services/libs/opensearch/src/repo/indexing.repo.ts
  services/libs/opensearch/src/repo/member.repo.ts
  services/libs/opensearch/src/repo/organization.repo.ts
  services/libs/opensearch/src/service/member.sync.service.ts
  services/libs/opensearch/src/service/organization.sync.service.ts
  services/libs/types/src/queue/search_sync_worker/index.ts
Labels: Improvement

#2861 Activity relations conflict check fix
  services/libs/data-access-layer/src/activities/sql.ts
Labels: Bug

#2862 Improve resilience in activity relations migration
  pnpm-lock.yaml
  services/apps/script_executor_worker/package.json
  services/apps/script_executor_worker/src/main.ts
  services/apps/script_executor_worker/src/schedules/schedulePopulateActivityRelations.ts
Labels: Improvement

#2871 Blacklisted titles filtering fix
  services/libs/data-access-layer/src/old/apps/data_sink_worker/repo/memberAffiliation.repo.ts
  services/libs/data-access-layer/src/old/apps/profiles_worker/index.ts
Labels: Bug

#2875 Deciding primary org id on `memberCount` fixes
  services/apps/nango_worker/src/activities/nangoActivities.ts
  services/libs/data-access-layer/src/old/apps/data_sink_worker/repo/memberAffiliation.repo.ts
Labels: Bug

#2863 Handle activity relations without username or platform or segmentId
  services/apps/script_executor_worker/src/activities.ts
  services/apps/script_executor_worker/src/activities/populate-activity-relations/index.ts
  services/apps/script_executor_worker/src/schedules/schedulePopulateActivityRelations.ts
  services/apps/script_executor_worker/src/types.ts
  services/apps/script_executor_worker/src/workflows/populateActivityRelations.ts
  services/libs/data-access-layer/src/activities/sql.ts
Labels: Bug
