Repository CrowdDotDev/crowd.dev, pull requests merged in 2025-04, with the labels that each got.

#2975 Collection & project changes
  backend/src/database/migrations/U1743723469__collectionProjectUniqueNames.sql
  backend/src/database/migrations/U1743723883__projectUniqueSegmentId.sql
  backend/src/database/migrations/U1743724207__projectEnable.sql
  backend/src/database/migrations/U1743724307__isProjectLf.sql
  backend/src/database/migrations/U1743724684__projectKeywords.sql
  backend/src/database/migrations/V1743723469__collectionProjectUniqueNames.sql
  backend/src/database/migrations/V1743723883__projectUniqueSegmentId.sql
  backend/src/database/migrations/V1743724207__projectEnable.sql
  backend/src/database/migrations/V1743724307__isProjectLf.sql
  backend/src/database/migrations/V1743724684__projectKeywords.sql
  backend/src/services/collectionService.ts
  services/libs/data-access-layer/src/collections/index.ts
Labels: Improvement

#2996 Development tab tinybird endpoints QA items
  services/libs/tinybird/pipes/contributors_leaderboard.pipe
  services/libs/tinybird/pipes/organizations_leaderboard.pipe
  services/libs/tinybird/pipes/pull_requests_review_time_by_size.pipe
Labels: --skip-regression-tests

#3008 feat: add support for duplicated contributor identities
  frontend/src/modules/contributor/components/details/contributor-details-identities.vue
  frontend/src/modules/contributor/components/details/identity/contributor-details-identity-item-image.vue
  frontend/src/modules/contributor/components/details/identity/contributor-details-identity-item-value.vue
  frontend/src/modules/contributor/components/details/identity/contributor-details-identity-item.vue
  frontend/src/modules/contributor/types/Contributor.ts
Labels: Feature, Frontend 🖼️

#3019 feat(tinybird) Ingishts projects list send also widgets
  frontend/package.json
  frontend/tailwind.config.js
  services/libs/tinybird/pipes/insightsProjects_filtered.pipe
  services/libs/tinybird/scripts/format_all.sh
Labels: --skip-regression-tests
