Repository CrowdDotDev/crowd.dev, pull requests merged in 2025-05, with the labels that each got.

#3032 fix: array format in updateProject query
  services/libs/data-access-layer/src/collections/index.ts
Labels: Bug

#3034 refactor: search endpoint sorting improvements
  services/libs/tinybird/pipes/collections_filtered.pipe
  services/libs/tinybird/pipes/collections_list.pipe
  services/libs/tinybird/pipes/search_collections_projects_repos.pipe
Labels: Improvement, --skip-regression-tests

#3033 feat: provide data for the about section (TinyBird side) [INS 458]
  services/libs/tinybird/README.md
  services/libs/tinybird/pipes/insightsProjects_filtered.pipe
Labels: Feature, --skip-regression-tests

#3024 feat: security best practices
  backend/src/database/migrations/U1744813638__securityInsights.sql
  backend/src/database/migrations/V1744813638__securityInsights.sql
  pnpm-lock.yaml
  scripts/builders/security-best-practices-worker.env
  scripts/services/docker/Dockerfile.security_best_practices_worker
  scripts/services/docker/Dockerfile.security_best_practices_worker.dockerignore
  scripts/services/security-best-practices-worker.yaml
  services/apps/security_best_practices_worker/example-config.yml
  services/apps/security_best_practices_worker/package.json
  services/apps/security_best_practices_worker/src/activities.ts
  services/apps/security_best_practices_worker/src/activities/index.ts
  services/apps/security_best_practices_worker/src/main.ts
  services/apps/security_best_practices_worker/src/schedules/scheduleCheckReposWithObsoleteSecurityInsights.ts
  services/apps/security_best_practices_worker/src/types.ts
  services/apps/security_best_practices_worker/src/workflows.ts
  services/apps/security_best_practices_worker/src/workflows/triggerSecurityInsightsCheckForRepos.ts
  services/apps/security_best_practices_worker/src/workflows/upsertOSPSBaselineSecurityInsights.ts
  services/apps/security_best_practices_worker/tsconfig.json
  services/libs/data-access-layer/src/index.ts
  services/libs/data-access-layer/src/security_insights/index.ts
  services/libs/tinybird/README.md
  services/libs/tinybird/datasources/securityInsightsEvaluationSuiteControlEvaluationAssessments.datasource
  services/libs/tinybird/datasources/securityInsightsEvaluationSuiteControlEvaluations.datasource
  services/libs/tinybird/pipes/security_and_best_practices.pipe
  services/libs/tinybird/pipes/segments_filtered.pipe
  services/libs/types/src/index.ts
  services/libs/types/src/securityInsights.ts
Labels: Feature, --skip-regression-tests

#3046 feat: refactor display of collections and insights projects [INS-469]
  backend/src/database/migrations/U1746554597__addStarredColumnToCollectionsTable.sql
  backend/src/database/migrations/V1746546438__addStarredColumnToCollectionsTable.sql
  services/libs/data-access-layer/src/collections/index.ts
  services/libs/tinybird/datasources/collections.datasource
  services/libs/tinybird/pipes/collections_filtered.pipe
  services/libs/tinybird/pipes/collections_list.pipe
Labels: Backend 🛠️, --skip-regression-tests

#3049 fix(organizations): nested filters in query
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#3045 fix: security and best practices QA items
  services/apps/security_best_practices_worker/src/activities.ts
  services/apps/security_best_practices_worker/src/activities/index.ts
  services/apps/security_best_practices_worker/src/main.ts
  services/apps/security_best_practices_worker/src/types.ts
  services/apps/security_best_practices_worker/src/workflows/triggerSecurityInsightsCheckForRepos.ts
  services/apps/security_best_practices_worker/src/workflows/upsertOSPSBaselineSecurityInsights.ts
  services/libs/data-access-layer/src/security_insights/index.ts
  services/libs/tinybird/pipes/security_and_best_practices.pipe
Labels: --skip-regression-tests

#3043 feat: add star/feature functionality for collections
  frontend/src/modules/admin/modules/collections/components/lf-collection-add-dropdown.vue
  frontend/src/modules/admin/modules/collections/components/lf-collection-add.vue
  frontend/src/modules/admin/modules/collections/components/lf-collection-dropdown.vue
  frontend/src/modules/admin/modules/collections/components/lf-collection-table.vue
  frontend/src/modules/admin/modules/collections/models/collection.model.ts
  frontend/src/modules/admin/modules/collections/pages/collection.page.vue
Labels: Feature, Frontend 🖼️

#3053 fix(oganizations): correct logic for lfxMembership filter
  backend/src/database/repositories/organizationRepository.ts
Labels: Bug

#3055 feat: implement infinite scroll and loading state for insights projects list
  frontend/components.d.ts
  frontend/src/modules/admin/modules/collections/components/lf-collection-add.vue
  frontend/src/modules/admin/modules/collections/components/lf-insights-projects-list-dropdown.vue
  frontend/src/modules/admin/modules/insights-projects/services/insights-projects.service.ts
  frontend/src/shared/types/Pagination.ts
  frontend/src/shared/types/tanstack.ts
Labels: Feature, Frontend 🖼️

#3058 feat: on TinyBird, when sorting collections by "starred", sort them also by "projectCount"
  services/libs/tinybird/pipes/collections_list.pipe
Labels: Backend 🛠️, --skip-regression-tests

#3054 fix: enabled typo in `insightProjects` tinybird resources
  services/libs/tinybird/datasources/insightsProjects.datasource
  services/libs/tinybird/pipes/collections_list.pipe
  services/libs/tinybird/pipes/insightsProjects_filtered.pipe
  services/libs/tinybird/pipes/segments_filtered.pipe
Labels: --skip-regression-tests

#3064 feat: add `integrations` and `memberIdentities` to Tinybird
  backend/src/database/migrations/U1747210214__addMemberIdentitiesAndIntegrationsToTinybird.sql
  backend/src/database/migrations/V1747210214__addMemberIdentitiesAndIntegrationsToTinybird.sql
  services/libs/tinybird/datasources/integrations.datasource
  services/libs/tinybird/datasources/memberIdentities.datasource
Labels: Feature, --skip-regression-tests

#3075 feat: handle API cache for list insights project API
  frontend/src/modules/admin/modules/collections/pages/collection.page.vue
  frontend/src/modules/admin/modules/insights-projects/components/lf-insights-project-add.vue
  frontend/src/modules/admin/modules/insights-projects/insight-project-helper.ts
  frontend/src/modules/admin/modules/insights-projects/models/insights-project.model.ts
  frontend/src/modules/admin/modules/insights-projects/pages/insights-projects.page.vue
  frontend/src/modules/admin/modules/insights-projects/services/insights-projects.service.ts
Labels: Frontend 🖼️

#3077 feat: public friendly display names for non-lf projects
  services/libs/tinybird/datasources/memberIdentities.datasource
  services/libs/tinybird/datasources/members_public_names_ds.datasource
  services/libs/tinybird/datasources/members_sorted.datasource
  services/libs/tinybird/pipes/contributors_leaderboard.pipe
  services/libs/tinybird/pipes/members_public_names_copy_pipe.pipe
  services/libs/tinybird/pipes/members_sorted_copy_pipe.pipe
Labels: --skip-regression-tests

#3083 feat: project-list first commit and details limit
  services/libs/tinybird/pipes/insightsProjects_filtered.pipe
Labels: --skip-regression-tests

#3092 fix: add missing filter for contributions in a materialized view
  services/libs/tinybird/pipes/segmentId_aggregates_mv.pipe
Labels: Bug, --skip-regression-tests

#3093 feat(segments): add isLF flag and constraints
  backend/src/database/migrations/U1747408625__addIsLfColumnToSegments.sql
  backend/src/database/migrations/V1747408625__addIsLfColumnToSegments.sql
  backend/src/database/repositories/segmentRepository.ts
  backend/src/services/segmentService.ts
  services/libs/common/src/i18n/en.ts
  services/libs/common/src/validations.ts
  services/libs/types/src/segments.ts
Labels: Feature

#3102 fix: always delete test branch on error or successful runs
  .github/workflows/tinybird-ci.yml
Labels: Bug

#3121 feat: add criticality scores to insights project endpoint
  services/libs/tinybird/pipes/insightsProjects_filtered.pipe
Labels: --skip-regression-tests
