Repository CrowdDotDev/crowd.dev, pull requests merged in 2025-10, with the labels that each got.

#3445 feat: add daily activities counter
  services/libs/tinybird/pipes/activities_daily_counts.pipe
Labels: Feature

#3447 feat: migrate github stats
  backend/src/database/repositories/integrationProgressRepository.ts
  backend/src/services/integrationService.ts
  services/libs/data-access-layer/src/activities/sql.ts
  services/libs/database/src/tinybirdClient.ts
  services/libs/tinybird/pipes/activities_relations_filtered.pipe
Labels: Feature

#3464 fix: add hard deleting when deleting a memberOrganization
  services/libs/data-access-layer/src/members/organizations.ts
Labels: Bug

#3475 fix: return null when llm return null
  services/libs/common_services/src/services/llm.service.ts
Labels: Bug

#3474 chore(devx): cleanup
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/backend-lint.yaml
  .github/workflows/frontend-lint.yml
  .github/workflows/pr-title-jira-key-lint.yml
  .github/workflows/release-drafter.yaml
  .github/workflows/reset-staging.yaml
  .github/workflows/test-frontend.yml
  CODEOWNERS
  CONTRIBUTING.md
  MAINTAINERS.md
Labels: DevX
