Repository CrowdDotDev/crowd.dev, pull requests merged in 2025-08, with the labels that each got.

#3299 fix: stuck integration runs preventing new ones [CM-2460]
  backend/src/database/repositories/integrationRunRepository.ts
  backend/src/serverless/integrations/services/integrationTickProcessor.ts
Labels: Bug, Support 🛟

#3308 refactor: deprecate data access for conversations [CM-2461]
  services/libs/data-access-layer/src/conversations/ilp.ts
  services/libs/data-access-layer/src/conversations/index.ts
  services/libs/data-access-layer/src/conversations/sql.ts
  services/libs/data-access-layer/src/conversations/types.ts
  services/libs/data-access-layer/src/index.ts
Labels: Improvement

#3330 fix: tb copy pipes sync and deadlock issues
  services/libs/tinybird/pipes/activityRelations_deduplicated_cleaned_copy_pipe.pipe
  services/libs/tinybird/pipes/members_sorted_copy_pipe.pipe
Labels: Bug

#3327 refactor: depcreate-sync-activities [CM-543]
  backend/package.json
  backend/src/bin/jobs/index.ts
  backend/src/bin/jobs/syncActivities.ts
  backend/src/bin/scripts/syncActivities.ts
Labels: Improvement

#3340 fix: update segment repositories table
  backend/src/database/repositories/segmentRepository.ts
  backend/src/services/collectionService.ts
  backend/src/services/integrationService.ts
  services/libs/data-access-layer/src/collections/index.ts
Labels: Bug

#3342 fix: tb sync `activityRelations_deduplicated_ds` schema
  services/libs/tinybird/pipes/activityRelations_deduplicated_copy_pipe.pipe
Labels: Bug
