Repository CrowdDotDev/crowd.dev, pull requests merged in 2025-06, with the labels that each got.

#3136 feat: oss index sorting
  services/libs/tinybird/pipes/categories_oss_index.pipe
  services/libs/tinybird/pipes/category_groups_oss_index.pipe
  services/libs/tinybird/pipes/collections_oss_index.pipe
Labels: --skip-regression-tests

#3152 fix: query to find groupsio integration based on group name
  services/apps/webhook_api/src/routes/groupsio.ts
  services/libs/data-access-layer/src/old/apps/webhook_api/webhooks.repo.ts
Labels: Bug, Support 🛟, Integrations

#3155 fix: payload sent to triggerIntegrationRun
  backend/src/serverless/integrations/services/integrationTickProcessor.ts
Labels: Bug

#3151 feat: top overall contributors and organizations
  services/libs/tinybird/datasources/member_org_activity_count_mv_ds.datasource
  services/libs/tinybird/pipes/member_org_activity_count_mv.pipe
  services/libs/tinybird/pipes/top_active_contributors.pipe
  services/libs/tinybird/pipes/top_active_organizations.pipe
Labels: --skip-regression-tests

#3164 feat: improve error message for GitHub repos connection
  backend/src/services/integrationService.ts
  frontend/src/config/integrations/github/components/settings/github-settings-drawer.vue
Labels: Frontend 🖼️

#3172 feat: add maintainer roles to pipes
  services/libs/tinybird/datasources/maintainers_roles_copy_ds.datasource
  services/libs/tinybird/datasources/member_org_activity_count_copy_ds.datasource
  services/libs/tinybird/datasources/member_org_activity_count_mv_ds.datasource
  services/libs/tinybird/pipes/contributor_dependency.pipe
  services/libs/tinybird/pipes/contributors_leaderboard.pipe
  services/libs/tinybird/pipes/maintainers_roles_copy.pipe
  services/libs/tinybird/pipes/member_org_activity_count_copy.pipe
  services/libs/tinybird/pipes/member_org_activity_count_mv.pipe
  services/libs/tinybird/pipes/member_roles.pipe
  services/libs/tinybird/pipes/top_active_contributors.pipe
  services/libs/tinybird/pipes/top_active_organizations.pipe
Labels: --skip-regression-tests

#3184 fix: using `members_sorted` pipe for filtering bot activities in main activity data pipeline
  services/libs/tinybird/pipes/activities_with_relations_sorted_deduplicated_copy_pipe.pipe
Labels: Bug, --skip-regression-tests

#3193 fix: implement pagination for getOrgRpos using octokit [CM-2361]
  backend/package.json
  backend/src/services/githubIntegrationService.ts
  pnpm-lock.yaml
Labels: Bug, Support 🛟

#3200 feat: add pagination for github repos & orgs [CM-2370]
  backend/src/api/integration/helpers/githubSearchOrgs.ts
  backend/src/api/integration/helpers/githubSearchRepos.ts
  backend/src/services/githubIntegrationService.ts
Labels: Improvement, Support 🛟

#3219 feat: add insight projects widgets api
  backend/src/api/collections/index.ts
  backend/src/api/collections/segmentsWidgetsGet.ts
  backend/src/services/collectionService.ts
  services/libs/types/src/enums/index.ts
  services/libs/types/src/enums/widgets.ts
Labels: Feature
