Repository CrowdDotDev/crowd.dev, pull requests merged in 2025-07, with the labels that each got.

#3228 feat: add fetchProjectDetails method to retrieve project insights data and update UI base on it
  frontend/src/modules/admin/modules/insights-projects/components/lf-insights-project-add.vue
  frontend/src/modules/admin/modules/insights-projects/services/insights-projects.service.ts
Labels: Improvement, Frontend 🖼️

#3238 feat: reflect integrations on insights
  backend/src/database/repositories/segmentRepository.ts
  backend/src/services/collectionService.ts
  backend/src/services/integrationService.ts
  backend/src/services/segmentService.ts
  services/libs/data-access-layer/src/collections/index.ts
  services/libs/data-access-layer/src/query.ts
  services/libs/types/src/enums/platforms.ts
Labels: Improvement

#3261 fix: add optional chaining [CM-2419]
  backend/src/services/integrationService.ts
Labels: Bug

#3178 feat: add the TInyBird resources for the search volume data
  services/libs/tinybird/datasources/searchVolume.datasource
  services/libs/tinybird/pipes/search_volume.pipe
Labels: Backend 🛠️, --skip-regression-tests

#3264 fix: missed one spot when renaming the slug column
  services/libs/tinybird/datasources/searchVolume.datasource
Labels: Bug, --skip-regression-tests

#3263 feat: improve github insights api [CM-2420]
  backend/src/services/collectionService.ts
  backend/src/services/githubIntegrationService.ts
  backend/src/services/integrationService.ts
Labels: Improvement

#3283 fix: workflow policy
  backend/src/services/integrationService.ts
Labels: Bug

#3288 fix: do nothing an conflict when assigning automatic categorization
  services/apps/categorization_worker/src/activities/activities.ts
  services/libs/data-access-layer/src/collections/index.ts
Labels: Bug

#3295 fix: use insights project id as primary key for the repositories
  backend/src/database/migrations/U1753798343__revert_primary_key_segment_repositories.sql
  backend/src/database/migrations/V1753798343__revert_primary_key_segment_repositories.sql
  backend/src/services/collectionService.ts
  services/libs/data-access-layer/src/collections/index.ts
Labels: Bug
